- packages/runtime-core/src/hydration.ts
- packages/runtime-dom/src/apiCustomElement.ts
close #4679 
The following logic is referenced：
https://github.com/vuejs/vue-next/blob/08bf7e360783d520bae3fbe37143c52d360bd52d/packages/runtime-core/src/renderer.ts#L357-L360
> fix(ssr): should remove dynamic children if patchFlag is bail

- packages/server-renderer/src/render.ts
This warning is spamming my build logs, and already has this condition at runtime:
https://github.com/vuejs/vue-next/blob/44b95276f5c086e1d88fa3c686a5f39eb5bb7821/packages/runtime-core/src/components/Teleport.ts#L58-L60
> fix(ssr): don't warn for missing teleport target if disabled

- packages/runtime-core/src/components/BaseTransition.ts
Passing an array of functions to transition hooks currently triggers
```
TS2322: Type '(() => void)[]' is not assignable to type '(el: Element) => void'.
```
or `onLeave is not a function` at runtime with the onEnter/onLeave/onAppear hooks.
> fix(runtime-core): transition hooks can be arrays of functions

- packages/runtime-core/src/componentProps.ts
Fixed https://github.com/johnsoncodehk/volar/issues/1261.
- Before the fix
- After the fix
> feat(types): avoid props JSDocs loss due to `default` option

- packages/runtime-core/__tests__/apiAsyncComponent.spec.ts
- packages/runtime-core/src/apiAsyncComponent.ts
> fix(runtime-core): AsyncComponent work with KeepAlive

- packages/runtime-core/__tests__/scheduler.spec.ts
Delete test code(`.cb` in runtime-core) that is no longer used.
> chore(runtime-code): delete job.cb related test code

- packages/compiler-core/__tests__/parse.spec.ts
I found a test case of the parser missing some types. So, I added it.
> chore(compiler): improve readability of compiler-core's test case

- .eslintrc.js
- packages/compiler-dom/src/index.ts
- packages/runtime-core/__tests__/componentPublicInstance.spec.ts
- packages/runtime-core/__tests__/rendererTemplateRef.spec.ts
- packages/runtime-core/src/componentProps.ts
- packages/runtime-core/src/hydration.ts
- packages/runtime-dom/__tests__/createApp.spec.ts
- packages/server-renderer/src/helpers/ssrRenderAttrs.ts
- packages/shared/src/typeUtils.ts
@yyx990803 Some `debugger` instructions slipped through commit 9309b044bd4f9d0a34e0d702ed4690a529443a41
This removes them, and adds a lint rule to fail the build if a debugger instruction is added
> chore: add no-debugger eslint rule

- packages/runtime-core/__tests__/helpers/withMemo.spec.ts
- packages/runtime-core/src/helpers/withMemo.ts
fix #5853
The case where the v-memo dependency is Nan is not equal.
> fix(runtime-core): v-memo dependency is NaN should be equal

- packages/runtime-core/__tests__/componentEmits.spec.ts
- packages/runtime-core/src/componentEmits.ts
- packages/runtime-dom/__tests__/directives/vModel.spec.ts
- packages/runtime-dom/src/directives/vModel.ts
close #5839
fix(runtime-dom): directives trim & number, number is not effect  #5839
> fix(runtime-dom): directives trim & number, number is not effect  #5839

- scripts/release.js
Running release script again when it failed previously will get a wrong `currentVersion`.
> workflow: recover version when error occurred

- packages/sfc-playground/src/main.ts
The correct appid of devtools is `repl`
> fix(sfc-playground): default selected app on devtools

- packages/runtime-core/__tests__/apiWatch.spec.ts
- packages/runtime-core/src/apiWatch.ts
> fix(reactivity): fix watching shallowRef array

- packages/compiler-sfc/src/compileScript.ts
> fix(compiler-sfc): fix checkInvalidScopeReference method error

- packages/server-renderer/__tests__/ssrTeleport.spec.ts
- packages/server-renderer/src/renderToString.ts
Teleports inside async components weren't SSR rendered into the `ctx.teleports` but were in the `ctx.__teleportBuffers`. This PR fixes the issue.
> fix(ssr): render teleport inside async component

- packages/shared/src/index.ts
`isDate({__proto__: new Date()})` should return false, but it actually returns true, so change
> fix(shared): Change the implementation of isDate

- packages/runtime-dom/types/jsx.d.ts
`runtime-dom` types do not account for `Set<any>` as a valid `v-model` type for checkbox input elements when using TS. This is causing "compile-time" errors stating that `Set<any>` is an invalid `v-model` binding.
> types(runtime-dom) add `Set<any>` to checkbox

- .eslintrc.js
- package.json
- pnpm-lock.yaml
This PR adds a linting job on CI to catch regressions.
A few lint issues have been fixed in the process (one lint rule has been removed as the restriction no longer applies, see https://github.com/vuejs/core/commit/7efb9dba3084816e54e2989d1812c13bba229ee9).
The test files are now also processed, and rules have been added to avoid letting focused or disabled tests slip through.
This has been discussed after https://github.com/vuejs/core/pull/5715
> chore: lint on ci and lint test files

- packages/runtime-dom/src/directives/vModel.ts
- packages/server-renderer/__tests__/ssrDirectives.spec.ts
> fix(ssr): Support vnode v-model when input type is dynamic

- packages/runtime-core/src/index.ts
The new type introduced in 98b821d94a0a0fb4d7701809da6bec331a47e6e5 is not publicly available
This is an issue for test-utils, as `mount` currently needs the same types as `DefineComponent` 
This commit exports the type `ComponentProvideOptions`, allowing to update the signature of `mount` (see https://github.com/vuejs/test-utils/pull/1510)
> fix(runtime-core): export ComponentProvideOptions

- packages/compiler-sfc/src/compileScript.ts
Add 'Promise' to inferRuntimeType() to recognize type-only defineProps Promise declaration.
> fix(compiler-sfc): type-only defineProps does not recognize Promise (fix #5941)

- packages/compiler-sfc/__tests__/rewriteDefault.spec.ts
- packages/compiler-sfc/src/rewriteDefault.ts
close #5935
feat(compiler-sfc): support syntax export { default } from '...'
> feat(compiler-sfc): support syntax export { default } from '...'

- packages/runtime-core/src/index.ts
- packages/runtime-core/src/vnode.ts
- packages/runtime-dom/types/jsx.d.ts
- test-dts/componentTypeExtensions.test-d.tsx
- test-dts/defineComponent.test-d.tsx
fix #5969
```ts
import { defineComponent } from 'vue'
declare function expectType<T>(t: T): void
const Child = defineComponent({
props: {
bar: String
}
})
const Parent = defineComponent({
props: {
...Child.props,
foo: String
}
})
const child = new Child()
expectType<JSX.Element>(<Parent {...child.$props} />) // error
```
> types: Spreading `$props` causes typescript error

- packages/runtime-dom/src/components/Transition.ts
> fix(transition): improve handle cancel leave before next frame

- packages/runtime-core/src/apiSetupHelpers.ts
- test-dts/setupHelpers.test-d.ts
Fix https://github.com/vuejs/core/issues/5938
> fix: allow use default factory for primitive types

- packages/compiler-sfc/src/rewriteDefault.ts
npx depcheck was failing with latest version
> fix(compile-sfc): remove optional check

- packages/runtime-dom/src/modules/events.ts
```js
function test(f) {
console.time()
let i = 0
while (i++ < 1e6) {
f()
}
console.timeEnd()
}
test(performance.now.bind(performance))
test(()=>performance.now())
// VM2470:7 default: 120.751220703125 ms
// VM2470:7 default: 453.26416015625 ms```
> Improve the performance of `performance`.

- packages/compiler-core/__tests__/transforms/__snapshots__/hoistStatic.spec.ts.snap
- packages/compiler-core/__tests__/transforms/hoistStatic.spec.ts
- packages/compiler-core/src/transforms/hoistStatic.ts
> fix(compiler-core): fix directives not working with SVG

- packages/runtime-core/src/compat/global.ts
- packages/vue-compat/__tests__/global.spec.ts
Closes #5699. Because `applySingletonAppMutations` copies the reference of the singleton context instead of a copy of it, all local asset registration into any local app modifies all other local apps both post-facto and globally. My initial take at solving this was to simply create a shallow copy of the singleton app context instead of copying the reference, but then I realized the existing implementation allows for code like the following to work:
```
const app = createApp({ template: '<foo />' });
Vue.component('foo', /* some impl */);
app.mount(...); // resolves 'foo' from the global registry even though it was created after the fact
```
I'm not sure if this is behavior we wanted or meant to have, but in the interest of not breaking anything, I added a test for both the original issue …
> [@vue/compat] Prevent local asset registration from affecting other local apps (fix #5699)

- packages/runtime-core/__tests__/hydration.spec.ts
- packages/runtime-core/src/hydration.ts
`app.unmount()` fails in a hydrated app because unlike `rende()r`, `hydrate()` doesn't cache cache ghe root vnode on the container element.
This PR fixes that, so that `app.unmount()` runs correctly for hydrated apps as well.
close: #5990
> fix(runtime-ssr): ensure app  can be unmounted when created with createSSRApp() (fix #5990)

- packages/sfc-playground/index.html
The current logic of setting dark mode actually doesn't persist the light mode when the user explicitly chooses it. This can be confirmed by clicking the moon icon in the dark mode and refreshing the page — the page will still be in dark mode if the OS uses it.
> fix(sfc-playground): persist light mode

- packages/compiler-ssr/__tests__/ssrSlotOutlet.spec.ts
- packages/compiler-ssr/src/transforms/ssrTransformSlotOutlet.ts
- packages/server-renderer/__tests__/ssrSlot.spec.ts
- packages/server-renderer/src/helpers/ssrRenderSlot.ts
close #5991
feat: Hydration when Transition with v-if
> feat: Hydration when Transition with v-if

- packages/sfc-playground/src/App.vue
- packages/sfc-playground/src/Header.vue
Version list should also be hidden when clicking on the preview panel.
> fix(sfc-playground): hide versions when click iframe & set color-scheme to dark

- packages/reactivity-transform/LICENSE
This is not a bug or a feature request.
It's more like housekeeping. A LICENSE file is missing from the reactivity-transform package.
Our build tooling tries to extract license information from package dependencies for easy review.
> docs(core): add LICENSE file in reactivity-transform

- packages/server-renderer/src/helpers/ssrRenderSlot.ts
This PR replaces `isComment` function in `ssrRenderSlot` with a faster version (upto 10x faster, see: https://jsbench.me/o5l45knpk2/1)
Old `isComment`: 8029029.23 ops/s (89.1% slower)
New `isComment`: 73631038.71 ops/s
> perf(ssr): improve ssrRenderSlot performance

- package.json
unit tests fail with a lower version due to:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Class_static_initialization_blocks
> chore: bumpo node engine requirement to node 16.11

- packages/compiler-sfc/__tests__/rewriteDefault.spec.ts
- packages/compiler-sfc/src/rewriteDefault.ts
> fix(compiler-sfc): make sure rewriteDefault get correct result when use  decorator before export default (fix #6318)

- packages/compiler-ssr/__tests__/ssrInjectCssVars.spec.ts
- packages/compiler-ssr/src/ssrCodegenTransform.ts
During SSR build, the `_unref` helper provided by injecting CSS binding is not forwarded to the main ast. Causing `_unref is not defined` error on SSR.
fix #6201
fix https://github.com/nuxt/framework/issues/6567
close #6218 as an alternative
Reproduction with Vite: https://stackblitz.com/edit/vitejs-vite-ukhxfu?file=README.md&terminal=run
> fix(ssr): forward helpers provided by CSS `v-bind`

- packages/runtime-core/src/componentEmits.ts
- packages/runtime-core/src/componentOptions.ts
- packages/runtime-core/src/componentProps.ts
On SSR if an unregistered component is used we have a hard crash as we try to cache the details about this component, but it's a string (not a resolved object) and can't be used as a cache key to the WeakMap that's we're using.
It's true this is wrong usage, and there is a helpful warning:
```bash
[Vue warn]: Failed to resolve component: SomeThing
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```
But there is also a fatal and hard error that occurs:
**Fatal error**:
```bash
Error: WeakMap key must be an object, got comp
at _evaluate (https://node-2lafe5-dfi279td.w-corp.staticblitz.com/blitz.bff91798029e1af88e01551d056a592b2882b9ac.js:15:286611)
at <anonymous> (<anonymous>)
```
```js
import { createSSRApp } from …
```
> fix(runtime-core): only set cache for object keys

- packages/runtime-core/src/componentProps.ts
this is reopen for https://github.com/vuejs/vue-next/issues/1942 and https://github.com/vuejs/vue-next/pull/1945 because:
After change prop value on component, HMR won't update prop if component has directive.
This reproduced if component in second or more level in SFC.
> HMR doesn't update component which uses directives

- packages/runtime-core/__tests__/apiOptions.spec.ts
- packages/runtime-core/src/component.ts
**this behavior supported in vue2.**
close #6249
> fix(runtime-core): support extends template for runtime compiler

- packages/server-renderer/__tests__/render.spec.ts
- packages/server-renderer/src/render.ts
ensure the current instance is not affected by rendering error.
close #6110
> fix(ssr): reset current instance after rendering error on SSR.(fix #6110)

- packages/runtime-core/__tests__/apiLifecycle.spec.ts
- packages/runtime-core/src/apiLifecycle.ts
the current deduping implementation of `injectHook` relies on lifecycle callbacks always being created within setup.
When using i.e. an imported function directly as a hook callback, it will not reliably be run for each instance of a component.
This PR wraps each received callback in another arrow function in in order to ensure that each component instance has its own distinct copy of the callback.
> fix(runtime-core): Lifecycle hooks should support callbacks shared by reference (fix #6686)

- packages/compiler-ssr/src/ssrCodegenTransform.ts
Fix https://github.com/nuxt/framework/issues/7343
It was introduced in https://github.com/vuejs/core/pull/6489
Out of scope of this PR, but should we consider doing some unique normalization for it to reduce maintenance burden, or even directly change it to `Set`?
> fix(ssr): avoid ast.helpers duplication

- packages/compiler-dom/__tests__/transforms/stringifyStatic.spec.ts
- packages/compiler-dom/src/transforms/stringifyStatic.ts
> fix(stringifyStatic):remove boolean attribute for false (fix #6617)

- packages/compiler-sfc/src/compileScript.ts
> fix(compiler-sfc): Resolve object expression parsing errors in `v-on`

- .github/workflows/ci.yml
- .github/workflows/release-tag.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- packages/runtime-core/src/h.ts
- test-dts/h.test-d.ts
> types: creating Teleport with h and RawSlots #2613

- packages/runtime-core/__tests__/vnode.spec.ts
- packages/runtime-core/src/componentRenderContext.ts
- packages/runtime-core/src/errorHandling.ts
fix #5657 
ensure that errors in slot function execution do not affect block tracking, and then affect dynamic children and patch
> fix(runtime-core): ensure that errors in slot function execution do not affect block tracking (fix #5657)

- packages/runtime-core/src/vnode.ts
- test-dts/compiler.test-d.ts
ensure createBlock() helper accepts Teleport and Supsense types, not their internal counterparts (TeleportImpl and SupenseImpl).
`createBlock()` only accepts `VNodeTypes` as first argument, and this type only included the internal types of Teleport and Suspense - `TeleportImpl` and `SuspenseImpl`.
This PR ads the public types `Teleport` and `Suspense` and thus ensures that the following, compiler-generated code now passes in vue-tsc and Volar:
```js
return (_ctx, _cache) => {
return (_openBlock(), _createBlock(_Teleport, { to: "body" }, [
_createTextVNode(" Foo " + _toDisplayString(_ctx.title), 1 /* TEXT */)
]))
}
```
fix: #2855
> fix(types): ensure createBlock() helper accepts Teleport and Supsense types (fix: #2855)

- packages/reactivity/__tests__/effect.spec.ts
- packages/reactivity/src/effect.ts
js allows use string to set length of array. 
The original code uses an implicit conversion that requires newValue to be a number as key's type is string.  If newValue is also a string, string comparison are performed instead of number comparison. The string comparison is lexicographical order, so "10"< "2", causing the length to be set to 2  but watch element at 10 will not be triggered
> fix(reactivity): enable trigger when use str to set length of arr

- packages/runtime-core/__tests__/componentProps.spec.ts
- packages/runtime-core/src/componentProps.ts
During Props normalization, we add a couple of flags to the definition object for internal purposes, so this:
```js
{
type: String
}
```
becomes this:
```js
{
type: String,
0: true,
1: false
}
```
The problem is that we do this to the original object provided by the developer  in the component's options. This can lead to issues when the developer re-uses these objects in different places.
This PR makes a shallow copy of that object before adding those flags, so the original definition stays untouched.
close: #6915
> fix(runtime-core): ensure props definition objects are not mutated during props normalization (close: #6915)

- packages/runtime-dom/__tests__/customElement.spec.ts
- packages/runtime-dom/src/apiCustomElement.ts
> fix(runtime-core): custom-element: ensure number casting of camelCase props. (fix: #5374)

- packages/shared/src/typeUtils.ts
Improve the implementation of `LooseRequired<T>`.
The purpose of `LooseRequired<T>` is to change the **Optional Properties** in an **Object Type** to required, while keeping the undefined type.
In the current version, LooseRequire<T> is implemented as follows.
```typescript
type LooseRequired<T> = { [P in string & keyof T]: T[P] }
```
This implementation has problems when it encounters index signatures, consider the following code.
```typescript
type Result = LooseRequired<{
[x:string]:any
a?:1
b:false
}>
```
The result here is `{ [x: string]: any; }`
This is because when the object type contains a string index signature, the `keyof T` will return string, so all other properties cannot be mapped
But TypeScript `keyof T` is a lazy value in the case of `[P in keyof T]`, so we can guarantee …
> types(shared): Improve LooseRequired<T>

- packages/runtime-core/src/h.ts
- test-dts/h.test-d.ts
> types(h): Support passing `props` to `Component` when using `h`

- packages/runtime-dom/src/components/Transition.ts
refactor(types): use template literal types insteads of any
> refactor(types): use template literal types insteads of any

- packages/runtime-core/src/apiCreateApp.ts
- test-dts/component.test-d.ts
- test-dts/componentTypeExtensions.test-d.tsx
This pull request adds support for customising the attributes of `globalProperties`.
This isn't breaking as the string index signature is still there.
Currently there's no way to augment the `globalProperties` type as
```ts
declare module '@vue/runtime-core' {
interface AppConfig {
globalProperties: {
$myAttr: Ref<boolean>;
};
}
}
```
gives the error of: `TS2717: Subsequent property declarations must have the same type. Property 'globalProperties' must be of type 'Record<string, any>', but here has type...`
and
```ts
declare module '@vue/runtime-core' {
type AppConfig = Omit<BaseAppConfig, 'globalProperties'> & {
globalProperties: Record<string, any> & { $myAttribute: Ref<boolean> };
};
}
```
give the error of: `TS2300: Duplicate identifier 'AppConfig'.`
> types(runtime-core): added `ComponentCustomProperties` type to `globalProperties`

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/compileScript.ts
> fix(compiler-sfc): Optimize the value of emitIdentifier.

- packages/runtime-core/__tests__/apiExpose.spec.ts
- packages/runtime-core/src/component.ts
This PR tries to fix #6137.
The component `exposeProxy` implements a fallback logic for accessing built-in instance properties but was missing the same logic for the `in` operator in the Proxy's `has()` handler.
> fix(runtime-core): `in` operator returning `false` for built-in instance properties in `exposeProxy` (fix #6137)

- packages/runtime-core/src/apiWatch.ts
- packages/runtime-core/src/helpers/useSsrContext.ts
- packages/server-renderer/__tests__/ssrWatch.spec.ts
- packages/server-renderer/src/render.ts
- packages/server-renderer/src/renderToStream.ts
- packages/server-renderer/src/renderToString.ts
> fix(watch): should work normal w/ sync flush in ssr

- packages/runtime-dom/__tests__/customElement.spec.ts
- packages/runtime-dom/src/apiCustomElement.ts
If a component wrapped with `defineCustomElement()` did not hae any props defined, and was passed any custom attribute (such as, in #6361, a data-v attribute), it would throw an error.
closes #6163, close #6895
> fix(runtime-dom): ensure customElement handles empty props correctly. (fix #6361,#6895)

- packages/compiler-sfc/__tests__/__snapshots__/compileScriptPropsTransform.spec.ts.snap
- packages/compiler-sfc/src/compileScript.ts
- packages/reactivity-transform/__tests__/__snapshots__/reactivityTransform.spec.ts.snap
- packages/reactivity-transform/src/reactivityTransform.ts
- [Demo](https://sfc.vuejs.org/#eNqNkU1OwzAQha8ysrpIpDZWYRelkdggluzrLkIyaVM5Y8t2SlGVLVsuwgE4DxfgCoxbQAhEhSVLnr/PT28O4srabDegyEXha9fZAB7DYEFXtF4EXyqqDfkAB2iNgREW0GDbEd46Y31xUASxkENFD4rGMkmlhH+e1+fHt5cn8Bsz6Aaqhi9/3neKJpOEoakiRe1AdegMweDx2pgkZSWOFTqCJQeLEqI+ozHTZp3MLy7TFYxx8CR7uV+x5EnyOc3MvwWeFbRPs12lB0wYUciTV+wOBwF7q6uAHAEUm3l5g1qbQvIrtn6VxVR0vTUuzPrKZltviF0/Oqg+Cl6JHI6ZmOO1xFiJTQjW51L6to672vrMuLXkV+YGCl2PGfp+dufMvUfHYCWm3xiSkzt0M4fUoEN3jvmj9Rc3YtndUYzvEJ25Jg==) | [Fixed Demo](https://deploy-preview-6303--vue-sfc-playground.netlify.app/#eNqNUUtOwzAQvcrI6iKRSAJUYlGlkdggluzrLkIyaY2cseVP26jKli0X4QCchwtwBSYtsANhyZLfvJl5T89HcWttvosoFqL0jVM2gMcQLeiaNsvgK0mNIR/gCJ0xMMISWuwU4YMz1pdHSTARC6hpkDRWSVoU8M/z/vr88fYCfmuibqFu+bJ4ryTNZgkvTSVJ6iI1QRmC6PHOmCRlJ44dOoIVg2UFkz+jMddmk1xdz9M1jNPg2fbqsGbLs+R7mnf+bv …
> fix(reactivity-transform): add semicolon after statements

- packages/compiler-sfc/src/parse.ts
- the correct type is  `Statement[]`, instead of `Statement`.
- comment of type annotation is useless for dts file. So I change it to dynamic import.
> fix(compiler-sfc): dynamic import type annotation

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/__snapshots__/compileScriptPropsTransform.spec.ts.snap
- packages/compiler-sfc/src/compileScript.ts
closes #6428
related #6303, #6430
> fix(compiler-sfc): add semicolon after `defineProps` statement

- packages/runtime-core/__tests__/directives.spec.ts
- packages/runtime-core/src/directives.ts
Fixes #6340
This commit improves the case when a directive is not found in a template. As `resolveDirective` returns `undefined`, some code was failing with the following error:
```
TypeError: Cannot read properties of undefined (reading 'deep')
```
> fix(runtime-core): do not throw on unknown directives

- packages/server-renderer/__tests__/ssrRenderAttrs.spec.ts
- packages/shared/src/domAttrConfig.ts
- packages/shared/src/normalizeProp.ts
> fix(normalizaProp): support css variable as number

- packages/compiler-core/__tests__/transforms/vIf.spec.ts
- packages/compiler-core/src/utils.ts
> fix(compiler-core): avoid duplicate keys with `v-if`

- packages/compiler-core/__tests__/transforms/vOn.spec.ts
- packages/compiler-core/src/transforms/vOn.ts
> fix(compiler-core): function expression support arrow function type in typescript

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/compileScript.ts
fix #6757 
[preview](https://deploy-preview-6778--vue-sfc-playground.netlify.app/#eNptUE1PwzAM/StWLu0k0t4YKtskhDhwgjvh0GXuyGg+lLgbVdX/jrtB2QGf8vye/Zw3iIcQimOHohKrpKMJBAmpCxvljA0+EgywR3rsYkRHzy5R7TTCCE30FjKezJRTTntmWKrpi7n1PyP54kY5OFeIPiQW7bAxDl8nlA+/JIAhtBVcNQCoD1jBy/aAmuY1U/GKumupgnwB6w3kw/hnAzDO76s2WkOz+RODlL9lujX6M3tf3Cu3Ki85cAIM+JbQ1oSMACZybogbcUlI2joUh+QdZ3i+Wv0QSYn5H0pwVBNW4oMopKosdxha38sQ8WjwJG+XyzspWSVToyV79PvoO7crHFJrmr6oQyiZLmLnyFgsMFm5jf6UMLK9EpPRqNwoxm9RoZkP)
> fix(sfc-compiler): fix duplicated declarations of macros

- packages/shared/__tests__/normalizeProp.spec.ts
- packages/shared/src/normalizeProp.ts
[Not Fixed Demo](https://vue-next-template-explorer.netlify.app/#eyJzcmMiOiI8ZGl2IHN0eWxlPVwiXG4gICAgICBib3JkZXI6IDFweCBzb2xpZCB0cmFuc3BhcmVudDtcbiAgICAgIGJhY2tncm91bmQ6IGxpbmVhci1ncmFkaWVudCh3aGl0ZSwgd2hpdGUpIHBhZGRpbmctYm94LFxuICAgICAgICByZXBlYXRpbmctbGluZWFyLWdyYWRpZW50KFxuICAgICAgICAgIC00NWRlZyxcbiAgICAgICAgICAjY2NjIDAsXG4gICAgICAgICAgI2NjYyAwLjVlbSxcbiAgICAgICAgICB3aGl0ZSAwLFxuICAgICAgICAgIHdoaXRlIDAuNzVlbVxuICAgICAgICApO1xuICAgIFwiPlxuPC9kaXY+Iiwic3NyIjpmYWxzZSwib3B0aW9ucyI6eyJpbmxpbmUiOnRydWV9fQ==)
---
[Fixed Demo](https://deploy-preview-6777--vue-sfc-playground.netlify.app/#eNqlkUFOwzAQRa8yMhsq1Q5IlEihIHEPb9x4mhoS2xq7aaOqd8cOoYXADm8sv/njr/lzYq/ei36PrGLriJ1vVcQXaQHW2vQQ4tDis2QZ5LNxpJEquPdHCK41GiIpG7witPHpolL1e0Nub3UFrbGoiDektEma28PORFzCeC3AK62NbfjGHZdf3QCEHlXMfN591QDwh5XG5lsbwE1d13D …
> fix(shared): parse multi-line inline style

- packages/runtime-core/src/apiDefineComponent.ts
- packages/runtime-core/src/componentOptions.ts
- packages/runtime-core/src/componentPublicInstance.ts
- packages/runtime-core/src/index.ts
- packages/runtime-dom/src/apiCustomElement.ts
- test-dts/defineComponent.test-d.tsx
- test-dts/defineCustomElement.test-d.ts
When using `inject` option api, I can't get `foo` in `this` type. 
```js
props: ['a'],
inject: {
foo: 'foo'
},
created() {
//  ts throw error：Property 'foo' does not exist 
console.log(this.foo)
}
})
```
I create a PR that infering `this.foo` as a `unkown`. Maybe can fix issues below.
close #5931 
close #3031
link #5216
> fix(types): support this type with `inject` option api

- packages/vue/macros.d.ts
> fix(reactivity-transform): typing without initial value

- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/compileScript.ts
> fix(compiler-sfc): check source for user imported bindings

- .github/workflows/ci.yml
https://github.com/nodejs/release#release-schedule
Node.js 18 has been LTS now, and 16 is `Maintenance`.
> ci: upgrade node to 18

- packages/compiler-core/__tests__/parse.spec.ts
- packages/compiler-core/src/parse.ts
Fix #6352
track 1c0a2c6
[playground](https://deploy-preview-6828--vue-sfc-playground.netlify.app/#eNqtU8uO2zAM/BWuLmmBlY30UCwCb4DeeumtQC+6KBaduLAeEOmkgeF/L23nAXRb9LE9WeRQnBlaHNSHlIpjj2qjKqpzmxgIuU9bE1qfYmYYIGMDIzQ5elhJ6coEE+oYiMHTHp4n/M3qI3ZdhC8xd+5h9daEqlzaSSMJGH3qLKNEABUlG7ZNjFIznQS/fAF2Ns93rzFUD1rD5wPCDrt4Eq7gMBNYAqOqw3r7CYnsHjdVKQEsKk6zCqNA64XQtUeoO0v0bNQ+RmfUnDf8osOSHobZ2jhKMN0vpcECTdHfKPoDQTt71SPAz/TcKFuCOnqPgaG2PSEBiwyZVT2J4RNimDOHNdjg5iPjNwaOAotQH4/orhoAbi5f6XEh+YW7PtimwZrRrX/ncmrzWilRTOf/Jejl2F2UoYd4mf+/jP9RzvfLMy79iS239f3X3G38OJCqvO2SelTLjmpvU/GVYpAtHuayC0BGbWDOTDnZ3Sk26sCcaFOWDlMXzzplPLZ40u+f3j1pLVWamloLx3mfYx9cEZC7tjkXNqVS4CL3gVuPBZLXuxxPhFnojZqI5DGNavwO4EZqDw==)
> fix(compiler-core): keep whitespaces with newline between interpolation and comment

- packages/runtime-core/__tests__/components/BaseTransition.spec.ts
- packages/runtime-core/src/components/BaseTransition.ts
> fix(Transition): should not be updated again after unmounted (#6835)

- packages/runtime-dom/types/jsx.d.ts
Issue: https://github.com/johnsoncodehk/volar/issues/1985
With `@types/node` version >= 18.8.1, `MouseEvent extends Function` is true, but with version <= 18.8.0 `MouseEvent extends Function` is false.
Close #6899
> fix: stricter type condition for `EventHandlers`

- packages/reactivity-transform/__tests__/__snapshots__/reactivityTransform.spec.ts.snap
- packages/reactivity-transform/__tests__/reactivityTransform.spec.ts
- packages/reactivity-transform/src/reactivityTransform.ts
closes #6838
---
Fixed cases:
- [case 1](https://deploy-preview-6840--vue-sfc-playground.netlify.app/#eNpNT1tqwzAQvIoQgdhQSX1RirFDS6+hH8fepGplaZHWCSb47l3XbYi+NA9mdi7yHVGfRpCVrHOXHJLIQCPubOhiyCQ+29B7+PCu+xaNKErR7MTFBiFWeXMltw+PT9t/IXrQPh6LTVGWNsw21GZN51wGBAP6lmBBVO9HohjEW7eUNFbeVFrJFsFvRfytzWpnvjbXHHkn3YAxkRpa1F85Bh70e6b9E7KV1Xr4wvHiBXMXEebKmB7Qx0lhgpODs3p5fb5Xil0qHzrFHdMxxTH0OgB5d5h0i2hY1mkM5AbQkAe1T/GcIXG9lUsRz57l/AOGIHfb)
- [case 2](https://deploy-preview-6840--vue-sfc-playground.netlify.app/#eNqlkNtqwzAMhl9FmF4kUDs7MUZoC3sP32SJ2mXEtpCdlBDy7pPXMUZ72cv/IH1Ci3onMtOIqla72HJPCSKmkQ7Wt8HHBBvYQ1HC/gCPT8/WX+wwoBnCqdgUZWn9rrpMyoyIhI6GJqEogGUB6cC65tZforaqdxQ4adeQ+YrBC37JffsbRKtq+HGyJ/dlbdVnShTrquqQhjBrYpx6POvXt5cHraWl47HVwphPHEbfGY9p6I+zaYgqiQ2PPvUODUanPzicI7Lgrdr+I1ViTsia0XfIyPeTrxbe0DNcHrSq9Rv0 …
> fix(reactivity-transform): don't overwrite scope and user imports

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/__snapshots__/compileScriptPropsTransform.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/__tests__/compileScriptPropsTransform.spec.ts
- packages/compiler-sfc/src/compileScript.ts
closes #6960
---
Reproduction:
- [Before](https://sfc.vuejs.org/#eNp9j81OwzAQhF9l5UtBapK7lRbxBtwxh5Bugqv6R7ubcrD87qwLQggkTvbMzn6aLeYx5/66obFm5Jl8FmCULcNliuvBGWFnji7OKbJAgefdktLuxYI+UOEAJ1x8xCdKmcfS3AcLLOTjCvV4d+/iOHxiFaJCMOTLJKgKoNwWoNaW+p6YvfEhJ5IuTLk/c4rarbS8+xpoJQs3p3lavmln3kQy22HgZW4XnblPtA7662mL4gP2yKF7pfTOSAp2Zv+DMah5ReoI4wkJ6T/mr+gfbsPqUdXUD6OkemQ=) | [After](https://deploy-preview-6963--vue-sfc-playground.netlify.app/#eNo9TstOwzAQ/JWVLwUJOwekSkRpEX/AHXMIySYYJfbK3rSKLP8764J6Ws1jZyarNyJz2VC1qktDdMSQkDeCpffzySpOVp2tH4JPDBk+DlMIh88W5ECBE4w4OY/vMVDqcmVfW0gcnZ+hnB8ere+av1gJEcC40tIzCgLItwcopbruinpSbqUQWa89mZ8UvGzL1W//BZnUwo2pnIyv2KpvZkpt04xIS9g1Rbw4vOrjy/FZa3HpNA1aOvY5hs2PxiMvbtpNT9SIbOLm2a1oMK36K4Zrwij1VtUimVhU+QWOdmkC)
- [Before](https://sfc.vuejs.org/#eNp9j01Ow0AMha9izSaNlJ99FIqQOAB7hk …
> fix(compiler-sfc): resolve computed object key

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/compileScript.ts
[Before](https://sfc.vuejs.org/#eNpNUFtugzAQvMrKPwGJgPKLaKpKPUAP4B+HGuIIP+RdiiLku3cNpKr8Yc/s7nh2VvERQv0za9GKDvtoAgFqmgNMyo1vUhBKcZUOYDF0/9SDmifC4lsPxumv6AN2a64CDN6/t8CUNag75Z7bFMBNReaRonFjZtK1KCs4hhQ+XZ9Hi/JFMbkoQ3DZYar2e9SUpfY+SflE9hkdnC6n/62plK5r9lXYAgPSNkyK9GZoXfN3kNIBWHMDXfPXJiphbPCRzlaF+oHecTibO3kUOJP25VcKTi9jKe5EAdumwaHPkT6w9nFs+FXH2ZGxutZoz7foF9SRhaXYDEuXRPoFHSSCLw==) | [After](https://deploy-preview-6972--vue-sfc-playground.netlify.app/#eNpNUNFqwzAM/BXjl7ZQJ3QPGwtZx2AfsA/wi9sqqUdiG0tpCMH/PjlpR/GDudNJOt0sv0IobgPIStZ4jjaQQKAhiM649kNLQi2P2gkxWrp+Q2OGjnB7gcY6+Ik+YD3nqhCN95+VYKq3CLVx09IlxMlE5pGidW1m0nG724t7k8HJnXPrdvegmByNJXFYYdqvfwuUR606TflF9hmd2Bw2z9K0064u11PYAgOCPnSGYDE0z3mdSOkOeOYC6vJfJvfS9sFHUr0JxS96x+Es7vS9wJlUD79acnoZa3klCliV5QVC5ycVItwsjOr1/e1FKVYpbM6Kd0xt9IO7FA6os81UmBBKLhdxcGR …
> fix(compiler-sfc): missing keywords of method property

- packages/compiler-sfc/__tests__/__snapshots__/cssVars.spec.ts.snap
- packages/compiler-sfc/__tests__/cssVars.spec.ts
- packages/compiler-sfc/src/cssVars.ts
This bug will affect dev mode only.
closes #6803
---
ATM, #6815 hasn't been merged. So reproduction cannot reproduce on SFC playground.
Reproduction:
```vue
<script setup>
import { ref } from 'vue'
const 蓝色 = ref('blue')
const 字体 = ref(800)
</script>
<template>
<div class="text">
hello
</div>
</template>
<style>
.text {
color: v-bind(蓝色);
font-weight: v-bind(字体);
}
</style>
````
> fix(compiler-sfc): escape non-word characters of css var

- packages/runtime-core/src/compat/compatConfig.ts
The compatibility warning for `@hook:` events currently recommends using the `@vnode-` prefix instead. However, the docs page linked in the warning message suggests using `@vue:`. I believe the latter is preferred.
There is a related PR in the migration guide repo: <https://github.com/vuejs/v3-migration-guide/pull/16>. That attempts to change the docs back to match the current warning. I believe it is the warning that should be changed rather than the docs, but either PR would make the two consistent.
> chore(compat): change 'vnode-' to 'vue:' in event hooks warning

- packages/runtime-dom/__tests__/patchStyle.spec.ts
- packages/runtime-dom/src/modules/style.ts
This adds a warning when an object `style` value ends with a semicolon. e.g. `:style="{ color: 'red;' }"`.
When a value ends with a semicolon, the entire value gets discarded, with no apparent error or warning from the browser. If the style already has a previous value then that will be retained, leading to reports of 'reactivity' issues.
Typically when this has been reported on Vue Land it has been for complex values, such a gradients. Consider this example:
[SFC Playground](https://sfc.vuejs.org/#eNpNUsturDAM/RUrvdIwVwOkV+qGMr3qsv+QRQMYSEseSsJ0KsS/14G+JBY+xz7HjvHCHp0rLjOyitWh9cpFCBhn9yCM0s76CAu0Vrs5YncCjz2s0Hur4UCigzDCtNaESJkOzimf8eMP28j2dfB2Nin5ZZNlRzg/wCIMkCDO3iR1cZHTjIkD+A/PkzIofT542Sk0MfNDk/1ZvuvgL/y7u4MSbjlfT8DpO57gpu/74/3zblLB4YZzTjOuNFFd7q+jdxGIqN0kIxICeDKtRxkQ4qgCbPZV4mtlaF645Np2 …
> dx(runtime-dom): warn when a style value ends in a semicolon

- packages/runtime-core/__tests__/apiWatch.spec.ts
- packages/runtime-core/src/apiWatch.ts
23e85e21a50926c48dea4f978e212e4301c20037 introduced a regression, this PR fixes it.
fix: #7074
> fix(watch): for immediate watch with single source, ensure cb is called with undefined as oldValue (fix: #7074)

- packages/runtime-core/__tests__/hmr.spec.ts
- packages/runtime-core/src/components/KeepAlive.ts
- packages/runtime-core/src/vnode.ts
> fix(hmr/keep-alive): fix error in reload component (#7042)

- packages/runtime-core/src/components/KeepAlive.ts
- packages/runtime-core/src/vnode.ts
> better shape-flags  bit clear

- packages/runtime-dom/__tests__/customElement.spec.ts
- packages/runtime-dom/src/apiCustomElement.ts
Without this patch, components in custom element mode would only be able to inherit provides from the first ancestor instance, anything provided further up the tree would not be available.
This PR ensures that each instance inherits its ancestors `provides`, ensureing any descendants have access to all provides.
fix: #5096
> fix(runtime-dom): Ensure custom Elements can inherit provides from ancestors (fix: #5096)

- packages/runtime-dom/__tests__/customElement.spec.ts
- packages/runtime-dom/src/apiCustomElement.ts
> fix(runtime-core): custom-element: ensure event names are hyphenated (fix: #5373)

- packages/runtime-dom/__tests__/customElement.spec.ts
- packages/runtime-dom/src/apiCustomElement.ts
defineCustomElement reflects all props as element properties, but it does so only after the element has connected.
When Vue sets props on elements, it prefers to add them via element properties if if can find a matching property on the element.
But since `defineCustomElement` sets these property getter/setters only after the element has connected, they don't exist when Vue is looking for them during mount.
This means that we can't do this:
```html
<my-el  :object-prop="{ some: 'object' }" />
```
because it will end up as an attribute containing `[object Object]`.
We have to do use the `.prop` modifier:
```html
<my-el  :object-prop.prop="{ some: 'object' }" />
```
...but not all web frameworks support such a feature.
This PR is a refactoring that ensures that the element property …
> fix(runtime-core: ensure customElements have set domprop listeners synchronously if possible.

- packages/runtime-dom/src/apiCustomElement.ts
if you use KeepAlive and CustomElement.CustomElement will not recreate.so the property of "_resolved" would be "true",it means that should update it
- fix #6934
> fix(runtime-dom): use KeepAlive and CustomElement at same time(#6934)

- CHANGELOG.md
Update outdated documentation link for migration build
Before: https://v3.vuejs.org/guide/migration/migration-build.html
After: https://v3-migration.vuejs.org/migration-build.html
> chore: update changelog link to migration build

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/compileScript.ts
> fix(compiler-sfc): never skip Function prop type

- packages/runtime-core/src/apiCreateApp.ts
- test-dts/appUse.test-d.ts
This enables type inference for:
1. The `options` arg of a plugin's `install` function
2. The options passed to `createApp().use()`
```typescript
/**
* Plugin
*/
type PluginAOptionType = {
option1?: string;
option2: number;
option3: boolean;
}
const PluginA = {
install(app: App, ...options: PluginAOptionType[]) {
}
}
const PluginB = {
install(app: App) {
}
}
/**
* Main
*/
createApp({})
.use(PluginA, { option3: true }) // ❌ option2 (required) missing
.use(PluginA, {}) // ❌ option2 and option3 (required) missing
.use(PluginA) // ✅
.use(PluginA, { option2: 1, option3: true }) // ✅
.use(PluginA, { option1: 'foo', option2: 1, option3: true }) // ✅
.use(PluginB) // ✅
.use(PluginB, {}) // ❌ unexpected plugin option
```
[demo](https://www.typescriptlang.org/play?#code/PQKhFgCgAIWgVAngBwKbQCaoMYBsC …
> types(runtime-core): enable plugin option types

- packages/shared/src/domTagConfig.ts
> chore: add `hgroup` to supported `HTML_TAGS` (fix: #6313)

- packages/compiler-core/__tests__/__snapshots__/parse.spec.ts.snap
- packages/compiler-core/__tests__/codegen.spec.ts
- packages/compiler-core/src/ast.ts
- packages/compiler-core/src/codegen.ts
- packages/compiler-core/src/transform.ts
- packages/compiler-sfc/src/compileScript.ts
- packages/compiler-ssr/__tests__/ssrInjectCssVars.spec.ts
- packages/compiler-ssr/src/ssrCodegenTransform.ts
relate https://github.com/vuejs/core/pull/6664#issuecomment-1259213080
> refactor(compiler-core): make ast.helpers a Set

- packages/vue/__tests__/Transition.spec.ts
Complete the TODO:
https://github.com/vuejs/core/blob/c454aa5cd069d1ed56aca958a7dc8adb14ab7f72/packages/vue/__tests__/Transition.spec.ts#L331-L335
> test(Transition): events with arguments

- .github/contributing.md
I changed the dependency graph to the mermaidJS syntax to have a better graphical representation.
GitHub already [supports it](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/) and will be easier to maintain in the future using just text definitions.
You can preview the end result [here](https://github.com/isflavior/core/blob/contributing-docs/.github/contributing.md#package-dependencies).
> docs(contributing): change dependency graph to mermaid syntax

- packages/runtime-core/__tests__/scopeId.spec.ts
- packages/runtime-core/src/renderer.ts
Exchange the order of `setScopeId` and `props initiate`, and update the test case. #6923
> Exchange the order of `setScopeId` and `props initiate`

- packages/compiler-core/src/validateExpression.ts
`typeof` is actually a prohibited keyword. There was a mistake in the comment. I just fix the comment and ordered the keywords so it's easier to read and identify this kind of error in the future.
> chore: comment and order keywords in list alphabetically

- packages/compiler-sfc/__tests__/compileScriptPropsTransform.spec.ts
- packages/compiler-sfc/src/compileScript.ts
- packages/reactivity-transform/__tests__/reactivityTransform.spec.ts
- packages/reactivity-transform/src/reactivityTransform.ts
> fix(reactivity-transform): respect const keyword

- packages/runtime-core/__tests__/componentProps.spec.ts
- packages/runtime-core/src/componentProps.ts
> fix(runtime-core): custom type props warning

- packages/runtime-core/src/vnode.ts
- packages/runtime-dom/__tests__/customElement.spec.ts
> fix(customElement): customElement can emit event

- packages/runtime-dom/types/jsx.d.ts
Some elements are missing the `referrerpolicy` attribute, such as `ImgHTMLAttributes`. So I add or update it according to the latest `@types/react`.
> fix(types): add or update referrerpolicy

- packages/compiler-sfc/__tests__/__snapshots__/compileScriptPropsTransform.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScriptPropsTransform.spec.ts
- packages/compiler-sfc/src/compileScript.ts
hi :wave: this PR fix #7460.
It allow declaring multiple variables with a single variable declaration.
this would fail because of a `return` which has been changed to `continue` in this pr 
`const   {hello} = defineProps(['hello']), test = "HALLO"`
> fix(compiler-sfc): allow declaring variables after defineProps

- packages/runtime-dom/__tests__/patchStyle.spec.ts
- packages/runtime-dom/src/modules/style.ts
[demo](https://sfc.vuejs.org/#eNp9UttOwzAM/RWTl4K0NRKPXcdF/EZeenG3bs1FiTtAU/8dJ+1QAYmnxPbx8fFJruLVufwyoihEGRrfO4KANLonZRT12llPcAWPHUzQeashY3C2Kr5Z7ZZKLmMQ2RgAEEEDEnRDdYB95LgnP+KDMqWcR8UhpiTUbqgIOQIo65HIGnhphr4575VYuu/iqUTCADTHyhwwMacmOXcl0WVSVAT6HPDW/wxZbX2LvoBH9wHBDn3LgtpdBsWttK0tc+g1oh6q5rzLeGyZVmP+Un7LFRsxe7DVlctPwRo28Zo2XwpBiQJSJubYlxgrcSRyoZAydE006xRy6w+Sb7kfDfuKOQa9rb19D+iZWInNikNy8sJyPRpWjf4/zl/QP7yRdlJm4lVuTxc/ws8XafvLYjthoNnvObcyQxkxfQFGTMkN)
> fix(runtime-dom): style update error when component use shorthand properties

- packages/reactivity/__tests__/reactiveArray.spec.ts
`Array.concat` returns a new instance
```javascript
test('read only copy methods', () => {
const res= original.concat([3, ref(4)])
const raw = toRaw(res)
expect(isRef(raw[1])).toBe(true)
expect(isRef(raw[3])).toBe(true)
})
```
refactor
```javascript
test('read only copy methods', () => {
const raw = original.concat([3, ref(4)])
expect(isRef(raw[1])).toBe(true)
expect(isRef(raw[3])).toBe(true)
})
```
> test(reactivity): Using toRaw on a raw Array

- packages/runtime-core/__tests__/apiExpose.spec.ts
- packages/runtime-core/src/component.ts
This PR adds a warning when invalid values are passed to `expose()` or `defineExpose()`.
Passing a `ref` directly to `defineExpose()` doesn't work, at least not in dev mode. The template ref on the setup proxy is replaced by the exposed ref, rather than having its value updated. This leads to the confusing scenario where the Vue Devtools show the correct value in the parent, even though the internal ref hasn't actually updated:
[Playground example](https://sfc.vuejs.org/#__DEV__eNqFkctugzAQRX9l5A1EIvY+IpGqqstuqi69oTAUUmNbtiGNIv69Yx5tlEiNxIJ5Hc/ce2FP1vKhR7ZjuS9dawN4DL09SN121rgAF3BYZ3AqQtnACLUzHSQ0kfx2vJ6fm1ZVS4mLJY5YapK6NNoH6M5vWMM+0lLdK7WJJSHgvWk90KdxQAdloRRWUk/PpdNMBukG9geIGKOQK/OZJvM6J+O+sEqyGc6HQvW4IXAu5lvoCgoCdlYVASkCyNdtaY+9ZNOgZCComIurTpax+bxtV1h+9EaTRJdIkEvBS7aDKRNzdGyMJWtCsH4nhK/Lq …
> dx(runtime-core): warn when expose() is misused

- scripts/build.mjs
Fixes https://github.com/vuejs/ecosystem-ci/actions/runs/4022763262/jobs/6912842567#step:8:122
The bug was introduced in https://github.com/vuejs/core/commit/ab45f6f8a27fd4ce8af703c42914a94a10a4017a which replaced `fs-extra` with native `fs`.
The `remove` function in `fs-extra` ["silently does nothing" if the path does not exist](https://github.com/jprichardson/node-fs-extra/blob/f3a7f0beeb5858c628b10010ad819c813c7f3565/docs/remove.md). Meanwhile `fs.rm` would throw [unless the `force` flag is set](https://nodejs.org/dist/latest-v18.x/docs/api/fs.html#fspromisesrmpath-options).
> build: do not throw when running `build --release` for the 1st time

- packages/runtime-core/src/componentOptions.ts
Currently `serverPrefetch()` explicitly requires returning a Promise, making the sync version not acceptable on types.
> fix(types): accept sync `serverPrefetch()`

- packages/runtime-dom/src/components/Transition.ts
As reported in https://github.com/vuejs/core/issues/6253 custom transition classes (e.g. with tailwind) are currently not working when vue is running in compat/migration mode.
This PR just adds a few checks to the `Transition` component to fix this.
We have been running a vue version with this fix applied in production for months and found no problems.
close: https://github.com/vuejs/core/issues/6253
> fix(runtime-core): Support for custom transition classes when running in compat mode

- packages/runtime-core/src/apiSetupHelpers.ts
- test-dts/setupHelpers.test-d.ts
closes #7116
closes #5847 
closes #7487
> fix(runtime-core): cast boolean type for optional props

- .github/workflows/ecosystem-ci-trigger.yml
Inspired by https://github.com/vitejs/vite/blob/main/.github/workflows/ecosystem-ci-trigger.yml with the following modifications:
- Allow all members of the `vuejs` organization to trigger the CI, instead of hard-coding the `allowedUsers` list
- Use a fine-grained personal access token instead of GitHub App, because we already have the `vue-bot` account, no need to create a new App.
- The personal access token needs these permissions:
- Actions: Read and Write
- Pull requests: Read and Write
- The token needs to be added to this repo & the `ecosystem-ci` repo's action secrets, in the name of `ECOSYSTEM_CI_ACCESS_TOKEN`
- https://github.com/vuejs/core/settings/secrets/actions
- https://github.com/vuejs/ecosystem-ci/settings/secrets/actions
Usage:
Add comment on any PR in the following …
> ci: add a ecosystem-ci-trigger workflow

- .github/workflows/canary.yml
- scripts/release.js
Requires an `NPM_TOKEN` secret to be set in https://github.com/vuejs/core/settings/secrets/actions
It should be a granular access token with the write permission to the `@vue` *scope* (NOT *organization*).
---
Implementation details:
- Named as `canary` rather than `nightly` because it runs weekly;
- Runs every Monday at 9 AM GMT+8
- Can be manually triggered via the GitHub Actions interface
- Usage:
- The easiest way is to use this companion package: `npx install-vue-canary` (https://github.com/sodatea/install-vue-canary)
- `npm add vue@npm:@vue/canary` for the latest, or `npm add vue@npm:@vue/canary@3.20230313.0` for a specific version.
- For other core packages, e.g. `@vue/reactivity`, it's `npm add @vue/reactivity@npm:@vue/reactivity-canary`
- Also added `--skip-git` and …
> ci: release canary versions every week

- rollup.config.js
- scripts/release.js
1. correct the rollup config after the package name changed
2. fix the same-day patch version bump of canary releases
> build: fix canary bundling issues

- packages/dts-test/utils.d.ts
- packages/vue/jsx-runtime/dom.d.ts
- packages/vue/jsx-runtime/index.d.ts
- packages/vue/jsx-runtime/index.js
- packages/vue/jsx-runtime/index.mjs
- packages/vue/jsx-runtime/package.json
- packages/vue/jsx.d.ts
- packages/vue/package.json
- tsconfig.json
Based on and supersedes #7083 
Closes #1033
Closes #1034 
- No longer implicitly register global JSX types by default
- This avoid conflict when using Vue in the same project with React
- Global registration must now be done by explicitly importing / referencing `vue/jsx`, or listing it in `compilerOptions.types`.
- Add `vue/jsx-runtime` to support `jsxImportSource` usage
- Can enable globally by setting `compilerOptions.jsxImportSource` to `'vue'`
- Can also opt-in per-file with `/** @jsxImportSource vue */`
---
Note that global JSX types requires explicit opt-in, which is technically a breaking change, but this is a type-only change and the update path is trivial, so it aligns with the [release policy](https://vuejs.org/about/releases.html#typescript-definitions) if we release this in a …
> feat(types/jsx): support jsxImportSource, avoid global JSX conflict

- packages/dts-test/defineComponent.test-d.tsx
- packages/dts-test/h.test-d.ts
- packages/runtime-core/__tests__/apiOptions.spec.ts
- packages/runtime-core/src/apiDefineComponent.ts
The type of `defineComponent()` when passing in a function has changed. This overload signature is rarely used in practice and the breakage will be minimal, so repurposing it to something more useful should be worth it.
Previously the return type was `DefineComponent`, now it is a function type that inherits the generics of the function passed in. The function passed in as the first argument now also requires a return type of a render function, as the signature is no longer meant to be used for other use cases.
Another side effect is that a very specific case of mixins usage breaks:
```ts
const a = {}
const b = {}
mixins: [defineComponent(a), defineComponent(b)],
data() {}
})
```
Note the breakage only happens when calling `defineComponent()` inline in the `mixins` …
> feat(types): `defineComponent()` with generics support

- scripts/release.js
The most recent release was blocked by this issue: https://github.com/vuejs/core/actions/runs/4532193370/jobs/7983273077#step:6:304
> build: don't wait for changelog edits when `--skip-prompts` or `--canary` is specified

- scripts/release.js
See https://github.com/vuejs/core/actions/runs/4527710331/jobs/7973811532#step:6:279
The canary release action should fail if the release script fails.
> build: exit with code 1 on release failure

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/compileScript.ts
- packages/runtime-core/src/apiSetupHelpers.ts
- packages/runtime-core/src/index.ts
- packages/runtime-core/types/scriptSetupHelpers.d.ts
closes #5218
related RFC: vuejs/rfcs#430
> feat(compiler-sfc): add defineOptions marco

- packages/vue/jsx-runtime/index.js
- packages/vue/jsx-runtime/index.mjs
- packages/vue/package.json
The JSX automatic runtime consists of two modules. These modules require different exports.
- `vue/jsx-runtime` is for production. This has the following exports:
- `jsx`
- `jsxs`
- `Fragment`
- `vue/jsx-dev-runtime` is for development. This has the following exports:
- `jsxDEV`
- `Fragment`
Whereas a JSX pragma of the classic runtime accepts children as the 3rd..nth arguments, in the automatic runtime this is passed as the `children` prop. If the JSX element has one child, the `jsx` function is used and `children` is that child. If the JSX element has more, the `jsxs` function is called and `children` is an array of all childrne. If no children are passed, this prop is omitted.
The third argument is the key. In the classic runtime this was part of props.
If the development transform is …
> fix(jsx-runtime): fix automatic runtime implementation

- packages/compiler-core/src/options.ts
- packages/compiler-core/src/transforms/transformElement.ts
- packages/compiler-core/src/transforms/transformExpression.ts
- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/__snapshots__/compileScriptHoistStatic.spec.ts.snap
- packages/compiler-sfc/__tests__/__snapshots__/cssVars.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/__tests__/compileScriptHoistStatic.spec.ts
- packages/compiler-sfc/__tests__/compileScriptPropsTransform.spec.ts
- packages/compiler-sfc/src/compileScript.ts
closes #5750
Introduce a option `hoistStatic` in `script`.
Only enables when there's only one `<script setup>` (enabled by default)
[Before](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj50eXBlIEEgPSBzdHJpbmc8L3NjcmlwdD5cbjxzdHlsZT5cbiAgZGl2eyB3aWR0aDoyMDsgfVxuICBkaXZ7IHdpZHRoOiB2LWJpbmQod2lkdGgpOyB9XG48L3N0eWxlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vc2ZjLnZ1ZWpzLm9yZy92dWUucnVudGltZS5lc20tYnJvd3Nlci5qc1wiXG4gIH1cbn0ifQ==) | [After](https://deploy-preview-5752--vue-sfc-playground.netlify.app/#eNqlkMFqwzAMhl9F+LRB7YxCGWRpoe/hS1qrqUfiCFlJMCHvPifbYbTH3qT/l/T9aFZnIjMOqEpVxSt7EogoA0Fbh+ZolUSrTpII4QxHiMI+NFXxO3myoYqSWswFgPPjDJN3ci/3H1+wPGgw6osP7m3r3jc/39m21U75jnoW3dVkvmMfcpp53bd/Rg5RwqasWo679lbdRSiWReGQ2j5pYhw9Tvrwedhrnad …
> feat(complier-sfc): add `hoistStatic` for `<script setup>`

- packages/compiler-sfc/__tests__/rewriteDefault.spec.ts
- packages/compiler-sfc/src/compileScript.ts
- packages/compiler-sfc/src/index.ts
- packages/compiler-sfc/src/parse.ts
- packages/compiler-sfc/src/rewriteDefault.ts
closes #7038, closes #7041, closes #7078
vite plugin PR https://github.com/vitejs/vite/pull/10888
---
thanks to @btea
> fix(compiler-sfc): analyze export default by AST

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/compileScript.ts
[Demo](https://sfc.vuejs.org/#__DEV__eNqFkEtuwzAMRK8iaBMbiKW9oRgoeoEeQBs3plMF0Qek7C4M372U0wRBCyQ7DcV5JGeRbympeQLZSkNHdCkLgjwlcenD6WBlJis7G5xPEbN4jz6JEaMXO6WLKNadDUZfvdzJIoNPlz4DKyHM5mnHGJlW1YduWa0Umv+MvjfKvbxOaHyf1Jli4H2WYre/H7xGK7ZKqfHUoq38yjlRqzWNx7LKmVTEk+aXwilk50EB+eYT4zcBMtjK/QNDc3EGbBDCAAj4jPmn9R+3YFcbVj7lFsyLTAcYXYAPjInMdhlndL+xqlsxRzfcsF1VP4n5Mcr1B2FooKQ=)
> fix(compiler-sfc): infer props type when TS interface function 

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/compileScript.ts
> fix(compiler-sfc): infer TS Extract&Exclude runtime type

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/compileScript.ts
fix https://github.com/vuejs/core/issues/4294#issuecomment-1361688687
> fix(compiler-sfc): infer TSIntersectionType

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/compileScript.ts
> fix(compiler-sfc): remove comma of macro definition

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/compileScript.ts
> fix(compiler-sfc): export call expression as default

- package.json
- packages/compiler-core/package.json
- packages/compiler-sfc/package.json
- packages/reactivity-transform/package.json
- packages/vue-compat/package.json
- pnpm-lock.yaml
Supports
- [export type *](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#support-for-export-type)
- [const Type Parameters](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#const-type-parameters)
> feat(compiler-core): support `const` modifier in type parameters

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/__snapshots__/compileScriptRefTransform.spec.ts.snap
- packages/compiler-sfc/__tests__/__snapshots__/cssVars.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/compileScript.ts
rename `expose` to `__expose` to avoid duplicate identifier
relate #7890
> fix(compiler-sfc): rename expose variable name

- packages/vue/jsx.d.ts
- packages/vue/types/jsx-register.d.ts
Otherwise, TypeScript will raise TS2322 errors. I have no idea why and
how the fix works. But it does.
Even importing the `ReservedProps` and `NativeElements` types from
`jsx-runtime` instead of declaring them in the module would fail the
tests. I have no idea why, either.
The failing tests are at https://github.com/vuejs/ecosystem-ci/actions/runs/4538928668/jobs/7998297656#step:7:3
JSX DOM interfaces need to be exported too.
After these changes a few more tests are passed in the ecosystem CI: https://github.com/vuejs/ecosystem-ci/actions/runs/4544919366/jobs/8011786793
The remaining ones are mostly related to `expose` types and snapshot tests; the vuetify ones are related to [module declaration augmentation of `@vue/runtime-dom`](https://github.com/vuetifyjs/vuetify/blob/29777628ac8839c05 …
> fix: copy-paste jsx-runtime types for global JSX namespace registration

- packages/compiler-sfc/src/compileScript.ts
relate 4355d2492dccdb175b18d083e20f3ec39a52801f
[demo](https://sfc.vuejs.org/#__DEV__eNqNj9FqwzAMRX/F+GmDpqaMMTBex/5gH+CHhlRdMhJbSGrYCP73yW0ppU99Evf63mNpsZ+I6/kI1tvAHQ0ohkGOaMY2fb8Lb2Paw2FI8EUZOSwxGXPI+cOb3S6msn16jim4c1OzKgQmHFuBqiT0G51a8GZZdJRSAcGd7OCuWbuyw4SZpJlaXP9wTrrQ6bN4eeBolVGd6unGVUfbi6B3bsxdO/aZxb9u3l4cU+c00uxhbpDy71+0q5uqY6AZqCHQ4wjoEdRd5RZdyXpXseUfG0hzjw==)
> fix(compiler-sfc): infer runtime type in defineProps

- packages/dts-test/setupHelpers.test-d.ts
- packages/runtime-core/src/apiSetupHelpers.ts
Reference: https://vue-macros.sxzz.moe/macros/short-emits.html (note only the tuple syntax is adopted)
Provide a more ergonomic syntax for `defineEmits()` with types, by allow passing a type literal where the key is the event name and the value is the arguments type (must be an array type).
```ts
const emit = defineEmits<{
foo: [id: string] // TS named tuple
bar: any[]
baz: []
}>()
emit('foo', 'hi')
// @ts-expect-error
emit('foo')
emit('bar')
emit('bar', 1, 2, 3)
emit('baz')
// @ts-expect-error
emit('baz', 1)
```
> feat(sfc): support more ergnomic defineEmits type syntax

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/compileScript.ts
- packages/dts-test/defineComponent.test-d.tsx
- packages/dts-test/functionalComponent.test-d.tsx
- packages/dts-test/setupHelpers.test-d.ts
- packages/runtime-core/src/apiDefineComponent.ts
- packages/runtime-core/src/apiSetupHelpers.ts
- packages/runtime-core/src/component.ts
- packages/runtime-core/src/componentOptions.ts
- packages/runtime-core/src/componentPublicInstance.ts
- packages/runtime-core/src/componentRenderUtils.ts
- packages/runtime-core/src/componentSlots.ts
- packages/runtime-core/src/h.ts
- packages/runtime-core/src/index.ts
- packages/runtime-core/types/scriptSetupHelpers.d.ts
- packages/runtime-dom/src/apiCustomElement.ts
This PR adds slots type checking for:
- Non-SFC Composition API via the new `slots` option and `SlotsType` utility type.
- SFC w/ `<script setup lang="ts">` via the new `defineSlots` macro.
- Volar will be updated to support `defineSlots` type checking
```ts
import { SlotsType } from 'vue'
slots: Object as SlotsType<{
default: { foo: string; bar: number }
item: { data: number }
}>,
setup(props, { slots }) {
expectType<undefined | ((scope: { foo: string; bar: number }) => any)>(
slots.default
)
expectType<undefined | ((scope: { data: number }) => any)>(slots.item)
}
})
```
```vue
<script setup lang="ts">
const slots = defineSlots<{
default: { foo: string; bar: number }
}>()
</script>
```
`SlotsType` and `defineSlots` also support using direct function types to declare …
> feat: add `defineSlots` macro and `slots` option

- scripts/setupVitest.ts
- tsconfig.json
> test: add setupVitest to tsconfig

- package.json
- packages/size-check/brotli.js
- pnpm-lock.yaml
- scripts/build.js
we don't need `brotli` as devDependencies now.
Comparison:
Signed-off-by: JayFate <37610029@qq.com>
> chore: replace brotli with node:zlib

- packages/reactivity/src/reactive.ts
- packages/reactivity/src/ref.ts
Remove redundant type assertion. In the isFunction function, source is determined to be of type Function.
> chore(reactivity): remove unnecessary type assertions.

- packages/runtime-core/__tests__/componentEmits.spec.ts
- packages/runtime-core/src/apiSetupHelpers.ts
- packages/runtime-core/src/componentOptions.ts
Fixes: https://github.com/vuejs/core/issues/7989
> fix(runtime-core): merge props and emits strategy

- packages/compiler-sfc/src/script/resolveType.ts
I just noticed this small typo while experimenting with upcoming 3.3's long-awaited imported types support.
Definitely not trying to farm contributions, just pointing at the typo. Feel free to ignore this PR if you'd rather push a fix along with an actual contribution :) And thank you so much for all the work put into these imported types, this will definitely be a game-changer to a lot of people!
> chore: fix typo in `compiler-sfc`'s thrown error

- packages/shared/src/globalsWhitelist.ts
many many times, I have to add this code at every vue project,  for log something at template
It's pretty boring and disgusting.
`app.config.globalProperties.console = 'console'` or `const console = window.console`
I don't think this is a very rare sense, that use log at template
I'm curious to know why this feature is not turned on
What harm could it do, THANKS
more https://github.com/vuejs/core/pull/3450#issue-835751911
> chore: PLEASE consider support console in template.

- packages/compiler-sfc/src/script/resolveType.ts
> fix(compiler-sfc): normalize windows paths when resolving types

- packages/shared/src/domAttrConfig.ts
`inert` attribute supported by all major browsers: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inert#browser_compatibility
closes #8208
> feat: add inert attribute support

- packages/runtime-core/src/components/BaseTransition.ts
- packages/runtime-core/src/components/KeepAlive.ts
- packages/runtime-core/src/components/Suspense.ts
- packages/runtime-core/src/components/Teleport.ts
This PR make built-in components slots navigable. Look to document (https://vuejs.org/guide/built-ins/suspense.html) these slots seems do not have binding variables so there just keep it empty.
> feat(types): add slots types for built-in components

- packages/runtime-dom/__tests__/patchProps.spec.ts
- packages/runtime-dom/src/modules/props.ts
> fix(runtime-dom): check attribute value before set option value

- packages/dts-test/setupHelpers.test-d.ts
- packages/runtime-core/src/apiSetupHelpers.ts
fix #8310
fix #8331 
fix #8325
Allow support for `defineProps` generics when using `withDefaults`.
There's a limitation to allows this to be smoother, default of generics are only allowed to be declared as `()=>T`  even if `T` is an native type
> types(withDefaults): Allow to be used with generic defineProps

- packages/compiler-sfc/src/script/defineProps.ts
The inferred type at this point is `['null']` and I don't think it can ever be the `UNKNOWN_TYPE` due to the code here https://github.com/vuejs/core/blob/a374d7e6ed973cde7fae36ee82618cf46a8ba68a/packages/compiler-sfc/src/script/defineProps.ts#L210
If it can be the `UNKNOWN_TYPE` via some other path, then I think would need to check for both. Null should be an allow any type so it shouldn't even bother trying to validate it default value here also,
closes #8326
> fix(compiler-sfc): props destructing default value type checking with unresolved type (#8326)

- scripts/release.js
Fixes errors like https://github.com/vuejs/core/actions/runs/4924472857/jobs/8797539690#step:6:332
> workflow: respect `--skipGit` on `pnpm publish`

- packages/compiler-sfc/__tests__/compileScript/__snapshots__/defineEmits.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript/defineEmits.spec.ts
- packages/compiler-sfc/src/script/defineEmits.ts
- packages/compiler-sfc/src/script/resolveType.ts
> fix(compiler-sfc): support type references in unions

- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/script/importUsageCheck.ts
> fix(compiler-sfc): parses correctly when inline mode is off

- packages/runtime-core/src/component.ts
- packages/server-renderer/__tests__/render.spec.ts
Warning: I'm just a monkey with a wrench - I don't know what I am doing.
Looking at the PR of https://github.com/vuejs/core/pull/6184 I think this might be something close-ish to the right fix. It at least fixes the tests I hallucinated together. 😄
Maybe @danielroe would be interested in reviewing this fix too?
close #7733
> fix(ssr): reset current instance if setting up options component errors (fix #7733)

- packages/compiler-sfc/src/script/defineModel.ts
- packages/compiler-sfc/src/script/definePropsDestructure.ts
There is currently an extra space between `experimental  feature`
> fix(compiler-sfc): typo in experimental feature warnings

- .github/contributing.md
The contributors' link have jumped to Vue2, changed to Vue3.
> chore: fix contributors link

- packages/vue/compiler-sfc/index.browser.js
- packages/vue/compiler-sfc/index.browser.mjs
- packages/vue/package.json
- pnpm-lock.yaml
- Don't require `typescript` and call `registerTS` function in browsers.
- Reduce the bundle size used in browsers.
- Add `typescript` as a peer dep.
> fix: don't register typescript in browsers

- packages/sfc-playground/index.html
- packages/sfc-playground/package.json
- packages/sfc-playground/src/App.vue
- packages/sfc-playground/src/Header.vue
- pnpm-lock.yaml
relate: https://github.com/vuejs/repl/pull/121
~Waiting for vue/repl to be merged and further improved~
https://github.com/vuejs/core/assets/32354856/723ebf32-a465-495c-a325-f39021d52c2d
> workflow: add light theme for sfc playground

- packages/runtime-core/src/apiCreateApp.ts
- packages/runtime-core/src/directives.ts
- packages/runtime-core/src/renderer.ts
- packages/runtime-core/src/vnode.ts
Hey! 👋
In TypeScript 4.8, we recently added some stricter checking around unconstrained generics being incompatible with emptyish object types (things that are effectively `{}` or `{ [key: string]: ... }`, etc. The changes are only in nightly versions of TypeScript right now, but we've been exploring how open-source projects have been impacted. These are the changes necessary for Vue's core repo to build cleanly in TypeScript 4.8.
> fix(types): propagate type parameter constraints for TypeScript 4.8

- packages/sfc-playground/src/Header.vue
The size of button content is larger than inner a tag and has set `cursor: pointer` so when we click the padding part of button will not open github
> fix(playground): fix github button style

- packages/shared/src/general.ts
- before
```ts
const event = 'click'
capitalize(event) // string
toHandlerKey(event) // string
```
- after
```ts
const event = 'click'
capitalize(event) // "Click"
toHandlerKey(event) // "onClick"
```
> types(shared): improve capitalize types

- packages/compiler-sfc/src/style/preprocessors.ts
Custom preprocessor options to stylus doesnot work.
reference: https://github.com/stylus/stylus/issues/2585 https://github.com/vitejs/vite/issues/2857
> fix(compiler-sfc): pass options directly to stylus

- packages/compiler-sfc/src/style/cssVars.ts
When I use scss, if I write v-bind and comment it out, the v-bind line of css is still compiled as a css variable
Here is a default project I created using "@vue/cli 4.5.15"
```
<template>
<div id="nav">
<router-link to="/">Home</router-link>|
<router-link to="/about">About</router-link>
</div>
<router-view />
</template>
<script setup>
const color =  "yellow"
</script>
<style lang="scss">
#app {
font-family: Avenir, Helvetica, Arial, sans-serif;
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
text-align: center;
color: #2c3e50;
}
#nav {
padding: 30px;
// background-color: v-bind(color); 
a {
font-weight: bold;
color: #2c3e50;
&.router-link-exact-active {
color: #42b983;
}
}
}
</style>
```
The line is actually commented out by css, but the v-bind variables are …
> fix(compiler-sfc): v-bind using // to comment will still compile

- packages/runtime-dom/src/jsx.ts
https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLImageElement/loading
close https://github.com/vuejs/core/issues/3691
> types(runtime-dom): add missing `img` attr `loading`

- packages/runtime-dom/src/jsx.ts
Normally, when we binding `:style` to an array of multiple objects in common HTML elements, ts wouldn't hint a type error. But if we do this in SVG elements, ts would hint a type error. 
_when we binding `:style` in common HTML elements:_
_when we binding `:style` in SVG elements:_
SVGAttributes.style type may be `StyleValue`, since vue compiler can parse this correctly.
> fix(runtime-dom): SVGAttributes style hint type error

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/script/importUsageCheck.ts
> fix(compiler-sfc): check used import bindings for template `ref`

- packages/reactivity/__tests__/ref.spec.ts
I think it is more recommended to use Vitest's way instead of manual counting.
> test(reactive): use vitest `vi.fn` instead of counting manually

- packages/runtime-dom/__tests__/directives/vOn.spec.ts
- packages/vue-compat/__tests__/utils.ts
According to https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent, use `Event` instead.
> test: replace deprecated `initEvent`

- package.json
- packages/runtime-core/src/apiAsyncComponent.ts
- packages/runtime-core/src/apiDefineComponent.ts
- packages/runtime-dom/src/apiCustomElement.ts
- pnpm-lock.yaml
Rollup now supports marking a function as sied-effect free: 
- https://github.com/rollup/rollup/pull/5024
It's a common pitfall in tree-shaking component libraries. For example
```ts
export const RouterView = defineComponent(...)
export const RouterLink = defineComponent(...)
```
```ts
import { RouterView } from './my-route.ts
```
It seems `RouterLink` should be tree shaken, but in reality, because `defineComponent` is a bit complex that Rollup can't know whether it contains side-effects, causing it still remain in the bundle even if it's not been used.
A solution to that is to add the `__PURE__` comment to mark them as pure. But that requires to do so every single time, which can easily be forgotten.
```ts
export const RouterView = /*#__PURE__*/ defineComponent(...)
export const …
```
> perf: mark `defineComponent` as side-effects-free

- packages/dts-test/setupHelpers.test-d.ts
- packages/runtime-core/src/apiSetupHelpers.ts
Before:
```ts
const props = withDefaults(defineProps<{ active?: boolean }>(), {
active: undefined
})
props.active // boolean
props.active.toString() // error!
```
After:
```ts
const props = withDefaults(defineProps<{ active?: boolean }>(), {})
props.active // boolean
const props = withDefaults(defineProps<{ active?: boolean }>(), {
active: undefined
})
props.active // boolean | undefined
```
Also matches the following usages:
```ts
export default defineComponent({
props: {
active: {
type: Boolean,
required: false,
default: undefined
}
},
setup(props) {
props.active // boolean | undefined
}
})
```
---
Related to: https://github.com/vuejs/core/issues/8576
> types(withDefaults): improve the type of boolean attribute value

- packages/runtime-dom/src/apiCustomElement.ts
We should disconnect `MutationObserver` in `disconnectedCallback` and set it to null for better garbage collection.
> perf: cancel `MutationObserver` listener when disconnected

- packages/reactivity/src/baseHandlers.ts
encapsulate reactive handlers in class:
- `BaseReactiveHandler`: has the `get` function that all reactive objects use
- `MutableReactiveHandler`: extend `BaseReactiveHandler` with `set`, `deleteProperty`, `has`, `ownKeys`
- `ReadonlyReactiveHandler`: extend `BaseReactiveHandler` with `set` & `deleteProperty` warners
> refactor(reactivity): encapsulate reactive handlers in class

- packages/runtime-core/__tests__/apiWatch.spec.ts
- packages/runtime-core/src/apiWatch.ts
In certain scenarios, there are instances when I only need to use the `watch` function to monitor data changes once. For example, when detecting duplicate submissions of a form. Currently, my approach involves calling the `stop` function within the callback, but this method lacks elegance. Hence, I have introduced an `once` parameter to the `watch` function. When the `once` parameter is set to `true`, it automatically stops monitoring after the initial change is detected.
Now:
```ts
const formData = ref({
name: 'John',
age: 18
})
const stop = watch(formData, (newVal, oldVal) => {
console.log(newVal, oldVal)
stop()
})
```
Expect: 
```ts
const formData = ref({
name: 'John',
age: 18
})
watch(formData, (newVal, oldVal) => {
console.log(newVal, oldVal)
}, { once: true })
```
> feat(runtime-core): add `once` option to watch 

- packages/compiler-sfc/src/index.ts
- packages/compiler-sfc/src/script/defineEmits.ts
- packages/compiler-sfc/src/script/defineProps.ts
- packages/compiler-sfc/src/script/resolveType.ts
internal API, for babel plugin usage
downstream: https://github.com/vuejs/babel-plugin-jsx/pull/664
> feat(compiler-sfc): expose resolve type-based props and emits

- packages/runtime-core/src/hydration.ts
At the moment I think the console log is misleading.
The text here labelled 'Client' is in fact the server rendered HTML. I think reversing these two labels might be better.
> fix(runtime-core): swap client/server debug labels

- packages/compiler-core/src/index.ts
- packages/compiler-dom/src/index.ts
#4537 
The dev environment has a more friendly error message when compiling a template that reports an error. But the prod environment has only one error code
```
SyntaxError: Element is missing end tag.  # dev
```
```
SyntaxError: 24  #prod
``` 
we can add error-messages export for better production bug and error report 
```
import {errorMessages, DOMErrorMessages} from '@vue/compiler-dom'
const errorLogProd = 'SyntaxError: 24'
const code = errorLogProd.split(':')[1].trim()
const message = errorMessages[code] || DOMErrorMessages[code]
sendErrorReport(message ...) // Invalid end tag.
...
```
> feat(compiler-core): export error message

- packages/runtime-core/src/index.ts
Relate #9165 https://github.com/vuejs/docs/pull/2515
> feat: export runtime errors

- packages/runtime-core/src/compat/instance.ts
According to https://v2.vuejs.org/v2/api/#Vue-set, the expected behavior is:
> Returns: the set value.
> fix(compat): return value of vue compat set()

- packages/compiler-sfc/__tests__/templateTransformAssetUrl.spec.ts
- packages/compiler-sfc/src/template/transformAssetUrl.ts
- packages/dts-test/defineComponent.test-d.tsx
See https://github.com/vuejs/vitepress/issues/2596. 
When including an image into a markdown file, most tools must encode the space to render the image in preview mode.
But the encoded space will fail the vitepress building process due to the `import` statement containing the encoded path. So we need to decode it back when it's an absolute path.
> Using space in the filename is a bad idea, but the operating system allows it, and many automatic processes will generate a filename with space, so I hope we can support it!
The `transformAssetUrl` will use `parseUrl` to the asset path, which encodes the path.
> feat: support space contained in the filename for asset

- packages/compiler-ssr/__tests__/ssrScopeId.spec.ts
- packages/compiler-ssr/src/transforms/ssrTransformTransitionGroup.ts
> fix(compiler-ssr): TransitionGroup owns style-scoped properties on SSR

- .eslintrc.cjs
- scripts/build.js
We have excluded the `no-unused-vars` rule for TypeScript (`.ts`) files in our existing ESLint configuration, as TypeScript inherently checks for unused variables. However, if we don't configure this rule, ESLint won't perform the `no-unused-vars` check for TypeScript files. Nevertheless, we do need to enable this rule for JavaScript (`.js`) files to ensure that variables defined in JavaScript files are also being utilized.
```diff
-    'no-unused-vars': [
-      'error',
-      // we are only using this rule to check for unused arguments since TS
-      // catches unused variables but not args.
-      { varsIgnorePattern: '.*', args: 'none' }
-    ],
+    {
+      files: ['*.js'],
+      rules: {
+        // We only do `no-unused-vars` checks for js files, TS files are checked by …
```
> chore(eslint): update eslint `no-unused-vars` rules

- packages/compiler-ssr/__tests__/ssrVModel.spec.ts
- packages/compiler-ssr/src/transforms/ssrVModel.ts
close #9440
BTW, support `optgroup`
> fix(ssr): render initial selected properly

- packages/compiler-sfc/__tests__/compileScript/resolveType.spec.ts
- packages/compiler-sfc/src/script/resolveType.ts
Closes #8671
Closes https://github.com/vuejs/vue-loader/issues/2048
`dirname` is the safest way to get a directory name from a path string.
As for this specific bug, it's because
`path.posix.join(AnyWindowsPathUsingBackSlashes, '..')` returns `.`.
I'm not sure whether there will be unexpected regression if I modify the `joinPaths` utility, so I changed the smallest possible bit of code to fix this.
> fix: correctly resolve types from relative paths on Windows

- packages/runtime-core/__tests__/scheduler.spec.ts
- packages/runtime-core/src/scheduler.ts
Fixes #7576.
There is an existing PR to fix this issue, #7622, but I believe it introduces some new problems. The changes to `findInsertionIndex()` that I'm proposing here are quite different to the changes in that PR, so I decided it was better to open a new PR rather than just adding review feedback to the existing PR.
The additions to the first test case are exactly the same as in #7622, confirming that this fix also fixes the original problem. I've then added an extra test case, checking some of the edge cases that #7622 misses.
Whether the new job is `pre: true` doesn't affect the insertion point. Either way, the job should be inserted after any `pre` jobs with the same id. If there is a job with the same id without `pre: true` (there can only be one in the active part of the queue) …
> fix(runtime-core): ensure jobs are in the correct order

- packages/runtime-core/__tests__/hydration.spec.ts
- packages/runtime-core/src/hydration.ts
closes #6152
When hydrating a teleport inside a component will cause the warning `Hydration completed but contains mismatches.`, caused because the lookhead of teleport start was based on being always the next sibling when teleport is disabled the next sibling is the content.
> fix(ssr): Using teleport disabled causes mismatch

- packages/runtime-core/src/components/Suspense.ts
- packages/vue/__tests__/e2e/Transition.spec.ts
closes #5844 , #5952
`Suspense` was executing `effects` before the Transition ended.
> fix(Suspense): mount runs too early when used in Transition

- packages/compiler-core/src/transforms/vSlot.ts
- packages/compiler-ssr/__tests__/ssrComponent.spec.ts
- packages/compiler-ssr/src/transforms/ssrTransformComponent.ts
- packages/compiler-ssr/src/transforms/ssrTransformSuspense.ts
close #7095
the root cause see https://github.com/vuejs/core/issues/7095#issuecomment-1321084603
> fix(compiler-core):  proper scope analysis for ssr vnode slot fallback

- vitest.e2e.config.ts
- vitest.unit.config.ts
Merge the `vitest` configurations using the `mergeConfig` function.
> chore: use helper function for merging vitest config

- packages/runtime-core/__tests__/apiOptions.spec.ts
- packages/runtime-dom/__tests__/customizedBuiltIn.spec.ts
- packages/vue-compat/__tests__/global.spec.ts
- packages/vue-compat/__tests__/instance.spec.ts
- scripts/setupVitest.ts
The commonly used APIs in vitest are global, so there is no need to import.
> chore: remove unnecessary imports from vitest

- packages/compiler-core/__tests__/transforms/__snapshots__/transformExpressions.spec.ts.snap
- packages/compiler-core/__tests__/transforms/transformExpressions.spec.ts
- packages/compiler-core/src/transforms/transformExpression.ts
fixed #9482
When there is a naming conflict between variables in bindingMetadata and global variables, prioritize the variables in bindingMetadata.
> fix(compiler-core): fix conflicts between template variables and global variables

- packages/runtime-dom/src/jsx.ts
> types(runtime-dom): update aria-relevant type

- packages/compiler-sfc/__tests__/compileScript/__snapshots__/defineProps.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript/defineProps.spec.ts
- packages/compiler-sfc/src/script/resolveType.ts
[reproduction](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCBDb21wIGZyb20gJy4vQ29tcC52dWUnO1xuY29uc3QgZXJyID0gbmV3IEVycm9yKCdoZWxsbycpO1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPENvbXAgOm1zZz1cImVyclwiIC8+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vc2ZjLnZ1ZWpzLm9yZy92dWUucnVudGltZS5lc20tYnJvd3Nlci5qc1wiXG4gIH1cbn0iLCJDb21wLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5kZWZpbmVQcm9wczx7XG4gIG1zZzogc3RyaW5nIHwgRXJyb3Jcbn0+KCk7XG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbnt7bXNnfX1cbjwvdGVtcGxhdGU+In0=)
Obviously this list of types doesn't currently cover all Web APIs, and I also don't think "find one, add one" is a good way.
> fix(compile-sfc): Support define Error as prop type

- packages/reactivity/src/computed.ts
`computed` internally uses `Object.is` to compare whether the old and new values ​​have changed. This is valid for primitives, but cannot compare objects (this is the correct behavior).
We can expose the `computed` last value for getter, so the user can decide whether to return the last value for object to pass `Object.is`.
```ts
const a = ref(1);
const b = ref(2);
const c = computed(oldValue => {
if (oldValue && oldValue[0] === a.value && oldValue[1] === b.value) {
return oldValue;
}
return [a.value, b.value];
});
```
```ts
import isEqual from 'lodash.isequal';
const a = ref(1);
const b = ref(2);
const c = computed(oldValue => {
const newValue = { a: a.value, b: b.value };
return isEqual(oldValue, newValue) ? oldValue : newValue;
});
```
Another alternative is to provide `isEqual` …
> feat(reactivity): expose last result for computed getter

- packages/compiler-core/__tests__/transforms/vBind.spec.ts
- packages/compiler-core/src/transforms/vBind.ts
- packages/compiler-sfc/__tests__/__snapshots__/compileTemplate.spec.ts.snap
- packages/compiler-sfc/__tests__/compileTemplate.spec.ts
```vue
<template>
<input v-bind:value />
<input :value />
<input .value />
<input :value.attr />
<input :value-key.camel />
</template>
```
> feat(compiler-core): support shorthand syntax for v-bind

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/script/importUsageCheck.ts
close #9493 
Due to the dynamic directive argument cannot contain spaces, this means it cannot be a possible TypeScript expression. I think it just need to strip out the string.
> fix(compiler-sfc): properly handle dynamic directive arguments usage check

- packages/runtime-core/__tests__/components/Suspense.spec.ts
- packages/runtime-core/src/components/Suspense.ts
- packages/runtime-core/src/vnode.ts
The actual use case comes from Vue Router when doing:
```vue
<router-view v-slot="{ Component }">
<transition mode="out-in">
<keep-alive>
<suspense>
<component :is="Component"></component>
<template #fallback>
<div>
Loading...
</div>
</template>
</suspense>
</keep-alive>
</transition>
</router-view>
```
`Component` will be `null` initially (initial navigation) or when nothing is matched. The warning could be avoided by using `<component v-if="Component" :is="Component" />` but I think having the warn could be confusing for users as they would be looking for a multi-node root they don't have
I also added missing tests for the existing warning
> fix(warn): avoid warning on empty children with Suspense

- packages/compiler-sfc/src/script/context.ts
fixed #9560
In the `resolveParserPlugins` function, `plugins` is not initially configured to include the possibility of `decorators`. Therefore, we should check if `userPlugins` contains `decorators`.
> fix(compiler-core): fix `resolveParserPlugins` decorators check

- packages/reactivity/__tests__/readonly.spec.ts
- packages/reactivity/__tests__/shallowReadonly.spec.ts
- packages/reactivity/src/collectionHandlers.ts
clear on readonly collections return the proxy
```javascript
const warp = readonly(new Map())
console.log(warp.clear() === warp)  // true
```
This fix now return undefined
```javascript
const warp = readonly(new Map())
console.log(warp.clear())  // undefined
```
> fix(reactivity): clear on readonly collections return undefined

- packages/dts-test/defineComponent.test-d.tsx
- packages/runtime-core/src/apiDefineComponent.ts
- packages/runtime-core/src/componentPublicInstance.ts
Fixes #5885
```ts
// never
type Foo = {
size:  'small' | 'big'
} & {
size: number
}
```
> fix(types): props type is incompatible with setup returned type

- packages/dts-test/tsx.test-d.tsx
- packages/runtime-dom/src/jsx.ts
> fix(types): allow undefined in `StyleValue`

- packages/runtime-core/src/components/Teleport.ts
- packages/runtime-dom/src/jsx.ts
`ImgHTMLAttributes` missing the `loading` attribute, more see [MDN](https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading#images_and_iframes).
Also I sync some new properties from latest `@types/react`.
> fix(runtime-dom): update type definition for jsx

- packages/dts-test/setupHelpers.test-d.ts
- packages/runtime-core/src/apiSetupHelpers.ts
Props should also be read-only in the following two cases:
```ts
const props = withDefaults(defineProps<{ name?: string }>(), {})
props.name // readonly
```
```ts
const props = withDefaults(defineProps<{ name?: string }>(), {
name: ''
})
props.name // readonly
```
> types(withDefaults): enhance read-only type

- packages/runtime-core/src/hydration.ts
In the basic renderer, we inject `__vnode` on dev for devtools to grab it. We missing that information in SSR as we didn't do so in hydration.
https://github.com/vuejs/core/blob/a6ae876c54cc218479b8ff3bc09b59070d9b72a6/packages/runtime-core/src/renderer.ts#L689-L698
> fix: hydration `__vnode` missing

- packages/compiler-sfc/__tests__/compileScript/__snapshots__/defineProps.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript/defineProps.spec.ts
- packages/compiler-sfc/src/script/defineProps.ts
- packages/compiler-sfc/src/script/utils.ts
- packages/compiler-sfc/src/style/cssVars.ts
fixes https://github.com/vuejs/core/issues/8635
fixes https://github.com/vuejs/core/issues/8910
fixes https://github.com/vitejs/vite-plugin-vue/issues/184
---
The first and second issues were caused by [`RegExp.test()` called on stateful regular expression with `g` flag](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test#using_test_on_a_regex_with_the_global_flag:~:text=Using%20test()%20on%20a%20regex%20with%20the%20%22global%22%20flag)
```js
const re = /a/g
re.test('a') // true
re.test('a') // false
re.test('a') // true
re.test('a') // false
```
---
The third issue was caused by a missed dash in the `escapeSymbolsRE` regex
I decided to fix the second issue in this pull request in order to include it to the new test case to avoid possible merge …
> fix(compiler-sfc): consistently escape type-only prop names

- packages/compiler-sfc/__tests__/compileStyle.spec.ts
- packages/compiler-sfc/src/style/pluginScoped.ts
> feat(compileStyle): support `:is` and `:where` selector

- packages/runtime-core/__tests__/apiWatch.spec.ts
- packages/runtime-core/src/apiWatch.ts
> fix(reactivity): onCleanup also needs to be cleaned

- package.json
This commit [chore: fix sfc-playground build](https://github.com/vuejs/core/commit/90588534110b929eabadcd88d98e1e9ec8569f1f) changed package script `build-compiler-cjs` to `build-all-cjs`, while that in dev-sfc-prepare was left out.
> chore: fix dev-sfc-prepare command

- packages/dts-test/appUse.test-d.ts
- packages/runtime-core/src/apiCreateApp.ts
fix CI issue https://github.com/vuejs/ecosystem-ci/actions/runs/6925726707/job/18836836250 
Probably because the type is just to complex to resolve as `Component`
I've seen this issue, other way to fix is to offload the component to a variable
```ts
// Too complex
awesomeFunction(defineComponent(/* ... */))
// works
const c = defineComponent(/* ... */)
awesomeFunction(c)
```
> types: support `app.component` to be `defineComponent`

- packages/compiler-core/src/errors.ts
- packages/runtime-core/src/errorHandling.ts
relate https://github.com/vuejs/docs/pull/2515
> refactor(compiler-core): link errors to docs on prod

- packages/compiler-core/__tests__/transforms/transformExpressions.spec.ts
- packages/shared/src/globalsAllowList.ts
> feat(compiler-core): support Error in template

- packages/dts-test/functionalComponent.test-d.tsx
- packages/runtime-core/src/component.ts
Expose events to props for consumer of components to be correctly typed, `onX` handlers where not exposed as such the interface for functional components is incorrect for consuming FunctionalComponents in parent components.
Before:
```tsx
const Foo: FunctionalComponent<{}, { change(): void }> = () => {}
// type error: Property 'onChange' does not exist on type '...'
<Foo onChange={() => {}} />
```
After: 
```tsx
const Foo: FunctionalComponent<{}, { change(): void }> = () => {}
// No type error:
<Foo onChange={() => {}} />
```
> fix(runtime-core): expose events to props for functional components

- packages/runtime-core/src/customFormatter.ts
#5502 ,  may not it's not the best color, but at least it's a bit clearer
before:
after:
> chore: acceptable color in dark mode for custom formatter

- packages/compiler-sfc/__tests__/compileScript/__snapshots__/defineModel.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript/__snapshots__/defineProps.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript/__snapshots__/definePropsDestructure.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript/defineModel.spec.ts
- packages/compiler-sfc/__tests__/compileScript/definePropsDestructure.spec.ts
- packages/compiler-sfc/src/script/defineEmits.ts
- packages/compiler-sfc/src/script/defineProps.ts
close #9500
ensure `mergeDefaults` and `mergeModels` can be treeshaken
> fix(compiler-sfc): generate more treeshaking friendly code

- packages/compiler-core/__tests__/parse.spec.ts
- packages/compiler-core/__tests__/transforms/transformExpressions.spec.ts
- packages/compiler-core/src/ast.ts
- packages/compiler-core/src/babelUtils.ts
- packages/compiler-core/src/options.ts
- packages/compiler-core/src/parser.ts
- packages/compiler-core/src/transforms/transformExpression.ts
- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/__tests__/utils.ts
- packages/compiler-sfc/src/parse.ts
- packages/compiler-sfc/src/script/importUsageCheck.ts
Use proper AST analysis to perform import usage check.
close #8897
close https://github.com/nuxt/nuxt/issues/22416
This PR also adds two new parser options (both are already transform options, they just now also apply to the parser):
-  `prefixIdentifiers`
- `expressionPlugins`
When enabled, `SimpleExpression` and `CompoundExpression` nodes now also has an `ast` property attached, which is the Babel AST parsed from the original JS expression. During the transform phase, `transformExpression` will reuse the ASTs if they are already present on expression nodes.
`SFCParseOptions` from `@vue/compiler-sfc` now also gets a new `parseExpressions: boolean` option. Since this is required for the new import usage check to work, it is enabled by default. The only case where you'd want to disable it …
> feat(compiler-sfc): analyze import usage in template via AST

- packages/server-renderer/__tests__/ssrComputed.spec.ts
- packages/server-renderer/src/render.ts
> fix(ssr): ensure computed only run once during render

- packages/compiler-sfc/__tests__/compileScript/resolveType.spec.ts
- packages/compiler-sfc/src/script/resolveType.ts
> fix(compiler-sfc): support infer generic type

- packages/vue/src/index.ts
closes #9618
create multiple template caches depending on app options
> fix(app): prevent template from being cached between apps with different options

- packages/shared/__tests__/toDisplayString.spec.ts
- packages/shared/src/toDisplayString.ts
closes https://github.com/vuejs/core/issues/9727
[playground](https://deploy-preview-9731--vue-sfc-playground.netlify.app/#eNqNUstOwzAQ/JWVhdRElFRVbyVUgqoHkHiIcvShId20aR3b8qMPovw7tkMDSKjitrszo51Zuya3UiY7i2RMUp2rUhrQaKycUF5WUigDNSgsoIFCiQp6jtqjnPJccG2gOj5mEm48I+K4B9dFcXztCYXluSkFB8GnrMy3UQw15dBKkl3GLCZuUzQ/Vu+CRXG/hQEMalPy1RgWX9XVRf1LVH4gXMKwWfS9oPHrGsq7Nf8o00Eb1YUE1xmsJMsM+hbS9XBStwubJh24zvM7CukTo134olwlGy24u1vwTUkuKlkyVM/Sx9aUjE+JKMkYE/uHMDPKYjAeNGvMt3/MN/rgZ5S8KNSodkhJh5lMrdC08Gz+hAdXd2AllpY59hnwFbVg1ntsaXeWL53tH7zg9j68vjv/m54dDHJ9CuWNhsMHPiXuR0zPRP+2O0pGQeeeizSfaxfTmw==)
> fix(render): Prevent error when displaying symbol keys on a map

- packages/runtime-core/__tests__/apiWatch.spec.ts
- packages/runtime-core/src/apiWatch.ts
- packages/runtime-core/src/renderer.ts
- packages/runtime-core/src/scheduler.ts
> fix(watch): should not fire pre watcher on child component unmount

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/__tests__/utils.ts
- packages/compiler-sfc/src/rewriteDefault.ts
- packages/compiler-sfc/src/script/context.ts
upgrade babel, add `importAttributes` and `explicitResourceManagement` for parser plugins.
TypeScript 5.2 already supports these syntaxes.
- [import attributes (stage 3)](https://github.com/tc39/proposal-import-attributes)
- [explicit resource management (stage 3)](https://github.com/tc39/proposal-explicit-resource-management)
relate https://github.com/microsoft/TypeScript/issues/53656
```ts
import json from "./foo.json" with { type: "json" }
import json from "./foo.json" assert { type: "json" } // deprecated & legacy syntax
```
```ts
using foo = useFoo()
```
> feat(compiler-sfc): support import attributes and `using` syntax in TS

- packages/compiler-core/__tests__/transform.spec.ts
- packages/compiler-core/src/transform.ts
When using `nodeTransform`, I have found myself needing the absolute path in which the component is to do filesystem operations, which well cannot be done without that and I don't think a fork of the compiler is warranted for just that ;)
Since we already have this available to infer the component name, why not just pass it in the context to make it available to hooks?
This has no effect to the core and just allows plugins to use the current filename in hooks like `nodeTransforms` and `directiveTransforms`
> feat(compiler-core): add current filename to TransformContext

- packages/compiler-core/__tests__/transform.spec.ts
- packages/compiler-core/src/transform.ts
- packages/runtime-core/__tests__/hydration.spec.ts
- packages/runtime-core/src/hydration.ts
- Include the actual element in the warning message
- Also warn class/style/attribute mismatches
Note: class/style/attribute mismatches are check-only and will not be rectified. This is because the performance overhead of checking and rectifying all props in production will be prohibitively expensive.
The check could potentially lead to false positives so we need to test this in a beta.
close #5063
> feat(ssr): improve ssr hydration mismatch checks

- packages/runtime-core/src/apiCreateApp.ts
- packages/runtime-core/src/index.ts
> types: export object and function plugin

- packages/runtime-dom/src/jsx.ts
> types: export type AriaAttributes

- packages/dts-test/appDirective.test-d.ts
- packages/runtime-core/src/apiCreateApp.ts
- packages/runtime-core/src/compat/global.ts
Right now, when you want to create a typed global directive you have to:
```typescript
import { createApp, type Directive } from 'vue'
const app = createApp(App);
app.directive('custom', <Directive<HTMLElement, string>>{
mounted(element, { value }) {
// `element` has type `HtmlElement`
// `value` has type `string`
}
});
```
Also, if you want to create a `FunctionDirective`, you will have to provide the typings outside, if not, TS will complain:
```typescript
const custom: Directive<HTMLElement, string> = (element, { value }) => {
// `element` has type `HtmlElement`
// `value` has type `string`
};
app.directive('custom', custom);
```
With this PR, you will be able to provide Directive typings without having to import `type Directive` and without having to cast the object/function inline: …
> feat: add types when creating global directives

- packages/runtime-core/__tests__/components/Suspense.spec.ts
- packages/runtime-core/__tests__/hydration.spec.ts
- packages/runtime-core/src/components/Suspense.ts
- packages/runtime-core/src/renderer.ts
*The previous one is closed because I rename the source patch.*
Fixes: #6949 
Fixes: #6463
This is a patch that intended to properly fix crash caused by #6949 , a crash caused by race condition between the component update and component hydration.
There are actually two bugs triggered by doing such actions.
1. The suspense boundary try to render the fallback content even it totally shouldn't (We already have the content of default slot because SSR)
2. The update of the component that wrap async component crashed 
a. Because host node relies on the subTree of async component it wraps.
b. And the async component is not rendered yet.
This pull request does two things.
1. Make patch of fallback content during hydration no-op
2. Delay the patch of content when the subTree is missing until the …
> fix(runtime-core): fix suspense crash when patch non-resolved async setup component

- packages/shared/src/domTagConfig.ts
There are elements that are not there in MathML Core but are part of MathML 3 and 4 and are used by things like mathjax and katex. Adding them to the list here.
> fix: update known MathML tags

- packages/runtime-dom/__tests__/helpers/useCssVars.spec.ts
- packages/runtime-dom/src/helpers/useCssVars.ts
- packages/runtime-dom/src/modules/style.ts
fixed #9821
During the `patchStyle` process, if a string type is passed, it will overwrite the entire `cssText`, leading to the loss of the `useCssVars` variable. In `useCssVars`, I store CSS variables in a private property of the style, which is then collectively set to `cssText` during the `patchStyle` process.
I attempted to use a `MutationObserver` to monitor style changes in all child elements. However, in the scenario where we also need to listen to the `childList` of the `parentNode`, I had to add another `MutationObserver` within the `parentNode`'s observer to simultaneously monitor newly added child elements. This approach introduces complexity to the logic, so I opted for the current solution.
> fix(useCssVars): fix the loss of CSS variables during updates

- packages/compiler-core/src/errors.ts
The @vnode- hooks syntax is now an error in templates since 8abc754d5d86d9dfd5a7927b846f1a743f352364 This commit updates the message to explain that the syntax is no longer supported since v3.4 (and not just a deprecation as it was in v3.3).
> fix(compiler-core): vnode hooks error message

- packages/runtime-core/__tests__/hydration.spec.ts
The comment has been introduced in 2ffc1e8cfdc6ec9c45c4a4dd8e3081b2aa138f1e
> fix(runtime-core): uncomment assertion in hydration test

- packages/runtime-core/__tests__/hydration.spec.ts
- packages/runtime-core/src/hydration.ts
> fix(hydration): handle appear transition before patch props

- packages/runtime-core/__tests__/apiSetupHelpers.spec.ts
- packages/runtime-core/src/apiSetupHelpers.ts
> fix(defineModel): ensure trigger effect when prop changed

- packages/compiler-core/__tests__/utils.spec.ts
- packages/compiler-core/src/utils.ts
- packages/runtime-dom/src/directives/vOn.ts
> fix(compiler-core): fix crash when modifier is empty

- .eslintrc.cjs
- package.json
- pnpm-lock.yaml
Use `import xxx from 'node:xxx' ` to import node built-in modules.
> style: prefer `node:` protocol

- .eslintrc.cjs
- package.json
- pnpm-lock.yaml
- tsconfig.eslint.json
I have added the following rules using the `@typescript-eslint/eslint-plugin`:
- `@typescript-eslint/prefer-ts-expect-error`: replace `@ts-ignore` with `@ts-expect-error`
- `@typescript-eslint/no-unnecessary-type-assertion`: avoid unnecessary type assertions
- `@typescript-eslint/consistent-type-imports`: use the `type` keyword when importing types
- `@typescript-eslint/no-import-type-side-effects`: enforce the use of top-level import type qualifier when an import only has specifiers with inline type qualifiers
- `@typescript-eslint/no-import-type-side-effects`: ensure consistent usage of indexed object access style in TypeScript code
https://typescript-eslint.io/rules/
> style: add `@typescript-eslint/eslint-plugin` plugin

- packages/compiler-core/src/babelUtils.ts
- packages/compiler-sfc/__tests__/compileTemplate.spec.ts
> fix(compile-core): reuse analyzed scope variables if they are already present on node

- packages/runtime-dom/__tests__/customizedBuiltIn.spec.ts
- scripts/setupVitest.ts
The `SpyInstance` type has been deprecated in vitest and is now marked as obsolete. According to the documentation, should replace it with `MockInstance`.
https://github.com/vitest-dev/vitest/blob/039814bd0eb9ed7b7f6e649a1c3def38d5174a5d/packages/spy/src/index.ts#L107-L110
> test: replace deprecated `SpyInstance` with `MockInstance`

- package.json
The current lint script checks all files, causing errors when checking files in directories like dist and temp. In this PR, I have added "--ignore-path .gitignore" to exclude these files from the linting process.
> chore(eslint): eslint ignore .gitignore

- packages/dts-test/watch.test-d.ts
- packages/runtime-core/src/apiWatch.ts
> fix(types): fix defineModel watch type error

- packages/runtime-core/src/apiWatch.ts
Not sure why this import is `@vue/runtime-core`, it should be imported relatively, unless there's a specific reason for this, if there is, it should have a comment
> chore(apiWatch): use relative import location instead of package

- packages/compiler-ssr/__tests__/ssrSlotOutlet.spec.ts
- packages/compiler-ssr/src/transforms/ssrTransformSlotOutlet.ts
> fix(ssr): fix hydration error for slot outlet inside transition-group

- packages/sfc-playground/src/App.vue
Fix #9957
In this PR, I modified the `<Repl>` in `App.vue` of the `sfc-playground` package, adding an automatic execution of `initCustomFormatter()` to `preview-options`.
However, I'm uncertain whether this setting should be applied within `sfc-playground` or if I should directly modify [`Preview.vue`](https://github.com/vuejs/repl/blob/main/src/output/Preview.vue) in [`@vue/repl`](https://github.com/vuejs/repl) to make it the default value.
I would appreciate any opinions on this.
> feat(sfc-playground): init custom formatter when preview

- packages/runtime-core/__tests__/components/Suspense.spec.ts
- packages/runtime-core/src/components/Suspense.ts
- packages/sfc-playground/src/App.vue
> fix(runtime-core): correctly assign suspenseId to avoid conflicts with the default id

- packages/server-renderer/__tests__/ssrSlot.spec.ts
- packages/server-renderer/src/helpers/ssrRenderSlot.ts
- packages/sfc-playground/src/App.vue
> fix(ssr): avoid rendering transition-group slot content as a fragment

- packages/runtime-core/src/apiWatch.ts
Ref: https://github.com/vuejs/core/pull/7330#issuecomment-1872461341
This is solution 1, relatively high risk.
Solution 2: #9949
> fix(watch): remove instance unmounted short circuit in getter of `watchEffect`

- packages/runtime-core/__tests__/apiSetupHelpers.spec.ts
- packages/runtime-core/src/apiSetupHelpers.ts
This PR attempts to fix a problem with the logic for detecting local mode. The problem occurs when the parent uses kebab-case and the child uses camelCase.
Here's an example illustrating the problem I'm trying to fix with 3.4.3:
- [SFC Playground](https://play.vuejs.org/#eNp9Uk2PmzAQ/SsjX0K0BHa1t4hE7W730Eppq37cfGFhCN41NrINSYX47x0bkqZSlJvnvTfDG94M7GPbJn2HbM0yWxjROrDounbLlWhabRwMYLCK4ZC7ooYRKqMbWFDH4qzY/XmuhSxnKknn2o8lEVeFVtZBoTvlYOOnRQ9Lj4eRUcBjiPolbLYwcAXQk2yXuzpp8mN0H89voaI+hof7JTXDNC7pc9khqXuuRoKzdNqB3FPhsGll7pAqgGGYHYyjL7PaBDg7me9XjS5RriutV6+52XAW5JxBSsIsPQ9jMXOWVqrEPnmzWtGfC6Z9Q9MKieZb6wStzNl6WsdzuZT68CVgznQYn/CixuL9Cv5mjx7j7LtBi6ZHzs6cy80eyZmnX35+xSO9zyRt0UlS3yB/oNWy8x4n2VOnSrJ9oQtuP4d0hdr/si9Hh8qelvJGvXIMes4o5+cbq/+z+5g8hj4Ki/7ixZlcub7paEImlG+JlVC481W0oIiecrO4nXdWij48QvTTnCl64l4757SC …
> fix(defineModel): support kebab-case/camelCase mismatches

- packages/runtime-core/src/apiWatch.ts
relate #9572
In #9572, modify `deep` to accept `number` type, allowing control of the depth of the watching object. To prevent users from inadvertently passing other types in previous versions, In the current version, add a warning message.
> chore(apiWatch): constraint deep passes boolean

- packages/runtime-core/__tests__/apiWatch.spec.ts
- packages/runtime-core/src/apiWatch.ts
When this cleanup was first introduced, effectScope did not exist yet. For today, I think it's reasonable to expand this cleanup to general effectScope.
> perf(watch): cleanup scope's effects after effect stopped

- packages/compiler-sfc/__tests__/compileTemplate.spec.ts
- packages/compiler-ssr/src/transforms/ssrTransformComponent.ts
> fix(ssr): clone node support Set and Map

- packages/compiler-core/package.json
- packages/compiler-dom/package.json
- packages/compiler-sfc/package.json
- packages/reactivity/package.json
- packages/runtime-core/package.json
- packages/runtime-dom/package.json
- packages/server-renderer/package.json
- packages/shared/package.json
- packages/vue-compat/package.json
- packages/vue/package.json
In [Nitro](https://nitro.unjs.io/), we create a minimal `node_modules/` just for our final output. This traces the files that are used, respecting the correct export conditions.
At the moment, `NODE_ENV` governs whether we load the prod/dev CJS versions of the Vue packages. However, we can support custom export conditions like `production` and `development` (see [nodejs reference](https://nodejs.org/api/packages.html#community-conditions-definitions)). These have broad community support and can be used on the CLI (for example, with `node --conditions=development index.js`) and by bundlers like Nitro which have support for them.
This PR adds production/development conditions for the Node/CJS bundles. To make it backwards compatible it:
1. adds `./*` as a subpath export so any file that was …
> build: add production/development export conditions

- .eslintrc.cjs
- packages/compiler-ssr/src/transforms/ssrTransformComponent.ts
- packages/runtime-core/src/components/Suspense.ts
- packages/server-renderer/src/renderToStream.ts
- Removes `console.log` that introduced in https://github.com/vuejs/core/pull/9983
- Add an ESLint rules to disallow console statement
> chore: disallow console statement

- packages/reactivity/src/reactiveEffect.ts
The underlying container for collecting effects has been changed from set to map
> docs: dep changed from set to map

- packages/runtime-core/src/components/Suspense.ts
- packages/vue/__tests__/e2e/Transition.spec.ts
> fix(Suspense): correctly update the transition anchor point

- packages/dts-test/tsx.test-d.tsx
- packages/runtime-dom/src/jsx.ts
> types: `value` of `TextareaHTMLAttributes` adds `null` type

- packages/compiler-core/src/parser.ts
Fixes https://github.com/vitejs/vite-plugin-vue/issues/330
I didn't include a test here because I think this case is more like an integration issue, it makes more sense to test that in the `vite-plugin-vue` repository.
> fix(parser): skip compat mode check for SFC root `<template>` tags

- scripts/utils.js
Some packages do not have a package.json, so an error will be reported when you run `build-all-cjs`
> fix(script): an error is reported if package.json does not exist

- packages/dts-test/h.test-d.ts
- packages/runtime-core/src/h.ts
- stricter children/slots type
- fix emits/`EE` type argument of `FunctionalComponent`
fixes downstream https://github.com/sxzz/vue-simple-props
> types: fix functional component for `h`

- packages/compiler-core/package.json
- packages/compiler-dom/package.json
- packages/compiler-sfc/package.json
- packages/reactivity/package.json
- packages/runtime-core/package.json
- packages/runtime-dom/package.json
- packages/server-renderer/package.json
- packages/shared/package.json
- packages/vue-compat/package.json
- packages/vue/package.json
/cc @danielroe #9977 has caused a number of regressions with different causes: #10012, #10020, also got another private report from @lehni in his project.
It seems I merged it to soon and it was indeed risky in a patch. For now I have reverted the exports conditions in 7bd4e9050 to avoid other unknown regressions.
This PR fixes #10012, but I need further confirmation for the other two cases. @Mister-Hope / @lehni would appreciate if you can try this commit in your project to see if it fixes your issue.
I am also not sure if the addition of `module` would intefere with the bundle size gain in Nitro / Nuxt.
> fix(build): add module condition in package exports

- packages/runtime-core/__tests__/hydration.spec.ts
- packages/runtime-core/src/hydration.ts
close #10081 , close #10083 
When the server value of `attr` is `undefined` or `null`, just validate whether actual `el.hasAttribute`
> fix(runtime-core): improve mismatch when client value is null or undefined

- packages/reactivity/__tests__/computed.spec.ts
- packages/reactivity/__tests__/effect.spec.ts
- packages/reactivity/src/computed.ts
- packages/reactivity/src/constants.ts
- packages/reactivity/src/effect.ts
This resolves the regression introduced by #10091 and re-fix #10082.
Also fix a test of #10085, #10090.
> fix(reactivity): `allowRecurse` effects's `dirtyLevel` unreliable

- scripts/dev.js
Need this function for vue-vapor. Commit it to upstream to avoid conflicts on every merge.
> chore: dev build for multi-packages

- packages/reactivity/__tests__/computed.spec.ts
- packages/reactivity/src/effect.ts
close #10114
**This PR will re-introduce the problem of https://github.com/vuejs/core/pull/10085, https://github.com/vuejs/core/pull/10090, but the `computed` would not lose reactivity**
I think this might be a trade-off in short term.
> fix(effect): computed lost reactivity

- packages/reactivity/__tests__/computed.spec.ts
- packages/reactivity/src/computed.ts
- packages/reactivity/src/effect.ts
Re-fix #10114 and resolve #10085 and #10090 regressions introduced in 3.4.14.
> fix(reactivity): re-fix #10114

- packages/runtime-core/__tests__/componentSlots.spec.ts
- packages/runtime-core/src/componentSlots.ts
> fix(runtime-core): should not warn when mounting another app in setup

- packages/runtime-core/src/customFormatter.ts
`isShallow` is inline-imported in [runtime-core.esm-bundler.js](https://unpkg.com/browse/@vue/runtime-core@3.4.15/dist/runtime-core.esm-bundler.js), line 7937
> fix(runtime-core): don't inline isShallow

- packages/runtime-dom/src/directives/vModel.ts
These codes are introduced by https://github.com/vuejs/core/commit/2ffb956efe692da059f4895669084c5278871351 and it's the edge perf.
So I think it's ok to delete it to prevent the options from skipping updates.
close #10194
> fix(runtime-dom): fix option selected update failed

- packages/runtime-core/__tests__/hydration.spec.ts
- packages/runtime-core/src/component.ts
- packages/runtime-core/src/hydration.ts
- packages/runtime-dom/src/helpers/useCssVars.ts
> fix(hydration): v-bind supports hydration

- packages/compiler-core/__tests__/transforms/transformSlotOutlet.spec.ts
- packages/compiler-core/src/transforms/transformSlotOutlet.ts
close #10213 
support use v-bind shorthand syntax for slotName: `<slot :name />`
> fix: support v-bind shorthand syntax for slotName

- packages/reactivity/__tests__/computed.spec.ts
- packages/reactivity/src/computed.ts
- packages/reactivity/src/constants.ts
- packages/reactivity/src/effect.ts
fix #10185, ~~still have to add a test case~~ done.
> fix(reactivity): handle `MaybeDirty` recurse

- packages/runtime-dom/__tests__/directives/vShow.spec.ts
- packages/runtime-dom/src/directives/vShow.ts
- packages/runtime-dom/src/modules/style.ts
According to the [doc](https://vuejs.org/api/built-in-directives.html#v-show). In this [case](https://play.vuejs.org/#eNqNVMtu2zAQ/JUtL0oAR2rqmyC7bYwcWiBp0QQ96SLLa5kxRQoipTgQ9O9dUrYeRR6+UTOzw9klqYZ9Lwq/rpCFLNJpyQsDGk1VLGPJ80KVBhoocTuDHbSwLVUOHqm9WMYyVVIb4Pov13wtEBZWeLFNhMbLE5urTSIezEtPN1RpNlwXInkJwZNKojeLJUCelBmXBF1/Lg4WasnkZEORboRK92RycQmLJZANlfTmfp2ICv2jL6m8tZVTzHZick/bne/hwk0sjMoygXe2ZmrTT6FzIfLTf9DEJ90lMsPjXM5L8za16NuFr+BxKbjEqyNA8xxNIgq6I6bDpQ+DORkYpC+Aphk2aG1SE2147agoOK36lsKm6ddvqqN1ZYyS8C0VPN0vYjaaXsyWK4vCHUZBp7OhzrIZDY9srARg5TDoQFf+geljmUjNDXcS69CLuiWE2nrRdsNcYgb1ld6pZ0L79imCUwCdrEFphj3ISBeJXF5/mdPg7eqIDimCSYwoGB0JmzGjyXPLM/9JK0kP1F0R6l/lBRdY/ipsnY5Z2F0eyyVCqOefDjNlhe5luZodpvtX8Cd9sFjMfpeosaypnZ4z9CLRdPTtwz0eaN2T1HNlm3+H/INaicpm7GQ3ldxQ7JHOpf3hfjNcZo/69kAT1KembFCrbJ0+ZvTfWb3T+hB37s …
> fix(runtime-dom): fix vShow not respect passing display

- packages/runtime-core/__tests__/apiCreateApp.spec.ts
- packages/runtime-core/src/apiCreateApp.ts
> fix(runtime-core): support for nested calls to runWithContext

- packages/reactivity/__tests__/reactive.spec.ts
- packages/reactivity/src/reactive.ts
> fix(reactivity): skip non-extensible objects when using `markRaw`

- packages/runtime-dom/__tests__/directives/vShow.spec.ts
- packages/runtime-dom/src/modules/style.ts
a optimize about #10161，close #10151 and won't lead to the issue in #10294
For an element with `v-show`, when its `style` changes, `el[vShowOldKey]` is assigned as `style.display`, regardless of whether display exists in the style. If `v-show === false` and there is no `display` in `style`, the value of `style.display` is `'none'` at this time, so `el[vShowOldKey]` will also be incorrectly assigned as 'none'.
The correct logic should be: `el[vShowOldKey] = style.display` only when display exists in the next style; otherwise, `el[vShowOldKey] = ''`.
> fix: the value of display is sometimes incorrect with v-show

- packages/runtime-core/src/componentProps.ts
While running some hot path optimisation within a Nuxt application (server-side) I found out that `getType` was creating unnecessary levels of GC.
This PR tries to optimize it by reducing the creation of temporary objects and strings which are the primary contributors to garbage collection (GC) activity. Functions like `toString()` and `match()` can create temporary strings and objects that may increase GC activity if called frequently.
I've validated that the amount of GC was reduced and speed improved.
This benchmark is worth what is worth but give's a rough idea.
<details>
<summary>Micro-benchmark</summary>
```js
// Original getType function
function getTypeOriginal(ctor) {
const match = ctor && ctor.toString().match(/^\s*(function|class) (\w+)/);
return match ? match[2] : ctor === …
```
> perf(runtime): improve `getType()` GC and speed

- packages/runtime-dom/src/directives/vShow.ts
Re-fix #10294 
Should not trigger transition when the old value and the new value of `v-show` are both `false`.
For this case in vuetify:
https://play.vuetifyjs.com/#eNq9VU1vGjEQ/SsjXwCJhVS0PawIUtQeeumlVU7AwbUHYtW7tmwvTYX47xkv2WU/AKFEysn2+M28N/O03uWeeSemD9ZOdgWylM0DZlbzgItVDjDfJYI7CUJz7+9XLHtOeBHMisE/JcMTRWZ3dytWYku0Vj7ALsmMRJ0aizlKAsVNjapxiSIusA7pViZKmDwySJU8mQyJIqigkUI/yuNiPm2kUa1uta0zhYUd10VMevTofIOTcFVnpM9rE1IugtrxYBzB96TDWA+HVkpbajMOVOSPymNzZeKKtW/PdMWFMEUeEqGc0NRQO6Fq9lV387LXeS1u2jCrET47kAeZqaYJbx5Jx7/uHOpOKsJL6i/qvz71TSluuCxpxhAHvKZlBCoHHil7XqR/8T+lqF68UlquvduOhXHpYarhnqlwxbWmP7c4R6aY2NYHeldTfqB7whXydvOujP791t5u3pVwFTy+pHSITykdOoObe+GUPaLw2RoXQOKGFzrA/lhI8sBTGI7gfgHD1xhAfFRTWA7KF2OwHlfx40dANyfVy8FPnvMtZpiHwRgGzecoIyJlNSamCFrl2KgUE39jCCrf+ipNmO0Z5GlXmtgh/+aQmq0qWF34C2S/kMsKtlEXNT1amk …
> fix(runtime-dom): should not trigger transition when the old value and the new value of `v-show` are both `false`

- packages/reactivity/__tests__/computed.spec.ts
- packages/reactivity/src/computed.ts
warn users when computeds are not side-effect-free
refer #10232
> feat(reactivity): warn users when computeds are not side-effect free

- changelogs/CHANGELOG-3.0.md
- packages/compiler-core/__tests__/transforms/vOn.spec.ts
- packages/dts-test/README.md
This PR updates the spelling of 'TypeScript' in several files, ensuring consistency across the Vue 3 codebase. The changes are purely textual and do not affect the functionality of the code.
The following files are updated:
- In `changelogs/CHANGELOG-3.0.md`, the spelling of 'Typescript' is corrected to 'TypeScript'.
- In `packages/compiler-core/__tests__/transforms/vOn.spec.ts`, the test description is updated to use the correct spelling of 'TypeScript'.
- In `packages/dts-test/README.md`, the description is modified to use the standardized spelling of 'TypeScript'.
These changes improve the documentation and code comments' consistency, aligning with the official spelling of TypeScript.
> docs: Standardize Spelling of 'TypeScript' in Various Files

- packages/runtime-core/__tests__/components/Suspense.spec.ts
- packages/runtime-core/src/components/Suspense.ts
> fix(suspense): handle suspense switching with nested suspense 

- packages/runtime-core/src/apiDefineComponent.ts
Component declared using the direct setup syntax now have better support in `.tsx` and `.vue` files.
- PublicProps added and merge with the Props
- vue-language-server will now properly infer generic. The previous behavior of returning `any` caused the language-server to fail to infer the props.
Fixes: 
- #8604
- #8855
- https://github.com/vuejs/language-tools/issues/3745
- https://github.com/vuejs/language-tools/issues/3309
- Maybe more?
It's an alternative to this #9127 PR, but I belive it is more complete here.
> fix(runtime-core) better typing for direct setup

- packages/runtime-core/src/components/BaseTransition.ts
remove unused getTransitionKey
> refactor(runtime-core): remove-get-transition-key

- packages/runtime-core/__tests__/components/Suspense.spec.ts
- packages/runtime-core/src/components/Suspense.ts
> fix(suspense): ensure nested suspense patching if in fallback state

- packages/runtime-core/src/warning.ts
> fix(warning): stringify args in warn handler

- packages/runtime-dom/__tests__/patchProps.spec.ts
- packages/runtime-dom/src/modules/props.ts
> fix(runtime-dom): avoid unset option's value

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/compileScript.ts
> fix(compiler-sfc): use options module name if options provide runtimeModuleName options

- packages/runtime-dom/src/jsx.ts
This PR fixes the [`scroll` event type](https://developer.mozilla.org/en-US/docs/Web/API/Element/scroll_event#event_type) and adds support for the new [scrollend](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollend_event) event.
> types: fix `scroll` event type; add support for `scrollend`

- packages/sfc-playground/src/download/download.ts
- packages/sfc-playground/src/download/template/README.md
When using `download` to download a project in the sfc-playground, the `tsconfig.json` file is being downloaded into the `src` directory. Since the downloaded project is a JavaScript project, I overlooked the `tsconfig.json` file in this PR. vite@4.3.0 requires [Node.js version 14.18+, 16+](https://vitejs.dev/guide/#scaffolding-your-first-vite-project) updated README.md for this.
> chore(playground): save `tsconfig.json` to the root directory; update Node.js version requirement

- packages/template-explorer/package.json
- pnpm-lock.yaml
Most notably, the `source-map-js` package.
Hopefully, it can fix the failing ecosystem-ci test at https://github.com/vuejs/ecosystem-ci/actions/runs/8354053421/job/22866774080#step:7:896
> chore: dedupe dependencies

- .gitignore
- packages/runtime-core/src/hydration.ts
These warnings are currently not shows when that flag is set:
https://github.com/vuejs/core/blob/01172fdb777f9a0b51781ed2015a1ba3824340a3/packages/runtime-core/src/hydration.ts#L799-L815
> fix(runtime-core): show hydration mismatch details for non-rectified mismatches too when __PROD_HYDRATION_MISMATCH_DETAILS__ is set

- README.md
I added a download badge that display the number of download of amazing **Vue.js** framework
> chore: add download badge

- packages/compiler-sfc/__tests__/compileScript/__snapshots__/importUsageCheck.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript/importUsageCheck.spec.ts
- packages/compiler-sfc/src/script/importUsageCheck.ts
> fix(compile-sfc): analyze v-bind shorthand usage in template

- packages/runtime-core/__tests__/hydration.spec.ts
- packages/runtime-core/src/hydration.ts
close #10607 
- when the checkbox is clicked and the slot content is re-rendered, the `STABLE` flag is removed here: https://github.com/vuejs/core/blob/3bf34b767e4dd3cf6a974301ecf0363ae4dda4ec/packages/runtime-core/src/componentSlots.ts#L219-L221. this causing the `processFragment` to exit the optimized mode.
- the `optimized` value here is preserved in `setupRenderEffect` during the hydrate phase of `mountComponent`. However, the value of `optimized` should be true. because the `patchFlag` for slot content with the `STABLE` flag should be `STABLE_FRAGMENT`, and it should enter the `optimized mode` during patching.
```js
function render(_ctx, _cache, $props, $setup, $data, $options) {
return (_openBlock(), _createBlock($setup["TestComponent"], null, {
default: _withCtx(() => [
//....
]), …
```
> fix(hydration): properly handle optimized mode during hydrate node

- packages/runtime-core/src/errorHandling.ts
添加对callWithAsyncErrorHandling函数fn 数组校验
当data.count 被触发更新时， 导致函数调用栈溢出
> fix: fn添加数组校验

- packages/runtime-core/__tests__/components/BaseTransition.spec.ts
- packages/runtime-core/src/components/BaseTransition.ts
- packages/runtime-core/src/components/KeepAlive.ts
> fix(Transition): ensure the KeepAlive children unmount w/ out-in mode

- packages/compiler-dom/__tests__/transforms/validateHtmlNesting.spec.ts
- packages/compiler-dom/src/htmlNesting.ts
- packages/compiler-dom/src/index.ts
- packages/compiler-dom/src/transforms/validateHtmlNesting.ts
According to the HTML spec, `<p><div></div></p>` is not a valid syntax. However, it functions when utilizing the JS DOM API. Consequently, it operates effectively in Vue runtime but fails with SSR. So I introduced this warning on dev mode.
[SSR Demo](https://play.vuejs.org/#__SSR__eNp9kU9LxDAQxb/KmEsVli26npa6oLKgHlRU8JJLaac1a5qE/KmF0u/uJGXXPcjmlHm/l8mbZGS3xiz7gGzNCldZYTw49MFsuBKd0dbDCBYbmKCxuoOMrBlXXFVaOQ+da+Em8vPsAaXU8KmtrM+yC66KfG5Hjajw2BlZeqQKoIjdgVZRi35zebUq8rhJKI+syI/8bMG8o+sa0S53TitKOkYrZ5XujJBoX4wXFIezNSQSWUlpfp6S5m3AxV6vvrD6/kffuSFqnL1adGh75OzAfGlb9DPevj/jQPsD7HQdJLlPwDd0WoaYcbbdBVVT7CNfSvuY3luo9sNtB4/K7YeKQaNzSn7O6A/uT4z+F3e1vE7nuJrY9AvVFKCo)
> dx(compiler-dom): warn on invalid html nesting

- packages/runtime-dom/src/components/Transition.ts
When the transition's enter event is canceled final CSS styles are applied and all transition's *-active styles are removed for a short period so the element is flickering, getting its final state(no transition classes applied) 
https://github.com/vuejs/core/assets/49036220/bb310578-5376-49cd-a08d-bd0993300a79
fix #2482
fix #10677
> transition is breaking/flickering when enter is canceled (fix #2482, #10677)

- packages/compiler-core/__tests__/transforms/__snapshots__/transformElement.spec.ts.snap
- packages/compiler-core/__tests__/transforms/transformElement.spec.ts
- packages/compiler-core/__tests__/transforms/vFor.spec.ts
- packages/compiler-core/src/transforms/transformElement.ts
The ref is resolved at runtime from the object. However, the identifier that the ref is inside a v-for is set at compile time. Due to this, the ref is often set to a random element in the list, typically the last one.
We could set the identifier that a ref is inside a v-for without having the ref props explicitly set, but that would require adding an extra prop to every element inside the v-for that has `v-bind="object"` set. I'm not sure if this approach is worth the added complexity, especially since the extra prop would not be used most of the time.
I'm opening a PR for the team to consider this potential solution. Let me know if you have any other thoughts or suggestions.
fix #10696 
https://github.com/vuejs/core/assets/49036220/82a80ab3-031f-4ab4-9dfe-bf9234f19d10
> fix(compiler-core): Refs inside v-for are not applied through v-bind (fix #10696)

- packages/runtime-core/src/componentSlots.ts
- packages/shared/src/general.ts
> fix(runtime-core): ensure slot compiler marker writable

- packages/compiler-core/src/parser.ts
- packages/reactivity/src/effect.ts
- packages/reactivity/src/reactiveEffect.ts
- packages/runtime-core/src/components/Suspense.ts
Based on https://github.com/vuejs/core/pull/4882#issuecomment-957064008, I believe optional chaining is avoided due to its impact on bundle size. Some recent changes have used the `?.` operator, so I have removed them here.
I have only removed instances that had an impact on the size of `vue.global.prod.js`. Code for SSR or tests or dev hasn't been changed. While some of the replacement code looks a bit verbose, I have confirmed that each change does reduce the size of the unzipped `vue.global.prod.js`.
> refactor: remove optional chaining

- packages/runtime-core/src/apiWatch.ts
This PR simplifies the logic in `traverse()`. It should also shave a few bytes off the bundle.
The current implementation of `traverse()` takes two numbers, the `depth` and the `currentDepth`. The function calls itself recursively, incrementing `currentDepth` at each stage and then comparing that to `depth`.
But there's no need to use two numbers. Just one is enough. Each recursion can just decrement `depth` and then check whether it is still greater than 0.
For `deep: true`, a `depth` value of `Infinity` can be used, rather than trying to handle it specially.
The current depth logic was originally introduced in #9928, partly in preparation for adding #9572. While my proposed changes will introduce small conflicts with that second PR, I believe they are easily fixable, just by treating …
> refactor: simplify traverse() for deep watchers

- packages/runtime-core/__tests__/componentProps.spec.ts
- packages/runtime-core/src/componentRenderUtils.ts
This is a follow up to changes made yesterday: b93f26464785de227b88c51a88328ae80e80d804 and a7cf74277ee57093656faaa7f65610ee7584a507.
Those changes fixed issues #8216 and #10736. There was an existing PR that fixed those issues at #8222. That PR also made `attrs` readonly for functional components. This PR just makes that extra change.
Making the `attrs` readonly allows the test expectation changes in a7cf74277ee57093656faaa7f65610ee7584a507 to be rolled back. The `props` and `attrs` will both be the same `shallowReadonly` proxy.
The `attrs` are already readonly in other places, I believe functional components are the only place where this isn't currently enforced.
Here's a Playground that illustrates the type of code that I'm hoping to prevent:
- [Playground - …
> fix(runtime-core): attrs should be readonly in functional components

- packages/compiler-dom/__tests__/transforms/__snapshots__/stringifyStatic.spec.ts.snap
- packages/compiler-dom/__tests__/transforms/stringifyStatic.spec.ts
- packages/compiler-dom/src/transforms/stringifyStatic.ts
Close #6568.
This fixes an edge case for code like this:
```html
<select v-model="foo">
<option :value="1">...</option>
<option :value="2">...</option>
<option :value="3">...</option>
<option :value="4">...</option>
<option :value="5">...</option>
</select>
```
For 5 or more `<option>` elements, a static VNode is created. But this loses the type information on the `value`, so `v-model` treats it as a string.
- [Playground](https://play.vuejs.org/#eNqFkstOwzAQRX9l5E1B6kN9baoUCVAXsAAELL2J0klJcWzLnoSiKP/O2KEFJNruPPeeSWau3Yhra4d1hWIhEp+5whJ4pMpeSV2U1jiCBhzm0ELuTAk9RntSZ0Z7gtwYWAb34lLqZNS1cyMXhKVVKSFXAIlHhRlBPSjNGtVSCu6UInrsGkuF0bCoU1Uhm2O2xsmok49BE4Ym56ApQ9Nz0Iyh2TloztD8D8T7xq1i0TQxjLaFQTjTp0WTf0shmkMcoi/Ic3p5sRluvdEcexM+IEVmSlsodI/xF16KBUQneKlS5uM+auQq7O/17A2z93/0rd8FTYonhx5djVIcPErdBqmzVy8Pu …
> fix(compiler-dom): restrict createStaticVNode usage with option elements

- packages/runtime-core/__tests__/apiWatch.spec.ts
These tests were inspired by the changes in #9417. I don't think the changes proposed there can be merged as they would break backwards compatibility, but I found it interesting that they didn't cause the existing tests to fail.
It seems we have relatively few tests for `watch(reactiveArray, ...)`, and in particular how it differs from `watch(plainArray, ...)`. I experimented locally and found I was able to introduce various bugs without triggering any test failures.
Here I've aimed to test 3 ways that reactive arrays behave differently from plain arrays when passed as a source to `watch`:
1. If the reactive array contains a function, it should not be invoked.
2. If the reactive array contains a ref, it should not be unwrapped in the `newValue` or `oldValue` passed to the callback.
3. A …
> test(watch): watching a reactive array

- packages/dts-test/README.md
- packages/dts-test/setupHelpers.test-d.ts
Evan was faster than me to fix #10841 but I thought the tests I started to add in my PR could still be useful to prevent future regressions, as the `defineOptions` helper has currently no dts tests
> test: defineOptions dts tests

- packages/runtime-core/src/compat/instance.ts
- packages/vue-compat/__tests__/instance.spec.ts
This fixes https://github.com/vuejs/core/issues/8869. As mentioned in the issue, Vue 2.7 `$scopedSlots` now also supports non-scoped slots (a default slot without scope for example). This PR reflects on that change.
> fix(compat): include legacy scoped slots

- packages/compiler-sfc/__tests__/compileScript/resolveType.spec.ts
- packages/compiler-sfc/src/script/resolveType.ts
> fix(compiler-sfc): handle keyof operator

- packages/runtime-dom/src/jsx.ts
> fix: correct the type of `<details>`'s `onToggle` event handler

- vitest.config.ts
If the newly added folder is not excluded, an error will be reported when running `pnpm test-coverage`.
> test: update coverage exclude

- .github/workflows/size-report.yml
Critical RCE Vulnerability:
An attacker can exploit this vulnerability by uploading files named `scripts/size-report.ts`, which will overwrite the existing file and subsequently execute the injected code.
This flaw grants the attacker the ability to execute arbitrary code in a secure environment that has write permissions to both `pull-requests` and `issues`.
Special thanks to @RedYetiDev
> ci: fix RCE vulnerability in file overwrite

- packages/runtime-core/__tests__/components/Suspense.spec.ts
- packages/runtime-core/src/components/KeepAlive.ts
> fix(KeepAlive): properly cache nested Suspense subtree

- packages/runtime-core/src/components/KeepAlive.ts
- The timing of caching subtree was changed in https://github.com/vuejs/core/pull/1984
- The attr fallthrough / scopedId issue is actually #1511 instead of #1513
> chore: correct the comments in KeepAlive.ts

- packages/runtime-core/src/componentPublicInstance.ts
Use shared utils to replace `Object.assign` and `() => {}`.
> refactor: replace `Object.assign` with `extend`

- packages/runtime-core/src/component.ts
There's an existing warning that's shown when a component doesn't have a template or render function:
> Component is missing template or render function
A common cause of this warning is that the object being used as a component is not actually a component. This typically happens when there's a mistake with the `import`/`export` from a library. The 'component' might actually be a plugin, or an object with a `default` property.
This PR adds the component object to the warning, saving a bit of time trying to debug the problem.
> dx(runtime-core): log the component object when warning about missing template/render function

- packages/compiler-core/__tests__/transforms/transformElement.spec.ts
- packages/compiler-core/src/transforms/hoistStatic.ts
- packages/compiler-core/src/transforms/transformElement.ts
- packages/runtime-dom/__tests__/nodeOps.spec.ts
> fix(compiler-core): should set `<math>` tag as block to retain MathML namespace after patching

- eslint.config.js
- packages/compiler-core/src/babelUtils.ts
- packages/reactivity/src/effect.ts
- packages/runtime-core/src/devtools.ts
- packages/runtime-core/src/hydration.ts
- packages/runtime-core/src/warning.ts
Disallow the use of optional chaining (`a?.b`, `a?.()`), except when running on Node.js.
> chore: disallow optional chaining

- packages/runtime-core/src/components/Teleport.ts
This PR removes a warning when `Teleport` is disabled and its `to` target is not found. [Reproduction link](https://play.vuejs.org/#__DEV__eNqNUstOwzAQ/JXIXEmsqreqVAXUAxwAQY+5pPHSuvgle5NGqvrvrN0HaXmIWzyzuzM7my27da5oG2AjNkbQTlUIk9Jk2XgOCpz1mAkZqoUCkaG9KdkVwRoM5riqMBcWQm4s5tDJgCVLrdQsZDuprUEqHPP4SCP5cSY9x7wnx66Z1JHIdeWKdbCG/GxjT3kgQslGWUIiRobju2QrRBdGnNfCUJsAJVtfGEBunOZTKuO+MSg1kFM9HRbDYjAgPwH7eAFB5wtvNwE8TSnZdU+HE9iCzz0YAR78f3Uv2s60L7hv+lF+V5odxYKBYnyXy4tQaqudVOCfHUprzsOplLKbx4Shb+C0TL2C+uMHfB26/VIvHpKzXgBY+SXQXSM9e3uCjr5PpLaiUYdD/EK+QrCqiR73ZXeNEWS7V5fcPqQbS7Och1lHP004LhWNpjRSfTrI/R+rf9mluE8p7j4B9DP5Uw==).
> fix(teleport): not throw warning when teleport is disabled

- .github/workflows/size-data.yml
- .github/workflows/size-report.yml
In the latest version of `maintain-one-comment`, pr number can be set automatically https://github.com/actions-cool/maintain-one-comment/pull/9
See also https://github.com/vuejs/core/pull/10985#issuecomment-2122885655
> ci: omit pr number

- packages/runtime-core/__tests__/apiWatch.spec.ts
- packages/runtime-core/src/apiWatch.ts
Currently, deep watchers don't traverse symbol properties.
#402 already attempts a fix for this, but that seems to have stalled due to some performance tweaks that were made at the same time. Here I've just tried to fix the core problem with symbols.
String properties are traversed using `for`/`in`. That traverses enumerable properties, including those inherited from the prototype. I didn't want to do anything that might break that, so I've left it untouched.
For symbols I've used `getOwnPropertySymbols` and `propertyIsEnumerable`. This doesn't take the prototype chain into account.
Is traversing symbol properties actually useful? I don't know. If not, perhaps it should be documented that they aren't supported? Currently it's a bit inconsistent, as adding or removing a symbol property …
> fix(watch): deep watching symbol properties

- packages/compiler-core/__tests__/transforms/vFor.spec.ts
- packages/compiler-core/src/utils.ts
> fix(compiler-core): missing source and have with multiple spaces should emit error during compiler

- packages/compiler-sfc/src/compileScript.ts
> fix(compiler-sfc): throw error when import macro as alias

- packages/runtime-core/src/compat/component.ts
*This only affects compat mode*
When a SFC uses `Vue.extend()` to define the component script, the compiler adds the render function as a property on the constructor, not the options object in `.options`
The same goes for internal properties added by the SFC compiler like `__hmrId`.
So when we create a vnode for such a component in compat mode, we have to re-assign these properties to the options object, which we then consequently use to create the actual component from.
If we don't do that, we get a `template or render function missing`error.
fix: #7766
> fix(compat): ensure proper handling of render function from SFC using Vue.extend (fix: #7766)

- packages/server-renderer/src/helpers/ssrRenderSlot.ts
The `s` (dotAll) regexp flag is not supported in ES2015.
See also https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/dotAll
The code is converted by [Babel](https://babeljs.io/repl#?browsers=chrome%2010&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYewdgzgLgBATgUwOYIB4wLwwPQD0A8AhALTEB0AVKQHwAk2EQA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=true&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=true&targets=&version=7.24.6&externalPlugins=%40babel%2Fplugin-proposal-decorators%407.24.1&assumptions=%7B%7D)
> fix(server-renderer): avoid using `s` regex flag

- packages/compiler-core/__tests__/transforms/vFor.spec.ts
- packages/compiler-core/src/transforms/vBind.ts
- packages/compiler-core/src/transforms/vFor.ts
close #10882  
Similar to #10939, this PR arises when the reference to the actual expression (`.exp`) for the `:key` binding is lost. In this PR it is kept correctly.
> fix(compiler-core): fix for :key shorthand patchflag and keep .exp reference

- packages/reactivity/__tests__/readonly.spec.ts
In readonly.spec.ts, use `isReadonly` to test `markRaw` instead of `isReactive`.
> test(reactivity): replace isReactive with isReadonly

- packages/runtime-core/src/component.ts
The `defineExpose` method takes an optional generic to declare the type of the exposed object (it was introduced in https://github.com/vuejs/core/pull/5035). However, it seems like that generic is missing from the type definitions in another file.
I found this error because I'm authoring a library with components that are declared using the generic, but the compiled code is using this other type without the generic and it throws an error.
> fix(runtime): declare generic in expose setup context

- packages/runtime-core/src/hydration.ts
PR for possible fix of this issue: https://github.com/vuejs/core/issues/9369
Having visibility of Hydration errors in production is very important when using large CMS driven Nuxt 3 projects (with async components)
> fix(hydration): log hydration error even when using async components

- packages/runtime-core/__tests__/helpers/withMemo.spec.ts
- packages/runtime-core/src/component.ts
- packages/runtime-core/src/helpers/withMemo.ts
- packages/runtime-core/src/renderer.ts
- packages/runtime-core/src/vnode.ts
> fix(runtime-core): improve v-memo work with v-if

- packages/compiler-sfc/src/compileTemplate.ts
Remove the excessive punctuation
> chore: improve compileTemplate warn message

- packages/compiler-sfc/__tests__/compileScript/resolveType.spec.ts
- packages/compiler-sfc/src/script/resolveType.ts
> fix(compiler-sfc): support as keyword with template literal types

- packages/compiler-sfc/__tests__/compileScript/resolveType.spec.ts
- packages/compiler-sfc/src/script/resolveType.ts
> fix(compile-sfc): Support project reference with folder, fix #10907

- packages/dts-test/reactivity.test-d.ts
- packages/dts-test/watch.test-d.ts
- packages/reactivity/src/index.ts
- packages/reactivity/src/reactive.ts
- packages/runtime-core/src/apiWatch.ts
- packages/runtime-core/src/index.ts
> fix(apiWatch): correct type inference for reactive array

- packages/dts-test/inject.test-d.ts
- packages/runtime-core/src/apiCreateApp.ts
> fix(types): fix `app.provide` type checking

- packages/runtime-core/src/apiSetupHelpers.ts
Change the type from `string` to `number`, because the following code example emits a **number** instead of a **string**.
```ts
const emit = defineEmits<{
// <eventName>: <expected arguments>
change: []
update: [value: number] // named tuple syntax
}>()
emit('change')
emit('update', 1)
```
> docs: fix typo

- rollup.dts.config.js
In Vue versions 3.4.22 and later, the command for building declaration files (.dts) in the `scripts` field of `package.json` has been updated from `"build-dts": "tsc -p tsconfig.build.json && rollup -c rollup.dts.config.js"` to `"build-dts": "tsc -p tsconfig.build-browser.json && tsc -p tsconfig.build-node.json && rollup -c rollup.dts.config.js"`. 
However, the warning message `'no temp dts files found. run tsc -p tsconfig.build.json first.'` in the `rollup.dts.config.js` file, which checks for the existence of `temp/packages` files, has not been updated synchronously. This may lead to confusion or unnecessary troubles for developers.
Should modify the warning message `'no temp dts files found. run tsc -p tsconfig.build.json first.'` in the `rollup.dts.config.js` file to `'no temp dts …
> fix(rollup-plugin-dts.js): update warning message when `temp/packages` directory is missing

- packages/runtime-core/__tests__/rendererFragment.spec.ts
- packages/runtime-core/src/renderer.ts
close #10547
Calling `traverseStaticChildren` on vnodes with `PatchFlags.BAIL` appears to cause unexpected behavior. In development mode, HMR requires `traverseStaticChildren` to ensure static vnode elements (`el`) are correctly updated. However, it seems that for vnodes that are fully diffed (`PatchFlags.BAIL`), this traversal may not be necessary and could lead to issues.
Change:
- Added a check to skip `traverseStaticChildren` for vnodes with `PatchFlags.BAIL`.
> fix(runtime-core): avoid traversing static children for vnodes w/ PatchFlags.BAIL

- packages/compiler-sfc/__tests__/compileScript/resolveType.spec.ts
- packages/compiler-sfc/src/script/resolveType.ts
> fix(compiler-sfc): support keyof for intersection types

- packages/reactivity/__tests__/computed.spec.ts
- packages/reactivity/src/computed.ts
- packages/reactivity/src/constants.ts
- packages/reactivity/src/effect.ts
introduce a new dirty level `MaybeDirty_ComputedSideEffect_Origin` mark which computed is the original side effect one, and treat it different in triggerEffects and dirty judgement
close #11121
> fix(reactivity): avoid infinite loop when render access a side effect computed

- scripts/verify-treeshaking.js
fix a typo `refactoed` -> `refactored`
> chore: fix typo [skip ci]

- packages/reactivity/__tests__/computed.spec.ts
- packages/reactivity/src/computed.ts
- packages/reactivity/src/effect.ts
thanks to @wanghanzhen for `resetTracking` and test case
close #11181, #11169
> fix(reactivity): fix side effect computed dirty level changed unexpected

- packages/runtime-dom/__tests__/customElement.spec.ts
- packages/runtime-dom/src/patchProp.ts
close #11163
In Vue 3.4.28+, the `value` prop for custom elements is being set as an attribute and converted to a string, causing issues when `value` is meant to be an object.
Changes:
- Added a condition to skip setting `form state` as an attribute for custom elements.
> fix(patchProp): prevent setting state as attribute for custom elements

- packages/runtime-core/__tests__/rendererOptimizedMode.spec.ts
- packages/runtime-core/src/renderer.ts
close #11168
The optimized mode's fast path skips the unmount process for dynamic component receiving an exting vnode with component children (component not in `dynamicChildren`), causing the `onUnmounted` hook to be missed, a simplified reproduction in [playground](https://play.vuejs.org/#eNqNVE2Pm0AM/SsWFxIpC0lQLylEald72B7aVT9uo1YIzMcuzKCZgY0U8d/rmWkIjdJ0L1FsP9vPnmeO3oeuC4YevZ0Xq0zWnQaFuu/2jNdtJ6SGI0gsVlDBCIUULfiE9t9P4XvRdn8CQWgMU81nnPFMcKUh66WExNRYrJeUxngYwn2F2QvoCsGARIPWm1H2BsTLlGrtBKqFqbsiJjxtcQe+MTc+jMspbXuRtqW0xRKSPSX7eT34K+B909AY12ptTa2JnMmPdoAHXfMSBi5yhFfnFhw5NajqJpfo0LlAxX0NWtZliRIE/8Fb0XON+ZxQZOf4P5XoTIXe4ZHKyCFtFm6WI+NgFxqQr0f4mcCG8XEFm/V6TcuIQ/eE9HhkaGy7JtVIFkBMnWG4q4uEeaYC86ybAue5drUyUbNcCsfhFLkF3b4dGl2BxiERo39xONH1Vp5WtLmiLoNnJThJ0w7uitQNyi+drmmzzNu5lZhY2jTi9ZP1adnj6uTPjNSu+ …
> fix(runtime-core): ensure unmount dynamic components in optimized mode

- packages/reactivity/src/effect.ts
Cached the result of `dep.get(effect)` to reuse it within the same scope
> refactor(effect): cache tracking value

- packages/runtime-dom/__tests__/patchAttrs.spec.ts
- packages/runtime-dom/src/modules/attrs.ts
This covers an edge case where a web component actually overrides `el.setAttribute` and thus is able to receive non-string values as attribute values (appareantly, extJS web components do this).
This patch ensures that we leave stringification to the browser when patching an element attribute except for the case of symbols, where we need to explicitly stringify it ourselves as the browser would throw an error.
fix: #11177
> fix(runtime-dom): ensure only symbols are explicitly stringified during attribute patching

- packages/runtime-core/src/components/Suspense.ts
- packages/runtime-core/src/components/Teleport.ts
- packages/runtime-core/src/renderer.ts
Not sure if these are left in case these components are plugged-in with other renderers in the future though.
> refactor(built-ins): remove unused code from Teleport and Suspense components

- packages/runtime-core/__tests__/hydration.spec.ts
- packages/runtime-core/src/hydration.ts
> fix(hydration): fix css vars hydration mismatch false positive on attr-fallthrough

- .github/workflows/size-report.yml
* Pass PR number as input
* Migrate to thollander/actions-comment-pull-request. It's most used, frequently updated and allows to pass a file directly
> ci: fix size-report

- .github/workflows/size-report.yml
Follow-up of #11203 (see [this comment](https://github.com/vuejs/core/pull/11203#issuecomment-2185010423))
* comment_tag comes last so GH Actions interpreter doesn't trip with special characters from the previous' input
* The action already encloses the tag with the appropiate hidden markers
> ci: re-fix size report

- packages/compiler-core/__tests__/transforms/transformExpressions.spec.ts
- packages/compiler-core/src/babelUtils.ts
- packages/compiler-core/src/transforms/transformExpression.ts
- packages/compiler-sfc/src/compileScript.ts
- packages/compiler-sfc/src/script/definePropsDestructure.ts
- packages/global.d.ts
close #11216
- Update `parent` type annotations from `Node` to `Node | null` in various functions to reflect the correct type as per [estree-walker’s implementation](https://github.com/Rich-Harris/estree-walker/blob/master/src/sync.js#L9). This ensures type accuracy and prevents potential runtime errors.
> fix(compiler-core): handle inline comments with undefined bindings

- .github/workflows/size-data.yml
- .github/workflows/size-report.yml
I noticed that the [size report action](https://github.com/vuejs/core/actions/workflows/size-report.yml) has not been working recently. 
The failure is due to the action using `github.event.workflow_run.pull_requests[0].number` to read the PR number. However, according to GitHub's security policy (ref: https://github.com/orgs/community/discussions/25220), this approach does not work for PRs from forked repositories as `pull_requests` can be empty.
To resolve this, I have reverted the method of retrieving the PR number to the previous implementation using artifact.
> ci: correct PR number retrieval to fix size-report action

- packages/global.d.ts
- scripts/setup-vitest.ts
- Removed Jest custom matcher types from `global.d.ts`.
- Align with Vitest and keep related type declarations and implementations together.
> chore: move custom matcher types to setup-vitest.ts

- packages/server-renderer/__tests__/unrollBuffer.bench.ts
- packages/server-renderer/src/renderToString.ts
Currently, `unrollBuffer` is an `async` function, which results in approximately a 10x slowdown in a mixed buffer and around a 1.5x slowdown in a synchronous buffer. Any `Promise` on the hot path is a performance killer.
In this PR, `unrollBuffer` will return a `Promise` only if a child buffer does; otherwise, it will always operate synchronously. However, even if a child buffer returns a `Promise`, we can continue to operate synchronously if further nesting is not required for another child buffer.
Of course, there are other functions where something similar happens, such as `renderComponentVNode`, but this requires separate consideration.
Performance was tested on the following hardware:
CPU: `AMD Ryzen 7950x3D`
System: `WSL 2 Arch Linux on Windows 11`
Node.js: `v22.4.0`
Before
```
✓ …
```
> perf(server-renderer): optimize `unrollBuffer` by avoiding promises

- packages/runtime-core/__tests__/componentEmits.spec.ts
- packages/runtime-core/src/helpers/useModel.ts
Closes #4848.
There is an existing PR for this, #4850. This PR includes the commits from that PR, but I thought there was another edge case that needed addressing, otherwise it would cause a regression.
The original PR assumed that the prop would always be written in either kebab-case or camelCase. While this is usually true, it doesn't take account of the possibility that the prop name could be written in neither case convention. In that scenario, an exact match should still work, which is what I've tried to handle here.
I've also switched the new tests from `jest` to `vi`  and added some extra tests.
> fix(runtime-core): v-model modifiers trim and number when cases don't match

- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
Replenish #11317
@yyx990803 When using the pnpm catalog, the `@babel/types` version was incorrectly written.
> chore: use pnpm catalog

- packages/runtime-core/__tests__/apiWatch.spec.ts
fix https://github.com/vuejs/core/issues/8284
> fix(runtime-core): fix watch immediate error not captured in effectscope 

- packages/compiler-sfc/__tests__/compileScript/resolveType.spec.ts
- packages/compiler-sfc/src/script/resolveType.ts
> fix(compiler-sfc): correctly parse type annotation for declared function

- packages/runtime-core/src/hydration.ts
- packages/runtime-core/src/renderer.ts
- packages/runtime-dom/__tests__/patchProps.spec.ts
- packages/runtime-dom/src/modules/props.ts
- packages/runtime-dom/src/patchProp.ts
> fix: When patching the elements that use innerHTML or textContent should first `unmountChildren`

- packages/runtime-core/__tests__/components/Teleport.spec.ts
- packages/runtime-core/__tests__/rendererOptimizedMode.spec.ts
- packages/runtime-core/src/components/Teleport.ts
- packages/runtime-core/src/scheduler.ts
This pull request introduces a new prop for the built-in `Teleport` component: `defer`.
A deferred Teleport will wait until all other DOM content in the same update cycle has been rendered before locating the target container and mounting its children, so this is now possible:
```vue
<Teleport defer to="#target">...</Teleport>
<div id="target"></div>
```
Even if `<div#target>` appears after `<Teleport>`, it can still be resolved. This also works even if `<div#target>` is rendered by other components, as long as they are mounted in the same tick with the component containing the `<Teleport>`.
Another use case for `defer` is inside `<Suspense>`. Previously, `<Teleport>` inside `<Suspense>` will eagerly resolve its target and therefore can only target containers outside of the `<Suspense>`. …
> feat(teleport): support deferred Teleport

- packages/runtime-dom/__tests__/patchProps.spec.ts
- packages/runtime-dom/src/modules/props.ts
> fix(runtime-dom): handle undefined values in v-html

- packages/runtime-core/__tests__/helpers/useId.spec.ts
- packages/runtime-core/src/apiAsyncComponent.ts
- packages/runtime-core/src/apiCreateApp.ts
- packages/runtime-core/src/component.ts
- packages/runtime-core/src/componentOptions.ts
- packages/runtime-core/src/helpers/useId.ts
- packages/runtime-core/src/index.ts
Similar to React's [useId](https://react.dev/reference/react/useId), this composable returns a unique ID that can be used for form elements and accessibility attributes.
The generated IDs look like `v:1-2-3` and are unique across each app instance and are stable across server rendering and client rendering. This is ensured by dividing an app into async boundaries (async components, async setup, serverPrefetch). The order of appearance of direct child async boundaries are always consistent assuming the same data is used between server and client, but their order of resolution may be different. Even if two async boundaries resolve in different orders between server and client, `useId()` calls inside the two boundaries should not affect each other.
> feat(runtime-core): useId()

- packages/runtime-core/__tests__/helpers/useModel.spec.ts
- packages/runtime-core/src/helpers/useModel.ts
> fix(defineModel): correct update with multiple changes in same tick

- .github/contributing.md
The project uses the catalogs added in `pnpm`v9.5.0, and the contribution guide should be updated synchronously.
ref https://pnpm.io/catalogs
If the pnpm version used is lower than 9.5, the following error will occur when installing dependencies:
> docs(github): update the minimum requeird version of pnpm

- packages/reactivity/src/arrayInstrumentations.ts
- packages/runtime-core/src/helpers/renderList.ts
- reuse the `isProxy` and `isShallow` checks within the `apply` method
> refactor(reactivity): simplify the wrapping logic for returned values

- packages/sfc-playground/src/Header.vue
- packages/sfc-playground/src/VersionSelect.vue
> chore(sfc-playgroud): highlight the commit and latest version when active in dropdown

- packages/dts-test/ref.test-d.ts
- packages/dts-test/watch.test-d.ts
- packages/reactivity/src/ref.ts
- packages/runtime-core/src/apiWatch.ts
> fix(types/ref): allow getter and setter types to be unrelated

- packages/reactivity/src/collectionHandlers.ts
- replace custom `Iterable` and `Iterator` interfaces with built-in types
> chore(types): reuse built-in Iterator type

- packages/runtime-core/src/componentProps.ts
Closes #9739.
The result of `normalizePropsOptions` is cached, so the performance usually doesn't matter too much. But there are two cases where the cache may not help:
- SSR. The cache is per application instance, so a new cache is used for each request.
- Components created on-the-fly, e.g. by defining them inside the `<script setup>` block of another component.
A lot of time in `normalizePropsOptions` is spent in `getType`, trying to figure out the values of the `shouldCast` and `shouldCastTrue` flags. I go into a bit more detail about that at https://github.com/vuejs/core/pull/9739#issuecomment-2144177971.
The Playground isn't necessarily the best tool for benchmarking, but here's an example to try to illustrate that my changes have improved the performance:
- [Playground - …
> perf(runtime-core): improve efficiency of normalizePropsOptions

- packages/runtime-core/__tests__/hydrationStrategies.spec.ts
- packages/runtime-core/src/apiAsyncComponent.ts
- packages/runtime-core/src/componentOptions.ts
- packages/runtime-core/src/hydration.ts
- packages/runtime-core/src/hydrationStrategies.ts
- packages/runtime-core/src/index.ts
- packages/runtime-core/src/renderer.ts
- packages/vue/__tests__/e2e/e2eUtils.ts
- packages/vue/__tests__/e2e/hydration-strat-custom.html
- packages/vue/__tests__/e2e/hydration-strat-idle.html
- packages/vue/__tests__/e2e/hydration-strat-interaction.html
- packages/vue/__tests__/e2e/hydration-strat-media.html
- packages/vue/__tests__/e2e/hydration-strat-visible.html
- packages/vue/__tests__/e2e/hydrationStrategies.spec.ts
Async components can now control when they are hydrated by providing a hydration strategy.
- Vue provides a number of built-in hydration strategies. These built-in strategies need to be individually imported so they can be tree-shaken if not used.
- The design is intentionally low-level for flexibility. Compiler syntax sugar can potentially be built on top of this in the future either in core or in higher level solutions (e.g. Nuxt).
- Why is it coupled to async components? Mostly because async components are already natural boundaries for async operations inside a render tree. Async sub trees require special handling in regards of reactivity tracking and suspense resolution. By coupling async hydration to async components we can support the feature without introducing extra complexities …
> feat: lazy hydration strategies for async components

- packages/runtime-core/__tests__/helpers/useTemplateRef.spec.ts
- packages/runtime-core/src/helpers/useTemplateRef.ts
Declaring `useTemplateRef` with the same key multiple times results in a `TypeError: Cannot redefine property: xxx` at runtime, see [playground](https://play.vuejs.org/#eNp9kE9Lw0AQxb/Kspco1EQIvdQYUOlBDyq1xwUJySTdutld9k8MhHx3ZxNbK2hvu+/3ZubNDPRO67jzQFc0c9BqUTjImSQkq3hHDNS3jNZKMZpnCSqIsuTEh19bGq4dseC8JqKQDVY4iwVM8lYr48hAvIXtd9EGajKS2qiWRDg3uglNfvOLCCdGl0j+07NknprTBc4qlax5E++tkrjGENIzWqpWcwHmRTuuJOZZkYkEVgihPp8mzRkPi4Ne7qD8+EPf2z5ojL4asGA6YPTIXGEacDNevz1Dj+8jbFXlBbrPwA1YJXzIONvuvaww9olvSvs4nZLLZmvXvQNpD0uFoME5Tn5G8aYPZ1b/iZvG6VTH5IhXfO/AhJ54wDRextdXhdC7Il7S8QtbtLVb)
---
There's another issue: in dev mode, the `useTemplateRef` returned value is `readonly`:
```ts
return (__DEV__ ? readonly(r) : r) as any
```
When a variable declared with `useTemplateRef` has the same name as a template ref, a …
> dx(useTemplateRef): warn when declaring with the same key

- packages/runtime-dom/__tests__/customElement.spec.ts
- packages/runtime-dom/src/apiCustomElement.ts
> feat(customElement): support for expose on customElement, fix #5540

- packages/runtime-test/__tests__/testRuntime.spec.ts
This pr added mockWarn test case  https://github.com/vuejs/core/pull/194/files five years ago. Now, mockWarn was deleted, so, this test case is useless
> chore(runtime-test): remove useless test code

- packages/dts-test/defineComponent.test-d.tsx
- packages/runtime-core/src/apiDefineComponent.ts
- packages/runtime-core/src/componentPublicInstance.ts
> feat(types): provide internal options for using refs type in language tools

- packages/dts-test/setupHelpers.test-d.ts
- packages/runtime-core/src/apiSetupHelpers.ts
In some edge cases, casting type with `any` is helpful when using `withDefaults`. However, currently, when the default values have `any` casting, it incorrectly includes the `undefined` type.
```ts
const _ = <T extends string>() => {
const props = withDefaults(defineProps<{ foo?: T }>(), { foo: 'bar' as any })
// before: T | NotUndefined<T> | undefined
// after: NotUndefined<T>
props.foo
}```
> fix(types/withDefaults): ensure default values of type `any` do not include `undefined`

- packages/runtime-core/src/component.ts
- packages/runtime-core/src/hmr.ts
- packages/runtime-core/src/index.ts
- packages/runtime-core/src/renderer.ts
- packages/runtime-dom/__tests__/customElement.spec.ts
- packages/runtime-dom/src/apiCustomElement.ts
close #4662
close #6610
close #7941
This references both #6610 and #7942 but implements it in a way that minimizes changes to `runtime-core` and also handles HMR for child-injected styles, without relying on changes to `@vitejs/plugin-vue`.
With this change, a `*.ce.vue` component can import other `*.ce.vue` components and use them directly as Vue child components instead of custom elements. Child component's styles will be injected as native `<style>` tags into the root custom element's shadow root:
```js
import { defineCustomElement } from 'vue'
import Root from './Root.ce.vue'
customElements.define('my-el', defineCustomElement(Root))
```
```vue
<script setup>
import Child from './Child.ce.vue'
</script>
```
```vue
<style>
div { color: red }; /* will be injected to Root.ce.vue's shadow …
```
> feat(custom-element): inject child components styles to custom element shadow root

- scripts/utils.js
This fixes the canary release workflow which has not run successfully in weeks due to the new exec util introduced in https://github.com/vuejs/core/commit/93324b2ec06b26662b77abc2a75d21ecbe8913db#diff-0b21831cd9ed897d64279bd0b4bb242a206cbf2f949101967ca14dba17bb7dd4 that doesn't reject bad exit codes compared to execa.
> fix(ci): canary release workflow

- packages/dts-test/ref.test-d.ts
- packages/reactivity/src/ref.ts
> fix(types/ref): correct type inference for nested refs

- packages/runtime-dom/src/helpers/useCssVars.ts
> fix(runtime-dom): cssvars correctly handles execution time

- packages/runtime-core/src/helpers/renderSlot.ts
- packages/runtime-core/src/index.ts
- packages/server-renderer/__tests__/ssrSlot.spec.ts
- packages/server-renderer/src/helpers/ssrRenderSlot.ts
fix #11326.
we should ensure the rendering result of slot is valid in `ssr`. keep it consistent with `runtime`.
> fix(ssr): ensure content is valid when rendering normal slot

- packages/runtime-core/__tests__/apiCreateApp.spec.ts
- packages/runtime-core/src/apiInject.ts
> fix(runtime-core): prioritize using the provides from currentApp in nested createApp

- packages/runtime-core/src/hydrationStrategies.ts
- packages/vue/__tests__/e2e/hydration-strat-visible.html
This PR allows for fine tuning of some hydration strategies, like requestIdleCallback and IntersectionObserver. This allows end-developers to have full control over the specifics of when and how to hydrate. This also changes some of the related types to provide better intellisense and avoid `any`
> feat: allow fine tuning of lazy hydration strategy triggers

- packages/runtime-core/src/directives.ts
When I tried to edit my component, I encountered a type error:
```javascript
const InputComponent = defineComponent({
render() {
return withDirectives(
createElementBlock(
'input',
{
'onUpdate:modelValue': (event: string | number) =>
(modelValueWritable.value = event),
readonly: props.readonly,
disabled: props.disabled,
},
null,
512
),
[[vModelText, modelValueWritable.value, void 0, props.modelModifiers]]
);
},
});
```
The error message indicated that `undefined` cannot be assigned to type `string`:
```text
Type 'undefined' is not assignable to type 'string'.
```
However, upon reviewing the code generated in the Playground and Vue's source code, I found that when `DirectiveArguments` has a length of 4, the third argument can indeed be `undefined`.
```javascript
function render(_ctx, …
```
> fix(types): allow `DirectiveArguments` third parameter to accept undefined

- packages/runtime-dom/__tests__/customElement.spec.ts
My PR was originally fixing the warning as well, but Evan already fixed it in https://github.com/vuejs/core/commit/197afc2c: the test is still with the previous name though.
> chore: fix wrong test name for useShadowRoot

- packages/runtime-core/__tests__/helpers/useModel.spec.ts
- packages/runtime-core/src/helpers/useModel.ts
resolve: https://github.com/vuejs/core/issues/11541
resolve: https://github.com/vuejs/core/issues/11526
related: https://github.com/vuejs/core/pull/11527
This change can solve both problems https://github.com/vuejs/core/issues/11541 and https://github.com/vuejs/core/issues/11526 at the same time, but it is only for the sake of solving the problem. I think it needs to be fundamentally solved from the design point of view. The logic of `haschange` should judge the custom setter and getter together. 
```ts
set(value) {
if (
!hasChanged(options.set ? options.set(value) : value, options.get ? options.get(localValue) : localValue) &&
!(prevSetValue !== EMPTY_OBJ && hasChanged(value, prevSetValue))
) {
return
}
....
}
```
If it is changed like this, then the phenomenon of …
> fix(defineModel): detect changes respect custom getter and setter

- packages/compiler-core/src/transforms/transformElement.ts
align with https://github.com/vuejs/core/blob/29425df1acb9e520c6ae894d06bcff73fde90edd/packages/compiler-core/src/transforms/vBind.ts#L106
> fix(compiler-core): initialize `isProp.exp` with `arg.loc` instead of `isProp.loc`

- packages/sfc-playground/src/VersionSelect.vue
- packages/sfc-playground/src/icons/Copy.vue
Every time I raise an issue, I need to provide a vue version and a minimal implementation based on playground, so I hope it will be more convenient to have a shortcut button to copy the vue version.
> feat(playground): Support copying vue version

- packages/reactivity/__tests__/reactiveArray.spec.ts
- packages/reactivity/src/arrayInstrumentations.ts
> fix(reactivity): avoid wrapping extended array methods

- packages/runtime-dom/src/index.ts
Resolves TS error `Variable must have an explicit type annotation with –isolatedDeclarations.ts(9010)`
> chore: add explicit type annotation to `initDirectivesForSSR`

- packages/runtime-core/src/components/KeepAlive.ts
the filter is always not null
https://github.com/vuejs/core/blob/ad603c663dbde31e520afe9d6cd6d81e3e293dcd/packages/runtime-core/src/components/KeepAlive.ts#L224-L225
> perf: remove unnecessary check as filter is always non-null

- packages/runtime-dom/src/index.ts
> fix(types): add fallback stub for DOM types when DOM lib is absent

- packages/runtime-core/__tests__/components/KeepAlive.spec.ts
- packages/runtime-core/src/components/KeepAlive.ts
When keep-alive receives a regular expression, I think it should match the component correctly even if the `g` flag is carried.
> fix(keep-alive): optimize the matching rules when regexp carry flags

- packages-private/dts-test/ref.test-d.ts
- packages/reactivity/src/computed.ts
- packages/runtime-core/src/apiComputed.ts
> fix(types/computed): ensure type safety for `WritableComputedRef`

- packages/runtime-core/src/componentOptions.ts
- packages/runtime-core/src/componentPublicInstance.ts
Update JSDoc examples for augmentation to be consistent with the examples in the docs https://vuejs.org/guide/typescript/options-api.html#augmenting-global-properties.
Fixes #11605.
> fix(types): update examples in JSDoc for augmenting global properties and custom options

- packages/compiler-sfc/__tests__/compileScript/resolveType.spec.ts
- packages/compiler-sfc/src/script/resolveType.ts
fixes https://github.com/vuejs/core/issues/11580
> fix(compiler-sfc): handle keyof operator with indexed object

- packages/dts-test/defineCustomElement.test-d.ts
- packages/runtime-dom/src/apiCustomElement.ts
Fixes type error when using `defineCustomElement` with `required: true` props.
```ts
const Comp1Vue = defineComponent({
props: {
a: { type: Number, required: true },
},
})
const Comp = defineCustomElement(Comp1Vue)
//                               ^^^^^^^^ No overload matches this call. ts(2769)
```
```
No overload matches this call.
The last overload gave the following error.
Argument of type 'DefineComponent<ExtractPropTypes<{ a: { type: NumberConstructor; required: true; }; }>, ...>' is not assignable to parameter of type 'DefineComponent<any, any, any, any>'.
Type 'DefineComponent<ExtractPropTypes<{ a: { type: NumberConstructor; required: true; }; }>, ...>' is not assignable to type 'ComponentOptionsBase<Readonly<any>, ...>'.
Types of property 'setup' are incompatible.
Type '(this: …
```
> fix(types/custom-element): `defineCustomElement` with required props

- SECURITY.md
Update SECURITY.md
Incorrect linking causes the email to jump to an error, which I think needs attention, although it does not affect the overall usability.
> docs: modify email link error

- packages/runtime-core/__tests__/errorHandling.spec.ts
- packages/runtime-core/src/apiWatch.ts
> fix(runtime): handle errors for computed watch keys (fix #11624)

- packages/runtime-core/__tests__/rendererComponent.spec.ts
- packages/runtime-core/__tests__/scheduler.spec.ts
- packages/runtime-core/src/renderer.ts
- packages/runtime-core/src/scheduler.ts
Closes #7745.
I have an old PR, #7745, that fixes a minor bug in `invalidateJob`. However, since Vue 3.4, the external symptoms of the bug disappeared. The problem in the code is still present, but it can no longer be reproduced via the public API.
Longer explanation at https://github.com/vuejs/core/pull/7745#issuecomment-2143943660.
In short, I believe we no longer need to use `invalidateJob` to remove child jobs from the queue. We can just leave the job in the queue. Since 3.4, update jobs check their `dirty` flag before doing anything else, so running an unnecessary job is very cheap.
Removing the job involves calls to `indexOf` and `splice`, neither of which are cheap operations. Using a flag instead is similar to the approach used by `invalidateMount` (see …
> refactor(scheduler): remove invalidateJob

- packages/runtime-core/__tests__/scopeId.spec.ts
- packages/runtime-core/src/renderer.ts
close https://github.com/vuejs/core/issues/5148
> fix(runtime-core): ensure suspense content inherit scopeId

- packages/reactivity/src/watch.ts
- packages/runtime-core/__tests__/apiWatch.spec.ts
Not sure if this is intentional, but I think the destruction logic of once should be consistent with stop
> fix(reactivity): ensure stop and once same behavior

- packages/compiler-sfc/src/parse.ts
Some error messages are missing this information, which results in search, which file is the reason for this:
> chore: improve error message for missing template and script tag in vue file

- package.json
- scripts/dev.js
Corrected the paths in the `dev` scripts for `template-explorer` after its migration to the `packages-private` directory
> fix(build): update paths for private packages in `dev` script

- packages/reactivity/src/effect.ts
- packages/reactivity/src/effectScope.ts
This PR primarily modifies effectScope.ts, attempting to replace multiple let declarations within for loops with a single let declaration to enhance performance and maintain consistency with the stop function's style. Additionally, it removes redundant code from effect.ts.
> chore(reactivity): effectScope.ts variable declarations optimized and remove useless code in effect.ts

- packages/runtime-core/__tests__/components/KeepAlive.spec.ts
- packages/runtime-core/src/components/KeepAlive.ts
> fix(runtime-core):  reset keep alive flag when the component is removed from include

- packages/compiler-sfc/__tests__/compileScript/resolveType.spec.ts
- packages/compiler-sfc/src/script/resolveType.ts
> fix(compiler-sfc): skip circular tsconfig project reference (#11382)

- package.json
"Illegal characters in path" error in Windows when running clean script.
> chore(fix): clean script

- packages/reactivity/src/effect.ts
- packages/reactivity/src/watch.ts
The new API introduced in 205e5b5e277243c3af2c937d9bd46cf671296b72 has a few parameters not documented.
Also fixes some typos in `onEffectCleanup` documentation.
> chore: document parameters of onWatcherCleanup

- .github/workflows/ci.yml
- .github/workflows/size-data.yml
- .github/workflows/size-report.yml
The ci `size data`, `size report`, and `ci` will run in the forks project, [actions](https://github.com/tolking/vue-core/actions)
Depending on the content of the jobs, perhaps they should not be run on forks.
> ci: prevents action from running on forks

- packages/reactivity/__tests__/ref.spec.ts
I think it is more recommended to use Vitest's way instead
> test(reactive): use vitest fn instead of counting manually

- packages/runtime-core/__tests__/hydration.spec.ts
- packages/runtime-core/src/hydration.ts
> fix(hydration): handle text nodes with 0 during hydration

- packages/compiler-sfc/src/script/utils.ts
- packages/compiler-sfc/src/style/cssVars.ts
- packages/runtime-core/__tests__/hydration.spec.ts
- packages/runtime-core/src/hydration.ts
- packages/shared/src/escapeHtml.ts
> fix(hydration): escape css var name to avoid mismatch

- packages/reactivity/__tests__/reactiveArray.spec.ts
- packages/reactivity/src/arrayInstrumentations.ts
> fix(reactivity): correctly handle method calls on user-extended arrays

- packages/server-renderer/__tests__/render.spec.ts
- packages/server-renderer/src/render.ts
This fixes a bug where the serverPrefetch option _would not be called_ with an async setup method.
A `prefetches` reference was created while `instance.sp` was `null`. However, with an async setup, `instance.sp` has the serverPrefetch methods only after setup resolves.
The fix is achieved by waiting to for setup to resolve before trying to access the the serverPrefetch options from `instance.sp`.
I added a unit test that reproduces the problem, by adding an async setup to the component definition. FWIW, I considered and experimented with adding more async setup variations of the existing tests, but backed out after they did not reproduce the problem and decided they weren't critical.
The bug can break SSR because the server renderer will not wait long enough to produce serializable state. …
> fix(server-renderer): Fix call to serverPrefetch in server renderer with an async setup

- packages/reactivity/__tests__/reactiveArray.spec.ts
- packages/reactivity/src/arrayInstrumentations.ts
> fix(reactivity): handle non-array arguments in reactive `concat` method

- packages/runtime-core/src/apiDefineComponent.ts
- packages/runtime-core/src/componentOptions.ts
Fix a dts emit regression for v3.5.
```ts
import { defineComponent } from "vue";
export default defineComponent({
props: {
/**
* The hello property.
*/
hello: {
type: String,
default: 'Hello'
},
},
});
```
```ts
declare const _default: import("vue").DefineComponent<import("vue").ExtractPropTypes<{
/**
* The hello property.
*/
hello: {
type: StringConstructor;
default: string;
};
}>, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<{
hello: string;
} & {} & {}>, {
hello: string;
}, {}, {}, {}, string, import("vue").ComponentProvideOptions, true, {}>;
export default _default;
```
```ts
declare const _default: import("vue").DefineComponent<import("vue").ExtractPropTypes<{
/**
* The hello property.
*/ …
```
> types(runtime-core): using intersection type in `Readonly<...>` breaks JSDoc emit

- packages/runtime-core/src/scheduler.ts
- packages/shared/src/typeUtils.ts
In Vue 3.5, we need to support different types for getters and setters. This feature requires TypeScript version >= 5.1. Therefore, in this PR, we are removing compatibility support for the `Awaited` type in TypeScript version 4.5.
> types(shared): removed the Awaited compatibility type tool

- packages/reactivity/__tests__/computed.spec.ts
- packages/reactivity/src/effect.ts
> fix(reactivity): pass oldValue to computed getter

- packages/reactivity/__tests__/computed.spec.ts
- packages/reactivity/src/dep.ts
As shared on Twitter with @yyx990803, here the fix for the endless recursion that is sadly very difficult to isolate form our code-base. I will keep trying to create a simple test-case.
> fix(reactivity): prevent endless recursion in computed getters

- packages/runtime-core/src/components/Suspense.ts
- packages/vue/__tests__/e2e/Transition.spec.ts
> fix(suspense): avoid updating anchor if activeBranch has not been rendered to the actual container

- packages/compiler-core/__tests__/parse.spec.ts
- packages/compiler-core/src/ast.ts
- packages/compiler-core/src/parser.ts
- packages/compiler-core/src/transforms/transformElement.ts
- packages/compiler-core/src/transforms/vBind.ts
- packages/compiler-core/src/transforms/vModel.ts
- packages/compiler-dom/src/transforms/vOn.ts
We need to provide completion support for custom directives.
vuejs/language-tools#4810
> feat(compiler-core): parse modifiers as expression to provide location data

- packages/runtime-core/src/renderer.ts
Fixes #11793
Simply add a proper check on the existance of `__asyncHydrate` so that vue 3.5 and `vue3-lazy-hydration` can coexist until we get vue3-lazy-hydration up to date with the new hydration api
> fix(Hydration): implement proper check for __asyncHydrate

- packages/runtime-core/src/componentEmits.ts
> fix(runtime-core): correctly infer `TypeEmits` with both tuple and function syntax

- packages/compiler-sfc/__tests__/compileStyle.spec.ts
- packages/compiler-sfc/src/style/pluginScoped.ts
> feat(compiler-sfc): correct scoped injection for nesting selector

- packages/reactivity/__tests__/reactive.spec.ts
- packages/reactivity/src/reactive.ts
> fix(reactive): markRaw function return the value directly when it has been marked

- packages/runtime-core/src/scheduler.ts
Simplify `checkRecursiveUpdates` a little bit, and make sure it always returns a boolean value.
Feel free to close this PR.
> refactor(scheduler): simplify checkRecursiveUpdates

- packages/compiler-core/__tests__/parse.spec.ts
- packages/compiler-core/src/tokenizer.ts
> fix(compiler-core): fix handling of delimiterOpen in VPre

- packages/compiler-sfc/__tests__/compileStyle.spec.ts
- packages/compiler-sfc/src/style/pluginScoped.ts
> fix(compiler-sfc): nested css supports atrule and comment

- packages/runtime-dom/src/components/TransitionGroup.ts
- packages/vue/__tests__/e2e/TransitionGroup.spec.ts
> fix(TransitionGroup): not warn unkeyed text children with whitespece preserve

- packages/runtime-core/__tests__/hmr.spec.ts
- packages/runtime-core/src/components/Suspense.ts
- packages/runtime-core/src/hmr.ts
- packages/runtime-core/src/renderer.ts
> fix(hmr): reload async child wrapped in Suspense + KeepAlive

- packages/runtime-core/__tests__/components/KeepAlive.spec.ts
* The comment is #1513 , but correctly #1511 .
*  It was added in the [#1511 fix commit](https://github.com/vuejs/core/commit/d86b01ba3a29e2e04c13597a1b9123ca35beaf57 ).
* `Packages/runtime-core/src/components/KeepAlive.ts` is not modified as it was already modified
> chore:fix-issue-id

- packages/reactivity/__tests__/computed.spec.ts
- packages/reactivity/src/effect.ts
> fix(reactivity): rely on dirty check only when computed has deps

- packages-private/global.d.ts
- packages/global.d.ts
- Fix type errors in `packages-private` due to missing global types
- Clean up unused global types from the main package
> chore(types): migrate global types to packages-private

- packages/global.d.ts
- packages/runtime-core/__tests__/apiWatch.spec.ts
- packages/runtime-core/src/apiWatch.ts
Fixes the unwatch is not a function TypeError reported in https://github.com/vuejs/core/issues/11924.
fix #11924
> fix(runtime-core): unwatch should be callable during SSR

- packages/reactivity/__tests__/watch.spec.ts
- packages/reactivity/src/watch.ts
Ref: https://github.com/vuejs/core/blob/main/packages/runtime-core/src/apiWatch.ts#L161
v3.4.38: https://github.com/vuejs/core/blob/v3.4.38/packages/runtime-core/src/apiWatch.ts#L183
cc @LittleSound
> fix(watch): `once` option should be ignored by watchEffect

- packages/compiler-dom/__tests__/transforms/stringifyStatic.spec.ts
- packages/compiler-dom/src/transforms/stringifyStatic.ts
- packages/shared/src/domAttrConfig.ts
[Playground](https://play.vuejs.org/#eNrtUstOwzAQ/JVoz1WsqhxoFSoB6gFEAQFHX6JkSVL8kr15SFX+HduhpQfUA+deVqOZWWnW4z3cGpN2LcIKMkJpRE645ipJsrLpIvBQ5lQngxTK3XCoicyKsb7v036Ralux+XJ5zbbeE8f2icPPYlh163nG/Lww/2M89I86VcKmTjJ20hTMgFyh1WdTpTunlS9yH8wcCi1NI9C+GGq0chxWSVSClguh+8fIkW1xduCLGouvP/idGwLH4dWiQ9shh6NGua2QJnnz/oyDx0dR6rIV3n1GfEOnRRsyTra7VpU+9okvpn2QRltqVPXhNgOhcoejQtDgHKOfg//N92dO/427SK/iHlcjjN/QReVX)
[Playground with this PR](https://deploy-preview-11891--vue-sfc-playground.netlify.app/#eNrtUstOwzAQ/JVoz1WsqhxoFSoB6gFEAQFHX6JkSVL8kr15SFX+HduhpQfUA+deVqOZWWnW4z3cGpN2LcIKMkJpRE645ipJsrLpIvBQ5lQngxTK3XCoicyKsb7v036Ralux+XJ5zbbeE8f2icPPYlh163nG/Lww/2M89I86VcKmTjJ20hTMgFyh1WdTpTunlS9yH8wcCi1NI9C+GGq0chxWSVSClguh+8fIkW1xduCLGouvP/idGwLH4dWiQ9shh6NGua2QJnnz/oyDx0dR6rIV3n1GfEOnRRsyTra7VpU+9okvpn2QRltqV …
> feat(compile-dom): stringify mathML

- packages/reactivity/src/computed.ts
- packages/reactivity/src/dep.ts
- packages/reactivity/src/effect.ts
> fix(reactivity): avoid exponential perf cost and reduce call stack depth for deeply chained computeds

- packages/runtime-core/src/hydrationStrategies.ts
This PR optimizes the intersection based hydration by avoiding the observer overhead if the element is visible initially, ensuring it is immediately hydrated, as opposed to waiting for the observer to run its callback
The approach is originally taken from https://github.com/nuxt/nuxt/pull/26468/files#diff-8e89e3233ee017161774c7e5df6b9a18cc926d5a1b4081e7fcbf9651109ce45d by @huang-julien
> perf(hydration): avoid observer if element is in viewport

- packages/runtime-core/src/hydrationStrategies.ts
- packages/vue/__tests__/e2e/hydration-strat-visible.html
- packages/vue/__tests__/e2e/hydrationStrategies.spec.ts
> fix(hydration): avoid observing non-Element node

- packages/runtime-core/__tests__/scheduler.spec.ts
- packages/runtime-core/src/scheduler.ts
This PR was originally going to be just tests for #11826, which was merged a couple of weeks ago. But while working on the tests I realised there was a small bug in my original PR, which I've fixed here.
In my original fix, I assumed that it was safe to clear the `QUEUED` flag unconditionally after a job had run. However, this isn't always correct for jobs with `ALLOW_RECURSE`.
For a job with `ALLOW_RECURSE`, the `QUEUED` flag is already cleared before the job runs. If the job does recurse then the `QUEUED` flag will be set again. In that scenario it shouldn't be cleared after the job runs. Mistakenly clearing the flag allows the job to be added to the queue again.
In practice, even if the job does get queued twice, the dirtiness checks should significantly limit its impact. The 'Maximum …
> fix(scheduler): ensure recursive jobs can't be queued twice

- packages/compiler-sfc/src/script/definePropsDestructure.ts
Prevent mistakenly identifying properties such as `toString` inherited from `Object` as props.
> fix(compiler-sfc): initialize scope with null prototype object

- packages-private/sfc-playground/src/App.vue
I discovered that after upgrading from @vue/repl@4.4.0 to v4.4.2 #11939, there were issues with autosave conflicts and failure. The cause is that some default operations for [autoSave](https://github.com/vuejs/repl/pull/283/files) were added in [@vue/repl@4.4.1](https://github.com/vuejs/repl/releases/tag/v4.4.1), which led to changes in the property. This PR aims to resolve the conflict.
> fix(sfc-playground): resolve autosave conflict issue

- packages/compiler-core/src/transforms/vModel.ts
- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
> fix(compile-core): fix v-model with newlines edge case

- packages/compiler-ssr/__tests__/ssrTransitionGroup.spec.ts
- packages/compiler-ssr/src/ssrCodegenTransform.ts
- packages/compiler-ssr/src/transforms/ssrVIf.ts
> fix(ssr): don't render comments in TransitionGroup

- packages/runtime-dom/src/components/Transition.ts
This PR addresses the behavior when using `<Transitions :duration="0">`. According to the expected behavior, when the `duration` is set to `0`, no animations should be executed. However, the current implementation still triggers animations internally. This fix ensures that when the `duration` is set to `0`, animations are correctly skipped.
https://play.vuejs.org/#eNqNU8Fu2zAM/RXWO3QDasdDt0M9t9hW9LAd2mHL0RdFphM1smRIdJIiyL+PslwnG4qiN+rxvedHmdon37ou2/SYFEnppVMdgUfqu5vKqLazjmAPDhs4QONsC+dMPa+MtMYTCElqg3AdCO8boT1+qEw5izZswAfCttOCkE8A5aInsga+Sq3k+rpKJoOzWFXJwAO4DYRBMouaqD9LUyjnThivSLGRES2yTSNqlkJR904EnKGPbAVpehM185XysLVuHaDB6U0meTA5Gtw/zP8xYZtabWCTqmaaZZpgbEotvOfuwu64Vc4Ye9ZOdTk7pmGgnJ1cGh89PelQZuwB+yDYqppWBVzmebf7EoAVquWKTpGFkOuls72pU2m1dQW8y6+uuHUInlkYNkVD6NKY++IZ1Cg2OILxazSFK8B2Qip6gjz77AGFx …
> fix(transition): respect `duration` setting even when it is `0`

- packages/reactivity/src/ref.ts
> fix(reactivity): fix triggerRef to handle ObjectRefImpl instances

- packages/reactivity/__tests__/computed.spec.ts
- packages/reactivity/src/effect.ts
This is a follow up of 960706eebf73f08ebc9d5dd853a05def05e2c153
I have not managed to isolate a simple test-case yet, but in our app, some input fields appear to loose reactivity after a while without this fix
> fix(reactivity): do not remove dep from depsMap when cleaning up deps of computed

- packages/runtime-dom/src/directives/vModel.ts
> chore: remove unused argument

- packages/reactivity/src/dep.ts
ObjectRefImpl in toRef depends on getDepFromReactive
> fix(reactivity): optimising getDepFromReactive

- packages/runtime-core/src/componentEmits.ts
> fix(types): correct type inference of union event names

- packages/compiler-sfc/src/parse.ts
- packages/shared/src/general.ts
- packages/vue-compat/src/index.ts
- packages/vue/src/index.ts
close #12018 
revert https://github.com/vuejs/core/pull/9724
re-fix https://github.com/vuejs/core/issues/9618
> fix(vue): properly cache runtime compilation

- packages/runtime-core/__tests__/rendererChildren.spec.ts
- packages/runtime-core/src/vnode.ts
close #12035 
close https://github.com/vitejs/vite-plugin-vue/issues/353
I initially planned to fix this in [@vue/babel-plugin-jsx](https://github.com/vuejs/babel-plugin-jsx) [like this](https://github.com/vitejs/vite-plugin-vue/issues/353#issuecomment-2370012473). However, I encountered [this scenario](https://vue-jsx-explorer.netlify.app/#import%20%7B%20ref%2C%20defineComponent%20%7D%20from%20'vue'%0A%0Aexport%20const%20A%20%3D%20defineComponent(%7B%0A%20%20render()%20%7B%0A%20%20%20%20const%20textarea%20%3D%20%3Ctextarea%20id%3D%22textarea%22%2F%3E%3B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3Cdiv%3E%7Btextarea%7D%3C%2Fdiv%3E%0A%20%20%20%20)%3B%0A%20%20%7D%2C%0A%7D)%0A) during the process. It might require introducing additional runtime checks to determine whether the child is a …
> fix(runtime-core): avoid rendering plain object as VNode

- packages-private/dts-test/ref.test-d.ts
- packages/reactivity/src/ref.ts
> fix(types/ref): handle nested refs in UnwrapRef

- packages/compiler-sfc/src/script/definePropsDestructure.ts
> fix(compiler-sfc): not skip `TSSatisfiesExpression`

- packages/reactivity/__tests__/watch.spec.ts
- packages/reactivity/src/computed.ts
- packages/reactivity/src/effect.ts
> fix(reactivity): prevent overwriting `next` property during batch processing

- packages/runtime-core/src/apiDefineComponent.ts
- packages/shared/src/typeUtils.ts
> fix(types): correctly infer `TypeProps` when it is `any`

- packages/runtime-core/src/apiDefineComponent.ts
relate to #12059 
https://github.com/vuejs/core/blob/29de6f8b0bb1a604f247b0712daac29e93aa6f3e/packages/runtime-core/src/componentPublicInstance.ts#L311-L313
> fix(types): should not intersect `PublicProps` with `Props`

- packages/runtime-dom/__tests__/customElement.spec.ts
- packages/runtime-dom/src/modules/props.ts
- packages/runtime-dom/src/patchProp.ts
> fix(customElement): properly remove hyphenated attribute

- packages-private/dts-test/defineComponent.test-d.tsx
- packages/runtime-core/src/apiDefineComponent.ts
> fix(types): ensure `this.$props` type does not include `string`

- packages-private/sfc-playground/src/App.vue
- packages-private/sfc-playground/src/Header.vue
Before:
It always shows the text "Toggle dark mode" when hovering over the theme icon.
After:
It will show "Switch to light theme" if the theme is dark; otherwise, it shows "Switch to dark theme".
> chore(sfc-playground): adjust the tooltip text for toggling the theme

- packages/runtime-core/__tests__/hydration.spec.ts
- packages/runtime-core/src/hydration.ts
> fix(transition/ssr): make transition appear work with Suspense in SSR

- packages/runtime-core/__tests__/helpers/useModel.spec.ts
- packages/runtime-core/src/helpers/useModel.ts
> fix(runtime-core): handle kebab-case model correctly

- packages/compiler-dom/__tests__/transforms/__snapshots__/stringifyStatic.spec.ts.snap
- packages/compiler-dom/__tests__/transforms/stringifyStatic.spec.ts
- packages/compiler-dom/src/transforms/stringifyStatic.ts
> fix(compiler-dom): avoid stringify `<option>` with null value

- packages/reactivity/__tests__/computed.spec.ts
- packages/reactivity/src/effect.ts
I stumbled across an edge case where the performance of `computed` can go awry:
- [Playground - 3.5.11](https://play.vuejs.org/#eNp9U11v2jAU/St3fiGozEC7vTDo1k1o2jRtU9uXCVdTGi4hxbEjf1AkxH/ftZMQ2KbyQJxzj88999jZs5uq4luPbMKmNjNF5cCi89W1UEVZaeNgDwZXA8h0WXmHSzjAyugSerSpJ5RQmVbWwWNqEWaBmoz7LehMkedoGtwZj8dSK2epuHjodL7d/Jrf3hF4eRnAlTaQSHRQEDR6R49pQ6H1xUUf9kIBiYWtmBpZxG4LzvmxQRQPnOadV96ukwB1YJL0YXZdi4WfoQiMikPxbSo9wkUrzw0ufYZJYn1JqcR9tCRCVlMHMKIpg8ohPunv0M3n0kKSw/PGgdZk1bR73/lddM4lqtyt4TWMHxreBEZCUQehgnANxty8ylyhFeSaOpyEZF1KZzqDCg1lW6YqQ670cxI1/nYxg1dnQGSc9alltUQudZ707osSibFBNYEeRZL804bMRwv9NpbpsL52FAK9OCwrmTqMkUwfvXM0w4dMFtlmJliuBYsVgM86MoY1hcDp8GQvGzBnydmqyPmT1Ypud8xAsBBmIdH8qEI8VrBJe+qCpVLq568RC3d10OLZGrPNf/AnuwuYYD8NWjRbFOxYoxlzdHV5fvcdd7Q+Fku99JLYLxRvkVL1wWNN++jVkmyf8KLbL/EbLVR+b+c7h8q2QwWjgXmI …
> perf(reactivity): avoid unnecessary recursion in removeSub

- packages/runtime-core/__tests__/helpers/useId.spec.ts
- packages/runtime-core/src/component.ts
> fix(useId): ensure useId consistency when using serverPrefetch

- packages/runtime-core/src/components/Teleport.ts
- packages/runtime-dom/__tests__/helpers/useCssVars.spec.ts
> fix(runtime-core): handle disabled teleport with updateCssVars

- packages/compiler-sfc/__tests__/compileScript/__snapshots__/definePropsDestructure.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript/definePropsDestructure.spec.ts
- packages/compiler-sfc/src/script/definePropsDestructure.ts
Fix this kind of edge case
https://play.vuejs.org/#eNp9UsFu2zAM/RVClyZA4By2k+cY24oO2A5bsQU76eLajKtWlgSJyjJk/vdRUtKlw9aTLfKRfO+RR/HOuWofUdSiIZyc7ghbaQCaD9ZCve90xI0Ui6Gjbrlp00cKWDOkWV/g+Rl6rxxBQIqOI2py1hOkLjtvJ5CiWl/bKQ+T4k2qLxWMFStBobdmp8bqIVjDZI6JgxQ9VyiN/osjZU2QooacSblOa/vjU46Rj7g6x/t77B//EX8IhxST4tZjQL9nGk856vyIVNI33z7jgf+fkpMdomb0C8mvGKyOiWOBvY9mYNoXuMz2YzZFmXEbbg6EJpxFJaIJOWe8FGxSMut/0v/QfVW9znXSzOzi2eC0zct9gO7MyGskbsN+00+HeTMbaLbAetAMAQJ5Zga/wMTpDn2bd17DdgmbFvZWDdLwjgLBEfJZwMz1A+6UwVtvXWhO8Tq3ntvFMt1FKen6JILxWcJ9l92pYZF7n2QlpNVYaTsurr7nCSrUV6vStSn0Wm5a5MKzE+LH8/O9i0Q88W2vVf/I0guD6jQ625CGXqd0LliXir8vW8y/AWviDAE=
Click button. See error.
Value prop should be accessible even when used with `console.log('Value is:', value<string>)`
Although the user probably won't use it this way.
And it …
> fix(compiler-sfc):  do not skip TSInstantiationExpression when transforming props destructure

- packages/runtime-core/__tests__/rendererTemplateRef.spec.ts
- packages/runtime-core/src/rendererTemplateRef.ts
> chore(runtime-core): warn if use a non-ref to hold the element reference in DEV

- packages/runtime-core/__tests__/componentProps.spec.ts
- packages/runtime-core/src/componentProps.ts
> fix(runtime-core): use camelized prop key to check if it is absent

- packages/compiler-sfc/src/style/preprocessors.ts
https://sass-lang.com/documentation/breaking-changes/legacy-js-api
> refactor(compiler-sfc): support sass modern api

- packages/compiler-core/src/parser.ts
- packages/compiler-core/src/transforms/vIf.ts
fix vuejs/language-tools#4911 
The incremental update of language tools increased the start offset twice on the same loc object when traversing the v-if node.
> fix(compiler): clone loc to `ifNode`

- packages-private/dts-test/setupHelpers.test-d.ts
- packages/runtime-core/src/apiSetupHelpers.ts
> fix(types): retain union type narrowing with defaults applied

- packages/runtime-dom/src/directives/vModel.ts
- packages/vue/__tests__/e2e/vModel.spec.ts
close #12144
In the browser, the event order for an input click is `click` -> `change`.
When the `click` event has side effects, `vModelCheckbox`'s `beforeUpdate` hook updates `el.checked` based on the old `binding`, causing it to reset incorrectly. The `change` event then updates the `binding` with the wrong value, leading to the issue.
This PR ensures `el.checked` is only updated when the `binding` changes, fixing a 3.5 regression and restoring 3.4 behavior.
**NOTE**: This PR only addresses cases where the value is neither an array nor a set (issue #8638 is still unhandled).
> fix(runtime-dom): prevent unnecessary updates in v-model checkbox when value is unchanged

- packages/reactivity/src/collectionHandlers.ts
The diff looks horrendous... the change really isn't that complicated.
My primary goal was to reduce the bundle size. I've removed a lot of redundancy from `collectionHandlers.ts`. That involved moving around a lot of code, but it essentially all still works the same way.
To make this a bit easier to review I've split it up into individual commits. The first commit is the key change to understand what I've done. `createInstrumentations` was previously creating 4 lots of instrumentations and then returning them. The new version just creates the instrumentations for a single case, based on the arguments `readonly` and `shallow`. Just that one change reduces the bundle size by about 566 bytes, or roughly 135 bytes after gzipping.
The other commits gradually inline each of the functions. I …
> refactor(reactivity): reduce size of collectionHandlers

- packages/runtime-core/src/component.ts
Not sure whether this counts as `fix`, `perf` or `refactor`. Feel free to adjust accordingly.
I was doing some analysis of bundle size across Vue versions and noticed a jump in 3.2.39. This seems to have been caused by #6250. We didn't have size checks on PRs back then, and I don't see it discussed on the PR, so I assume this just slipped through.
It only impacts projects using `__VUE_OPTIONS_API__: false`.
The call to `resolveMergedOptions` prevents a big chunk of the Options API from being treeshaken. It's used to resolve `template` from `extends` and `mixins`, but I believe that is only relevant when `__FEATURE_OPTIONS_API__` is `true`.
> fix(runtime-core): use feature flag for call to `resolveMergedOptions`

- packages/runtime-core/__tests__/rendererAttrsFallthrough.spec.ts
- packages/runtime-core/src/componentRenderUtils.ts
If the subcomponent root element is `Teleport`, inheriting classes or events will also fail.
> chore: improve `renderComponentRoot` warn message

- packages/compiler-core/__tests__/transforms/__snapshots__/vOnce.spec.ts.snap
- packages/compiler-core/src/ast.ts
- packages/compiler-core/src/codegen.ts
- packages/compiler-core/src/transform.ts
- packages/compiler-core/src/transforms/vOnce.ts
- packages/runtime-core/__tests__/rendererOptimizedMode.spec.ts
- packages/runtime-core/__tests__/vnode.spec.ts
- packages/runtime-core/src/vnode.ts
> fix(v-once): setting hasOnce to current block only when in v-once

- packages/compiler-core/__tests__/transforms/__snapshots__/vMemo.spec.ts.snap
- packages/compiler-core/__tests__/transforms/vFor.spec.ts
- packages/compiler-core/__tests__/transforms/vMemo.spec.ts
- packages/compiler-core/src/transforms/transformExpression.ts
- packages/compiler-core/src/transforms/vFor.ts
> fix(compiler-core): handle v-memo + v-for with functional key

- packages/reactivity/src/effectScope.ts
this change was for #5783 in #12373. it's not necessary since #5783 was fixed via 2193284
> chore(reactivity): remove unnecessary array copy

- packages/compiler-sfc/package.json
- packages/compiler-sfc/src/style/pluginScoped.ts
- pnpm-lock.yaml
close #12279
there is a breaking change in `postcss-selector-parser` v7. see https://github.com/postcss/postcss-selector-parser/issues/297#issuecomment-2441658260
> chore(deps): update dependency postcss-selector-parser to v7

- packages/compiler-dom/__tests__/transforms/__snapshots__/stringifyStatic.spec.ts.snap
- packages/compiler-dom/__tests__/transforms/stringifyStatic.spec.ts
- packages/shared/__tests__/normalizeProp.spec.ts
- packages/shared/src/normalizeProp.ts
close #12391 
see https://github.com/vuejs/core/issues/12391#issuecomment-2476492699
> fix(compiler-dom): properly stringify template string style

- packages/reactivity/src/baseHandlers.ts
I don't think it's necessary to track his changes
> perf(reactivity): do not track inner key `__v_skip``

- packages/runtime-core/__tests__/hydration.spec.ts
- packages/runtime-core/src/hydration.ts
- packages/runtime-core/src/renderer.ts
> fix(hydration): the component vnode's el should be updated when a mismatch occurs.

- packages/runtime-dom/src/components/Transition.ts
- packages/vue/__tests__/e2e/Transition.spec.ts
- packages/vue/__tests__/e2e/e2eUtils.ts
- packages/vue/__tests__/e2e/transition.html
Fixes an old issue (#2593) that was introduced again by commit https://github.com/vuejs/core/commit/65109a70f187473edae8cf4df11af3c33345e6f6 while retaining the new functionality of the fixed issue (#10688). 
Maybe the v-leave-from class should just not be added at all if the enter transition is cancelled? This should be more looked into.
> fix(transition): reflow before leave-active class after leave-from (#2593), while fixing (#10688)

- packages/compiler-ssr/__tests__/ssrElement.spec.ts
- packages/compiler-ssr/src/transforms/ssrTransformElement.ts
Fixes #12309: `v-text` now functions correctly in SSR, even when other custom directives are applied to the same element.
The fix ensures that when `v-text` is present, it takes priority over `textContent` and `innerHTML` provided by other directives. This prevents conflicts in the SSR output, allowing `v-text` to render as expected.
`v-html` already behaves correctly by directly modifying `rawChildrenMap`, so this change aligns `v-text` behavior with that of `v-html` in SSR scenarios.
> fix(compiler-ssr): ensure v-text renders correctly with custom directives in SSR output

- packages/runtime-core/__tests__/rendererTemplateRef.spec.ts
- packages/runtime-core/src/rendererTemplateRef.ts
> fix(templateRef): set ref on cached async component which wrapped in KeepAlive

- changelogs/CHANGELOG-3.4.md
Some clean-up. All removed info is already included in [3.3 changelog](https://github.com/vuejs/core/blob/main/changelogs/CHANGELOG-3.3.md)
> docs: remove 3.3 info from 3.4 changelog

- packages/reactivity/__tests__/effectScope.spec.ts
- packages/reactivity/src/effectScope.ts
The following code does not work correctly in the current `vapor` branch. When the `button` is clicked, the button text does not update.
```vue
<script setup>
import { ref } from 'vue'
const count = ref(0)
</script>
<template>
<button id="btn" @click="count++">{{ count }}</button>
<div v-if="count < 1">{{ count }}</div>
<div v-else>{{ count * 2 }}</div>
</template>
```
The issue is because `scope.on` is called twice:
- inside `simpleSetCurrentInstance` > `i.scope.on()`
- `if (scope) scope.on()`
https://github.com/vuejs/core/blob/c2e7312da44cd79f8a66750085dd8a2ca0115a58/packages/runtime-vapor/src/renderEffect.ts#L30-L31
if `scope` equals `i.scope` the following happens
```js
scope1.on()  // activeEffectScope = scope1, prevScope = undefined
scope1.on()  // activeEffectScope = scope1, …
```
> feat(effectScope): allow multiple  `on()` calls by tracking call count

- packages/runtime-vapor/__tests__/componentSlots.spec.ts
- packages/runtime-vapor/src/componentSlots.ts
- template code
```vue
<Comp>
<template v-slot:[slotName] v-if="count <10">
<h1>{{ count * 2 }}</h1>
</template>
</Comp>
```
- compiled code
```js
const n3 = _createComponent(_ctx.Comp, null, {
$: [
() => (_ctx.count < 10
? {
name: _ctx.slotName, 
fn: () => {
const n1 = t1()
_renderEffect(() => _setText(n1, _ctx.count * 2))
return n1
}
}
: void 0)
]
})
```
the dynamic slot source result will be `undefined` if `_ctx.count > 10`, so we should ensure it is valid, otherwise `slot.name` will throw an error.
> fix(runtime-vapor): properly handle dynamic slot work with v-if

- packages/vue/__tests__/e2e/todomvc.spec.ts
- packages/vue/__tests__/e2e/tree.spec.ts
This fixes double clicks when using WebDriver BiDi. See https://github.com/puppeteer/puppeteer/issues/13550
> test(e2e): Replace deprecated 'clickCount' property with 'count'

- packages/compiler-sfc/src/rewriteDefault.ts
change `start` to a constant as it is never reassigned
> refactor(compiler-sfc): change `let start` to `const start` for consistency  

- packages/runtime-core/src/components/KeepAlive.ts
- packages/runtime-core/src/renderer.ts
- packages/vue/__tests__/e2e/Transition.spec.ts
> fix(runtime-core): prevent unmounted vnode from being inserted during transition leave

- packages/compiler-vapor/__tests__/transforms/__snapshots__/transformChildren.spec.ts.snap
- packages/compiler-vapor/__tests__/transforms/transformChildren.spec.ts
- packages/compiler-vapor/src/generators/template.ts
- packages/runtime-vapor/__tests__/dom/template.spec.ts
- packages/runtime-vapor/src/dom/node.ts
- packages/runtime-vapor/src/index.ts
see https://jsbench.me/a2m702k9zn/1
> perf(vapor): use nthChild instead of nextn

- scripts/size-report.js
The size-report script failed to run because node22 no longer supports assert syntax.
Ref: https://github.com/nodejs/node/pull/52104
> fix(ci): use `with` instead of `assert` syntax

- packages/reactivity/__tests__/reactive.spec.ts
- packages/reactivity/src/reactive.ts
close https://github.com/vuejs/core/issues/12807
> fix(reactivity): enhance reactive function to handle the WeakMap key 

- .github/workflows/ci.yml
pnpm patch don't support `pkg-pr-new`'s package. 
Can we add the vapor branch for pull requests so that I can use those PRs #12893 and #12890 before they are merged?
> ci(pkg-pr-new): add 'vapor' branch for pull-request

- packages-private/sfc-playground/package.json
- packages/compiler-sfc/__tests__/parse.spec.ts
- packages/compiler-sfc/src/parse.ts
- pnpm-lock.yaml
- open [playground with vapor branch](https://deploy-preview-12359--vue-sfc-playground.netlify.app/#eNp9kEFPwzAMhf9K5fPUCsFpiioB2gEOgIBjLlXmdRlpHCVOqTT1v5Ok2thh2inx+56tZx/h0bl6jAhrEEF57bgaO0e+Fc1SttJKKxgHZzrGVFWV2N+1OyLRpDex5gLCCjgosjvd14dANo095hYJiganDfp3x5pskLCuCsmsM4Z+X4vGPuLqpKs9qp8r+iFMWZPw4TGgH1HCmXHne+QFb77ecEr/MxxoG01y34CfGMjEnHGxPUW7TbEvfCXty5COxNr232EzMdpwWioHzc65+CWk2z7fWP0/7n39UPqknWH+A4drhZQ=)
- see the compiled code. the vapor mode code should be generated.
This is because we ignore empty script by default.
- https://github.com/vitejs/vite-plugin-vue/pull/529
- https://github.com/vuejs/repl/pull/322
> fix(vapor): handle vapor mode with empty script

- packages/runtime-vapor/src/index.ts
jsx-vapor's helper code need VaporFragment.
https://github.com/unplugin/unplugin-vue-jsx-vapor/blob/main/packages/unplugin/src/core/helper/code.js#L9
> feat(runtime-vapor): expose VaporFragment

- packages/reactivity/__tests__/gc.spec.ts
PR #12349 marked these tests as todo. They are actually working now.
> test(reactivity): enable tests marked as todo

- packages-private/dts-test/appUse.test-d.ts
- packages/runtime-core/src/apiCreateApp.ts
- JSDoc comments for `options` are preserved and visible in IDEs.
- `Go to definition` functionality works for plugin options.
- Autocomplete for `options` fields is fully supported.
> types: enhance plugin type inference for better IDE support

- packages-private/sfc-playground/src/download/download.ts
- packages-private/sfc-playground/src/download/template/package.json
- Replacing the static Vue version in `package.json` with the version selected by the user
- Using `"latest"` as the default Vue version if none is selected
> chore(sfc-playground): dynamically set Vue version in downloaded project

- packages/reactivity/src/reactive.ts
- packages/reactivity/src/ref.ts
I noticed this while running [api-extractor](https://api-extractor.com) on Vue 2 while porting over some APIs from here. It complains with the extra `()` and [docs](https://tsdoc.org/pages/tags/link/) indicate that the correct syntax is just the name of the symbol to link to. Parentheses are used for _selectors_.
> docs(tsdoc): remove extra () in link tag

- packages/runtime-dom/src/patchProp.ts
Fix #5705
As the [WebKit](https://bugs.webkit.org/show_bug.cgi?id=289197) devs said, this issue is currently only really visible on iOS, but it should also happen on Firefox and most likely on Chrome too.
> fix: always treat autocorrect as attribute

- packages/compiler-core/src/compat/compatConfig.ts
- packages/compiler-core/src/parser.ts
close #13133
According to this
https://github.com/vuejs/core/blob/069f838691b2238f31f4237e8412d9ff12921995/packages/compiler-core/src/parse.ts#L885
> fix(compat): correct deprecation message for v-bind.sync usage

- packages/reactivity/src/computed.ts
- packages/runtime-core/src/apiComputed.ts
- packages/runtime-core/src/apiCreateApp.ts
It's no longer needed in 3.6.
close https://github.com/vuejs/core/pull/12225
close https://github.com/vuejs/core/issues/12845
close https://github.com/vuejs/core/pull/12179
close https://github.com/vuejs/docs/pull/3072
> chore: remove `warnRecursiveComputed`

- packages/runtime-core/src/renderer.ts
> fix(runtime-core):  update __vnode of static nodes when patching along the optimized path

- packages/compiler-core/__tests__/transforms/cacheStatic.spec.ts
- packages/compiler-core/src/transforms/cacheStatic.ts
- packages/compiler-core/src/transforms/vSlot.ts
- packages/runtime-core/src/componentSlots.ts
- packages/runtime-core/src/renderer.ts
close #13211 
`vue-i18n` needs to update the following code
https://github.com/intlify/vue-i18n/blob/860a79e085043a7e76d28f04e893980fa9dd31f1/packages/vue-i18n-core/src/components/Translation.ts#L65
PR: https://github.com/intlify/vue-i18n/pull/2167 (merged)
> fix(compiler-core): remove slot cache from parent renderCache during unmounting

- packages/runtime-dom/src/components/TransitionGroup.ts
- packages/vue/__tests__/e2e/TransitionGroup.spec.ts
close #13181
When the child component is unmounted, the `el` was retained in `prevChildren` without being released, causing the memory leak
> fix(TransitionGroup): reset prevChildren to prevent memory leak

- packages/runtime-core/__tests__/components/Teleport.spec.ts
- packages/runtime-core/src/components/Teleport.ts
close #12816 
related to https://github.com/vuejs/core/commit/a959781dd6f609dcb6f16dd7fa47d3b16895e5ca
> fix(teleport): adjust static children traversal for HMR in dev mode

- packages/runtime-core/__tests__/helpers/renderList.spec.ts
- packages/runtime-core/src/helpers/renderList.ts
> fix(runtime-core): respect immutability for readonly reactive arrays in `v-for`

- packages/runtime-vapor/__tests__/apiCreateDynamicComponent.spec.ts
- packages/runtime-vapor/src/component.ts
- [Playground with vapor branch](https://deploy-preview-12359--vapor-repl.netlify.app/#eNp9Ub1OwzAQfpWTl4BUmgGmKkUC1AEGQMDoJaTX1sWxLfscIkV5d86OWjpUnXz3/ek7eRAPzs27iGIhqtB45QgCUnTQ1c76e2lUyy/BAB43MMLG2xYKNhTSNNYEgh21GpaJvip2qriWpiqnJHbzQtg6XRPyBlCtVZcHHhvL0QYNgQpLKb4jkTVSQHeTIhlJD+/l5Cwna1WeBIqZoMA1Nmo73wdr+IohiaVI4Uqjf3OkuKYUC8hM4mqt7e9LxshHnB3wZofNzxl8H/qESfHuMaDvUIojR7XfIk306vMVe56PZGvXUbP6AvmBweqYOk6yx2jWXPtEl9s+519QZvsVVj2hCYejUtGkHLNeCv6Zpwun/9e9nd9lnzSjGP8AigyrYg==)
> fix(runtime-vapor): dynamic component fallback rendering with insertionState

- packages/compiler-vapor/__tests__/transforms/__snapshots__/transformElement.spec.ts.snap
- packages/compiler-vapor/__tests__/transforms/transformElement.spec.ts
- packages/compiler-vapor/src/transforms/transformElement.ts
- pnpm-lock.yaml
This PR is related to [vuejs/vue-vapor#299](https://github.com/vuejs/vue-vapor/issues/299).
This PR continues the work from [vuejs/vue-vapor#305](https://github.com/vuejs/vue-vapor/pull/305) to fix an issue where components with v-for directives were incorrectly marked as single root components in vapor mode.
As noted in the original PR, when a component has only a single root element, the fourth argument is included in `createComponent`. However, if there are multiple elements or if the component uses `v-for`, it should not be marked as a single root.
Added `hasVFor` check to detect components with v-for directives.
```vue
<template>
<Comp v-for="item in items" :key="item" />
</template>
```
Now correctly compiles without marking the component as a single root.
The previous PR in …
> fix(compiler-vapor): prevent v-for components from being single root

- packages/runtime-vapor/__tests__/component.spec.ts
- packages/runtime-vapor/src/component.ts
- open [local playground with vapor branch](http://localhost:5173/#eNqNUk1PwzAM/StWLh3S1B7gNMokQDuAxIeAYw6rWq/LSJMoScukqf8dJ+3GkNjEoarj9xy/+HnHbo1JuxbZjOWutMJ46Aqj7Zwr0dDfw71uDKysbiBJs3AI9OSaqzwbCohKB4+NkYVHOgHklehiQGEoGWMAhwilVk5LBKnrFPwaoUHnihphWa6FrKDRrfJYLZcgHCjtA7HGKh3vixqGLtnQJs+OmrMp845arESdbpxW9LBdIHNWUp2QaF+MFySBsxlEJGCFlPrrMea8bXG6z5drLD//yG/cNuQ4e7Xo0HbI2QHzha3RD/Di/Rm3FB/ARletJPYZ8A1pPG3QONDuWlWR7CNeVPsQ7RGq/nCLrUfl9o8KQgOzj3zOyK4wslNP/5F7mV7FOq56muLe6tObsQOtngazoB9XZNyNAzCZXNzMY6/R9pTcnCS/nE4uqCN9/1woJ2knsjMb0H8DuMLxZQ==)
- observe the console; the message `child mounted` is not logged.
> fix(runtime-vapor): properly mount component when using setInsertionState

- packages/compiler-vapor/__tests__/transforms/transformElement.spec.ts
- packages/compiler-vapor/__tests__/transforms/transformSlotOutlet.spec.ts
- packages/compiler-vapor/__tests__/transforms/vIf.spec.ts
- packages/compiler-vapor/__tests__/transforms/vSlot.spec.ts
- packages/compiler-vapor/src/generators/component.ts
- packages/compiler-vapor/src/generators/prop.ts
- packages/compiler-vapor/src/transforms/transformSlotOutlet.ts
- packages/compiler-vapor/src/transforms/vSlot.ts
https://github.com/vuejs/core/blob/vapor/packages/compiler-vapor/package.json#L45-L47
`compiler-core` is not in `compiler-vapor`'s dependencies, we should use `compiler-dom` instead.
And the bundler size has been reduced by 15KB.
- Before
- After
> chore(compiler-vapor): use compiler-dom instead of compiler-core

- packages/runtime-vapor/__tests__/apiCreateDynamicComponent.spec.ts
- packages/runtime-vapor/src/block.ts
- pnpm-lock.yaml
- [Playground with vapor branch](https://deploy-preview-12359--vapor-repl.netlify.app/#eNqVUj1vwjAQ/SuWF0BCydBOUaAFxNAObUU7ekmNCYbEtvyRIiH+e892SKFKkTrZd/fe3buPI54plTSO4QznhmquLGoKJfWUCF7Da9ERmW1RVfJrxTbohDZa1mgAjEGHWMhazdpAkgbLp7wGzK8A8xZABJXCWESd1kxYNLkoNgyZRkRsnKCWS4GsLMuKDUfoSAQ6c5KmqBwD5i97MmmFPbT1s2gTcSIiT2Oz0CYYltWqKiwDC6H801kLxR5pxel+QnCsSvA0fvI0AiJ4zZvwgS+F7FL4LjJugNfqAWKedrHISiMtTy8q4zG2Bqax4WWyM1LARkKbkAjIvGL6VfkpGIKzOAAfC8N6Dj6rHRuf/XTL6L7HvzMH7yP4TTPDdAN9dTFb6JKBXh9evr+wA/y7YC3Xzk/hRnDFjKyc1xhhcyfWIPsCF9Q+haPgovwwy4Nlwpyb8kI98hTwBMOJ+I391fqP3LvkPvBgtTDF7gB7bvr25tV00d5ht68MzfJU9eyqu+KeKv+uMe+rcfoG5PY7IA==)
- click `toggle` button
> fix(runtime-vapor): dynamic component work with insertionState

- packages/compiler-vapor/__tests__/transforms/__snapshots__/vOn.spec.ts.snap
- packages/compiler-vapor/__tests__/transforms/vOn.spec.ts
- packages/compiler-vapor/src/generators/expression.ts
```ts
<div @click="handleClick as any" /> 
// convert to
n0.$evtclick = e => _ctx.handleClick as any(e) // syntax error
```
```ts
<div @click="handleClick as any" /> 
// convert to
n0.$evtclick = e => _ctx.handleClick(e) // correct
```
> fix(compiler-vapor): remove types for expressions

- packages/runtime-vapor/__tests__/componentProps.spec.ts
- packages/runtime-vapor/src/componentProps.ts
- open [Playground with vapor branch](https://deploy-preview-12359--vapor-repl.netlify.app/#eNqNU01v2zAM/SucLkmBzMawnTwnwDYU2HZoi7ZoL7oYNu2olSVBkt0Uhv97KTlJk36hhyAi36P0yEcP7JcxSd8hy1juSiuMB4e+MyuuRGu09XBT0N8f3RqorW5hlqT7TCic/eQqT6dSKqLAY2tk4ZEigHxPTinO0wOQLZh3pVa1aJI7pxVJGEIJZyXRhUR7brzQynGWQUQCVkipH/7HnLcdLnb5co3l/Rv5O7cJOc4uLDq0PXK2x3xhG/QTfHp1hhs678FWV50k9gfgJTotu6Bxov3uVEWyD3hR7b84SKGaa3e68ajcrqkgNDDHyOeMxhkm9V7rz3K/Jz9iHVcjTXFnxUsPoQ+zB1moZknVdNmzqwM8FL5cj1tTg5FckRnOg7HaOFhChbVQeBGiPGpoXZOB85Y6oYdX85Ngd7xmHmsW85PlKjLDRVpiInUzQUQd6ffRolSijweAYaCXRmqOsumUfrk4Ryv4dt+HvVqs4bjVXbP0ErVK+Hz2F8ksuNVWVl9mJHZbfbT6n9369bfVMMTLxzFPKYpZoUznof9K24OSLCGcMwgfBoHxnYxSrz6U3PlHGQ5JrfV2vlLbzGJFMmhOpCQy2PgEYNBNUw==)
- `Invalid watch source:....` occurred
[Playground with this …
> fix(runtime-vapor): should not warn invalid watch source when directly watching props

- packages/compiler-vapor/__tests__/transforms/__snapshots__/vBind.spec.ts.snap
- packages/compiler-vapor/__tests__/transforms/vBind.spec.ts
- packages/compiler-vapor/src/generators/expression.ts
- [Playground with vapor branch](https://deploy-preview-12359--vapor-repl.netlify.app/#eNp9kTFPwzAQhf+KdStVOsAUpa0AdYABEDB6SZNrcHBsyz6HSFH+O+dELR1QN99735Pf2SPcO5f1ESGHIlReORIBKTrRl876rTSVNYGEPbRiI8ZJmmK9YGzxQNg5XRLyVNSqF7mqNxKY3mVHa8VNCu6yQ+klbIs1EwlcX6RgBRT4jqNqsjZYwz1GaYSQUNnOKY3+1ZHiDhJyMTvJK7W2P8+zRj7i6qRXX1h9/6O3YUiahDePAX2PEs4elb5BWuz9xwsOfD6bna2jZvqK+Y7B6pg6LthDNDXXvuDmtk8dvycp03yG/UBowmmpVDSR08xL4M94vLL6X93b7G7OSTPB9AvSMJbU)
> fix(compiler-vapor): properly cache variable with optional chaining

- packages/runtime-vapor/src/vdomInterop.ts
- [Playground with vapor branch](https://deploy-preview-12359--vapor-repl.netlify.app/#eNp9UctuwjAQ/JWVL4CEkkN7ogGprTi0hxa1PfoShQVME9uyN4CE8u/dNeUhVHqyd2ZWHs/s1aP32aZFNVJFrILxBBGp9bApvQsTbU3DJ8Gzazwsgmugl+UyyFLvQdsiP6yxlAfCxtclIU8Ahehyvhb5Ba6GimLl7MIss3V0ll/ei1qriuWmxvDuyTgbtRpBYoQr69ptXxNGocXhEa9WWH3/ga/jTjCtZgEjhg1qdeKoDEukAz39fMMd309k4+Ztzep/yA+Mrm7F40H21No5277QJbcvKTljl19xuiO08fgpMSrKLum14iQlqVtfP9u9y+7TnrYdp3hs4bq6c2l72JZUraD7bU4q05azjwQ+OB9hDHNcGIszmfoDbdNCP5FD6A9gPBEj/CBzN6u+brj7AZMQybs=)
There is a similar issue when directly watching props in the Vapor component. Related PR: #13384
> fix(runtime-vapor): ensure props are shallow reactive in VDOM component

- packages/compiler-vapor/__tests__/transforms/__snapshots__/vBind.spec.ts.snap
- packages/compiler-vapor/__tests__/transforms/vBind.spec.ts
- packages/compiler-vapor/src/generators/expression.ts
- [Playground with vapor branch](https://deploy-preview-12359--vapor-repl.netlify.app/#eNp9kT9PxDAMxb9K5JVTO8BUlZMA3QADIGDMUrWm5EiTKHZKpVO/O0l6/4bTbfZ7z9HP8Q4enCvGgFBBTa1XjgUhByfGxlm/lkaaulyMpWEcnG4YYyfqTo2iUt29BFewYo3iRuwrOpUS1nUZo3GkLs/mYQVMrTXfqi+2ZE1k2MVXhYTWDk5p9G+OlTUkoRLZSV6jtf17yRr7gKuD3v5g+3tB39KUNAnvHgn9GHGOHje+R17szecrTrE+moPtQoK/Yn4gWR0S4xJ7DKaL2Ge5TPs8xL9kZfov2kyMhg5LJdCUnHNeQjzE05XVT7i3xV2ek2aG+R8hM5VS)
> fix(compiler-vapor): handle cache variable name substring edge cases

- packages/runtime-core/src/apiInject.ts
Found a missed spot to use `getCurrentInstance` API instead of direct instance access.
> chore: migrate to getCurrentInstance API

- packages/compiler-vapor/package.json
- pnpm-lock.yaml
fix https://github.com/vuejs/ecosystem-ci/actions/runs/16107157715/job/45444649085
> fix(compiler-vapor): add missing dependency for @babel/parser

- packages/runtime-vapor/src/index.ts
To determine if a node is a block for vue-jsx-vapor.
```ts
function normalizeNode(node: any): Block {
if (node instanceof Node || isFragment(node) || isVaporComponent(node)){
return node
} else {
// ...
}
}
```
> feat(runtime-vapor): expose isVaporComponent

- packages/compiler-vapor/__tests__/transforms/__snapshots__/vOn.spec.ts.snap
- packages/compiler-vapor/__tests__/transforms/vOn.spec.ts
- packages/compiler-vapor/src/generators/component.ts
- packages/compiler-vapor/src/generators/expression.ts
```ts
const _on_update:model = () => {} // variable name error
```
> fix(compiler-vapor): handle special characters in cached variable names

- packages/compiler-core/src/utils.ts
https://play.vuejs.org/#eNp9kLuOwjAQRX8lmpoNxW6FIqTdFQUUgIDSTZQMweB4LHscIqH8O7YRjwLR2fecse74Ar/G5J1HmEDB2BpVMk6FzrKill3Wfe2J8mkxDpeQFuMXBUbAriK9l01+dKTDC5c4KKCi1kiFdmVYknYCJlkikZVK0XmRMrYeR/e8OmB1epMfXR8zAWuLDm2HAh6MS9sg3/Bsu8Q+nB+wpdqrYH+AG3SkfOx40/68rkPtFy+1nbeGLEvd7NysZ9TuvlQsGs0h+QLCN/5/WP1Z9zv/SXNCDzBcAU2TfbA=
> fix(compiler-core): recognize empty string as non-identifier

- packages/compiler-core/src/parser.ts
- packages/compiler-core/src/utils.ts
`v-pre.` and `v-pre:xxx` will cause all subsequent updates of the template to be completely stuck in pre state.
> fix(compiler-core): avoid self updates of `v-pre`

- packages/runtime-vapor/__tests__/componentSlots.spec.ts
- packages/runtime-vapor/src/block.ts
- packages/runtime-vapor/src/dom/prop.ts
- packages/runtime-vapor/src/insertionState.ts
close #13764
- [Playground with vapor branch](https://deploy-preview-12359--vapor-repl.netlify.app/#eNp9UkFOwzAQ/Ioxh4KEkgOcSloJUCXgAAiQuPgSJZuQ4tiW7YRKUf7Orts0DYLedndm7LF3On5jTNQ2wOc8cZmtjGcOfGOWQlW10dazO10bVlhds1kUU0P02bVQSbwVIBUbD7WRqQfsGEuIFyqsB4Sd5lCkjSQBAQjlVbvcDZOYmp0knpw2OaPQeqrHwRFtEixjOZnzC+5dplVRldHaaYWv74gteIbsSoJ9Nr7Sygk+ZwEhLJVSfz+GmbcNXAzz7BOyrz/ma7ehmeAvFhzYFgTfYz61JfgtvHp7gg3We7DWeSORfQR8BadlQx63tNtG5Wj7gBfcPoQdVqp8d6uNB+WGR5FRYvaBLzjulD7qv6ePdi+jq6ATqsdfHPLwOz6sTfHiMUQds1CwfpcjChCFBjfgPKtdyRaEn83uAU2zD21lfjI7Px6xg5U7qT2LJ51Ka1gIjuEQfIRI03Xhxr4fUzNU04z0PyecBUA=)
- [Playground with this PR](https://deploy-preview-13558--vapor-repl.netlify.app/#eNp9UkFOwzAQ/Ioxh4KEkgOcSloJUCXgAAiQuPgSJZuQ4tiW7YRKUf7Orts0DYLedndm7LF3On5jTNQ2wOc8cZmtjGcOfGOWQlW10dazO10bVlhds1kUU0P02bVQSbwVIBUb …
> fix(runtime-vapor): properly handle consecutive prepend operations with insertionState

- packages/compiler-vapor/__tests__/transforms/transformText.spec.ts
- packages/compiler-vapor/src/transforms/transformComment.ts
- packages/compiler-vapor/src/transforms/transformText.ts
see [Playground](https://play.vuejs.org/#eNp9UMFKAzEQ/ZUlh55qKlY8tGFBpQc9qKjHgITsuE3NJiGZrAtl/90kS2sPpbeZ997MvHl7cu8c7SOQFWFBeuWwCoDRVb1w1tfcsMUEpzI1CJ3TAiF1VcUa1ddM2gbqmcb1pJu1uGaLArJFFuQVJ2NkTjBIa75VS3fBmnR4n5dxIm3nlAb/6lBZEzhZVYXJnNDa/j4XDH2E+QGXW5A/Z/BdGDLGyZuHAL4HTo4cCt8CTvTm4wWGVB/JzjZRJ/UF8h2C1TF7nGQP0TTJ9omuuH3qUoCoTPsZNgOCCYenstGsHIuek5T+44XX/+0u6W2Z42ZMKX714PPOFOCS3tHrK6HdVtAbMv4BMW+aBQ==)
https://github.com/vuejs/core/blob/5edb7ba546f5ad911c98575cca54d721fdebcac2/packages/compiler-dom/src/transforms/stringifyStatic.ts#L299-L315
> fix(compiler-vapor): escape html for safer template output 

- packages/runtime-core/src/hmr.ts
> Revert "fix(hmr): prevent __VUE_HMR_RUNTIME__ from being overwritten by vue runtime in 3rd-party libraries"
