vuejs/core

- packages/compiler-core/src/transforms/vBind.ts
**What kind of change does this PR introduce?** (check at least one)
**Does this PR introduce a breaking change?** (check one)
If yes, please describe the impact and migration path for existing applications:
**The PR fulfills these requirements:**
If adding a **new feature**, the PR's description includes:
**Other information:**
> chore: fix typo about vBind.ts

- packages/compiler-core/src/ast.ts
- packages/compiler-core/src/codegen.ts
- packages/compiler-core/src/errors.ts
- packages/compiler-core/src/transforms/transformExpression.ts
- packages/compiler-core/src/transforms/vBind.ts
- packages/compiler-core/src/transforms/vFor.ts
- packages/compiler-core/src/transforms/vOn.ts
- packages/runtime-core/src/apiOptions.ts
- packages/runtime-dom/src/modules/class.ts
- packages/runtime-dom/src/modules/events.ts
- packages/shared/src/patchFlags.ts
> chore: comment typos

- packages/reactivity/src/ref.ts
All in all, TS has recursion, but it is limited by 50 steps.
> types: use recursion for unwrapping refs

- packages/reactivity/__tests__/collections/WeakMap.spec.ts
- packages/reactivity/__tests__/collections/WeakSet.spec.ts
This is my first open source contribution, so hopefully I did everything correctly.
Fixed a small copy & paste error with the collection types in the tests.
> test(reactivity): fixed small copy & paste error

- lerna.json
See: https://github.com/lerna/lerna/blob/master/commands/bootstrap/README.md#--use-workspaces
> build: sepecify yarn in lerna config

- packages/reactivity/src/baseHandlers.ts
use function `isSymbol` instead of `typeof`
> refactor(reactivity): use function isSymbol instead of typeof

- .gitignore
Add the yarn error log file to git ignore
> chore: add the yarn error log file to git ignore

- packages/reactivity/src/effect.ts
1. Prefer to use symbol for effect.
2. Add `isEffect()` to check if a function is reactive effect.
> refactor(reactivity): prefer to use effect symbol and add isEffect()

- packages/runtime-core/src/apiReactivity.ts
I used `any` since there was an error but types matched
> refactor(apiReactivity): improve types

- packages/runtime-test/src/serialize.ts
- scripts/build.js
use `Boolean` to filter empty strings of array
this will be easier to read and understand
> chore: use Boolean to filter empty

- packages/runtime-core/src/helpers/renderList.ts
> refactor(runtime-core): use `Array.from` instead of loop over `iterable`

- packages/runtime-core/src/apiLifecycle.ts
> refactor(runtime-core): add `createLifecycleInjector`

- .circleci/config.yml
add friendly name to each ci job step
> ci: add step name

- jest.config.js
- packages/global.d.ts
- packages/runtime-core/__tests__/version.spec.ts
- packages/runtime-core/src/index.ts
- rollup.config.js
Reason: backwards compat with previous versions
Please tell me if I'm wrong and this should go to `vue` package.
> feat(core): export version

- packages/runtime-core/__tests__/apiApp.spec.ts
- packages/runtime-core/src/apiApp.ts
- packages/runtime-core/src/component.ts
- packages/runtime-dom/src/index.ts
- packages/shared/src/element.ts
> feat: runtime component name validation

- packages/runtime-dom/__tests__/vModel.spec.ts
- packages/runtime-dom/src/directives/vModel.ts
Checkbox model probably contained an error so I went ahead and fixed it.
> test(runtime-dom): vModel tests

- packages/compiler-core/__tests__/parse.spec.ts
- packages/compiler-core/src/parse.ts
- packages/runtime-core/src/apiApp.ts
- packages/runtime-core/src/component.ts
- packages/vue/__tests__/index.spec.ts
> feat: add isCustomElement option for declaring custom elements

- packages/runtime-core/__tests__/directives.spec.ts
- packages/runtime-core/src/component.ts
- packages/runtime-core/src/directives.ts
- packages/runtime-core/src/index.ts
- packages/runtime-dom/src/directives/vModel.ts
Reason: backwards compat with v2 (https://vuejs.org/v2/api/#Vue-directive)
> feat(directives): add support for function directives

- packages/runtime-core/src/component.ts
- packages/runtime-core/src/errorHandling.ts
- packages/shared/src/index.ts
reason: this will reduce repeating of code and add a type guard
> refactor(runtime-core): extract promise check into shared

- packages/compiler-core/__tests__/transforms/transformElement.spec.ts
- packages/compiler-core/src/runtimeHelpers.ts
- packages/compiler-core/src/transforms/transformElement.ts
- packages/runtime-core/__tests__/helpers/resolveAssets.spec.ts
- packages/runtime-core/src/helpers/resolveAssets.ts
- packages/runtime-core/src/index.ts
> feat(compiler-core/runtime-core): dynamic component implementation & tests

- packages/runtime-core/__tests__/apiApp.spec.ts
- packages/runtime-core/src/apiApp.ts
- packages/runtime-core/src/component.ts
- packages/runtime-core/src/directives.ts
Check whether dev is trying to register a directive named as built-in one and create a warning in dev mode.
> feat(apiApp): validate directives names

- packages/compiler-core/__tests__/__snapshots__/parse.spec.ts.snap
- packages/compiler-core/src/parse.ts
> fix(parse): fix types

- packages/runtime-core/src/apiInject.ts
This mistake could cause this error:
> fix(apiInject): fix stringifying of injection key

- scripts/utils.js
I think this method doesn't use the character of some,some use forEach instead is better
> chore: some->forEach

- packages/runtime-core/__tests__/apiApp.spec.ts
- packages/runtime-core/src/apiApp.ts
It was removed some unnecessary `else` in code too
> fix(runtime-core): fix error when passed plugin is undefined

- .github/contributing.md
I think add a little details can make this part description more clear and friendly.
> docs: add more details about automatically validated and formatted

- packages/compiler-sfc/__tests__/compileTemplate.spec.ts
- packages/compiler-sfc/package.json
- packages/compiler-sfc/src/compileTemplate.ts
Basically a port of the current component-compiler-utils, though drastically simplified thanks to new architecture (and there could be something that I didn't get right...).
> feat(compiler-sfc): compile template

- packages/compiler-sfc/__tests__/__snapshots__/compileTemplate.spec.ts.snap
- packages/compiler-sfc/__tests__/compileTemplate.spec.ts
- packages/compiler-sfc/src/compileTemplate.ts
> test(compiler-sfc): more tests for compileTemplate

- packages/vue/examples/__tests__/commits.spec.ts
- packages/vue/examples/classic/commits.html
- packages/vue/examples/composition/commits.html
- packages/vue/examples/mocks/commits.js
Besides the test from Vue 2.0, I added `waitForResponse` to enhance the testing a bit more.
So that if `watch` is broken or something, the test can catch it.
(or probably we should mock the API requests for testing?
> test(e2e): add e2e test for commits example

- packages/vue/examples/__tests__/svg.spec.ts
- packages/vue/examples/classic/svg.html
- packages/vue/examples/composition/svg.html
- Remove duplicate `valueToPoint`
- Expose `stats` as `globalStats` for testing (no idea for a better name)
> test(e2e): add test for svg example

- package.json
- packages/runtime-dom/jsx.d.ts
- packages/runtime-dom/package.json
- yarn.lock
update jsx types base on @types/react@16.9.
fixed some typo
> types: update jsx support

- packages/compiler-sfc/__tests__/parse.spec.ts
> test(compiler-sfc): add real tests for source maps

- packages/runtime-dom/src/components/TransitionGroup.ts
> fix(transition-group): handle multiple move-classes (#678, #638)

- packages/server-renderer/__tests__/renderToString.spec.ts
- packages/server-renderer/src/renderToString.ts
Component setup utils update `instance` but `server-renderer` expects `render` function to be on component options object.
> fix(server-renderer): render components returning render function from setup

- packages/compiler-core/__tests__/transforms/vBind.spec.ts
- packages/compiler-core/src/transform.ts
- packages/compiler-core/src/transforms/transformElement.ts
> fix(compiler-core): should alias name for helpers

- packages/compiler-core/src/parse.ts
use 'const' instead of 'let' here
> style(compiler): use 'const' instead of 'let'

- packages/server-renderer/src/renderToString.ts
Non-functionality code structure change, extract buffer and portal related code.
> refactor(ssr): extract buffer resolving and resolvePortals

- packages/runtime-core/src/componentRenderUtils.ts
> chore: fix componentRenderUtils.ts comment typo

- packages/reactivity/src/baseHandlers.ts
- packages/reactivity/src/collectionHandlers.ts
> types(reactivity): remove this in get accessor

- packages/runtime-core/src/renderer.ts
fix https://github.com/vuejs/vue-next/issues/808
> fix(runtime-core): pass prev value to hostPatchProp

- packages/runtime-core/src/apiOptions.ts
Match current behavior of Vue 2 - https://github.com/vuejs/vue/commit/3a5432a9e3f470ebafcef905281b830537897037#diff-cb87aa7890fa694dd923ea9f162256d2
> fix(runtime-core): pass instance proxy as data() argument

- .ls-lint.yml
- package.json
- yarn.lock
> feat(test): add ls-lint

- packages/shared/src/domTagConfig.ts
> fix: invalid lineGradient svg tag

- packages/runtime-dom/src/directives/vModel.ts
> fix(runtime-dom): fix getModelAssigner order in vModelCheckbox

- packages/runtime-core/src/componentRenderUtils.ts
update dynamic children
fix #943
> fix(runtime-core): set fragment root children should

- packages/runtime-core/src/index.ts
> Revert "feat(effect): add effect to public api"

- test-dts/ref.test-d.ts
> types(ref): fix dts test for ref

- README.md
Vuex Released New Beta Version
> fix: Vuex Is Beta Now

- scripts/build.js
https://github.com/vuejs/vue-next/blob/892fb6d2290516df44241992b62d65f1376f611a/scripts/build.js#L126
> fix(script): extractorResult is not defined

- packages/runtime-dom/src/components/TransitionGroup.ts
> fix(TransitionGroup): should collect raw children with Fragment

- .github/workflows/release-tag.yml
> ci: add changelog link in releases

- packages/runtime-core/__tests__/vnode.spec.ts
- packages/shared/src/normalizeProp.ts
> fix(mergeProps): There is no merge when a string type is passed in

- packages/runtime-dom/src/components/Transition.ts
> fix(Transition): should reset enter class when have appear props

- packages/server-renderer/src/index.ts
> types(server-renderer): export SSRContext type

- packages/runtime-dom/src/directives/vModel.ts
> fix(runtime-dom): should ignore change event when input is composing in Safari 

- packages/runtime-dom/src/modules/events.ts
> chore: fix typo.

- package.json
- scripts/checkYarn.js
> workflow: alert developer to use yarn

- packages/runtime-core/src/components/BaseTransition.ts
- packages/runtime-core/src/vnode.ts
> types(runtime-core): improve types for transition hook

- packages/reactivity/__tests__/reactive.spec.ts
- packages/reactivity/__tests__/readonly.spec.ts
- packages/reactivity/__tests__/ref.spec.ts
test(reactivity): 100% reactivity coverage
> test(reactivity): 100% reactivity coverage

- packages/runtime-core/src/components/KeepAlive.ts
Iterator is more efficient than Array.from
https://codepen.io/ysj16/pen/MWKwLpz
> perf: optimize LRU in keep-alive

- packages/compiler-sfc/src/compileTemplate.ts
- packages/runtime-core/src/components/KeepAlive.ts
> fix(types): improve typing

- packages/runtime-core/src/renderer.ts
fix #1336
Maybe we only test it with e2e test?
> fix: should attach instance for path props when mount element

- packages/runtime-core/__tests__/hmr.spec.ts
- packages/runtime-core/src/componentRenderUtils.ts
- packages/runtime-core/src/renderer.ts
fixes https://github.com/vuejs/vue-next/issues/1305
> fix(HMR): parent static class not removed on HMR

- packages/vue/__tests__/index.spec.ts
- packages/vue/src/index.ts
set istanbul ignore in __DEV__ has false value statement
> test(vue): 100% vue packages coverage

- packages/compiler-sfc/__tests__/templateUtils.spec.ts
Submit the test for the first time, be familiar with the process, and complete later
> test(compiler-sfc):test isRelativeUrl

- packages/compiler-core/__tests__/transforms/vIf.spec.ts
add vif with comments test case
> test(compiler-core): add vif with comments test case

- packages/vue/__tests__/index.spec.ts
test mount with selector of rootContainer
> test(vue): mount with a selector

- packages/runtime-dom/src/directives/vShow.ts
> fix: fix v-show unmount

- packages/runtime-core/src/componentProps.ts
- packages/runtime-core/src/vnode.ts
refactor(types): remove unnecessary as any
> refactor(types): remove unnecessary as any

- packages/reactivity/src/collectionHandlers.ts
- packages/reactivity/src/ref.ts
1、add Iterable & Iterator
2、simplified UnwrapRefSimple
> refactor reactivity types

- packages/runtime-core/src/componentRenderUtils.ts
fix #https://github.com/vitejs/vite/issues/536
> fix(runtime-core): shouldn't set self scopeId into props

- packages/runtime-core/__tests__/rendererComponent.spec.ts
add test for rendererComponent
> test(runtime-core): add test for rendererComponent

- packages/compiler-dom/src/errors.ts
- packages/compiler-ssr/src/errors.ts
make the error message in `compiler-dom` and `compiler-ssr` a bit
cleaner and fix grammar
> chore: fix error message

- CHANGELOG.md
ฏ๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎ฏ๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎ฏ๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎ฏ๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎ฏ๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎ฏ๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎
> BREAKING CHANGE: add ` to Changelog!!

- packages/runtime-dom/__tests__/directives/vOn.spec.ts
> Perfect shortcut key test

- packages/reactivity/src/reactive.ts
Use a local variable to reduce code size
> refactor(reactive): reduce code size by assigning symbol to a local variable

- test-dts/defineComponent.test-d.tsx
Just adding an extra checking to dts
> test(types): method return type inference VOA test

- packages/runtime-core/src/renderer.ts
fix https://github.com/vitejs/vite/issues/613
> fix(hmr): should update el for `HYDRATE_EVENTS` patchFlags node

- packages/compiler-core/src/errors.ts
I'm not sure if my new error message is completely accurate, but I think this error message might benefit from more detail. When I saw this message, I wasn't sure what it meant, and I had to search through the GitHub issues to figure out what to do.
> chore(compiler-core): improve X_V_IF_KEY error message

- packages/reactivity/__tests__/reactive.spec.ts
- packages/reactivity/src/reactive.ts
use isExtensible instead of isFrozen
> fix(reactive): use isExtensible instead of isFrozen

- packages/reactivity/src/baseHandlers.ts
- packages/reactivity/src/reactive.ts
- test-dts/ref.test-d.ts
1. add dts for `proxyRefs`
2. improve typings for `createGetter`
> types(reactivity): add dts for proxyRefs & improve typings

- packages/reactivity/__tests__/ref.spec.ts
- packages/reactivity/src/ref.ts
> feat(reactivity): Support returning an array from toRefs

- packages/reactivity/__tests__/reactive.spec.ts
The current test case does not seem to fulfill the test purpose.
> test(reactivity/reactive): replace invalid test cases

- README.md
Vue Router is now marked with Beta.
> docs(readme): update Vue Router status footer note

- packages/runtime-core/__tests__/vnode.spec.ts
- packages/runtime-core/src/vnode.ts
> fix: class and style should be properly normalized in cloneVNode

- packages/runtime-core/src/componentPublicInstance.ts
Type `this` of ComponentPublicInstance#watch should be `ComponentPublicInstance`,
instead of `ComponentInternalInstance` which declared by `instanceWatch`
> fix(runtime-core): fix `this` type of ComponentPublicInstance#$watch

- packages/runtime-dom/__tests__/directives/vModel.spec.ts
- packages/runtime-dom/src/directives/vModel.ts
- packages/shared/src/index.ts
- packages/shared/src/looseEqual.ts
> feat(runtime-dom): allow Set as model

- packages/runtime-core/__tests__/apiOptions.spec.ts
- packages/runtime-core/src/componentOptions.ts
Fix https://github.com/vuejs/vue-next/issues/2071
> fix(runtime-core): optional `from` option in inject object config

- packages/compiler-core/__tests__/transforms/vIf.spec.ts
- packages/compiler-core/src/transforms/vIf.ts
> fix(compiler-core): allow spaces between if-else branches

- packages/runtime-dom/src/directives/vModel.ts
> fix(runtime-dom): avoid clearing unresolved text when update

- packages/compiler-core/__tests__/__snapshots__/parse.spec.ts.snap
- packages/compiler-core/__tests__/parse.spec.ts
> test(compiler-core): more test cases for baseParse

- packages/runtime-core/src/apiWatch.ts
There seems to be no need to make additional judgments.
> refactor(runtime-core): simplify traverse

- jest.config.js
Introduced by https://github.com/vuejs/vue-next/commit/6ba7ba47d59288b8cd39c985a2163ebd220607bc#diff-1e058ca1442e46581b13571fb8d261f9e1f5657e26c96634d4c1072f0f0347f1R25
> test: package exclusion from code coverage

- packages/runtime-core/src/componentProps.ts
close #https://github.com/vitejs/vite/issues/872
> fix(hmr): full diff props for non-sfc component

- .circleci/config.yml
- .github/workflows/size-check.yml
> ci: add size check integration

- packages/runtime-core/src/componentProps.ts
- test-dts/defineComponent.test-d.tsx
- test-dts/h.test-d.ts
> types(defineComponent): fix prop Boolean to be of type Boolean

- packages/runtime-core/src/component.ts
fix typo: ocmponent -> component
> chore(runtime-core): fix typo

- packages/runtime-core/src/renderer.ts
> fix(runtime-core): remove static node in production mode

- packages/compiler-sfc/__tests__/parse.spec.ts
- packages/compiler-sfc/src/parse.ts
> fix(compiler-sfc): lang="" on a html tag produces error (close #2566)

- packages/runtime-dom/__tests__/patchProps.spec.ts
- packages/runtime-dom/src/modules/props.ts
> fix(runtime-dom): attribute should be removed with nullish values

- rollup.config.js
Close #2470
Close #2457 
See https://github.com/terser/terser#minify-options.
> fix: enable safari10 option for terser (close #2470)

- packages/runtime-core/src/renderer.ts
- packages/vue/examples/classic/commits.html
> fix(runtime-core): skip patchBlockChildren if n1.dynamicChildren is null

- packages/shared/src/patchFlags.ts
./renderer.ts -> ../../runtime-core/src/renderer.ts
> chore: wrong file path in comments

- packages/runtime-core/src/hmr.ts
Hi,
Just a typo found while experimenting with Vue 3 today.
Thanks :wave: 
Bruno
> chore: typo "depdendency"

- README.md
GitHub 'h' should be capitalized.
> chore: GitHub typo

- packages/runtime-core/src/apiWatch.ts
Ref: https://github.com/vuejs/vue-next/pull/2425
> chore: remove overloads numbers in comments

- packages/runtime-core/__tests__/apiOptions.spec.ts
- packages/runtime-core/src/componentOptions.ts
> fix(runtime-core): component methods should override global properties in DEV

- packages/compiler-core/src/parse.ts
> chore: comment initial space (#3192) [skip ci]

- packages/runtime-core/src/componentOptions.ts
> fix(runtime-core): properties in methods should be writable and enumerable in DEV

- packages/runtime-core/src/scheduler.ts
> fix(scheduler): ensure only skip unflushed job

- packages/compiler-core/__tests__/parse.spec.ts
- packages/compiler-core/src/parse.ts
> fix(compiler-core): should not condense whitespace in RCDATA text mode

- packages/compiler-dom/__tests__/transforms/stringifyStatic.spec.ts
- packages/compiler-dom/src/transforms/stringifyStatic.ts
> fix: stringifyStatic should remove attribute with `null` value

- packages/runtime-core/__tests__/componentEmits.spec.ts
https://github.com/vuejs/vue-next/commit/c1cd42e627bdeb561d54e64ea5fea87ccbbae637#r49017891
> test: typo in spy

- packages/reactivity/__tests__/shallowReactive.spec.ts
Close this PR if I have misunderstand with `und`
> chore: Fix typo in test case description

- packages/reactivity/__tests__/effect.spec.ts
- packages/reactivity/src/collectionHandlers.ts
> fix(reactivity): fix the tracking when readonly + reactive is used for Map

- packages/compiler-core/__tests__/transforms/__snapshots__/vSlot.spec.ts.snap
- packages/compiler-core/__tests__/transforms/vSlot.spec.ts
- packages/compiler-core/src/transforms/vSlot.ts
> fix(compiler-core): fix the whitespace management of component slots

- packages/runtime-core/src/compat/componentVModel.ts
> fix(compat): avoid accidentally delete the modelValue prop

- packages/compiler-core/src/transforms/transformExpression.ts
- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
> fix(compiler-sfc): template assignment expression codegen correctly

- packages/runtime-dom/src/directives/vModel.ts
> fix(runtime-dom): only set selectedIndex when the value changes

- packages/vue-compat/index.js
See https://unpkg.com/browse/@vue/compat@3.1.0/dist/ for built file names.
You may alternatively wish to change the built filenames, in which case do just let me know, or consider this a bug report.
> fix(compat): update cjs dist file names

- packages/compiler-core/__tests__/transforms/vSlot.spec.ts
- packages/compiler-core/src/transforms/vSlot.ts
> fix(compiler-core): forwarded slots work with template tag

- packages/compiler-core/src/ast.ts
- packages/compiler-core/src/errors.ts
> refactor(types): improve of type assertion

- packages/runtime-core/src/renderer.ts
I want to be a Vue Contributor ^.^
> chore(runtime-core): use bit operations instead

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/compileScript.ts
> fix(compiler-core): defineProps infer TSParenthesizedType

- packages/reactivity/__tests__/effect.spec.ts
> test(reactivity): correct the description of the test case

- packages/compiler-sfc/src/compileStyle.ts
remove unnecessary type assertion
> chore(types): remove unnecessary type assertion

- packages/compiler-core/src/transforms/vBind.ts
- packages/compiler-ssr/src/transforms/ssrTransformComponent.ts
remove unnecessary non-null assertion
> chore(types): remove unnecessary non-null assertion

- README.md
use `vite` instead of `@vitejs`
> docs: use vite as a startup tool

- packages/runtime-core/__tests__/helpers/withMemo.spec.ts
- packages/runtime-core/src/helpers/renderList.ts
> fix(vMemo): should work on v-for with constant expression

- packages/compiler-core/__tests__/transforms/__snapshots__/vMemo.spec.ts.snap
- packages/compiler-core/src/transforms/vFor.ts
- packages/runtime-core/src/helpers/withMemo.ts
> fix(vMemo): ensure track block when returning cached vnode

- packages/compiler-core/__tests__/transforms/vSlot.spec.ts
- packages/compiler-core/src/transforms/vSlot.ts
> fix(compiler-core): nested component w/ slot

- packages/runtime-core/src/apiDefineComponent.ts
ComponentOptionsWithoutProps has been processed internally
> fix(types): delete useless props type

- packages/reactivity/__tests__/effectScope.spec.ts
- packages/reactivity/src/effectScope.ts
> test(reactivity): add test case for effectScope

- packages/runtime-dom/types/jsx.d.ts
reference #4242
see https://github.com/vuejs/vue-next/pull/4242#issuecomment-896628155
> fix(types): ReservedProps.key allow symbol

- packages/runtime-core/src/componentPublicInstance.ts
> types(runtime-core): improve forceUpdate type

- packages/runtime-core/src/componentEmits.ts
- test-dts/defineComponent.test-d.tsx
> fix(types): tsx wrong emit handler return type

- packages/runtime-core/src/componentRenderUtils.ts
- packages/runtime-core/src/hydration.ts
- packages/runtime-core/src/renderer.ts
- packages/runtime-core/src/vnode.ts
It can reduce calculation and code
> style: merge logic to reduce calculation and code

- packages/shared/__tests__/toDisplayString.spec.ts
- packages/shared/src/toDisplayString.ts
> fix(shared): improve toDisplayString

- packages/compiler-core/__tests__/transforms/transformElement.spec.ts
- packages/compiler-core/src/transforms/transformElement.ts
> fix(compiler-normalizeProps):add the condition for normalizeProps

- packages/runtime-dom/types/jsx.d.ts
when ref is callback function,passing component instance type error
> fix(types): fix the jsx type of ref function

- packages/reactivity/src/collectionHandlers.ts
> chore: missing space in warn

- packages/runtime-core/src/vnode.ts
> types: improve the type of createElementBlock

- packages/reactivity/__tests__/shallowReactive.spec.ts
- packages/reactivity/__tests__/shallowReadonly.spec.ts
delete the redundant code -- 'async'
> test(reactivity): delete unnecessary async in tests

- packages/reactivity/__tests__/effectScope.spec.ts
> test(reactivity): remove useless 'async'

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/compileScript.ts
> fix(compiler-sfc): support using declared interface in normal script with defineProps()

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/compileScript.ts
similar #4517 , have the same problem with `defineProps `
> types(compile-sfc): support  `Date` prop type with defineProps

- packages/runtime-core/src/componentProps.ts
- test-dts/defineComponent.test-d.tsx
> types(runtime-core): fix for multiple possible prop types including Date

- packages/runtime-dom/types/jsx.d.ts
> Extend CSSProperties with PropertiesHyphen

- packages/runtime-core/src/compat/compatConfig.ts
chore: fix docs typo in compatConfig.ts
> chore: fix docs typo in compatConfig.ts

- packages/compiler-core/__tests__/transforms/vSlot.spec.ts
- packages/compiler-sfc/src/cssVars.ts
- packages/runtime-dom/types/jsx.d.ts
> chore: prettier format

- .github/workflows/ci.yml
update to `actions/checkout@v2`
> workflows:update checkout version

- packages/ref-transform/README.md
Word spelling mistake,by the way, i love vue.
> docs: typo

- packages/runtime-core/src/renderer.ts
> runtime-core: typo in comments

- packages/runtime-core/src/components/BaseTransition.ts
- packages/vue/__tests__/Transition.spec.ts
- Be consistent with other judgment. (more performant and memory-efficient)
- Add test for invalid transition mode.
> chore: improve BaseTransition

- packages/reactivity/src/index.ts
- packages/reactivity/src/ref.ts
> fix(reactivity): export `ShallowRef`

- packages/runtime-dom/src/components/TransitionGroup.ts
> refactor(types): use `DOMRect` instead of the `Position` type

- packages/runtime-core/__tests__/componentProps.spec.ts
- packages/runtime-core/src/componentProps.ts
> fix(runtime-core): prop assigned to undefined also need to put into attrs

- packages/runtime-core/src/component.ts
Fixed minor typo in comment.
compliation → compilation
> chore: typo in comment [skip ci]

- .github/contributing.md
Signed-off-by: pengjie <37610029@qq.com>
> docs(contributing): missing structure info for compiler-sfc

- packages/runtime-dom/src/modules/events.ts
I think this line of code is written by mistake and it has no effect, so remove it.
> fix: remove superfluous code

- packages/compiler-sfc/src/index.ts
> types(compiler-sfc): export SFCParseResult type

- packages/runtime-core/src/renderer.ts
The value has been assigned here
https://github.com/vuejs/vue-next/blob/master/packages/runtime-core/src/renderer.ts#L1368
> chore(runtime-core): remove duplicate assignment

- packages/runtime-core/src/devtools.ts
> fix(runtime-core): fix eslint error

- packages/shared/src/typeUtils.ts
When I first read this type definition I have no idea what this type means. The type's name is kind of misleading I think. My first thought about this type is to conditionally output type by checking **if any** sub-type of type `T` is type `Y`, or something like that.  since that is what *IfAny* means in English. Clearly this is not what it means, and I think it is not a common use case, so it is better to leave some explaination there.
Maybe we can come up with a better name, but currently I cannot think of any more suitable. 😄
> chore: Add explaination about the utility type IfAny<T, Y, N>

- packages/reactivity/src/reactive.ts
> Micro comment edit in reactive.ts

- packages/compiler-core/src/transforms/transformElement.ts
- packages/compiler-sfc/__tests__/__snapshots__/compileTemplate.spec.ts.snap
- packages/compiler-sfc/__tests__/compileTemplate.spec.ts
> fix(compilre-core): dynamic v-on and static v-on should be merged

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/compileScript.ts
> feat(sfc): support using extends interface with defineProps()

- packages/runtime-core/src/componentPublicInstance.ts
- test-dts/watch.test-d.ts
> fix(types): `$watch` callback parameters type

- .github/workflows/ci.yml
- package.json
- packages/compiler-sfc/src/compileScript.ts
- packages/reactivity/src/ref.ts
- packages/runtime-core/__tests__/componentEmits.spec.ts
- packages/runtime-core/src/componentEmits.ts
To avoid making noise, make sure all PRs is formatted.
> ci: check prettier format

- packages/shared/src/typeUtils.ts
> fix:spell checker

- packages/compiler-sfc/__tests__/parse.spec.ts
- packages/compiler-sfc/src/parse.ts
> fix(compiler-sfc): require <template> or <script> in SFC

- packages/sfc-playground/src/App.vue
relate #6803
Make all scopes (`template`, `script`, and `style`) to production mode, then I can debug issue #6803 in production or dev mode.
> fix(sfc-playground): set all scopes to production mode

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/compileScript.ts
> refactor(compiler-sfc): drop Function prop type when no static default value

- packages/compiler-core/__tests__/transforms/__snapshots__/vModel.spec.ts.snap
- packages/compiler-core/__tests__/transforms/vModel.spec.ts
- packages/compiler-core/src/transforms/vModel.ts
> fix(compiler-core): case casting of v-model

- packages/shared/src/domTagConfig.ts
> fix(shared): `feDistanceLight` changed to `feDistantLight`

- .github/contributing.md
> chore: fix broken link

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/compileScript.ts
- packages/runtime-core/__tests__/componentProps.spec.ts
- packages/runtime-core/src/componentProps.ts
> feat(runtime-core): add skipCheck for prop

- packages/compiler-core/__tests__/transforms/transformExpressions.spec.ts
- packages/compiler-core/src/transforms/transformExpression.ts
> fix(compiler-core): check if expression is constant

- packages/runtime-core/__tests__/vnode.spec.ts
> test(vnode): Duplicate test statements

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/compileScript.ts
> fix(compiler-sfc): allow `StringLiteral` node in `defineEmit` tuple syntax

- packages/reactivity/src/ref.ts
Remove meaningless type assertion in unref.
> chore(reactive): remove unref type assertion

- package.json
- pnpm-lock.yaml
- scripts/dev.js
see https://github.com/remorses/esbuild-plugins/pull/29#issuecomment-1497077035
closes #7329
> chore: remove deprecated package

- packages/runtime-core/src/vnode.ts
> fix: fix template ref

- packages/reactivity/__tests__/collections/Map.spec.ts
- packages/reactivity/__tests__/collections/Set.spec.ts
- packages/reactivity/__tests__/collections/WeakMap.spec.ts
- packages/reactivity/__tests__/collections/WeakSet.spec.ts
- packages/reactivity/__tests__/reactive.spec.ts
- packages/runtime-dom/__tests__/createApp.spec.ts
- packages/vue-compat/__tests__/filters.spec.ts
> test: update test syntax

- packages/runtime-dom/src/index.ts
> fix(runtime-dom): update broken link in warning message

- packages/compiler-sfc/src/script/definePropsDestructure.ts
fixup https://github.com/vuejs/core/commit/862edfd91a2c2f6b75f943cb1a9682c4be5d7fa8
> fix(compiler-sfc): transform destructured props when reactivity transform option is enabled

- rollup.config.js
> fix(build): fix dev flag replacement in esm-builder builds

- packages/compiler-sfc/__tests__/compileScript/resolveType.spec.ts
- packages/compiler-sfc/src/script/resolveType.ts
> fix(compiler-sfc): support resolve multiple re-export /w same source type name

- packages/runtime-core/src/apiSetupHelpers.ts
> fix(runtime-core): fix typo

- scripts/const-enum.js
looks like isolation misspell to insolation
thank you
:five: :one:
:five: :one:
:five: :one:
:five: :one:
:five: :one:
> chore: fix typo

- packages/shared/src/globalsAllowList.ts
Fixes the regression described at https://github.com/vuejs/core/issues/8416#issuecomment-1566583260
> fix: add isGloballyWhitelisted back, but deprecated

- packages/reactivity/__tests__/reactive.spec.ts
test(reactivity): bigint test for non-observable values
> test(reactivity): bigint test for non-observable values

- packages/runtime-dom/src/jsx.ts
- [`inert`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert) global attribute
- [`hidden`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden) global attribute: `until-found` (new) and `hidden` (missing) value
> types(jsx): add `inert` attribute and missing `hidden` values

- packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript.spec.ts
- packages/compiler-sfc/src/script/importUsageCheck.ts
> fix(compiler-sfc): take into account imports that are used within dynamic arguments

- CHANGELOG.md
fix link to comment in changelog
> chore: fix link in changelog [ci-skip]

- packages/compiler-sfc/__tests__/compileScript/__snapshots__/defineModel.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript/defineModel.spec.ts
- packages/compiler-sfc/src/script/context.ts
https://play.vuejs.org/#eNp9kE1LAzEQhv/KMpcqlPXQWymCSg8KfmA95lJ2p2tqdiZkJnWh7H83ydLqQXoL7/NkeGeOcOd9fYgIS1hJE6zXSlCjvzXU4s4SPnOL7mqmvNFgqZtdG1rdTGZyYA4qDdPOdvVemNKYo6GqMtBw763D8OrVMomBZVVIZlvn+PupZBoizk9584nN1z/5XoacGXgLKBgOaODMdBs61AmvNy84pPcZ9txGl+wL8B2FXcwdJ+0+Uptq//FK28fec9B0gA9ZD4okp6Vy0WyOxTeQbvlwYfXfuot6Uf4ZGmH8AbOFgKk=
> fix(compiler-sfc): unexpected model name conflict

- packages/compiler-sfc/src/script/resolveType.ts
- packages/vue/compiler-sfc/register-ts.js
Relate https://github.com/nuxt/nuxt/issues/20936
> fix(compiler-sfc): throw errors for loading TS

- packages/sfc-playground/src/Header.vue
- packages/sfc-playground/src/VersionSelect.vue
> feat(sfc-playground): add style to the active item

- packages/runtime-core/src/scheduler.ts
> fix(runtime-core): Infinite Loop Detection should throw a real error

- packages/dts-test/reactivity.test-d.ts
- packages/reactivity/src/ref.ts
> fix(types): extract properties from extended collections

- .github/contributing.md
`ni` suggests that one can `npm install ni`, but that will get the wrong package.
> chore: correct `@antfu/ni` package name

- packages/dts-test/ref.test-d.ts
- packages/reactivity/src/ref.ts
> type(reactivity): support distribution of union types

- packages/runtime-core/src/vnode.ts
replace -1 to PatchFlags.HOISTED in `cloneVNode`
> chore: replace -1 to PatchFlags.HOISTED

- scripts/release.js
- `pnpm run test` instead of `pnpm test run`
- also need `--no-git-checks` when drying run
- fix spelling
> workflow: fix test command

- packages/reactivity/src/computed.ts
add more info of computed side effect warning
related #10341
> dx(reactivity): add getter into computed side effect warning

- packages/runtime-core/src/apiCreateApp.ts
- packages/runtime-core/src/component.ts
see this: https://github.com/vuejs/core/blob/fe5d919b0f1b235a918a720ef10a9fcbd80ae78e/packages/runtime-core/src/apiCreateApp.ts#L170
> chore(runtime-core): optimize validateComponentName

- packages/runtime-dom/__tests__/patchStyle.spec.ts
- packages/runtime-dom/src/modules/style.ts
> fix: should clear previous css string value

- packages/runtime-dom/__tests__/directives/vModel.spec.ts
- packages/runtime-dom/src/directives/vModel.ts
> fix(runtime-dom): `v-model` string/number coercion for multiselect options

- packages/runtime-core/__tests__/components/BaseTransition.spec.ts
- packages/runtime-core/src/components/BaseTransition.ts
> fix(runtime-core): getKeepAliveChild support slot

- packages/runtime-core/src/components/BaseTransition.ts
close #10771 
see https://github.com/vuejs/core/issues/10771#issuecomment-2071455456
> fix(runtime-core): properly get keepAlive child

- packages/runtime-core/__tests__/components/BaseTransition.spec.ts
- packages/runtime-core/__tests__/hmr.spec.ts
- packages/runtime-core/src/components/BaseTransition.ts
- packages/runtime-core/src/components/KeepAlive.ts
- packages/vue/__tests__/e2e/Transition.spec.ts
revert https://github.com/vuejs/core/pull/10632
re-fix #10620 
close #10827
> fix(Transition): re-fix #10620

- packages/compiler-sfc/__tests__/compileScript/__snapshots__/definePropsDestructure.spec.ts.snap
- packages/compiler-sfc/__tests__/compileScript/definePropsDestructure.spec.ts
- packages/compiler-sfc/src/compileScript.ts
> fix(compile-sfc): register props destructure rest id as setup bindings

- packages/runtime-core/src/components/BaseTransition.ts
- packages/runtime-core/src/vnode.ts
- packages/vue/__tests__/e2e/Transition.spec.ts
> fix(Transition): ensure  enterHooks is fresh after clone

- packages/reactivity/src/reactiveEffect.ts
- packages/runtime-core/src/apiSetupHelpers.ts
- packages/runtime-core/src/compat/global.ts
- packages/runtime-core/src/components/KeepAlive.ts
- packages/runtime-core/src/helpers/useModel.ts
- packages/runtime-core/src/renderer.ts
- packages/runtime-core/src/vnode.ts
- packages/runtime-dom/src/jsx.ts
Changed types, closes stale PR
Closes [https://github.com/vuejs/core/pull/8559](https://github.com/vuejs/core/pull/8559)
> chore: use PropertyKey type

- SECURITY.md
> feat(security): add @RedYetiDev to HoF

- packages/reactivity/__tests__/computed.spec.ts
This is a regression introduced in #11135.
> test(reactivity): add a failed test for computed

- package.json
- packages/compiler-core/package.json
- packages/compiler-sfc/package.json
- packages/sfc-playground/package.json
- packages/vue-compat/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
> workflow: use pnpm catalog for workspace deps

- packages/compiler-ssr/__tests__/ssrTransitionGroup.spec.ts
- packages/compiler-ssr/src/transforms/ssrTransformTransitionGroup.ts
> fix(ssr): don't render v-if comments in TransitionGroup + static tag

- packages/runtime-core/__tests__/components/Suspense.spec.ts
- packages/runtime-core/src/components/KeepAlive.ts
> fix(KeepAlive): avoid cache suspense comment root

- packages/reactivity/__tests__/reactiveArray.spec.ts
- packages/reactivity/src/arrayInstrumentations.ts
> fix(reactivity): ensure extended method arguments are not lost

- packages/reactivity/src/dep.ts
- packages/reactivity/src/effect.ts
- packages/runtime-core/__tests__/apiWatch.spec.ts
- packages/runtime-core/src/apiWatch.ts
> fix(reactivity): sync watch should be executed correctly

- .vscode/extensions.json
- vitest.workspace.ts
It is convenient to quickly run or debug a test case.
> chore: add recommendations extensions vitest

- .github/workflows/close-cant-reproduce-issues.yml
auto close issues that can't reproduce and have not been active for more than 3 days
> feat(workflows): auto close issues with `can't reproduce` label

- packages/runtime-core/src/apiDefineComponent.ts
found this while reviewing https://github.com/vuejs/core/pull/11478/files#r1730482979
> chore: correct the issue number

- packages/runtime-core/src/components/BaseTransition.ts
> fix(Transition): avoid applying transition hooks on comment vnode

- packages-private/dts-test/tsx.test-d.tsx
- packages/runtime-dom/src/jsx.ts
> fix(typo): added name attribute support to details tag

- packages/runtime-core/__tests__/helpers/renderList.spec.ts
- packages/runtime-core/src/helpers/renderList.ts
> fix(runtime-core): handle shallow reactive arrays in renderList correctly

- packages/runtime-core/__tests__/apiAsyncComponent.spec.ts
- packages/runtime-core/src/apiAsyncComponent.ts
> fix(runtime-core): properly update async component nested in KeepAlive

- packages-private/dts-test/appDirective.test-d.ts
- packages/runtime-core/src/apiCreateApp.ts
Update directive generics
https://github.com/vuejs/core/blob/effcccd2586711ae32ebced9f021a58d8a07c09b/packages/runtime-core/src/directives.ts#L105-L112
> chore(types): update directive types

- packages-private/dts-test/setupHelpers.test-d.ts
- packages/runtime-core/src/apiSetupHelpers.ts
> fix(types): defineEmits w/ interface declaration

- packages/compiler-ssr/__tests__/ssrVModel.spec.ts
- packages/compiler-ssr/src/transforms/ssrVModel.ts
> fix(ssr): handle initial selected state for select with v-model + v-for option

- packages/compiler-core/src/transforms/vBind.ts
- packages/compiler-core/src/transforms/vOn.ts
just fixing a few typos in comments
> fix(typos): fix comments referencing transformElement.ts

- package.json
- pnpm-lock.yaml
close #12511
skip upgrade [puppeteer](https://redirect.github.com/puppeteer/puppeteer/tree/main#readme) due to e2e failing
> chore(deps): update test

- packages/vue/__tests__/e2e/e2eUtils.ts
ref https://github.com/puppeteer/puppeteer/pull/13426
> fix(test): use LaunchOptions instead of PuppeteerLaunchOptions

- packages/compiler-sfc/src/compileScript.ts
> refactor(compiler-sfc): remove unused variable

- tsconfig.build.json
tsconfig.build.json   global.d.ts repeat
> chore(tsconfig):  remove repeated global.d.ts

- packages/compiler-sfc/__tests__/parse.spec.ts
- packages/compiler-sfc/src/compileTemplate.ts
ref https://github.com/7rulnik/source-map-js/pull/27/files
> chore(deps): fix MappingItem type

- .github/workflows/ci.yml
> Revert "ci(pkg-pr-new): add 'vapor' branch for pull-request"

- .github/workflows/ci.yml
#12941 should be merged in vapor branch.
> ci(pkg-pr-new): add vapor branch

- README.md
[current image](https://camo.githubusercontent.com/9e9e17d772fbf48c875571563b467eb6e425e6185af4a1536ffbc5a17432c978/68747470733a2f2f6f70656e636f6c6c6563746976652e636f6d2f7675656a732f636f6e7472696275746f72732e7376673f77696474683d383930) is too large to load.
https://github.com/orgs/community/discussions/116471
> fix(readme): update contributors image

- packages/compiler-sfc/__tests__/compileStyle.spec.ts
- packages/compiler-sfc/src/style/pluginScoped.ts
> Revert "fix(compiler-sfc): add scoping tag to trailing universal selector"

- packages/compiler-sfc/src/parse.ts
fix https://github.com/vuejs/ecosystem-ci/actions/runs/16132137101/job/45521395291
> fix(parse): make 'vapor' property optional
