packages/reactivity/__tests__/collections/Map.spec.ts, packages/reactivity/__tests__/collections/Set.spec.ts, packages/reactivity/__tests__/computed.spec.ts, packages/reactivity/__tests__/effect.spec.ts, packages/reactivity/__tests__/reactive.spec.ts, packages/reactivity/__tests__/readonly.spec.ts
- improve typescript in the tests where types can be specified, some tests were ignored based on the nature of the tests. 
The goal is to prevent the usage of as `any` and some direct casts (since typescript sometimes just trusts the user and we cannot be trusted )
=> chore: improve typings in reactivity tests

packages/runtime-core/__tests__/apiApp.spec.ts, packages/runtime-core/__tests__/apiCreateComponent.spec.tsx, packages/runtime-core/__tests__/apiSetupContext.spec.ts, packages/runtime-core/__tests__/rendererSuspense.spec.ts
- improve `runtime-core/createComponent type inference`, removed unnecessary `as any` and added as `() => string[]` as an valid option for the type.
- improve typescript in the testing removed `as any` 
- Test to validate the props passed in the setup are actually with the correct typings
=> test: Runtime-core added test and improving type

packages/compiler-core/__tests__/__snapshots__/compile.spec.ts.snap, packages/compiler-core/__tests__/transforms/__snapshots__/vSlot.spec.ts.snap, packages/compiler-core/src/codegen.ts
Added missing opening bracket in codegen.
[example](https://vue-next-template-explorer.netlify.com/#%3Cdiv%20v-if%3D%22count%20%3C%203%22%3ECount%3A%20%7B%7B%20count%20%7D%7D%3C%2Fdiv%3E)
=> fix(v-if): add simple expression node opening bracket

packages/reactivity/src/computed.ts, packages/reactivity/src/ref.ts
avoid the user to self-implement a ref obj
=> feat: use a ref Symbol to replace Ref._isRef

packages/reactivity/__tests__/readonly.spec.ts, packages/reactivity/src/baseHandlers.ts
``` ts
const qux = Symbol('qux')
const original = {
foo: 1,
bar: {
baz: 2
},
[qux]: 3
}
const observed = readonly(original)
```
If we try to mutate a symbol type key property like `observed[qux]`, will get an error: 
```
TypeError: Cannot convert a Symbol value to a string
```
https://github.com/vuejs/vue-next/blob/31345b5af922c3093e38ab20a90c6dce61560043/packages/reactivity/src/baseHandlers.ts#L106-L118
=> fix(reactivity): explicitly do type conversions in template string

rollup.config.js
=> chore: fix typo in rollup.config.js

packages/vue/src/index.ts
This would allow us to play with templates in runtime esm build.
Otherwise you'd get:
> vue.esm-browser.js:23 Uncaught ReferenceError: Vue is not defined
at eval (eval at compileToFunction (vue.esm-browser.js:6769), <anonymous>:1:14)
at compileToFunction (vue.esm-browser.js:6769)
at finishComponentSetup (vue.esm-browser.js:6644)
at handleSetupResult (vue.esm-browser.js:6629)
at setupStatefulComponent (vue.esm-browser.js:6605)
at mountComponent (vue.esm-browser.js:5454)
at processComponent (vue.esm-browser.js:5408)
at patch (vue.esm-browser.js:5030)
at render (vue.esm-browser.js:5983)
at Object.mount (vue.esm-browser.js:4880)
=> fix: add missing Vue reference to compiled template

packages/runtime-dom/src/modules/events.ts
Minimal test case (haven't found runtime dom tests so didn't commit this):
```javascript
{
setup() {
return {
clicked: false,
}
},
render() {
const clicked = this.clicked ? h('button', { onClick: () => this.clicked = false, }, 'Clicked') : null;
const notClicked = !this.clicked ? h('button', { onClick: () => this.clicked = true, }, 'Not clicked') : null;
return h('div', [
clicked,
notClicked,
]);
}
}
```
After we click the button once the new callback won't be assigned and nothing will happen on click.
=> fix: wrong scope for event value

jest.config.js
`jest --watch` fails with open file limit reached.
=> chore(jest): ignore node_modules from watched files

packages/shared/src/globalsWhitelist.ts
Use the `benchmark` to test.
Mac OS X 10_14_0
Node v10.16.0
```
set#split x 326,627 ops/sec ±1.36% (86 runs sampled)
set#spread x 714,082 ops/sec ±0.46% (91 runs sampled)
Fastest is set#spread
```
Chrome/76.0.3809.132
```
set#split x 287,831 ops/sec ±3.21% (57 runs sampled)
set#spread x 714,024 ops/sec ±1.01% (60 runs sampled)
Fastest is set#spread
```
=> refactor(shared): use spread syntax replace split

packages/reactivity/src/baseHandlers.ts
In non-strict mode, should not trigger effect when deleting property returns false.
In strict mode, deleteing property returning false will arise an error and this is ok.
=> fix(reactivity): not trigger effect when deleting property returns false

packages/runtime-core/src/component.ts
Type on `instance` to make TS check properties' types more properly and simplify type anotations.
=> types(runtime-core): simplify types in createComponentInstance()

packages/reactivity/__tests__/computed.spec.ts, packages/reactivity/src/computed.ts
Reason: TODO comment.
Tested using Jest unit tests.
=> feat(computed): warn if trying to set a readonly computed

packages/runtime-core/__tests__/apiOptions.spec.ts, packages/runtime-core/__tests__/componentProxy.spec.ts, packages/runtime-core/src/apiOptions.ts, packages/runtime-core/src/componentProxy.ts
Added warnings which were marked as TODO (except #81)
- invalid watch handler path
- attempting to mutate readonly computed value
- attempt of mutating public property
- attempt of mutating prop
=> fix: add warnings

packages/runtime-core/__tests__/h.spec.ts, packages/runtime-core/src/h.ts, packages/runtime-core/src/vnode.ts
1. Update `h()`'s usage comments.
In `processElement()`'s implementation  (the same for other non-component processors), it doesn't handle slot children, it means the following code doesn't work as the usage comments in `h()`:
```js
h('div', () => 'text')
```
2. Make `h()` support passing single vnode as children.
In `h()`'s `RawProps` interface, a property `_isVNode: never` exists and I think `h()` should also work for `h('div', h('br'))`.
3. Update tests for `h.ts` to reduce ambiguous.
=> refactor(runtime-core): make h() support single vnode child

packages/compiler-core/src/ast.ts
correct typo 'ListDynamicSlotNode' instead of 'ListDynamicSlotNode'
=> chore: correct typo 'ListDynamicSlotNode' instead of 'ListDynamicSlotNode'

packages/reactivity/__tests__/reactive.spec.ts, packages/reactivity/__tests__/ref.spec.ts, packages/reactivity/src/computed.ts, packages/reactivity/src/reactive.ts, packages/reactivity/src/ref.ts
```typescript
const a = ref(0)
const b = ref(a)
expect(typeof (b.value + 1)).toBe('number') // rather than b.value.value
``` 
This seems more reasonable
=> feat(reactivity): unwrap nested ref

packages/compiler-core/__tests__/transforms/vOnce.spec.ts
The spec for `v-once` introduced in 93c6aa4c9080136c8b2df09adcc64795664aedc1 mentionned `v-cloak` instead of `v-once`
=> fix(compiler): v-once spec

packages/compiler-core/__tests__/__snapshots__/codegen.spec.ts.snap, packages/compiler-core/__tests__/codegen.spec.ts, packages/compiler-core/src/utils.ts
https://github.com/vuejs/vue-next/blob/cbb4b19cfbef2fac9c2c41e412245e69a433885a/packages/compiler-core/src/utils.ts#L240-L245
`toValidAssetId` converts both `bar-baz` and `barbaz` to `_component_barbaz`, this may cause repeated definition of constant `_component_barbaz` in the generated code: 
``` js
const _component_barbaz = resolveComponent("bar-baz")
const _component_barbaz = resolveComponent("barbaz")
```
=> fix(compiler-core): assest id

packages/compiler-core/__tests__/transforms/vOnce.spec.ts
Comment isn't valid for v-once and could cause confusion
=> test(compiler): remove copy-paste comment from v-cloak

rollup.config.js
typo 'isBunlderESMBuild' in rollup.config.js
=> chore: fix typo 'isBundlerESMBuild' instead of 'isBunlderESMBuild'  in rollup.config.js

packages/compiler-core/__tests__/__snapshots__/codegen.spec.ts.snap, packages/compiler-core/__tests__/__snapshots__/compile.spec.ts.snap, packages/compiler-core/__tests__/codegen.spec.ts, packages/compiler-core/__tests__/transforms/__snapshots__/hoistStatic.spec.ts.snap, packages/compiler-core/__tests__/transforms/__snapshots__/vFor.spec.ts.snap, packages/compiler-core/__tests__/transforms/__snapshots__/vIf.spec.ts.snap, packages/compiler-core/__tests__/transforms/hoistStatic.spec.ts, packages/compiler-core/__tests__/transforms/vIf.spec.ts, packages/compiler-core/src/codegen.ts, packages/compiler-core/src/runtimeHelpers.ts, packages/compiler-core/src/transforms/vIf.ts, packages/runtime-core/src/vnode.ts
The original intent of this pull request is to make `v-if` working in templates.
Making so includes: 
* replace rendering no more existing `Empty` VNodeType (removed @ 76a1196) with `Comment` type
* rename `Comment` symbol from `Empty` to `Symbol` for consistency 
* fix passing `0` to `Comment` props in `genComment` to `null` as it is expected by `createVNode` typing
* if we want to hoist a `Comment` node in compiler function mode, we need to add additional helper at the top
This PR will add an additional helper if it is used elsewhere in the template. That means that if the comment node exists in the template but is not hoisted - we will have a useless helper declaration.
IMO single comment node is safe to hoist to file top (that will be addressed in follow-up PR), so right now it seems …
=> fix(compiler): update v-if directive to use Comment instead of Empty

.vscode/settings.json
By default, VSCode uses its own formatting tool to format javascript and typescript files. These changes force VSCode to use Prettier.
This is especially useful for devs who have already selected VSCode's formatting tool as their default tool.
=> Enable prettier for vscode formatting

packages/runtime-core/__tests__/vnode.spec.ts
=> chore: fix typo

packages/runtime-core/__tests__/errorHandling.spec.ts
typo fix : groupCollpased renamed to groupCollapsed
@znck
=> chore: fix typo in runtime-core/__tests__/errorHandling.spec.ts

packages/runtime-core/src/componentRenderUtils.ts
removed unnecessary condition check for prevPros !== null when already prevProps === nextProps and prevProps === null have been checked.
@znck
=> fix(runtime-core): removed unnecessary condition check in componentRenderUtils.ts

packages/reactivity/src/ref.ts
``` js
const a = ref(0) // the type is Ref<number>
const b = reactive(a) // the type is Ref<number>
const c = ref(b) // the type should be Ref<number> instead of Ref<Ref<number>>
```
Because the ref function determines if it is a `Ref`, then return it directly.
=> types(reactivity): improve ref function types

packages/compiler-core/src/utils.ts
At the moment, since `acorn.parse` compatible options are only being accepted. Probably need a custom interface instead.
CC: @znck
=> chore(compiler-core,typings): improve typings

packages/compiler-core/src/transforms/transformElement.ts
When analyzing the patch flag, we assign `key.content` to `name` variable and use it on all if-else branches except the last one.
=> chore: use `name` const consistently

packages/runtime-core/src/suspense.ts
Reverts vuejs/vue-next#245.
The `else` signifies the branch relationship so that we don't need to read the content of the first branch to realize it returns early.
=> Revert "style(runtime-core): remove useless else"

.circleci/config.yml
Should use `--frozen-lockfile` on ci run, prevent lock file update & dependencies version difference.
~https://github.com/vuejs/vue-next/pull/246#discussion_r334264415~
Update: not version problem, but still should frozen
=> ci: use `--frozen-lockfile` when install

rollup.config.js
`ES module` is suggested by rollup, https://rollupjs.org/guide/en/#configuration-files
=> build: switch `rollup.config.js` to `esm` format

packages/runtime-core/src/scheduler.ts
I found all the `trycatch` under packages and found that only this place can be replaced with`callWithErrorHandling`
=> refactor(scheduler): replace try catch with callWithErrorHandling

packages/runtime-core/__tests__/apiOptions.spec.ts, packages/runtime-core/src/apiOptions.ts
1. waring if computed option miss getter 
1. waring when set value but miss setter
=> fix(apiOptions): invalid computed option

packages/reactivity/src/computed.ts, packages/reactivity/src/ref.ts
``` js
const a = ref(0)
const b = computed(() => a.value)
const c = reactive({ b }) // The type of C is unknow, but it should actually be number
```
=> types(ref): improve UnwrapRef types

package.json
single quotes can't work on windows
=> chore: fix yarn lint command failure on windows

packages/compiler-core/__tests__/transforms/transformElement.spec.ts, packages/compiler-core/src/ast.ts, packages/compiler-core/src/parse.ts, packages/compiler-core/src/transforms/transformElement.ts
Add support for using `portal` in template.
```html
<portal target='#portal-target'>
<div>something</div>
</portal>
<main>content</main>
```
Without this feat, we have to:
* use custom render to use, or
* use custom component like `(props, { slots }) => h(Portal, props, slots.default && slots.default())`.
It's worth noting that we cannot use `Portal` directly in `ComponentOptions#components`, because the compiler will treat it as Component and wrap its children as `() => children`. And renderer only handle array children and text children for portal, it means children will be ignored and nothing  rendered in portal target.
=> feat(compiler-core): support portal in template

packages/compiler-core/__tests__/__snapshots__/parse.spec.ts.snap, packages/compiler-core/__tests__/parse.spec.ts, packages/compiler-core/__tests__/transforms/__snapshots__/hoistStatic.spec.ts.snap, packages/compiler-core/__tests__/transforms/hoistStatic.spec.ts, packages/compiler-core/__tests__/utils.spec.ts, packages/compiler-core/src/ast.ts, packages/compiler-core/src/parse.ts, packages/compiler-core/src/transforms/hoistStatic.ts, packages/compiler-core/src/transforms/transformElement.ts, packages/compiler-core/src/transforms/transformExpression.ts, packages/compiler-dom/__tests__/parse.spec.ts
This PR enhances hoisting optimization:
```html
<div><span :foo="0"></span></div>
```
Before:
```JS
import { createVNode, createBlock, openBlock } from "vue"
export default function render() {
const _ctx = this
return (openBlock(), createBlock("div", null, [
createVNode("span", { foo: 0 }, null, 8 /* PROPS */, ["foo"])
]))
}
```
Now: 
```js
import { createVNode, createBlock, openBlock } from "vue"
const _hoisted_1 = createVNode("span", { foo: 0 })
export default function render() {
const _ctx = this
return (openBlock(), createBlock("div", null, [
_hoisted_1
]))
}
```
```html
<div><span>{{ 1 + 2 }}</span></div>
```
Before:
```js
import { toString, createVNode, createBlock, openBlock } from "vue"
export default function render() {
const _ctx = this
return (openBlock(), createBlock("div", …
```
=> feat(compiler-core): more hoisting optimizations

packages/reactivity/src/baseHandlers.ts
define hadKey after `if (isRef(oldValue) && !isRef(value)){ ... }`
=> refactor(reactivity): define hadKey if necessary

packages/runtime-core/__tests__/apiWatch.spec.ts, packages/runtime-core/src/apiWatch.ts
This PR updates `watchApi` array type to allow pass readonly arrays. When we mark array as const, its length and order of contained types is being preserved, so it allows for better type inference without type checking of each array element. It doesn't break current behaviour and it is allowed to pass non-readonly arrays aswell.
No `const` casting.
We have to check if element is a object or number, since it is an array of any length with these two types:
```ts
const count = ref(0);
const state = reactive({ count: 1 })
watch(
[() => state, count], // ({ count: number } | number)[]
([state, count]) => {
if (typeof state === 'object') {
state.count++;
}
if (typeof count === 'number') {
count++;
}
}
);
```
With `const` casting.
More type information is being preserved and array has constant …
=> types(watch): allow to accept readonly arrays

packages/compiler-core/__tests__/transforms/transformExpressions.spec.ts, packages/compiler-core/src/transforms/transformExpression.ts
I noticed that empty interpolation will be compiled into `toString(_ctx.)`.
E.g:
```html
{{}}
```
Generated:
```js
import { toString } from "vue"
export default function render() {
const _ctx = this
return toString(_ctx.)
}
```
=> fix: avoid compiler generating incorrect code

scripts/utils.js
Updated the error message inside the fuzzy-matching util to reflect the style in other files (i.e. scripts/verifyCommit.js)
=> refactor(scripts): updated error-message for not-found fuzzy-matching error

packages/runtime-core/src/component.ts
Another Set can be replaced by the makeMap method.
=> refactor(runtime-core): isBuiltInTag -> use makeMap instead of Set

packages/runtime-core/src/createRenderer.ts
using Array.fill seems a bit faster than looping.
Array.fill is not supported on IE maybe use a polyfill when the time comes?
=> chore(runtime-core): use new Array.fill to populate array

packages/reactivity/src/reactive.ts
use the `jsperf` to test.
OS:`Mac OS X 10.14.6`
Chrome 77.0.3865
> RE:31,462  ±2.59%    35% slower  
> Set:48,254  ±1.52%   fastest
the test link [https://jsperf.com/regandset](https://jsperf.com/regandset)
=> perf(reactivity): optimize the performance of the `canObserve`

rollup.config.js
Full build is missing compiler due to the wrong regexp, testing against `/vue`, when it's actually system-dependent, so it can be both `\vue` or `/vue`. Also removed unnecessary console.log.
=> fix: add missing compiler to the full build on Windows

packages/reactivity/__tests__/ref.spec.ts, packages/reactivity/src/ref.ts
I filter the ref type in the array on type `UnwrapRef`
---
before:
```ts
type ArrayA = Ref<[number, Ref<string>, Ref<Ref<boolean>>, Ref<string>]>
```
will display
```ts
value: (string | number | boolean | Ref<string> | Ref<Ref<boolean>>)[]
```
but now
```ts
value: (string | number | boolean)[]
```
=> type: improve typing

packages/runtime-core/src/apiCreateComponent.ts
As I see, it can't return a function, but types say so. Changed to inference type with `Props`
=> fix(createComponent): fix types

packages/runtime-core/src/componentProps.ts
use `makeMap` instead of `RE` for higher performance.
the online test link [https://jsperf.com/reandobject](https://jsperf.com/reandobject)
=> perf(runtime-core): use `makeMap` instead of `RE`

.vscode/launch.json, scripts/jest.js
Four steps:
1. Open the object file
2. Add it.only for object test (Optional)
3. Make breakpoint
4. Click Start debugging
=> chore: support debug single jest test file in vscode

packages/runtime-core/src/createRenderer.ts
example:
```ts
const el = document.createElement('div')
h(Portal, {
target: el
}, children)
document.body.appendChild(el)
```
This can also help us write tests for portals since we don't have `querySelector` in `runtime-test`. I'd like to do that. Also, we could probably create `querySelector` there. @yyx990803 what do you think?
=> feat(Portal): add ability to use element as target

packages/runtime-core/src/suspense.ts, packages/runtime-core/src/vnode.ts
TS thought `VNodeTypes = string | Component | symbol` due to ternary. Now `VNodeTypes` is correct:
`VNodeTypes = string | Component | typeof Fragment | typeof Portal | typeof Text | typeof Comment | typeof Suspense`
I fixed `SuspenseSymbol` too.
Wrong `Portal` type:
Fixed one:
=> fix(types): fix VNodeTypes unique symbols

packages/runtime-core/src/warning.ts
There was an error code for it, but handling wasn't actually implemented
=> fix(warning): handle errors in warn handler

packages/compiler-core/src/transforms/vBind.ts, packages/compiler-core/src/transforms/vOn.ts
`transformElements.ts` used to be named `element.ts` and the `vBind` and `vOn` transforms still reference the old name in their comments.
=> chore: fix comments referencing renamed file

packages/compiler-core/src/transforms/transformElement.ts
This code:
```vue
<suspense>
<template #default><div>default</div></template>
<template #fallback><div>fallback</div></template>
</suspense>
```
was compiled with errors, now it builds slots OK.
UPD: what's about validation of Suspense slots?
=> fix(transformElement): build suspense slots

packages/reactivity/src/ref.ts
I think it's necessary to warn when pass an unreactive value to toRefs function.
=> chore: add warn of toRefs parameter

packages/reactivity/__tests__/ref.spec.ts, packages/reactivity/src/ref.ts
Check if the types of the return reactive unwraps correctly, since `dummy`s are of type undefined
=> tests: Add check if the child array gets unwrap

packages/reactivity/__tests__/ref.spec.ts, packages/reactivity/src/ref.ts
Allows to keep the tuple types when unwrapping 
https://www.typescriptlang.org/docs/handbook/basic-types.html#tuple
```ts
const tuple = ref<string,number(["hello", 10]).value
tuple[0].concat('world') // valid
tuple[1]++ // valid
tuple[0]++ // invalid because is string
```
=> types(reactivity): add support for tuples

packages/runtime-dom/__tests__/modules/style.spec.ts, packages/runtime-dom/src/modules/style.ts
Support `!important` for patch style, but i have a question about the css varibale feat. can i import `csstype` module to support css variable?
=> feat(runtime-dom): support !important for patchStyle.

packages/runtime-core/__tests__/vnode.spec.ts, packages/template-explorer/src/index.ts
spelling is wrong ('with'=>'width')
=> fix: spelling is wrong ('with'=>'width')

packages/runtime-dom/__tests__/directives/vModel.spec.ts, packages/runtime-dom/src/directives/vModel.ts, packages/runtime-dom/src/patchProp.ts
I noticed that the current `v-model` does not handle `true-value` and `false-value` for checkboxes as we had in Vue 2.x.
This is a rough attempt to implement it, just to start a discussion.
Is this a feature you plan to keep in v3? If so, does this look the right way to handle it?
=> feat(vModel): handle true-value and false-value

packages/runtime-dom/src/modules/props.ts
While implementing #449 I noticed that `patchDOMProp` is currently doing several checks where only one should be enough.
This commit adds some early returns to slightly speed up the overall function in some cases.
=> refactor(runtime-dom): avoid unnecessary checks in patchDOMProp

packages/runtime-core/src/scheduler.ts
The demo is as follows:
```js
const state = reactive({ count: 0 })
let dummy
watch(() => {
dummy = state.count
state.count++
})
```
`flushPostFlushCbs` dost not check maximum recursive updates, the code above will cause a maximum call exceed
=> feat(scheduler): prevent from maximum recursive updates

packages/compiler-dom/__tests__/transforms/vOn.spec.ts, packages/compiler-dom/src/transforms/vOn.ts
Created a function to generate modifiers in just one loop, instead of use filters inside `transformOn`. Also, it was added a test with multiple events with modifiers.
=> perf(compiler-dom): generate modifiers in a function

packages/runtime-dom/src/components/CSSTransition.ts
- It was added a function to remove repeatable code
- Changed use `for` instead of `Math.max` with `map`  for a better performance
- Removed unnecessary type from `toMs` function
=> feat(transition): Added functions to remove repeat and removed unnecessary type

packages/runtime-core/__tests__/helpers/renderList.spec.ts, packages/runtime-core/src/helpers/renderList.ts
When made a `v-for` with an undefined value, without a default value, will throw an error:
<details><summary>Show error</summary>
</details>
=> fix(runtime-core): renderList with default value when source is undefined

packages/runtime-core/package.json
jsx.d.ts has been deleted in this commit 66ecd8b47f7d4ecb70fd380048fb8dc576be33c5.
=> chore: remove jsx.d.ts from package.files

packages/runtime-dom/src/components/Transition.ts
Current build results:
```ts
// runtime-dom/dist/runtime-dom.d.ts
export declare const Transition: FunctionalComponent;
```
Expected results(after fix):
```ts
// runtime-dom/dist/runtime-dom.d.ts
export declare const Transition: FunctionalComponent<TransitionProps>;
```
=> fix(transition): props should be declared by generic

packages/vue/examples/__tests__/todomvc.spec.ts
Simply followed from https://github.com/vuejs/vue/blob/dev/test/e2e/specs/todomvc.js
The only difference is that `.toggle-all` is not visible, so I used `.toggle-all+label` instead.
And I'm not sure if there is more elegant way for the `classList` part.
=> test(e2e): complete e2e test for todomvc

packages/runtime-core/src/vnode.ts
It's safer to use `String()` to convert primitive types.
E.g:
```sh
> Symbol() + ''
Thrown:
TypeError: Cannot convert a Symbol value to a string
> String(Symbol())
'Symbol()'
```
=> fix(core): use String to convert primitive types

packages/vue/examples/composition/grid.html
I was going to submit a PR fixing the grid composition example, but @yyx990803 already did in commit 27a72bd8f150be956a7931b64590cf3867bb4803 .
It introduced a useless import though.
Or we can use `toRefs`and get rid of `state`, what do you prefer?
=> chore: fix grid composition example

packages/vue/examples/composition/markdown.html
To make the behavior of classic/composition examples the same.
=> chore: fix debounce of markdown example

packages/vue/examples/__tests__/e2eUtils.ts, packages/vue/examples/__tests__/tree.spec.ts
Add `children()` to utils, and try to improve the order of util functions slightly.
=> test(e2e): add e2e test for tree example

packages/vue/examples/__tests__/e2eUtils.ts, packages/vue/examples/__tests__/markdown.spec.ts
Add test for markdown example, and use `HTMLInputElement` instead of `any` for the utils that expected to be used on input elements.
=> test(e2e): add e2e test for markdown example

packages/runtime-core/__tests__/apiOptions.spec.ts, packages/runtime-core/__tests__/apiSetupContext.spec.ts, packages/runtime-core/__tests__/apiTemplateRef.spec.ts, packages/runtime-core/__tests__/errorHandling.spec.ts, packages/runtime-core/__tests__/rendererAttrsFallthrough.spec.ts, packages/runtime-core/__tests__/rendererPortal.spec.ts, packages/runtime-core/src/apiDefineComponent.ts, packages/runtime-core/src/apiOptions.ts, packages/runtime-core/src/component.ts, packages/runtime-core/src/h.ts, packages/runtime-core/src/index.ts, packages/runtime-core/src/renderer.ts, packages/runtime-dom/__tests__/directives/vModel.spec.ts, packages/runtime-dom/__tests__/directives/vShow.spec.ts, packages/runtime-dom/__tests__/modules/class.spec.ts, test-dts/defineComponent.test-d.tsx, test-dts/h.test-d.ts, test-dts/tsx.test-d.tsx
I think "define" is more accurate than "create" in this case, since nothing is really being created per se - the function just returns the same object. But it _is_ useful for defining a component, to get better typings.
I think it would also be helpful to reserve the "define" prefix (or some other verb) for any future functions that only exist for typings, to help differentiate them from functions that create a new instance of something.
Thoughts?
=> Rename createComponent to defineComponent

packages/runtime-core/src/apiWatch.ts
It may be useful for user, for example:
```ts
import { watch, StopHandle } from 'vue'
const stoppers = new Set<StopHandle>()
for (let i = 0; i < arr.length; i++) {
stoppers.add(watch(/*...*/))
}
// ...
```
=> types: exports watch api types

packages/reactivity/__tests__/ref.spec.ts
I've extracted repeated code into a function. I believe it makes the code more concise and pleasant to the eye of the reader.  No logic has changed.
=> test(reactivity): extracted repeated code into a function 

packages/reactivity/src/ref.ts
Allow inferring the T value if the condition `isRef` is true
```ts
export function unwrap<T>(o: T | Ref<T>): T {
return isRef(o) ? o.value : o;
}
```
EDIT: because `.value` is `UnwrapRef<T>` and `T` !== `UnwrapRef<T>` you need to cast `o.value as T` to make it work.
but this works perfectly when we have typed argument:  
```ts
interface MyObject {
a: 1,
other: 'string'
}
function returnOther(o: MyObject| Ref<MyObject>): string {
return isRef(o) ? o.value.other : o.other
}
```
=> types: improve isRef typing

packages/runtime-core/src/apiReactivity.ts, packages/runtime-core/src/apiWatch.ts
I think `computed` have same problem, but unless expose a stop api, I don't think there is an easy way to fix it.
=> fix(watch): memory leak

packages/runtime-core/__tests__/apiApp.spec.ts, packages/runtime-core/src/apiCreateApp.ts
In vue 2.x we could pass a class to `Vue.use()` with a static `install` method as it checked for `PluginObject` first.
https://github.com/vuejs/vue/blob/6fe07ebf5ab3fea1860c59fe7cdd2ec1b760f9b0/src/core/global-api/use.js#L15
=> fix(runtime-core): allow classes to be passed as plugins

packages/runtime-core/src/apiOptions.ts
`this` is `undefined` in runtime, `null` may cause misunderstanding, and TS think `this` is `void`.
https://www.typescriptlang.org/play/index.html?ssl=1&ssc=21&pln=1&pc=30#code/GYVwdgxgLglg9mABFApgZygCigCxmgLkXABMVgYwUSBKRAbwF8AoZ1DTGoA
=> types: correct api types

packages/reactivity/src/ref.ts, test-dts/defineComponent.test-d.tsx
We need special string or number types sometime.
Ex. RelativePath, AbsolutePath
```typescript
type AbsolutePath = string & { __brand: unknown }
function readFile (path: AbsolutePath) {
// do some thing
}
function getAbsolutePath (path: string) {
if (path.startWith('file://')) return path as AbsolutePath
}
```
I use it for safe use translation keys,
but code is broken when pass UnwrapRef on vetur template interpolation.
=> types(reactivity): fix corner case on UnwrapRef

packages/compiler-sfc/__tests__/__snapshots__/templateTransformAssetUrl.spec.ts.snap, packages/compiler-sfc/__tests__/__snapshots__/templateTransformSrcset.spec.ts.snap, packages/compiler-sfc/__tests__/compileTemplate.spec.ts, packages/compiler-sfc/__tests__/templateTransformAssetUrl.spec.ts, packages/compiler-sfc/__tests__/templateTransformSrcset.spec.ts, packages/compiler-sfc/src/templateTransformAssetUrl.ts, packages/compiler-sfc/src/templateTransformSrcset.ts, packages/compiler-sfc/src/templateUtils.ts
Issue first reported in `vue-loader`: https://github.com/vuejs/vue-loader/issues/1632
Absolute asset URLs, such as those that start with a forward-slash `/` or are even `http(s)://` URLs are currently interpreted as relative URLs and their path is transformed into an `import` expression by the SFC compiler.
This PR adds a utility method `isRelativeUrl` and uses it to differentiate between URLs that need to be imported and thus transformed, and those that do not.
I can also imagine other names for the helper method, such as `requiresTransform`.
_I only started looking into the source yesterday, so if the solution presented in this PR does not match with how you would solve this, feel free to give pointers and close this._
=> fix(compiler): only transform relative asset URLs

packages/compiler-core/__tests__/transforms/__snapshots__/vIf.spec.ts.snap, packages/compiler-core/__tests__/transforms/vIf.spec.ts, packages/compiler-core/src/utils.ts
Remove the repeat `key` in v-if when you set `key` property directly.
Template:
```html
<div>
<div v-if="xxx" key="2"></div>
</div>
```
Before:
```js
import { openBlock, createVNode, createBlock, createCommentVNode } from "vue"
export function render() {
const _ctx = this
return (openBlock(), createBlock("div", null, [
(openBlock(), (_ctx.xxx)
? createBlock("div", {
// this key is redundant
key: 0,
key: "2"
})
: createCommentVNode("v-if", true))
]))
}
```
After:
```js
import { openBlock, createVNode, createBlock, createCommentVNode } from "vue"
export function render() {
const _ctx = this
return (openBlock(), createBlock("div", null, [
(openBlock(), (_ctx.xxx)
? createBlock("div", { key: "2" })
: createCommentVNode("v-if", true))
]))
}
```
=> feat(compiler-core): remove repeat key

packages/runtime-dom/src/components/Transition.ts
=> fix(transition): correct pass argument into classList api (#638)

packages/runtime-core/__tests__/apiWatch.spec.ts, packages/runtime-core/src/apiWatch.ts
=> fix(runtime-core): trigger watcher with undefined as initial value

packages/compiler-sfc/__tests__/parse.spec.ts, packages/compiler-sfc/src/parse.ts
Empty nodes with `src` attribute was ignored.
```vue
<script src="./com"/>
```
=> fix(sfc): handle empty nodes with src attribute

packages/reactivity/__tests__/reactive.spec.ts, packages/reactivity/src/baseHandlers.ts, packages/reactivity/src/index.ts, packages/reactivity/src/reactive.ts
Fixes #674. Also this PR exposes `shallowReadonly`.
=> feat(@vue/reactivity): add shallowReactive function

packages/reactivity/src/computed.ts
I made `computed` use `track` and `trigger` directly.
Why?
- **Code is shorter and simpler**. `trackChildRun` depended on `activeEffect` and was basically a copy of tracking internals. The new code is straightforward to understand: it simply calls `track` when value is read.
- **Debugging is more clear**. If you look at dependencies during debugging, you'll see the computed, rather than what's cached behind.
- **It's more efficient**. If the getter depends on hundreds of values (typical use case: computed filters or summarizes an array), those 100+ dependencies will be registered on the computed effect, but then transitively copied as dependencies of any effect that reads the computed. With `N` dependencies and `M` readers, before PR we had `N*(M+1)` entries, after PR `N+M`.
Not only does …
=> perf(reactivity): better computed tracking

.github/FUNDING.yml
Leverage the GitHub sponsor button to make people aware about the various ways in which one can support the development.
=> meta: Added GitHub sponsor button config

packages/runtime-core/src/apiReactivity.ts
#689 added `shallowReactive` to fix #674 but it forgot to add it to Vue public API, so it's only available internally.
=> feat(reactive): expose shallowReactive

packages/server-renderer/__tests__/renderToString.spec.ts, packages/server-renderer/package.json, packages/server-renderer/src/renderToString.ts
I've got some questions about this:
1. Should compiler be removable (`server-renderer` built w/o compiler, just as in Vue client renderer)?
2. Should I rewrite existing SSR tests with templates to simplify them (except, of course, `render`/`ssrRender` ones)?
=> feat(server-renderer): compile templates on-the-fly

packages/reactivity/src/effect.ts
fix(effect): optimize effect trigger
=> fix(effect): optimize effect trigger

packages/runtime-core/__tests__/apiWatch.spec.ts, packages/runtime-core/src/apiWatch.ts
Make watchEffect  behavior not affected by deep option when the callback function returns a nested Reactive or Ref.
=> fix(runtime-core): make watchEffect ignore deep option

.github/contributing.md
Formatted the document using prettier and got some whitespace changes. Please let me know if I should avoid that.
=> docs(typo): fixes a small typo and prettifies the document

packages/reactivity/src/collectionHandlers.ts
The next version of Typescript disallows 'this' parameter annotations on accessors, which causes vue-next to fail to compile.
This PR removes the annotation and adds a cast instead.
Fixes #800
=> Remove 'this' annotation from 'get' accessor

packages/template-explorer/package.json, yarn.lock
This removes `estree-walker` as it is no longer needed, and updates `monaco-editor` to the latest release.
=> chore(template-explorer): update dependencies

packages/runtime-core/__tests__/components/Suspense.spec.ts, packages/runtime-core/src/apiCreateApp.ts, packages/runtime-core/src/apiLifecycle.ts, packages/runtime-core/src/errorHandling.ts
The type of error passed to `onErrorCaptured` should be any, because JavaScript can throw anything other than `Error`.
React does not convert the thrown value to `Error`, and passes it to componentDidCatch as it is.
=> fix(runtime-core): Update error type to unknown

packages/runtime-core/src/components/Suspense.ts, packages/runtime-core/src/index.ts, packages/server-renderer/__tests__/ssrSuspense.spec.ts, packages/server-renderer/src/renderToString.ts
=> feat(server-renderer): render suspense

packages/runtime-core/src/componentRenderUtils.ts, packages/runtime-core/src/components/Suspense.ts
This avoids some variables to be typed as any throughout the Suspense code
=> refactor(Suspense): remove unecessary casts

packages/runtime-core/src/vnode.ts
Currently, when a component used is not properly registered, we have a warning and the vnode type is set to a Comment type in DEV mode. But in prod mode, we have no default value, making such an application broken and throw a strange error (`can not read _isSuspense of undefined`).
This commit avoids such an error in prod mode (as it is currently the case in Vue 2.x).
=> fix(runtime-core): always set invalid vnode type

packages/runtime-core/src/apiCreateApp.ts
=> fix(types): app.component should accept defineComponent return type

packages/runtime-core/__tests__/vnode.spec.ts, packages/runtime-core/src/component.ts, packages/runtime-core/src/h.ts, packages/runtime-core/src/vnode.ts
This PR adds a special property `__vueClassComponentOptions` to process class style component. 
If a component passed to `createVNode` is a `function` and having `__vueClassComponentOptions` property, it gets the actual component options from that property. To decouple with vue-class-component as possible, Vue core only knows where the options object of class component is stored. vue-class-component should convert the class to a component options object.
Vue v3 + vue-class-component is already working with this change. The brief idea of the implementation looks like below:
```ts
// Providing Vue base constructor from vue-class-component
export class Vue<Props = unknown> implements ComponentPublicInstance<{}, {}, {}, {}, {}, Props> {
// Define a getter to convert the class to options …
```
=> feat(runtime-core): add special property to get class component options

packages/runtime-core/__tests__/component.spec.ts, packages/runtime-core/src/componentProps.ts
If you define the following property:
`props: { active: Boolean }`
And then use it without a value:
`<Component active>`
Then it is not set to `true` but to `''`.
There are in fact 2 different bugs in source code preventing this from working, check the changes.
There were no tests for props (just a TODO), I added one test for this specific fix.
Fixes #843
=> fix(runtime-core): empty boolean props

packages/runtime-core/__tests__/vnode.spec.ts
should use `for of` to iterate array
=> test(runtime-core): fix test for vnode key

packages/runtime-core/__tests__/h.spec.ts, packages/runtime-core/src/h.ts
In Vue Test Utils (VTU) we provide two core features: “Shallow Mount” and “Stubs”. 
Both `shallowMount` and `stubs` enable the user to short circuit rendering a component tree. You can opt into this feature on any mount command (using stubs) or `shallowMount` command (stubs everything).
This PR adds the necessary functions to enable Vue Test Utils to implement shallowMount and stubs for Vue 3.
**Existing shallowMount functionality in VTU w/ Vue 2**
`shallowMount` is implemented by overwriting `$createElement` in a `beforeCreate` hook and conditionally choosing to apply the real `$createElement`. In VTU we are able to support shallowMounting parent components that use the `h` function directly.
**Implementing shallowMount in Vue 3**
Identical implementation using `beforeCreate` hook is not …
=> feat: add hook to transform h's arguments

packages/runtime-dom/src/components/TransitionGroup.ts
=> fix(TransitionGroup): ignore comment node when warn (fix#869)

package.json
fix: #827 
When using yarn to install dependencies, the node version that does not match the requirements will be interrupt.
=> fix: Check the node version

packages/vue/README.md
Fixes typos introduced by 9fc8ade884ca0331eaa5387a77c769fb1c237a9c
[ci skip]
=> chore: readme typos

packages/runtime-core/__tests__/apiAsyncComponent.spec.ts, packages/runtime-core/__tests__/components/Suspense.spec.ts, packages/runtime-core/__tests__/hydration.spec.ts, packages/runtime-core/src/apiAsyncComponent.ts, packages/runtime-core/src/index.ts
As we declare a component with `defineComponent`, it feels less surprising to declare an async component with `defineAsyncComponent`.
=> chore(runtime-core): rename createAsyncComponent as defineAsyncComponent

.ls-lint.yml, packages/runtime-core/src/index.ts
These types were not being exported but they are necessary for applications to bundle: https://circleci.com/gh/vuejs/vue-router-next/531
There are more types that are marked as _forgotten export_ by API Extractor but I changed only those
I also change ls-lint because it was checking files inside `dist` folders
=> fix(types): export missing types from runtime-core

packages/runtime-core/__tests__/apiInject.spec.ts, packages/runtime-core/src/apiInject.ts
Check the arguments length instead of the argument being `undefined` to issue the warning
Close #892
=> fix(inject): allow default value to be `undefined`

packages/compiler-dom/__tests__/transforms/warnTransitionChildren.spec.ts, packages/compiler-dom/__tests__/warnings.spec.ts, packages/compiler-dom/src/transforms/warnTransitionChildren.ts
I'm not sure this is the best way to test it. I think in Vue 2 this was a runtime warning instead of a compiler one
=> fix(transition): warn only when there is more than one rendered child

packages/compiler-core/src/index.ts
`transformElement` is not currently exported, but it's required for our custom renderer's tests similar to what's used in `compiler-dom` transform tests:
https://github.com/vuejs/vue-next/blob/b7b0d16b1cc076a80ab51388f8f861d14e6fe8a0/packages/compiler-dom/__tests__/transforms/transformStyle.spec.ts#L10
If it makes sense, I can update [all the imports](https://github.com/vuejs/vue-next/search?p=3&q=transformElement&unscoped_q=transformElement) to use the new export.
=> fix(types): export missing type from compiler-core

packages/runtime-core/src/component.ts
The check for `config.performance` is already done inside `endMeasure` and is not done anywhere else `endMeasure` is called.
=> refactor(runtime-core): remove unnecessary tracing check

packages/runtime-core/src/componentProps.ts, test-dts/defineComponent.test-d.tsx
Allows retrieve the correct function type
```ts
{
e: Function,
// return type
ee: Function as PropType<() => string>,
// arguments + object return
ff: Function as PropType<(a: number, b: string) => { a: boolean }>,
// required + object return
eee: {
type: Function as PropType<() => { a: string }>,
required: true
},
// required + arguments + object return
fff: {
type: Function as PropType<(a: number, b: string) => { a: boolean }>,
required: true
}
}
```
=> fix(types): allow use PropType with Function

packages/runtime-core/src/index.ts
For writing custom renderers it would be nice to be able to follow a similar structure as found in the base renderer:
https://github.com/vuejs/vue-next/blob/5c33776e67a5136aca5100f8ad1b0c968527f8de/packages/runtime-core/src/renderer.ts#L1095-L1097
This would require having the `effect` function available to use. We can't import it from the reactivity package because of the following snippet from the readme:
> This package is inlined into Global & Browser ESM builds of user-facing renderers (e.g. @vue/runtime-dom), but also published as a package that can be used standalone. The standalone build should not be used alongside a pre-bundled build of a user-facing renderer, as they will have different internal storage for reactivity connections. A user-facing renderer should re-export all APIs …
=> feat(effect): add effect to public api

packages/compiler-sfc/src/parse.ts
Template blocks are never padded hence they need offset for generating correct source map.
=> fix(compiler-sfc): always use offset for template block sourcemaps

packages/runtime-core/src/helpers/renderList.ts
Similar to `h()`, `renderList()` would be used to provide type check and completion in IDE toolings. For proper type inference, correct types for `renderList()` are required.
=> types(runtime-core): Adds type signature for renderList helper

CHANGELOG.md
white-space in changelog is not rendered
=> chore: show non-breaking space in changelog

packages/reactivity/src/ref.ts, test-dts/ref.test-d.ts
=> fix(types): UnwrapRef should bail on DOM element types (fix #951).

packages/runtime-dom/__tests__/patchProps.spec.ts, packages/runtime-dom/src/patchProp.ts
=> fix(runtime-dom): should patch svg  innerHtml

packages/reactivity/__tests__/ref.spec.ts, test-dts/ref.test-d.ts
This add tests for symbols and dts tests.
This is a follow up to the https://github.com/vuejs/vue-next/pull/579
Question, when using a custom symbol it seems you can't do `toBe`
```ts
expect(objRef.value[customSymbol]).toBe(obj[customSymbol]) // fails
expect(objRef.value[customSymbol]).toStrictEqual(obj[customSymbol])
```
Do we change the object to reactive for symbol properties?
=> test(reactivity): add tests for object with symbols

package.json, packages/compiler-sfc/src/templateTransformAssetUrl.ts, packages/reactivity/src/ref.ts, packages/template-explorer/src/index.ts, yarn.lock
`Symbol.observable` is brought by `@types/node@12` and is not a "well-known" typescript symbol https://www.typescriptlang.org/docs/handbook/symbols.html that can be find in lib.es20xx like the others. It has been removed in `@types/node@v13`.
It means that an application using vue@3.0.0-alpha.13 does not compile unless it explicitely adds `@types/node@v12` as a dependency and `node` in its own tsconfig types.
Otherwise here is the compilation error:
```
ERROR in /Users/ced-pro/Code/ninjasquad/.../node_modules/@vue/reactivity/dist/reactivity.d.ts(134,13):
134:13 Property 'observable' does not exist on type 'SymbolConstructor'.
132 |     [Symbol.observable]: infer V;
133 | } ? {
> 134 |     [Symbol.observable]: V;
|             ^
135 | } : {}) & (T extends {
136 |     [Symbol.replace]: …
```
=> fix(reactivity): remove Symbol.observable

README.md
Hi! 
We actually release the first public alpha for Vue Test Utils: 
https://www.npmjs.com/package/@vue/test-utils/v/2.0.0-alpha.1
https://github.com/vuejs/vue-test-utils-next/releases/tag/2.0.0-alpha.1
stay safe! 👋
=> Mark VTU as alpha

packages/runtime-core/src/index.ts
In an attempt to add some typesafety to `@vue/test-utils` I ended up with a PR that can check that `mount(defineComponent({ props: { a: string } }), { props: { a: 2 } })` does not compile.
To achieve the same without `defineComponent`, it looks like we'll need `ExtractPropTypes` to be public. See https://github.com/vuejs/vue-test-utils-next/pull/74 for more context.
Would it be possible?
=> chore: expose ExtractPropTypes

packages/runtime-core/src/apiWatch.ts, packages/runtime-core/src/componentOptions.ts, packages/runtime-core/src/componentProxy.ts, packages/runtime-core/src/index.ts, test-dts/componentCustomProperties.test-d.ts
Export an interface to allow typing for TS and JS users (free autocompletion) to custom added properties.
Here is an example of adding a property `$router` to every component instance:
```ts
import { createApp } from 'vue'
import { Router, createRouter } from 'vue-router'
declare module '@vue/runtime-core' {
interface ComponentCustomProperties {
$router: Router
}
}
// effectively adding the router to every component instance
const app = createApp({})
const router = createRouter()
app.config.globalProperties.$router = router
const vm = app.mount('#app')
// we can access the router from the instance
vm.$router.push('/')
```
=> feat(runtime-core): add ComponentCustomProperties interface

packages/runtime-core/__tests__/apiWatch.spec.ts, packages/runtime-core/src/apiWatch.ts
if you pass `{deep:true}` and you are watching a primitive ref it will always be `undefined`
```ts
const count = ref(0)
let dummy
watch(
count,
(c, prevCount) => {
dummy = [c, prevCount]
},
{
deep: true
}
)
```
=> fix(watch): allow to pass {deep: true} on ref primitives

packages/runtime-core/src/componentEmits.ts, packages/runtime-dom/src/modules/attrs.ts, packages/runtime-dom/src/patchProp.ts, packages/shared/src/normalizeProp.ts
In a few places, `someString.indexOf(somePrefix) === 0` is used to check if a string starts with some prefix. Using `startsWith` instead should enable the check to short-circuit in the negative case (indexOf will scan the whole string in the negative case); it also has clearer intent. In one case, checking if something was a v-model listener, the logic was checking existence of a string, but it should always be a prefix, so startsWith seems to make more sense.
=> perf(core): use startsWith instead of indexOf 0

packages/reactivity/src/ref.ts, test-dts/ref.test-d.ts
if you do `ref(false)` the type generated is `Ref<true>|Ref<false>`
This fixes that
```ts
const foo = ref(false);
if (!foo.value) {
foo.value = true; // error here
}
```
=> types: fix ref(false) type to Ref<boolean>

packages/reactivity/src/effect.ts
`activeEffect` don't need to be exported
=> chore: remove unnecessary export

packages/reactivity/src/index.ts, packages/reactivity/src/ref.ts, packages/runtime-core/src/index.ts
expose return type for `toRefs`
Some Typescript users might have some trouble when using `reactive` and with `toRefs`
```ts
interface Foo {
a: number,
b: number
}
interface FooReturn {
foo: ToRefs<Foo> // naming might be confusing, suggestions welcome
}
function useFoo(){
const state = reactive({
a: { a:1, b:2}
})
return {
foo: toRefs(state.a)
}
}
```
=> types(reactivity): creating type for return toRefs and export return type

packages/runtime-core/__tests__/components/Suspense.spec.ts, packages/runtime-core/src/apiDefineComponent.ts, packages/runtime-core/src/h.ts, test-dts/h.test-d.ts
Fixes #993
```ts
const Comp = defineComponent({
setup() {
return {};
}
});
export const someComponents: Component[] = [Comp]; //error
```
=> types: making defineComponent return a valid Component type fix #993

packages/runtime-core/__tests__/components/KeepAlive.spec.ts, packages/runtime-core/src/renderer.ts
=> fix(keepAlive): do not invoke onVnodeBeforeUnmount if is KeepAlive component

packages/runtime-core/src/index.ts
In some cases (such as the Vugel renderer), action needs to be taken immediately after a patch. nextTick could be used. But the danger is that application callbacks could be scheduled before it. queuePostFlushCb allows us to implement a more 'integrated' and less error-prone mechanism.
**Our use case**
In the case of Vugel, we use Vue3 with the custom renderer api to render on tree2d nodes. Three2d uses a render tree with children stored in arrays rather than linked list (HTML DOM). This causes O(n*n) complexity when adding new elements to a v-for. It leads to bad performance in some cases, when using a lot of items in a v-for. This is caused by the facts that vue iterates all items from the start, and when inserting new items one by one at the start of the array it will have to be copied …
=> feat(runtime-core): export queuePostFlushCb

packages/runtime-core/__tests__/components/Suspense.spec.ts, packages/runtime-core/src/renderer.ts
=> fix(runtime-core): should call Suspense fallback unmount hook

packages/runtime-core/src/apiCreateApp.ts
Since `key` can be a `Symbol`, it needs to be cast, otherwise it throws and the symbol is not overridden
=> fix(warn): cast symbols to strings

packages/reactivity/__tests__/reactive.spec.ts, packages/reactivity/src/reactive.ts
=> test: reactive proto

packages/runtime-dom/src/components/TransitionGroup.ts
=> fix(transitionGroup): inner children should skip comment node

packages/runtime-core/src/componentOptions.ts
`LegacyOptions` isn't used by other modules, so we can remove `export`
=> chore: LegacyOptions doesn't need to be exported

CHANGELOG.md
Leading slash was breaking a link in the "Bug fixes" section of "3.0.0-beta.10 (2020-05-07)"
=> chore: fix broken link in CHANGELOG.md

packages/runtime-dom/__tests__/directives/vOn.spec.ts, packages/runtime-dom/src/directives/vOn.ts
Current Vue 3 behaviour: https://codepen.io/nekosaur/pen/dyYqgyZ
Regular event handler sends all arguments, but with modifier it only sends first one (event). This seems inconsistent.
Scenario is if one would like to enable the use of modifiers and short template syntax while sending custom event values.
See https://github.com/vuejs/vue/issues/10867, https://github.com/vuejs/vue/pull/10958, https://github.com/vuetifyjs/vuetify/issues/9720
=> fix(runtime-dom): event handlers with modifiers should get all event arguments

packages/runtime-core/__tests__/apiWatch.spec.ts, packages/runtime-core/src/apiWatch.ts
`watch([1], () => {})` won't cause type error, even before my changes, I don't know how to fix it.
=> feat(watch): support directly watching reactive object in multiple sources with deep default

packages/reactivity/__tests__/reactive.spec.ts, packages/reactivity/src/collectionHandlers.ts, packages/reactivity/src/reactive.ts
fixes #1202 
Adds `shallowCollectionHandlers`
=> fix: shallowReactive for collections

packages/runtime-core/src/componentProps.ts
Fix #1294
see #1294 for the reasoning
=> fix(runtime-core): use array destructuring instead of object for edge compat (Fix #1294)

packages/compiler-dom/__tests__/transforms/stringifyStatic.spec.ts, packages/compiler-dom/src/transforms/stringifyStatic.ts
**Version**
3.0.0-beta.14
**Reproduction link**
[vue-next-template-explorer](https://vue-next-template-explorer.netlify.app/#%7B%22src%22%3A%22%3Cdiv%3E%5Cn%20%20%3Cdiv%3E%5Cn%20%20%20%20%5Cn%20%20%20%20%3Cdiv%20%2F%3E%5Cn%20%20%20%20%3Cdiv%20%2F%3E%5Cn%20%20%20%20%3Cdiv%20%2F%3E%5Cn%20%20%20%20%3Cdiv%20%2F%3E%5Cn%20%20%20%20%3Cdiv%20%2F%3E%5Cn%20%20%20%20%3Cdiv%20%2F%3E%5Cn%20%20%20%20%3Cdiv%20%2F%3E%5Cn%20%20%20%20%3Cdiv%20%2F%3E%5Cn%20%20%20%20%3Cdiv%20%2F%3E%5Cn%20%20%20%20%3Cdiv%20%2F%3E%5Cn%20%20%20%20%3Cdiv%20%2F%3E%5Cn%20%20%20%20%3Cdiv%20%2F%3E%5Cn%20%20%20%20%3Cdiv%20%2F%3E%5Cn%20%20%20%20%3Cdiv%20%2F%3E%5Cn%20%20%20%20%3Cdiv%20%2F%3E%5Cn%20%20%20%20%3Cdiv%20%2F%3E%5Cn%20%20%20%20%3Cdiv%20%2F%3E%5Cn%20%20%20%20%3Cdiv%20%2F%3E%5Cn%20%20%20%20%3Cdiv%20%2F%3E%5Cn%20%20%20%20%3Cinput …
=> Incorrectly determine node stringifiable when unstringifiable child exists after threshold is met(fix #1128)

packages/reactivity/__tests__/reactive.spec.ts, packages/reactivity/__tests__/shallowReactive.spec.ts, packages/reactivity/src/collectionHandlers.ts
Fixes #1210 
`shallowInstrumentations` were set to `readonly` by mistake
Moved tests to a separate file to be easier to manage the `shallowReactive` tests
=> fix(reactivity): shallowReactive collection to not-readonly

packages/compiler-core/__tests__/transforms/__snapshots__/vModel.spec.ts.snap, packages/compiler-core/__tests__/transforms/vModel.spec.ts, packages/compiler-core/__tests__/transforms/vOn.spec.ts, packages/compiler-core/src/transforms/vModel.ts, packages/compiler-core/src/utils.ts
fixes https://github.com/vuejs/vue-next/issues/1218
=> feat: allow multiline expression on v_model and v_on

packages/runtime-core/src/directives.ts
=> types(runtime-core): support type with directive value

packages/runtime-dom/__tests__/patchStyle.spec.ts, packages/runtime-dom/src/modules/style.ts
=> perf: should patch string style when value is changed

packages/runtime-core/src/componentProps.ts
fixes the typo `readonly proptotype: Function`
=> types(props): fix typo on prototype

packages/runtime-core/__tests__/componentProps.spec.ts, packages/runtime-core/src/componentProps.ts
fix https://github.com/vuejs/vue-next/issues/1348
=> fix: function type props not correct

packages/reactivity/__tests__/reactive.spec.ts, packages/reactivity/src/baseHandlers.ts
I don't know how to deal with types, I have to use `@ts-ignore` in test.
Or should this use case not be allowed?
=> fix(reactivity): allow setting property from a ref to another ref

packages/runtime-core/__tests__/hydration.spec.ts, packages/runtime-core/src/components/Teleport.ts
=> fix: shouldn't throw error on hydration `Teleport` mismatch

packages/vue/examples/__tests__/e2eUtils.ts, packages/vue/examples/__tests__/grid.spec.ts, packages/vue/examples/__tests__/svg.spec.ts
**Currently the failing test is expected**
I found a bug that is probably caused by `v-model`. I tried but I could't fix it so I add test to cover this issue (the new `assertStats` part). Therefore the test of this PR should fail now. I can rebase and push after it's fixed.
To reproduce the issue:
1. Open the svg example
2. Remove the first range control A
3. Drag other ranges, they are now broken
For now it can be fixed by adding `key`, but in Vue 2.0 `key` is not required. (If it is required in Vue 3.0, I can help with fixing the example in this PR)
I also add the `assertLabels` which can catch the issue of #552 for regression.
*The same SVG example in Vue 2.0 passes all the newly added tests.*
Changes:
- Rename `setValue` to more accurate `typeValue`
- Add `setValue` which will set …
=> test(e2e): enhance and fix test of svg example

.vscode/launch.json, scripts/jest.js
ref #360 
I can't match file in original way, and https://github.com/microsoft/vscode-recipes/pull/108 added a workaround configuration for windows users. [doc here](https://github.com/microsoft/vscode-recipes/blob/master/debugging-jest-tests/README.md#configure-packagejson-file-for-your-test-framework). I work fine in the config, but i didn't test other systems.
=> chore: debug jest in vscode

packages/runtime-core/__tests__/h.spec.ts, packages/runtime-core/src/h.ts, test-dts/h.test-d.ts
`RawSlots` is supported as a third argument in most signatures except when the first one is a `string`. I _think_ this is a valid use-case, as @dobromir-hristov used it for stubs in VTU next.
We are currently forced to cast the parameter as `any` to make TS happy in VTU. This commit should fix that.
=> fix(types): add RawSlots in h signature

packages/runtime-core/__tests__/apiTemplateRef.spec.ts
Add test for multi root components: 
```vue
<template>
<div ref="refKey1"/>
<div ref="refKey2"/>
<div ref="refKey3"/>
<template>
```
=> test(runtime-core): test multi-root ref assignment

packages/runtime-core/__tests__/helpers/toHandlers.spec.ts, packages/runtime-core/src/helpers/toHandlers.ts
`emit('eventName')` will call a prop with the name `onEventName`.
`@eventName="eventHandler"` will be compiled into the prop `onEventName: event => _ctx.eventHandler(event)`.
Both of those are completely fine, and event handlers are called as expected.
If you opt to use `v-on` with an object, it will probably not work as expected.
`v-on="{ eventName: eventHandler }"` is compiled to prop `{ oneventName: eventhandler }`, and will thus never be called by `emit('eventName')`.
Currently you'll have to capitalize the event name, `v-on"{ EventName: eventHandler }"`.
This is clunky, and it breaks with the common pattern that event names are in camelCase.
This PR fixes this by capitalizing the object keys before they're prepended with `'on'`.
=> fix(runtime-core): properly change v-on object keys

packages/runtime-core/src/index.ts
The newly introduced `ComponentOptionsMixin` was not re-exported.
This is needed for VTU to support Vue `3.0.0-beta.15`.
=> fix(types): export ComponentOptionsMixin

packages/compiler-core/__tests__/transforms/__snapshots__/hoistStatic.spec.ts.snap, packages/compiler-core/__tests__/transforms/vOn.spec.ts, packages/compiler-core/src/transforms/vOn.ts
When the compiler encounters a template such as this
```html
<AComponent @an-event="anEventHandler" />
```
the function passed as the prop `onAnEvent` to `<AComponent>` is generated like this
```js
$event => _ctx.anEventHandler($event)
```
This becomes a problem when the event is emitted with more than one argument. Only the first argument, `$event`, is passed to the event handler.
This is especially evident when wanting to use the transition enter/leave's `resolve` function.
```html
<script>
export default {
setup: () => ({
onEnter (el, resolve) {
...
resolve() // Uncaught TypeError: resolve is not a function
}
})
}
</script>
<template>
<transition @enter="onEnter">
<... v-if="..." />
</transition>
</template>
```
This PR fixes this by replacing `$event` with `($event, ...args)` in code …
=> fix(compiler-core): keep event handlers noninitial arguments

packages/reactivity/src/ref.ts
Because interface `ComputedRef` extends `WritableComputedRef` and interface `WritableComputedRef` extends `Ref`, So it seems that the first judgment is not needed.
=> refactor(types): simplified UnwrapRef

packages/compiler-core/__tests__/__snapshots__/codegen.spec.ts.snap, packages/compiler-core/__tests__/codegen.spec.ts, packages/compiler-core/__tests__/testUtils.ts, packages/compiler-core/__tests__/transforms/__snapshots__/vFor.spec.ts.snap, packages/compiler-core/__tests__/transforms/vFor.spec.ts, packages/compiler-core/src/ast.ts, packages/compiler-core/src/codegen.ts, packages/compiler-core/src/transforms/transformElement.ts, packages/compiler-core/src/transforms/vFor.ts
These are stable fragment?
```html
<p v-for="n in 10"></p>
<p v-for="s in 'abc'"></p>
```
=> feat(compiler-core): treat v-for with constant exp as a stable fragment

packages/compiler-sfc/__tests__/__snapshots__/templateTransformAssetUrl.spec.ts.snap, packages/compiler-sfc/__tests__/__snapshots__/templateTransformSrcset.spec.ts.snap, packages/compiler-sfc/__tests__/templateTransformAssetUrl.spec.ts, packages/compiler-sfc/__tests__/templateTransformSrcset.spec.ts, packages/compiler-sfc/__tests__/templateUtils.spec.ts, packages/compiler-sfc/src/templateTransformAssetUrl.ts, packages/compiler-sfc/src/templateTransformSrcset.ts, packages/compiler-sfc/src/templateUtils.ts
fix #https://github.com/vitejs/vite/issues/430
=> fix(compiler-sfc): should ignore inline data url

packages/runtime-core/__tests__/componentProps.spec.ts, packages/runtime-core/src/componentProps.ts
=> fix(runtime-core): should remove the props with camelCase key

packages/reactivity/src/baseHandlers.ts, packages/reactivity/src/collectionHandlers.ts, packages/reactivity/src/reactive.ts, packages/runtime-core/src/componentProxy.ts
rename key to follow the naming conventions of enums
=> chore(reactivity): use key of ReactiveFlags instead of `__v_properties`

packages/runtime-core/src/components/BaseTransition.ts, packages/runtime-core/src/index.ts, packages/runtime-dom/src/components/TransitionGroup.ts
=> fix(BaseTransition): collect correct children with `Transition` slot

packages/runtime-dom/src/nodeOps.ts
if anchor is none, insertBefore and appendChild has same effect
=> chore(runtime-dom): insertBefore anchor  null equals appendChild

packages/compiler-core/src/parse.ts
=> fix(compiler-core): add \r to accepted chars after end tag name (fix #1476)

packages/runtime-dom/__tests__/directives/vModel.spec.ts, packages/runtime-dom/src/directives/vModel.ts
=> fix(v-model): keep the same behavior as `v-model` with `undefined`value with 2.x

packages/runtime-dom/types/jsx.d.ts, test-dts/functionalComponent.test-d.tsx
`JSX.IntrinsicAttributes` represents common attributes of components.
Props of functional components are determined by type of first argument and this type.
=> fix(runtime-dom): add JSX.IntrinsicAttributes definition(#1516)

packages/compiler-core/__tests__/transforms/transformExpressions.spec.ts, packages/compiler-core/src/codegen.ts, packages/compiler-core/src/options.ts, packages/compiler-core/src/transforms/hoistStatic.ts, packages/compiler-core/src/transforms/transformElement.ts, packages/compiler-sfc/__tests__/templateTransformSrcset.spec.ts, packages/compiler-ssr/src/transforms/ssrTransformComponent.ts, packages/compiler-ssr/src/transforms/ssrTransformElement.ts, packages/reactivity/src/ref.ts, packages/runtime-core/__tests__/componentEmits.spec.ts, packages/runtime-core/__tests__/helpers/scopeId.spec.ts, packages/runtime-core/__tests__/vnode.spec.ts, packages/runtime-core/src/apiDefineComponent.ts, packages/runtime-core/src/componentProxy.ts, packages/runtime-core/src/componentSlots.ts, packages/runtime-core/src/hydration.ts, packages/runtime-dom/__tests__/patchProps.spec.ts, packages/runtime-dom/src/modules/props.ts, packages/vue/__tests__/index.spec.ts
This PR aims to fix a number of smaller typos in comments, JSDoc and an internal variable name, as well as smaller fixes in unit test expectation descriptions.
=> chore: typo fixes

packages/runtime-core/src/index.ts
Make `import { WritableComputedRef } from 'vue'` work
=> feat(runtime-core): expose WritableComputedRef

packages/runtime-core/src/component.ts, packages/runtime-core/src/componentEmits.ts, packages/runtime-core/src/h.ts, test-dts/defineComponent.test-d.tsx
relates to https://github.com/vuejs/vue-test-utils-next/issues/144
When using `ComponentPublicApi` the `emit` type defaults to an empty object, making the `$emit` to be **unknown** type instead of the default emit function `(event: string, ...args: any[]) => void`
=> types(runtime-core): provide valid type for default `$emit` 

packages/runtime-core/src/component.ts, test-dts/defineComponent.test-d.tsx
`vue-class-component` is broken https://github.com/vuejs/vue-next/pull/1498#issuecomment-658550984
The issue is caused by the default value of `SetupContext<ObjectEmitsOptions>` not being the same as the default on the ComponentOptions setup `SetupContext<EmitsOptions>`
=> types(runtime-core): default `SetupContext` generic argument to `EmitsOptions`

packages/compiler-core/__tests__/transforms/__snapshots__/vIf.spec.ts.snap, packages/compiler-core/__tests__/transforms/vIf.spec.ts, packages/compiler-core/src/transforms/vIf.ts
=> fix(compiler-core): generate different keys for multiple v-if

packages/runtime-core/src/renderer.ts
=> fix(runtime-core): call transition enter without inside suspense

packages/shared/src/domTagConfig.ts
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/element
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/shadow
=> chore(share):element tag and shadow tag is deprecated

packages/reactivity/src/effect.ts
The argument `fn` of `createReactiveEffect`, which passed by `effect`, will never accept arguments.
So, the arguments of the returned function is meaningless, since the arguments are only used by fn.
=> fix(reactive): reactiveEffect should accept no arguments

packages/compiler-core/src/options.ts, packages/compiler-sfc/src/compileScript.ts, packages/runtime-core/src/helpers/renderSlot.ts, packages/shared/src/slotFlags.ts
The markdown parser of VSCode explicitly disables html tags.
Before
After
=> chore: better comment hovers preview

packages/shared/src/domTagConfig.ts
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menuitem
=> chore(shared):menuitem tag has been deprecated

packages/compiler-dom/src/decodeHtml.ts, packages/runtime-core/src/component.ts, packages/runtime-core/src/componentProps.ts, packages/runtime-core/src/devtools.ts, packages/runtime-core/src/vnode.ts
Before:
`{ [key: string]: string }`
After:
`Record<string, string>`
Exactly the same for TypeScript, but more readable for human
=> chore: convert to records

packages/compiler-core/__tests__/transforms/vOn.spec.ts, packages/compiler-core/src/transforms/vOn.ts
Fix: #1639  The event handler of Multi-line writing should be processed correctly.
=> fix(compiler-core): event handler of Multi-line writing should be processed correctly

packages/runtime-core/__tests__/apiWatch.spec.ts, packages/runtime-core/src/apiWatch.ts
Fix #1636
This https://github.com/vuejs/vue-next/commit/341b30c961aa065fc59f0c2b592a11229cb6bd14 broke the `flush:sync` 
the job is not being called anymore, the `invoke` was calling the `getter` (aka the `cb`)
=> fix(apiWatch): callback not called when using `flush:sync`

packages/runtime-core/src/components/KeepAlive.ts, packages/vue/__tests__/index.spec.ts
=> fix(keep-alive): fix #1621 and add test.

packages/runtime-core/__tests__/apiWatch.spec.ts, packages/runtime-core/src/apiWatch.ts
fixes #1655
if check if array first, the array could be a reactive array.
=> fix: watch reactive array callback with array of undefined

packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap, packages/compiler-sfc/src/compileScript.ts, packages/compiler-sfc/src/genCssVars.ts
fix #https://github.com/vitejs/vite/issues/578
=> fix(compiler-sfc): use correct importer with `useCssVars`

packages/reactivity/__tests__/computed.spec.ts, packages/reactivity/src/computed.ts
if `computed` has no `setter` `isReadonly` returns `true`
```ts
const x = computed(() => 1)
expect(isReadonly(x)).toBe(true)
expect(isReadonly(x.value)).toBe(false)
```
=> feat(computed): add readonly flag if no setter is provided

packages/compiler-core/src/codegen.ts
I haven't added to  `onContextCreated` to `CodegenOptions` to avoid circular dependency as it is defined in `options.ts` and `CodegenContext` is  in `codegen.ts`.
=> feat(compiler-core): add onContextCreated option to CodegenOptions

packages/compiler-core/__tests__/transforms/vBind.spec.ts, packages/compiler-core/src/transforms/vBind.ts
Prevent ` { id:  }` experssion generate.
` <div v-bind:id=""></div>`
` return (_openBlock(), _createBlock("div", { id:  }, null, 8 /* PROPS */, ["id"]))`
=> fix(compiler-core): prevent generate empty key value for vBind

packages/runtime-dom/__tests__/helpers/useCssVars.spec.ts, packages/runtime-dom/src/helpers/useCssVars.ts
=> fix(cssVars): css vars use on suspense root

packages/reactivity/src/index.ts, packages/reactivity/src/ref.ts, packages/runtime-core/src/component.ts, packages/runtime-core/src/componentProxy.ts, packages/runtime-core/src/index.ts, test-dts/defineComponent.test-d.tsx
Template auto ref unwrapping for `setup()` return object is now applied only to the root level refs.
This change aims to ensure that non-ref values referenced in templates retain the same identity with the value declared inside `setup()`  regardless of whether it's wrapped with `reactive` or `readonly`.
Currently, the object returned from `setup()` is exposed to the template render context as a `reactive` proxy. This means all properties accessed from the template, even nested ones, will be reactive proxies as well. This has led to a edge cases that can be confusing:
```html
<div v-for="item in list">{{ isInList(item) }}</div>
```
```js
setup() {
const list = [
{ foo: 1 },
{ bar: 2 }
]
function isInList(item) {
// item here is a proxy of the original!
return list.includes(item)
}
return { …
```
=> feat(reactivity): `proxyRefs` method and `ShallowUnwrapRefs` type

packages/runtime-core/__tests__/componentProxy.spec.ts, packages/runtime-core/src/componentProxy.ts
On the `rc.5` I started getting errors because a `symbol` was used during render, because `indexOf` is not available on symbol.
This test is not representative on you will get this problem, but rather a way to trigger it.
The "errors" can be found [CI build here](https://app.circleci.com/pipelines/github/pikax/vue-composable/1810/workflows/027e25cb-27f0-4232-8d9b-929723f22dd3/jobs/1791) (the first error is not related to this particular case) but [exception is not being bubble up](https://github.com/vuejs/vue-next/pull/987)
after manually disabling the recursive `vue-next` log error:
```log
TypeError: key.indexOf is not a function
at Object.get (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5422:17)
at Proxy.render (eval at compileToFunction …
```
=> feat(runtime-core): check if the key is string

packages/runtime-core/__tests__/apiOptions.spec.ts, packages/runtime-core/src/componentOptions.ts
=> fix(watch): allow handler to be a string

packages/runtime-dom/__tests__/patchProps.spec.ts, packages/runtime-dom/src/patchProp.ts
=> fix: patch form as an attribute

packages/runtime-core/__tests__/components/KeepAlive.spec.ts, packages/runtime-core/src/renderer.ts
=> fix(keep-alive): call activated hook of nested components.(#1742)

packages/shared/src/codeframe.ts
When `String(line).length` (ie. when the source is >= 1000 lines), then `range` fails.
Closes #1806 
Related to #1804 except this PR uses a `max` rather than `abs`.
=> fix(codeframe): Added Math.max to prevent RangeError (#1806)

packages/runtime-core/__tests__/apiTemplateRef.spec.ts, packages/runtime-core/src/renderer.ts
Fix #1834
Fix #1789 .
Unresolved question: when `ref` is a function, keep the current behavior?
=> fix(runtime-core): set ref in the post-render queue

packages/runtime-core/src/renderer.ts
=> fix(runtime-core): should correctly call `beforeEnter` inside `Suspense`

packages/runtime-core/__tests__/apiWatch.spec.ts, packages/runtime-core/__tests__/scheduler.spec.ts, packages/runtime-core/src/renderer.ts, packages/runtime-core/src/scheduler.ts
=> fix(scheduler): allows to sort the PostFlushCbs

packages/runtime-core/src/components/Teleport.ts, packages/vue/__tests__/index.spec.ts
=> fix(runtime-core/Teleport): handle 0 as patchFlag value.

packages/runtime-core/src/componentOptions.ts, test-dts/defineComponent.test-d.tsx
Right now, it seems like `emits` validators cannot access `this` (for example, to validate event arguments based on the value of a prop). However, the typing doesn't reflect the fact that `this` isn't available.
I came across this because I wasn't sure if I could access `this` in `emits`, but accessing `this.propName` didn't give me a type error, so I thought it would probably work.
=> types(runtime-core): make `this` void in emits validator

packages/runtime-core/src/devtools.ts
`devtool.ts` has two unnecessary `export`
=> chore: remove unnecessary 'export'

test-dts/defineComponent.test-d.tsx
Due to the limitation of TS, prop validator must be fully annotated. 
`defineComponent` will produce prop type `unknown` in setup method because of contextual typing of object literal.
```ts
defineCopmonent({
props: {
validated: {
type: String,
validator(val) {
return val !== ''
}
}
},
setup(props) {  
props.validated // error, props is unknown
}
})
```
The fix now is to add explicit annotation to the validator function to suppress contextual typing.
This pull request adds an example test for this.
refer to https://github.com/microsoft/TypeScript/issues/38623
=> test(types): add prop validator test

packages/compiler-sfc/__tests__/parse.spec.ts, packages/compiler-sfc/src/parse.ts
There are cases in which we need the sourcemap of the content in custom blocks.
In the case of vue-i18n, when is compiling i18n resources from custom blocks to JS codes, we need the sourcemap to support DX.
In `vue-loader@next`, it does pass the sourcemap, but vue-i18n-loader can't receive it.
https://github.com/vuejs/vue-loader/blob/next/src/select.ts#L46
=> fix(compiler-sfc): custom blocks sourcemap

.github/contributing.md
Just a tiny readability change I spotted a few times:
Understand if it doesn't seem like a big enough deal to add the 'a' 🙂
=> docs: add indefinite article to bug fix sentence

packages/reactivity/__tests__/reactive.spec.ts, packages/reactivity/src/reactive.ts
Fixed usage scenarios using subtypes of collections: 
```javascript
class CustomMap extends Map {
get(key) {
console.log(key)
return super.get(key)
}
}
class SMap extends CustomMap {
set(key, value) {
console.log(key, value) // or other actions
return super.set(key, value)
}
}
const a = reactive(new SMap())
a.set('a', 'ok')
// Error:  TypeError: Method Map.prototype.set called on incompatible receiver [object Object] 
```
close #1868
=> fix(reactivity): accept subtypes of collections

packages/runtime-core/src/componentProps.ts, test-dts/defineComponent.test-d.tsx
Specifying the `default` value will affect the type inference of `props`:
This PR improves that:
=> types(runtime-core): improve the props' type

packages/runtime-core/src/componentOptions.ts, test-dts/defineComponent.test-d.tsx
Same as #1842, except for `validator`s and `default` factories in `props`. The typing currently doesn't reflect the fact that `this` isn't available in these functions.
=> types(runtime-core): make `this` void in prop validators and default factories

packages/runtime-dom/types/jsx.d.ts
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menuitem
=> chore(runtime-dom):menuitem tag has been deprecated

packages/shared/src/domTagConfig.ts
Deprecated
This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.
=> chore: element tag  is deprecated

packages/reactivity/src/ref.ts, test-dts/ref.test-d.ts
https://github.com/vuejs/composition-api/issues/453
```ts
const STATUS_INITIAL = 'initial'
const STATUS_READY = 'ready'
const STATUS_INVALIDATING = 'invalidating'
type Status = 'initial' | 'ready' | 'invalidating'
const status = shallowRef<Status>(STATUS_INITIAL)
if (status.value === STATUS_READY) {
status.value = STATUS_INVALIDATING
}
```
Explanation `shallowRef<Status>` is returning `Ref<'initial'> |  Ref<'ready'> | Ref<'invalidating'>` so when you do 
```ts
if (status.value === STATUS_READY) {
// status === Ref<'ready'> 
}
```
=> types(reactivity): improve typings for `shallowRef`

packages/runtime-core/src/component.ts, test-dts/functionalComponent.test-d.tsx
=> types(runtime-core): make `FunctionalComponent` emit string[] compatible with `Component`

packages/runtime-core/src/componentProps.ts, test-dts/defineComponent.test-d.tsx
fix #1891
Honestly don't know why adding `| {}` works here 🤔
=> types(runtime-core): handling PropType<Function>

packages/runtime-core/src/helpers/renderSlot.ts, packages/runtime-core/src/vnode.ts
=> fix(runtime-core): correctly track dynamic nodes in renderSlot

packages/runtime-core/__tests__/apiWatch.spec.ts, packages/runtime-core/src/apiWatch.ts
class getters/setters are not enumerable.
=> fix(watch): deep watch

packages/runtime-core/src/renderer.ts, packages/runtime-dom/src/directives/vModel.ts, packages/runtime-dom/src/modules/props.ts
more detail: https://github.com/vuejs/vue-next/issues/1935#issuecomment-678722785
close #1935
=> fix(runtime-dom): v-model breaks minlength validation

packages/runtime-dom/types/jsx.d.ts
```tsx
interface AProps extends HTMLAttributes {
}
const A = (props: AProps) => {
return <span {...props} />
}
<A onClick={xx} />
```
It's not necessary to define `onClick` or `onXxx` again.
=> types(runtime-core): HTMLAttributes should extends Events

packages/runtime-core/__tests__/apiOptions.spec.ts, packages/runtime-core/src/componentOptions.ts
=> fix(runtime-core): the lifecycle hooks in mixins & extends should be called correctly

packages/reactivity/__tests__/reactiveArray.spec.ts, packages/reactivity/src/baseHandlers.ts, packages/reactivity/src/effect.ts, packages/shared/src/index.ts
Fixed the scenarios below:
```
const observed = reactive(new Array(3))
effect(() => {
console.log(observed.length)
})
observed.x = 'x'
observed[-1] = 'x'
observed[1] = 1
// all they three statement will trigger the effect which would not be the expected result...
```
=> fix(reactivity): add existing index or non-integer prop on Array should not trigger length dependency

packages/reactivity/__tests__/collections/Map.spec.ts, packages/reactivity/src/collectionHandlers.ts
```js
let map = new Map()
map.has = function(key) {
console.log('trigger has')
return Map.prototype.has.call(map, key)
}
let proxy = reactive(map)
proxy.has('k')  // print 'trigger has' twice
```
```js
let map = new WeakMap()
map.has = function(key) {
console.log('trigger has')
return WeakMap.prototype.has.call(map, key)
}
let proxy = reactive(map)
proxy.has(reactive({}))  // print 'trigger has' twice
```
=> fix(reactivity): trigger Map custom has correctly

packages/compiler-sfc/src/index.ts
`generateCodeFrame` should be placed at "API" group
=> style(compiler-sfc): tweak api and types export

packages/runtime-core/__tests__/apiCreateApp.spec.ts, packages/runtime-core/__tests__/apiOptions.spec.ts, packages/runtime-core/src/componentOptions.ts
1. priority: see <del> #1985  </del> #1978 
2. flatten: see #1979 
<del> close #1985 </del> close #1978 , close #1979
=> fix(runtime-core): behavior of merging options is inconsistent with Vue2.x

packages/runtime-core/__tests__/rendererOptimizedMode.spec.ts, packages/runtime-core/__tests__/vnode.spec.ts, packages/runtime-core/src/helpers/renderSlot.ts, packages/runtime-core/src/helpers/withRenderContext.ts, packages/runtime-core/src/vnode.ts
=> fix(runtime-core): dynamicChildren should be tracked correctly when normalizing slots to plain children

packages/runtime-core/__tests__/components/Teleport.spec.ts, packages/runtime-core/src/components/Teleport.ts
I’m not sure if this PR really fix the #2015 , but it is indeed an improvement.
=> feat(runtime-core/teleport): don't throw warnings when teleport is disabled and no target is specified

packages/runtime-core/__tests__/rendererAttrsFallthrough.spec.ts, packages/runtime-core/src/componentRenderUtils.ts
=> fix(runtime-core): v-model listeners that already exists on the component should not be merged

packages/runtime-core/__tests__/apiCreateApp.spec.ts, packages/runtime-core/src/componentOptions.ts
my fault, previous fix didn't change the logic of `if !hasown(to, key)`, instead the global and local priorities were adjusted.
now it's fixed
close #2040
=> fix(runtime-core): priority of option merging

README.md
The plugin has moved from vueComponent/jsx to the main organization, so this PR updates the README.md with the direct link to the new repo.
=> docs(readme): update link to the JSX babel plugin

packages/runtime-core/src/apiDefineComponent.ts, packages/runtime-core/src/componentOptions.ts, packages/runtime-core/src/componentPublicInstance.ts, test-dts/defineComponent.test-d.tsx
=> types(runtime-core): unwrap the RawBndings

packages/runtime-core/__tests__/rendererFragment.spec.ts, packages/runtime-core/src/renderer.ts
=> fix: inherit `el` with hoisted nodes inside keyed `template` fragment

packages/reactivity/__tests__/reactiveArray.spec.ts, packages/shared/src/index.ts
Fixed: 
``` 
const observed = reactive(new Array(3))
effect(() => {
console.log(observed.length)
})
observed[NaN] = 1
```
=> fix(reactivity): add NaN prop on Array should not trigger length dependency

packages/compiler-sfc/__tests__/compileStyle.spec.ts, packages/compiler-sfc/src/stylePreprocessors.ts
vite 1.0.0-beta.9+ accepts `cssPreprocessOptions` but this ignores [`data` option](https://github.com/sass/node-sass#data) of scss/sass in `vite.config.ts`
This PR fix the issue
=> fix(compiler-sfc): user-defined options.data of scss should be respected

packages/runtime-core/src/component.ts
Reverts vuejs/vue-next#1849.
More information at [#1849](https://github.com/vuejs/vue-next/pull/1849#issuecomment-683658875)
=> Revert "refactor(runtime-core): add @internal for instance.proxy"

packages/reactivity/__tests__/collections/Map.spec.ts, packages/reactivity/__tests__/collections/Set.spec.ts, packages/reactivity/src/collectionHandlers.ts
```js
let map = new Map()
map.set = function(key) {
console.log('trigger set')
return Map.prototype.set.call(map, key)
}
let proxy = reactive(map)
proxy.set('k', 'foo')  // Nothing is printed
```
=> fix(reactivity): should trigger collection's write-function correctly on non-reactive keys

packages/runtime-core/src/componentOptions.ts
Fixes #1339
These lifecycle hooks were [mentioned in the RFC document](https://composition-api.vuejs.org/api.html#:~:text=beforeDestroy,onUnmounted)
and were implemented before.
But somehow dropped in this commit https://github.com/vuejs/vue-next/commit/81a31f79dc69dae1eac1b958af3f3a18bd1f67ac
Now that there's no mention of this breaking change in Vue 3 RFCs, I
think we need to support these legacy hooks.
=> fix: add beforeDestroy/destroyed lifecycle back to the options API

packages/compiler-sfc/__tests__/compileScript.spec.ts, packages/compiler-sfc/src/compileScript.ts
Fixes https://github.com/vuejs/vue-cli/issues/5863
=> fix: should be able to parse  decorators in script lang="ts" & jsx

packages/compiler-sfc/src/compileScript.ts, packages/vue/__tests__/index.spec.ts
This PR seeks to fix two broken tests by removing an unused `ParserOptions` import and renaming `destroyed` to `unmounted`
I only noticed one was broken at first - sorry about the vagueness of the PR title 😅 
1. `ParserOptions` is imported in `packages/compiler-sfc/src/compileScript.ts` but is unused and therefore breaks tests/build etc.
https://app.circleci.com/pipelines/github/vuejs/vue-next/4190/workflows/306e4d28-c993-4662-9565-93f68ff76137/jobs/9323
2. `destroyed` is used instead of `unmounted` in `packages/vue/__tests__/index.spec.ts`
https://app.circleci.com/pipelines/github/vuejs/vue-next/4191/workflows/6b37db70-b8ef-4e10-ab16-e92b49d6b45e/jobs/9326
=> test: remove unused ParserOptions, destroyed to unmounted

packages/reactivity/__tests__/ref.spec.ts, packages/reactivity/src/ref.ts
```ts
const r = { x: ref(1) }
toRef(r,'x') // { value: { value: 1 } } 
// it should be 
toRef(r, 'x') // { value: 1}
```
=> fix(reactivity): `toRef` should not wrap a `ref`

packages/runtime-core/__tests__/components/KeepAlive.spec.ts, packages/runtime-core/src/components/KeepAlive.ts
When exclude prop change, it should prune cache that not matched.
=> fix(KeepAlive): when exclude prop change, it should prune cache that not matched

packages/runtime-core/__tests__/apiAsyncComponent.spec.ts, packages/runtime-core/__tests__/components/Suspense.spec.ts, packages/runtime-core/__tests__/hydration.spec.ts, packages/runtime-core/src/component.ts, packages/runtime-core/src/components/BaseTransition.ts, packages/runtime-core/src/components/KeepAlive.ts, packages/runtime-core/src/components/Suspense.ts, packages/runtime-core/src/hydration.ts, packages/runtime-core/src/index.ts, packages/runtime-core/src/renderer.ts, packages/runtime-core/src/vnode.ts, packages/runtime-dom/src/helpers/useCssVars.ts, packages/server-renderer/src/helpers/ssrRenderSuspense.ts, packages/server-renderer/src/render.ts, packages/vue/__tests__/Transition.spec.ts, packages/vue/examples/classic/markdown.html, test-dts/tsx.test-d.tsx
Main changes:
- `<Suspense>` now expects a single root node (cannot be fragment) for the default/fallback slots.
- An already-resolved suspense only enters "pending state" when the default slot's root node changes.
- By default, the current *active tree* will stay on the screen until the *pending tree* is resolved. The pending tree, when resolved, replaces the previous active tree and becomes the new active tree.
- A `timeout` prop can be specified - if a pending tree remains pending past the timeout threshold, the active tree will be unmounted and be replaced by the fallback tree.
- New **nested** async child rendered inside an already resolved suspense no longer puts the suspense into pending state (TODO: components with `async setup()` should be allowed to declare its own loading state …
=> Update Suspense usage

packages/compiler-sfc/__tests__/compileStyle.spec.ts, packages/compiler-sfc/src/stylePreprocessors.ts
close https://github.com/vitejs/vite/issues/520
=> feat(compiler-sfc): `additionalData` support for css preprocessors

packages/runtime-core/src/index.ts, test-dts/defineComponent.test-d.tsx, test-dts/tsconfig.build.json
Fix error when libraries export `defineComponent` also added a verification on dts file.
=> types(defineComponent): fix missing exported types

packages/runtime-core/src/components/Suspense.ts, test-dts/tsx.test-d.tsx
Removes the mention of the recede event that has been replaced.
Adds a typing test on the new pending event
=> chore: typos in suspense events

packages/runtime-core/__tests__/hmr.spec.ts, packages/runtime-core/src/component.ts, packages/runtime-core/src/hmr.ts, packages/runtime-core/src/vnode.ts
fix https://github.com/vuejs/vue-class-component/issues/451
Since the raw class component is passed to the HMR reload API, it tries to extract component options from the class constructor which causes the issue. We have to extract its component options if a class is passed to the HMR API.
=> fix(runtime-core): make HMR working with class components

CHANGELOG.md
small typo on CHANGELOG.md, It should be right to `should`.
=> fix(typo) shoud to should on CHANGELOG.md

packages/runtime-core/src/componentEmits.ts, test-dts/functionalComponent.test-d.tsx
=> fix(types): make enable to use tuple type as EmitsOptions (#2159)

packages/reactivity/src/collectionHandlers.ts
Typescript 4.1 will have [stricter rules for type predicates](https://github.com/microsoft/TypeScript/pull/39258) like
```ts
export const isObject = (val: unknown): val is Record<any, any> =>
val !== null && typeof val === 'object'
```
As a result of these rules, an expression in collectionHandlers.ts in the reactivity package doesn't get narrowed to the type it did in TS 4.0 and below. Instead it gets an intersection type, which doesn't work with subsequent code.
I restored the old type using a cast, since that's essentially what the old version of Typescript was doing here.
Discovered in the Typescript user tests: https://github.com/microsoft/TypeScript/pull/40156/files#diff-3ff86ade791953efc13be67665963d94
Fixes #2218
=> Fix Typescript 4.1 compile error

packages/compiler-core/__tests__/transforms/vOnce.spec.ts, packages/compiler-core/src/ast.ts, packages/compiler-core/src/transforms/vIf.ts
Fix: #2035.
This PR only fix the issue of using `v-once` with `v-if/else-if/else`, but not for using the `v-once` inside `v-for`.
=> fix(compiler-core): make v-once work with v-if/else-if/else

packages/runtime-core/__tests__/rendererComponent.spec.ts, packages/runtime-core/src/renderer.ts
An instance’s `el` property can be `null` inside a watcher after a component was rerendered (e.g. as a result of a changed prop). In an instance’s `update` method, the branch for handling mounted instances doesn’t set the `el` property of what will become the instance’s `vnode` property early enough. Upon execution of the `updateComponentPreRender` function, the `el` property is then `null` which causes issues in watcher routines that rely on an instance’s `$el` property.
Fixes #2170.
_(I have no knowledge of Vue’s internals besides what I gathered from trying to fix this bug, so the description here and the proposed change might not be adequate.)_
=> fix(runtime-core): vnode.el is null in watcher after rerendering (fix #2170)

packages/reactivity/src/effect.ts, packages/runtime-core/__tests__/rendererComponent.spec.ts
=> fix(reactivity): should add allowRecurse to the effect

packages/runtime-core/__tests__/components/Suspense.spec.ts, packages/runtime-core/__tests__/errorHandling.spec.ts, packages/runtime-core/src/errorHandling.ts
=> fix(runtime-core): consist with vue2's error capturing behavior

packages/compiler-core/src/transforms/vOn.ts, packages/runtime-core/__tests__/componentEmits.spec.ts, packages/runtime-core/src/componentEmits.ts
In issue #2249 , we found inconsistent event casing for render functions.
The reproduction link in issue#2249 is here:
https://codesandbox.io/s/nervous-surf-f5lbs
In that case, when we emit `test-event`, only `onTest-Event` worked. But the one expected to work on the render function should be `onTestedEvent`.
So I fix it in this PR, and add test case for it.
All test cases were passed.
Close #2249
=> fix(runtime-core): fix inconsistent event casing for render functions, see issue#2249

packages/runtime-dom/__tests__/directives/vModel.spec.ts, packages/runtime-dom/src/directives/vModel.ts
fix #2252
I open a new PR and closed the old one https://github.com/vuejs/vue-next/pull/2254
=> fix(runtime-dom): `v-model.number` work with select tag

packages/compiler-core/__tests__/transforms/vIf.spec.ts, packages/compiler-core/src/utils.ts
=> fix(compiler-core): merge props when use v-if with v-on

packages/vue/README.md
H4 not showing correctly for https://www.npmjs.com/package/vue/v/3.0.0
=> fix(typo): heading for npm readme

packages/runtime-dom/__tests__/helpers/useCssVars.spec.ts, packages/runtime-dom/src/helpers/useCssVars.ts
=> fix(cssVars): should attach css vars while `subtree` changed

packages/runtime-dom/__tests__/directives/vModel.spec.ts, packages/runtime-dom/src/directives/vModel.ts, packages/shared/src/looseEqual.ts
More information at [cf1b6c66](https://github.com/vuejs/vue-next/commit/cf1b6c666f45a284494f80981522a3dc4804a683#r42355354).
=> perf(runtime-dom/vModel): remove looseHas if model is Set

packages/compiler-ssr/__tests__/ssrElement.spec.ts, packages/compiler-ssr/src/transforms/ssrInjectCssVars.ts, packages/compiler-ssr/src/transforms/ssrTransformElement.ts, packages/server-renderer/__tests__/renderToString.spec.ts
Hi,
First PR on Vue3, and first time looking at the SSR process!
This one kept me busy few hours, to understand how all of that that runs (hurray for the debugger!).
As you can see [in the Template explorer](https://vue-next-template-explorer.netlify.app/#%7B%22src%22%3A%22%3Cdiv%3E%5Cn%20%20%3Cdiv%20%3Aclass%3D%5C%22dynamic%5C%22%20class%3D%5C%22child%5C%22%3E%3C%2Fdiv%3E%5Cn%20%20%3Cdiv%20class%3D%5C%22child%5C%22%20%3Aclass%3D%5C%22dynamic%5C%22%3E%3C%2Fdiv%3E%5Cn%3C%2Fdiv%3E%5Cn%5Cn%5Cn%22%2C%22ssr%22%3Atrue%2C%22options%22%3A%7B%22mode%22%3A%22module%22%2C%22prefixIdentifiers%22%3Afalse%2C%22optimizeImports%22%3Afalse%2C%22hoistStatic%22%3Afalse%2C%22cacheHandlers%22%3Afalse%2C%22scopeId%22%3Anull%2C%22ssrCssVars%22%3A%22%7B%20color%20%7D%22%2C%22bindingMetadata%22%3A%7B%22TestCompone …
=> fix(compiler-ssr): fix SSR issue when dynamic and static class used

packages/runtime-core/__tests__/helpers/renderList.spec.ts, packages/runtime-core/src/helpers/renderList.ts, packages/server-renderer/__tests__/ssrRenderList.spec.ts, packages/server-renderer/src/helpers/ssrRenderList.ts, packages/shared/src/index.ts
=> feat(renderList):  warn with `v-for` has non-integer range number

packages/runtime-core/__tests__/rendererComponent.spec.ts
- rewrite test description, remove some non-English characters
- add test for `data` option
=> test(runtime-core): modify test for #2295

packages/runtime-core/src/component.ts
```js
Vue.createApp({
template: `<div>{{ hasOwnProperty }}</div>`,
data () {
return {
hasOwnProperty: 3,
};
},
}).mount('body');
```
**production mode**: Can't find prop `hasOwnProperty` on `instance.ctx` while renderring, which should on `instance.data` in fact, but skipped by `switch(n)` check. See `PublicInstanceProxyHandlers.get`.
---
**development mode**: Seems right on UI, but in fact, it's readed from `instance.ctx` copy, not `instance.data`, so when the prop value is `Vue.ref(3)`, there will be `{ "_rawValue": 3, "_shallow": false, "__v_isRef": true, "_value": "old" }` but not `3` on the UI.
```js
Vue.createApp({
template: `<div>{{ hasOwnProperty }}</div>`,
data () {
return {
hasOwnProperty: Vue.ref(3),
};
},
}).mount('body');
```
=> fix accessCache proto

packages/compiler-core/__tests__/transforms/vBind.spec.ts, packages/compiler-core/__tests__/transforms/vOn.spec.ts, packages/compiler-core/src/runtimeHelpers.ts, packages/compiler-core/src/transforms/vBind.ts, packages/compiler-core/src/transforms/vOn.ts, packages/compiler-dom/__tests__/transforms/vOn.spec.ts, packages/compiler-ssr/__tests__/ssrElement.spec.ts, packages/runtime-core/src/apiLifecycle.ts, packages/runtime-core/src/componentEmits.ts, packages/runtime-core/src/helpers/toHandlers.ts, packages/runtime-core/src/index.ts, packages/runtime-core/src/renderer.ts, packages/runtime-core/src/vnode.ts, packages/server-renderer/src/helpers/ssrRenderAttrs.ts, packages/shared/src/index.ts
close #2388 
also modify runtime-core, to avoid patching prop if prop's name is empty string
=> feat(compile-core): check if nullish for dynamic vOn

.github/workflows/size-check.yml
Added the size check as a log for on push
Result: https://github.com/vuejs/vue-next/pull/2392/checks?check_run_id=1263863311
=> ci: add size check on push

packages/runtime-dom/types/jsx.d.ts
Fix `Property 'xmlns' does not exist on type 'ElementAttrs<SVGAttributes>'.`
```tsx
const Svg = <svg xmlns="http://www.w3.org/2000/svg" />;
```
=> types(runtime-core): svg xmlns attribute typing

packages/runtime-core/src/componentProps.ts, packages/runtime-core/src/componentRenderUtils.ts, packages/runtime-core/src/vnode.ts, packages/shared/src/index.ts, packages/vue/__tests__/index.spec.ts
=> fix(runtime-core): EMPTY_ARR should be frozen to prevent changes

packages/compiler-dom/__tests__/__snapshots__/index.spec.ts.snap, packages/compiler-dom/__tests__/transforms/vText.spec.ts, packages/compiler-dom/src/transforms/vText.ts
Close #2430
TODO:
- When do we need to pass the `loc` parameter? It seems to be always optional but it changes what is highlighted on the template explorer
=> fix(compiler): stringify values on v-text

packages/runtime-core/__tests__/apiInject.spec.ts, packages/runtime-core/src/apiInject.ts
fix #2400 
This fix makes sure the injection in the component comes from the parent.
For the root component, it is possible to inject properties provided through plugins.
=> fix(runtime-core): prevent self-injection (#2400)

packages/compiler-core/__tests__/transforms/__snapshots__/vModel.spec.ts.snap, packages/compiler-core/__tests__/transforms/vModel.spec.ts, packages/compiler-core/src/utils.ts
=> feat(compiler-core): v-model multilines exp #2426

packages/runtime-core/__tests__/componentEmits.spec.ts, packages/runtime-core/src/componentEmits.ts
#2326 
This feature allows `v-model` built-in modifiers: `number` and `trim` to be used on component.
=> feat(runtime-core): allows v-model built in modifiers on component 

packages/runtime-core/__tests__/rendererOptimizedMode.spec.ts, packages/runtime-core/src/renderer.ts
=> fix(runtime-core): non-stable Fragment always need to diff its children

packages/runtime-core/src/h.ts, packages/runtime-core/src/helpers/resolveAssets.ts, test-dts/h.test-d.ts
Fix #2357 
> Note: resolveComponent cannot return `undefined`, so I removed it
=> types(h): support for resolveComponent

packages/runtime-core/src/scheduler.ts
fix https://github.com/vitejs/vite/issues/1021
=> fix(runtime-core): refactor scheduler queue not be empty

packages/compiler-core/src/codegen.ts, packages/compiler-core/src/options.ts, packages/compiler-core/src/runtimeHelpers.ts, packages/compiler-core/src/transform.ts, packages/compiler-core/src/transforms/transformElement.ts, packages/compiler-core/src/transforms/transformExpression.ts, packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap, packages/compiler-sfc/__tests__/compileScript.spec.ts, packages/compiler-sfc/src/compileScript.ts, packages/compiler-sfc/src/compileTemplate.ts, packages/compiler-sfc/src/genCssVars.ts
Related RFC: https://github.com/vuejs/rfcs/pull/222
=> New `<script setup>` and ref sugar implementation

packages/runtime-core/__tests__/apiWatch.spec.ts, packages/runtime-core/src/apiWatch.ts, packages/runtime-core/src/component.ts
it should always add its effects to its own instance
close: #2381
=> fix(runtime-core): $watch effects can register effects with wrong instance (fix: #2381)

packages/compiler-core/__tests__/transforms/transformSlotOutlet.spec.ts, packages/compiler-core/src/transforms/transformSlotOutlet.ts, packages/vue/examples/classic/commits.html
=> fix(compiler-core): transform kebab case props to camelcase on slots (close #2488)

packages/reactivity/__tests__/readonly.spec.ts, packages/reactivity/src/baseHandlers.ts
When using `readonly()` on a plain array, accessing the array in any way should not result in any tracking, no deps should be collected, as a plain array can't be tracked anyway.
However, for array methods like `includes`, we currently use `arrayImplementations` that *do* track wether or not the proxy is a reactive or readonly one.
Consequently, this doesn't result in tracking:
```js
readonly([1, 2])[0]
```
but this does:
```
readonly([1, 2]).includes(1)
```
close: #2493
=> fix(reactivity): ensure  readonly on plain arrays doesn't track array methods. (close: #2493)

packages/runtime-core/__tests__/rendererComponent.spec.ts, packages/runtime-core/src/component.ts
=> fix(runtime-core): should pause tracking deps when initializing legacy options

packages/reactivity/__tests__/collections/Map.spec.ts, packages/reactivity/__tests__/collections/Set.spec.ts, packages/reactivity/__tests__/collections/WeakMap.spec.ts, packages/reactivity/__tests__/collections/WeakSet.spec.ts, packages/reactivity/src/collectionHandlers.ts
We currently return the raw target instead of the proxy on the following calls:
```
reactive(new Map()).set('a', 'a')
reactive(new WeakMap()).set({}, 'a')
reactive(new Map()).add('a')
reactive(new WeakMap()).add({})
```
This fix now returns the proxy
close: #2530
=> fix(reactivity): ensure add/set on reactive collections return the proxy (fix: #2530)

packages/runtime-core/__tests__/componentEmits.spec.ts, packages/runtime-core/src/componentEmits.ts
See #2540 , `isEmitListener` function will not work when using kebab-case event.
So I fix the `isEmitListener` function and now it works correctly.
Close #2540
=> fix(runtime-core): fix the warning "Extraneous non-emits event listeners" shows up even when emits is set

packages/runtime-core/src/components/KeepAlive.ts
We currently watch components like this:
`watch(() => [props.include, props.exclude], ....)`
Which works when `include` / `exclude` are eithe refs or receive immutable values.
If either is a `reactive([])`, the watch would not be triggered.
Addind `deep: true` fixes the issue.
=> fix(runtime-core): ensure keep-alive deep-watches include/exlude props (fix #2550)

packages/runtime-core/__tests__/apiOptions.spec.ts, packages/runtime-core/src/apiInject.ts, packages/runtime-core/src/componentOptions.ts
Fixes https://github.com/vuejs/vue-next/issues/2615
=> fix(provide): support symbols in applyOptions

packages/runtime-core/__tests__/components/Teleport.spec.ts, packages/runtime-core/src/components/Teleport.ts
Currently, when using Teleport to move an SVGElement or into an SVGElement, the element is not rendered . The issue is due to the fact that the Teleport "process" method is not checking whether the target element is itself an SVGElement and therefore uses createElement instead of createElementNS. This PR fixes that issue.
=> fix: Teleport SVG elements

packages/runtime-dom/__tests__/directives/vModel.spec.ts, packages/runtime-dom/src/directives/vModel.ts
close: #2662 
According to the current behavior, if we bind a value of type `Set`, then the original `Set` will already be manipulated, so I think it is ok to manipulate the original array here.
=> fix(runtime-dom): the original array should be manipulated when checkbox binds the array value

packages/runtime-dom/src/components/Transition.ts, packages/vue/__tests__/Transition.spec.ts, packages/vue/__tests__/TransitionGroup.spec.ts
Close #2531, Close #2593
Make sure that `*-enter/leave-from` is the beginning of transition.
=> feat(runtime-dom): adjust transition class process

packages/runtime-dom/src/components/Transition.ts, packages/vue/__tests__/TransitionGroup.spec.ts
=> fix(runtime-dom): ensure styles from *-leave-active trigger transition

packages/runtime-core/src/componentOptions.ts, test-dts/defineComponent.test-d.tsx
Fix #2350
Provide mixing info inside of `data()` and infer mixins props in `setup(props)`
=> types: mixin and extends typing on data and setup

packages/runtime-core/src/apiWatch.ts, test-dts/watch.test-d.ts
When using `watch`, you could do this.
```
setup() {
const someRef = ref({ test: 'test' });
const otherRef = ref({a: 'b'});
watch([someRef, otherRef], values => {
const value1 = values[0];
// no type error
console.log(value1.test);
const value2 = values[1];
// no type error
console.log(value2.a);
});
}
```
=> types(watch): provide more type info in watch function

packages/runtime-dom/src/index.ts
=> feat(runtime-dom): support mount app on ShadowRoot

packages/runtime-core/src/renderer.ts
Fixes https://github.com/vuejs/vue-next/issues/2458
=> fix(setupRenderEffect): component anchor leak

packages/compiler-sfc/__tests__/parse.spec.ts, packages/compiler-sfc/src/parse.ts
See #2463
This tweak is based on the following consideration:
> An empty `<template>` block means it should render empty string, which is different from no `<template>` block.
=> fix(compiler-sfc): should keep template nodes with no content (close #2463)

packages/runtime-dom/src/index.ts, packages/vue/__tests__/index.spec.ts
Currently when mounting several applications, it is hard to know which one failed with the emitted warning:
Failed to mount app: mount target selector returned null.
This commit adds the not found selector to the warning message, helping developers to locate which of their application is not mounting properly:
Failed to mount app: mount target selector "#not-found" returned null.
=> fix(runtime-core): add selector in mount warning

.github/workflows/size-check.yml
There was a bug in the previous version comparing in the wrong direction and therefore showing size increases as decreases and vice versa
=> ci: fix size check script

packages/runtime-core/src/component.ts
typo: `reoslved` => `resolved`
=> chore: typo

packages/runtime-core/src/apiCreateApp.ts
When unmounting an app, we need to remove the `__vue_app__` property from the container element, otherwise the app instance can't be garbage collected for as long as that element exists.
closes #2907
=> fix(runtime-core): ensure app instance can be garbage collected after unmount (close #2907)

packages/runtime-core/__tests__/apiCreateApp.spec.ts, packages/runtime-core/src/apiCreateApp.ts
Updated `app.unmount()` type declaration.
`unmount()` doesn't actually take in any parameters, but the type declaration claimed that it does.
close #2922
=> docs(type): remove unmount parameters

packages/runtime-dom/src/index.ts
Otherwise this expression would throw in environments that do not
support `ShadowRoot`, including the common mocha testing environment
setup that uses `jsdom` and `jsdom-global`.
It is because `ShadowRoot` is not an enumerable property on `window`,
`jsdom-global` fails to expose it on the `global` object.
See the error message at https://app.circleci.com/pipelines/github/vuejs/vue-cli/779/workflows/17d7d7c4-7605-4588-878a-ddb3a6d37102/jobs/24147
=> fix: should prefix `ShadowRoot` with `window.`

packages/runtime-dom/__tests__/patchProps.spec.ts, packages/runtime-dom/src/patchProp.ts, packages/shared/src/domTagConfig.ts
=> fix(runtime-dom): enable set form attr to null on form-elements (#2840)

packages/compiler-sfc/__tests__/parse.spec.ts, packages/compiler-sfc/src/parse.ts
=> fix(compiler-sfc): the empty lang attribute should be treated as no lang specified

packages/compiler-sfc/LICENSE, packages/compiler-ssr/LICENSE, packages/shared/LICENSE, packages/vue/LICENSE
Some of the packages that are publsihed on NPM are missing the LICENSE file for the MIT license. This PR adds those where missing.
close #2650
=> fix: ensure all published packages contan a LICENCE file (close #2650)

README.md
mention we plan to drop the next suffix in early
2021 rather than 2020 since that deadline has
passed.
Fixes N/A
=> fix(docs): change reference to passed deadline

packages/compiler-sfc/__tests__/__snapshots__/templateTransformSrcset.spec.ts.snap, packages/compiler-sfc/__tests__/templateTransformSrcset.spec.ts, packages/compiler-sfc/src/templateTransformSrcset.ts
fix https://github.com/vitejs/vite/issues/1523
=> fix(compiler-sfc): compiler blank srcset

packages/reactivity/src/baseHandlers.ts
In DEV mode, the [custom formatter](https://github.com/vuejs/vue-next/blob/master/packages/runtime-core/src/customFormatter.ts#L26) will read the `__isVue`, which causes it to be tracked. I think it’s ok to not track it in the production environment.
=> perf(reactivity): should not track `__isVue`

packages/shared/__tests__/normalizeProp.spec.ts, packages/shared/src/normalizeProp.ts
Having any other primitive value than string in an array sent to `normalizeClass` results in extra spaces. In v2 there are no extra spaces.
```js
h('div', {
class: ['foo', undefined, false, 'bar'],
})
<div class="foo   bar"/>
```
=> fix: remove superfluous spaces when normalizing class

packages/runtime-core/src/componentRenderUtils.ts
close: #2741 , #3133
According to #2741 , I think he should not use `renderSlot` directly, but the cause of the problem lies in:
```js
result.patchFlag & PatchFlags.DEV_ROOT_FRAGMENT
```
When `result.patchFlag` is negative(e.g. `-2` BAIL), this condition is always true.
=> fix(runtime-core): check the DEV_ROOT_FRAGMENT flag correctly in the dev environment

packages/runtime-core/src/componentPublicInstance.ts
When we try to access a non-existing property on a component during rendering, we get this helpful warning:
> Property ${JSON.stringify(key)} was accessed during render but is not defined on instance.
However, the current implementation logs this warning as long as *some* component is currently rendering. In other words, the warning is not limited to the render cycle of the component instance that we tried to read the property from.
I think this warning should only be printed out during the component's own render. 
When reading a property from a child component instance obtained from a template ref, one might not know which kind of component the ref contains, so reading a prop in order to do a sort of duck typing is useful.
But with the current implementation, a warning would be logged to …
=> feat(runtime-core): improve render context warning

packages/runtime-core/src/componentProps.ts, test-dts/defineComponent.test-d.tsx
close: #2668 
The reason is in the definition of `DateConstructor`:
```ts
interface DateConstructor {
...
(): string;
...
}
```
For simplicity, we can just create a new judgment branch to deal with it.
=> fix(types): extract the correct props type for the DateConstructor

packages/runtime-core/__tests__/componentProps.spec.ts, packages/runtime-core/src/componentPublicInstance.ts
You currently can't add properties like `hasOwnProperty` to the proxied objects as the check uses `in` to verify if it is not a prop mutation.
This is useful for testing, as Jest can't spy on an object without `hasOwnProperty`.
VTU can add it, but this commit is needed first.
Related https://github.com/vuejs/vue-test-utils-next/pull/310
=> fix(runtime-core): allow overriding properties other than props

packages/runtime-core/__tests__/apiExpose.spec.ts, packages/runtime-core/src/component.ts, packages/runtime-core/src/componentPublicInstance.ts
=> fix(runtime-core): align $parent/$root with the template ref when using expose

packages/compiler-dom/package.json
`package.json` currently states:
```
"unpkg": "dist/compiler-dom/global.js",
"jsdelivr": "dist/compiler-dom/global.js",
````
but the filename in /dist is `compiler-dom.global.js`
this PR adjusts the names in package.json
closes #3181
=> fix(compiler-dom): ensure global build filename matches the one defined in package.json (close #3181)

packages/runtime-dom/__tests__/patchEvents.spec.ts, packages/runtime-dom/src/modules/events.ts
see issue #2841 .
The kebab-case custom event `foo-bar` in web components will parse to `foobar`. Vue will add `foobar` as the name of event listener. I think this needs a fix.
Close #2841 .
: )
=> fix: kebab-case events are attached correctly on web components, see #2841

packages/runtime-core/src/components/KeepAlive.ts
It seems the `inheritRef` option has been deprecated, I can't find any usage somewhere.
I read about the commit which add `inheritRef` and find it was used to put the `ref` into the root vnode of it's render result. Maybe we do need to add some api like `inheritRef`? I created an issue about this  couple days ago in rfcs, https://github.com/vuejs/rfcs/issues/258
=> feat: remove useless option  in KeepAlive

packages/runtime-core/__tests__/apiWatch.spec.ts, packages/runtime-core/src/apiWatch.ts
=> fix(runtime-core): instanceWatch should pass `this.proxy` to source as the first argument

packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap, packages/compiler-sfc/__tests__/compileScript.spec.ts, packages/compiler-sfc/src/compileScript.ts
Fixes an issue with `removeSpecifier` in `compilerScript.ts` when there are several initial imports removed.
```ts
import { defineProps, defineEmit, ref } from 'vue'
```
was being compiled to
```ts
import { , ref } from 'vue'
```
Adds a test case in `compileScript.spec.ts`
=> fix(compiler-sfc): removeSpecifier issue when removing initial imports (script-setup)

packages/runtime-dom/__tests__/patchProps.spec.ts, packages/runtime-dom/src/patchProp.ts
the `type` prop is readonly on textareas but writeable for other form inputs. When swithcing between different input elements in dynamic components, the renderer might attempt do unset the `type` attribute, which throws when done through a DOMprop, but silently fails (as we want) when done with `setAttribute`, so we want the latter to be used.
close #2766
=> fix(runtime-dom): ensure readonly type prop on textarea is handled patched as attribute (close #2766)

packages/runtime-core/src/component.ts, packages/runtime-core/src/index.ts, packages/runtime-dom/src/index.ts
=> feat(runtime-dom): add a warning for isCustomElement in runtime-only build

packages/runtime-core/src/componentProps.ts, test-dts/component.test-d.ts
```ts
name: "PropsTest",
props: {
foo: Object as PropType<object>
},
setup(props) {
props.foo // the foo will be unknown type
}
});
```
See the repro: https://codesandbox.io/s/busy-murdock-s4vf2?file=/src/index.ts:85-226
The root cause is:
```ts
type value = { new (...args: any[]): object } extends { new (...args: any[]): infer T & object } ? T : any
value // unknown
```
For this case, we can use `{}` instead of `object`.
=> types: support object as props type

packages/runtime-core/__tests__/scheduler.spec.ts, packages/runtime-core/src/scheduler.ts
Fix: #2768, Fix #2829
Let's talk about what happened first, well, they are very complex issues(#2768, #2829). I tried to point out the minimum reproduction, check out https://codesandbox.io/s/nifty-glitter-u11y9?file=/src/index.ts, it's based on #2768. I will use the reproduced code to illustrate what happened.
Take a look at the complete code:
```ts
const Wrap = defineComponent({ render(){ return this.$slots.default!() } })
const Test = defineComponent({
setup() {
const outerC = inject('outerC')! as any
return () => h('div', `injected: ${outerC.value}`)
}
})
const IssueComp = defineComponent({
props: ['issueShow'],
setup(props) {
return () => h("div", "I should disappear (show: " + props.issueShow + ")")
}
})
const Inner = defineComponent({
name: 'Inner',
props: ['innerShow'], …
```
=> fix(scheduler): should insert jobs in ascending order of job's id when flushing

packages/runtime-dom/__tests__/directives/vShow.spec.ts, packages/runtime-dom/src/directives/vShow.ts, packages/runtime-dom/src/modules/style.ts
Fix: #2757
This PR is also re-fixed https://github.com/vuejs/vue-next/issues/2583, even though [this commit](https://github.com/vuejs/vue-next/commit/3cd30c5245da0733f9eb6f29d220f39c46518162) can fix issue https://github.com/vuejs/vue-next/issues/2583, but it causes issue https://github.com/vuejs/vue-next/issues/2757.
=> fix(v-show): v-show takes higher priority than style attribute

packages/runtime-core/__tests__/hydration.spec.ts, packages/runtime-core/src/apiCreateApp.ts, packages/runtime-core/src/renderer.ts, packages/runtime-dom/__tests__/createApp.spec.ts, packages/runtime-dom/src/index.ts
=> fix(runtime-dom): support mounting app to svg container

packages/runtime-dom/types/jsx.d.ts
Vue supports array of string and CssProperties in style attribute.
=> fix(types): allow style to be an array in JSX

packages/runtime-core/__tests__/apiAsyncComponent.spec.ts, packages/runtime-core/src/renderer.ts
=> fix(runtime-core): the forwarded template ref should be set correctly

packages/reactivity/src/baseHandlers.ts, yarn.lock
This is a required fix to update to TS 4.2.2. `Reflet.ownKeys` does now return `(string | symbol)[]` since https://github.com/microsoft/TypeScript/commit/562237dfda3ab270a9f91d0e4e4d411ff7bbd844.
Without this commit, we run into the following compilation error:
```
packages/reactivity/src/baseHandlers.ts:195:3 - error TS2322: Type '(target: object) => (string | number | symbol)[]' is not assignable to type '(target: object) => ArrayLike<string | symbol>'.
Type '(string | number | symbol)[]' is not assignable to type 'ArrayLike<string | symbol>'.
Index signatures are incompatible.
Type 'string | number | symbol' is not assignable to type 'string | symbol'.
Type 'number' is not assignable to type 'string | symbol'.
```
This allows #3293 to land
=> chore: fix ownKeys signature

packages/compiler-sfc/__tests__/compileStyle.spec.ts, packages/compiler-sfc/src/stylePluginScoped.ts
=> fix(compiler-sfc): scope Id should not be attached to the Rules in the keyframes

packages/compiler-core/__tests__/transforms/vSlot.spec.ts, packages/compiler-core/src/transforms/vSlot.ts
Fix: #3347 
Forwarded slots detection should work with `v-if/v-for`
=> fix(compiler-core): fix the detection of forwarded slots

packages/runtime-core/__tests__/components/BaseTransition.spec.ts, packages/runtime-core/src/components/BaseTransition.ts
=> fix(transition): toggling branches with in-out mode should be transitioned correctly

packages/runtime-core/src/components/Suspense.ts
This is similar to what was done for Transition in d32aed09064d2c5531213682b0d5e02556be969e
It should fix https://github.com/vuejs/vue-test-utils-next/issues/426
=> chore: add display name for suspense component

packages/runtime-core/__tests__/components/Teleport.spec.ts, packages/runtime-core/src/components/Teleport.ts, packages/runtime-core/src/renderer.ts
=> fix(teleport): targetAnchor should also be removed when unmounted

packages/runtime-core/__tests__/errorHandling.spec.ts, packages/runtime-core/src/apiWatch.ts
=> fix(runtime-core): handle error in async watchEffect

packages/runtime-core/src/renderer.ts, packages/runtime-dom/__tests__/nodeOps.spec.ts, packages/runtime-dom/src/nodeOps.ts
close: #3072 
related: https://github.com/vuejs/vue-next/issues/3091
=> fix(rumtime-core): custom dom props should be cloned when cloning a hoisted DOM

packages/runtime-core/src/component.ts, packages/server-renderer/__tests__/render.spec.ts, packages/server-renderer/src/render.ts
=> fix(server-renderer): respect the mixed render function in ssr

packages/runtime-core/__tests__/components/Teleport.spec.ts, packages/runtime-core/src/components/Teleport.ts, packages/runtime-core/src/renderer.ts
Fix: #3156 
When removing the `Teleport` during patching, we cannot use the internal renderer method  `remove` because there may be components in Teleport’s children, so we need to use `unmount` instead.
BTW: The reason why a component with a single root can be removed is because the `vnode.el` of the component is the root DOM node of the component, which is not the case for components with multiple roots.
=> fix(Teleport): component with multi roots should be removed when unmounted

packages/compiler-sfc/__tests__/compileTemplate.spec.ts, packages/compiler-ssr/src/transforms/ssrTransformComponent.ts
=> fix(compiler-ssr): keep the order of imports expression for the fallback branch of SSR

packages/runtime-core/src/componentProps.ts, test-dts/defineComponent.test-d.tsx, test-dts/index.d.ts
Fix union typed function prop's type error.
Reproduction:
https://codesandbox.io/s/smoosh-cherry-q8rv1?file=/src/index.ts
=> fix(types): union function prop

packages/compiler-core/__tests__/__snapshots__/compile.spec.ts.snap, packages/compiler-core/__tests__/transforms/__snapshots__/vIf.spec.ts.snap, packages/compiler-core/src/transforms/vIf.ts
=> fix(compiler-core): should add the DEV_ROOT_FRAGMENT flag to v-if branchs

packages/runtime-core/__tests__/rendererComponent.spec.ts, packages/runtime-core/src/componentOptions.ts, packages/runtime-core/src/componentPublicInstance.ts
=> fix(runtime-core): should not set the access cache in the data-fn

packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap, packages/compiler-sfc/__tests__/compileScript.spec.ts, packages/compiler-sfc/src/compileScript.ts
=> fix(compiler-sfc): should not rewrite scope variable

packages/compiler-core/src/ast.ts
'undefined' type and '?' specifier, one of them is redundant.
=> fix(types): remove 'undefined' type, it is redundant

packages/runtime-dom/types/jsx.d.ts
Right now, this is invalid:
```
<div tabindex="0">Tabbable due to tabindex.</div>
```
and will result in a type error.
That is because all Vue attributes are `string`.
=> fix(types): Allow tabindex to be a string

packages/runtime-core/__tests__/componentProps.spec.ts, packages/runtime-core/src/componentProps.ts
=> fix(runtime-core): fix warning for absent props

packages/runtime-core/__tests__/apiOptions.spec.ts, packages/runtime-core/src/componentOptions.ts
=> fix(runtime-core): should call hooks from chained mixins and extends

packages/runtime-core/src/renderer.ts, packages/runtime-dom/__tests__/nodeOps.spec.ts, packages/runtime-dom/src/nodeOps.ts
Fix: #3199
Align with Vue2, https://github.com/vuejs/vue/blob/dev/src/platforms/web/runtime/node-ops.js#L7-L13
=> fix(runtime-core): the select tag's multiple prop should be set before the children mounting

packages/compiler-core/__tests__/transforms/vModel.spec.ts, packages/compiler-core/src/utils.ts
Fix: #3440
For simplicity, we can just allow non-ascii as part of the identifiers
=> fix(compiler-core): allow unicode to appear in identifiers

packages/runtime-core/__tests__/componentProps.spec.ts, packages/runtime-core/src/component.ts, packages/runtime-core/src/componentProps.ts
Fix: #3471 
We should cache the return value from the default factory to avoid unnecessary watcher triggering, which is what Vue2 does.
=> fix(runtime-core): cache the value returned from the default factory to avoid unnecessary watcher trigger

packages/reactivity/src/index.ts, packages/reactivity/src/reactive.ts, packages/runtime-core/src/componentPublicInstance.ts, test-dts/defineComponent.test-d.tsx
=> types: the data type of the public instance should be unwrapped

packages/runtime-core/__tests__/hydration.spec.ts, packages/runtime-core/src/hydration.ts
=> fix(hydration): vnode is of Text type and with empty text should be skipped when hydrateChildren

packages/runtime-core/__tests__/hmr.spec.ts, packages/runtime-core/src/components/Teleport.ts
=> fix(Teleport): fallback to non-optimized mode when HRM performing updates

packages/reactivity/__tests__/readonly.spec.ts, packages/reactivity/__tests__/shallowReactive.spec.ts, packages/reactivity/__tests__/shallowReadonly.spec.ts, packages/reactivity/src/baseHandlers.ts, packages/reactivity/src/reactive.ts
This fixes #2843
We currently track reactive proxies in one WeakMap, not differentiating between normal and shallow Proxies. the same is true for readonly proxies.
This means that for each target, only one kind of proxy can be created, because we use these WeakMaps to re-use existing proxies for each known target. 
```js
const target = { some: 'value' }
const normalProxy = reactive(target)
const shallowProxy = shallowReactive(target)
expect(normalProxy).not.toBe(shallowProxy)
```
The above test fails - `shallowProxy` will in fact be the same proxy as `normalProxy`.
This PR adds separate WeakMaps to track shallow Proxies on their own, which makes the above test pass.
=> fix(reactivity): ensure that shallow and normal proxies are tracked seperately (close #2843)

packages/compiler-core/src/parse.ts
If slot name is part of `v-slot`, `indexOf` get incorrect source location range, for example:
```
<template v-slot:slo />
^^^
```
=> fix(compiler-core): fix slot source location

packages/runtime-core/src/component.ts
While in `__dev__` mode `SetupContext` returns an additional `props` key which is not there when in production.
This PR brings the `SetupContext` object returned in `__dev__` mode inline what is returned in production and what is written in the docs.
`SetupContext` being the second argument when calling `setup()` or the result of calling `useContext()`.
=> fix(runtime-core): remove props from SetupContext while in __dev__ mode

packages/runtime-core/__tests__/components/Teleport.spec.ts, packages/runtime-core/src/renderer.ts
=> fix(runtime-core): avoid unmount teleport's children multiple times

packages/runtime-core/src/h.ts, packages/runtime-dom/types/jsx.d.ts, test-dts/functionalComponent.test-d.tsx, test-dts/tsx.test-d.tsx
JSX is compiled to `createVNode` calls, so should be compatible with functions that accept `VNode`. The functional component tests were invalid because components should return VNodes, I had to add `h` overloads for `Text` nodes to keep the same functionality.
=> fix(jsx): JSX.Element extends VNode

packages/reactivity/__tests__/effect.spec.ts, packages/reactivity/src/baseHandlers.ts
```js
import { reactive, toRaw, watchEffect } from 'vue'
const a = reactive({
a: 1,
})
const b = reactive({
b: 1,
})
const d = reactive([a, b])
watchEffect(() => {
console.log('d', d[0]) // Will consoled two times
})
d[0] = a
```
=> fix(baseHandlers): trigger will called two times when set the same proxy value

packages/runtime-core/src/apiDefineComponent.ts, packages/runtime-core/src/componentOptions.ts, test-dts/defineComponent.test-d.tsx
Fix: #3468
I noticed that when the mixins contain empty components:
```js
mixins: [
defineComponent({ methods: { foo() {} } }),
// empty component
defineComponent({})
]
})
```
Or they have the same type pattern:
```js
mixins: [
defineComponent({ props: [], methods: { foo() {} } }),
// props type are same
defineComponent({ props: [] })
]
})
```
Then the [Mixin type](https://github.com/vuejs/vue-next/blob/master/packages/runtime-core/src/apiDefineComponent.ts#L110) is not inferred as the Unions type of the two components. So my idea is to add a type-only differentiator to help infer the type of `Mixin`.
=> fix(types): add a type-only differentiator to assist Mixin's type infer

packages/compiler-core/__tests__/transforms/transformElement.spec.ts, packages/compiler-core/src/transforms/transformElement.ts
I was trying to make a transform that uses [`replaceNode`](https://github.com/vuejs/vue-next/blob/a8352506f6ee7fee784c47d2a6907071215602fc/packages/compiler-core/src/transform.ts#L189) to replace the `currentNode` with a new element node.
Since I pass in my transform in [`TransformOptions["nodeTransforms"]`](https://github.com/vuejs/vue-next/blob/67d1aac6ae683a3a7291dff15071d1eeacb7d22a/packages/compiler-core/src/options.ts#L143), it comes after all the transforms in [`BaseTransformPreset`](https://github.com/vuejs/vue-next/blob/5d825f318f1c3467dd530e43b09040d9f8793cce/packages/compiler-core/src/compile.ts#L25) which includes [`transformElement`](https://github.com/vuejs/vue-next/blob/a8352506f6ee7fee784c47d2a6907071215602fc/packages/compiler-core/src/transforms/transformElement.ts#L64). …
=> fix(transformElement): properly transform replaced nodes

packages/compiler-sfc/__tests__/__snapshots__/templateTransformSrcset.spec.ts.snap, packages/compiler-sfc/package.json, packages/compiler-sfc/src/templateTransformSrcset.ts
This pull requests fixes issues #3069, #1626 (as well as #1587) where the generated srcset would be invalid because the space between url and descriptor was missing. This PR aims at resolving this as it makes secret basically unusable.
The solution is to simply add a space in front and has already been used on [line 81](https://github.com/JonasKruckenberg/vue-next/blob/80a904e12517b1d594f6dab0f7bd14be2dbe6158/packages/compiler-sfc/src/templateTransformSrcset.ts#L81) so I think this should be really uncontroversial.
Cheers!
=> Fix missing whitespace issue in srcsets

packages/runtime-dom/src/modules/events.ts, packages/shared/src/index.ts
Fix: #3485
Find relevant information here https://github.com/erdong-fe/vue/commit/d3ce9d31221949cb367c38fa4c09dc3d2f6bef5c
I tested multiple scenarios in FF 52 and it works correctly
=> fix(runtime-dom): fix the event listeners call in firefox <= 53

packages/runtime-core/src/componentProps.ts
see https://www.measurethat.net/Benchmarks/Show/11546/0/fastfindindex
=> perf(runtime-core): optimize the performance of `getTypeIndex`

packages/sfc-playground/src/output/Output.vue
This commit is a super nit refactoring and introduces a more idiomatic way to declare the `Modes` type instead of copy/pasting the values.
As this code might be read as an example, it can help other developers to learn the right patterns.
=> refactor(sfc-playground): modes declaration

packages/runtime-core/__tests__/rendererOptimizedMode.spec.ts, packages/runtime-core/src/componentSlots.ts, packages/runtime-core/src/renderer.ts
=> fix(runtime-core): make manually written render function work with optimized slots

packages/runtime-core/src/renderer.ts
The parameter position of `mountChildren` is not consistent with other methods, which affects reading.
=> chore(runtime-core): change the position of the mountChildren parameter

packages/runtime-core/src/components/Teleport.ts
=> fix(Teleport): avoid changing the reference of vnode.dynamicChildren

packages/runtime-core/__tests__/hydration.spec.ts, packages/runtime-core/src/hydration.ts, packages/runtime-core/src/renderer.ts
Fix: #3560 
The root cause of #3560 is that during hydration, we will **wait for the async component to be resolved before creating a component instance for AsyncComponentWrapper**. This is the opposite of the client rendering order, that is, **create the instance for AsyncComponentWrapper first and then wait for the async component to be resolved**. This PR makes hydration consistent with the behavior of normal client rendering
=> fix(hydration): refactor async component hydration

packages/compiler-core/__tests__/transforms/__snapshots__/transformText.spec.ts.snap, packages/compiler-core/__tests__/transforms/transformText.spec.ts, packages/compiler-core/src/transforms/transformText.ts
=> fix(compiler-core): bail out to array children when the element has custom directives + only one text child node

packages/runtime-core/src/compat/globalConfig.ts, packages/runtime-core/src/componentOptions.ts, packages/shared/src/index.ts, packages/vue-compat/__tests__/global.spec.ts, packages/vue-compat/__tests__/options.spec.ts
Note: this fix does introduce some performance overhead to the hot-path, I've tried to negate it with a `__VUE_COMPAT__` check in `runLifecycleHook`.
Closes #3761
=> fix(compat): correctly merge lifecycle hooks when using Vue.extend (fix #3761)

packages/runtime-core/src/componentOptions.ts, packages/runtime-core/src/helpers/typeUtils.ts, test-dts/component.test-d.ts
A follow-up for https://github.com/vuejs/rfcs/pull/293.
=> fix(types): declared prop keys should always exist in `props` argument

package.json, yarn.lock
api-extractor 7.12.1 reports some warnings as following image
upgrade to 7.15.1 can fix it. api-extractor 7.12.1 depend on typescript 4.1.5, but vue-next and api-extractor 7.15.1 depend on typescript 4.2.*
there are some breaking changes,  typescript 4.1.5  `lib.es2015.reflect.d.ts` vs. typescript 4.2.4 `lib.es2015.reflect.d.ts`
maybe another solution, remove ownKeys return-type 
``` diff
-  function ownKeys(target: object): (string | symbol)[] {
+ function ownKeys(target: object) {
track(target, TrackOpTypes.ITERATE, isArray(target) ? 'length' : ITERATE_KEY)
return Reflect.ownKeys(target)
}
```
=> chore: bump api-extractor from 7.12.1 to 7.15.1

packages/runtime-core/src/componentProps.ts, test-dts/defineComponent.test-d.tsx
fix #3782
Allows `default:undefined` on prop types
=> types(props): Support `undefined` as default

packages/compiler-sfc/src/compileScript.ts
Discussed in https://github.com/vuejs/vue-next/pull/3823#discussion_r637833019
=> fix(compiler-sfc): support tsx in setup script

packages/runtime-dom/types/jsx.d.ts
fix #3788
Improve some of the types, most of the types had `number`  which is not valid HTML, all the `number` attributes should be valid string
```html
<textarea cols="3"/>
```
Also: 
- replaced all `boolean | 'false' | 'true'` to be `Booleanish`
- added to `capture` keywords: "The attribute's keywords are `user` and `environment`" [The capture attribute](https://www.w3.org/TR/html-media-capture/#the-capture-attribute)
=> types(jsx): improve type for number attributes

packages/reactivity/src/ref.ts
I'm use `readonly()` and pass a `Ref` type param, it will cause `error TS4058` when I build it.
=> fix(types/reactivity): error TS4058 caused by `RefSymbol`

packages/runtime-core/src/componentRenderContext.ts, packages/runtime-core/src/componentSlots.ts
=> fix(runtime-core): avoid the proxy object polluting the slots of the internal instance

packages/runtime-core/__tests__/components/KeepAlive.spec.ts, packages/runtime-core/src/apiAsyncComponent.ts, packages/runtime-core/src/componentOptions.ts, packages/runtime-core/src/components/KeepAlive.ts
=> fix(KeepAlive): should work with async component

packages/runtime-core/__tests__/rendererOptimizedMode.spec.ts, packages/runtime-core/src/compat/instance.ts, packages/runtime-core/src/compat/renderFn.ts, packages/runtime-core/src/componentRenderContext.ts, packages/runtime-core/src/componentSlots.ts, packages/runtime-core/src/helpers/renderSlot.ts, packages/runtime-core/src/vnode.ts
Fix: #3548 
**Edit:**
Also fix #3569, at first I tried to fix issue #3569 in another independent PR(https://github.com/vuejs/vue-next/pull/3573), and then I realized the strong coupling between issue #3548 and issue #3569, so I merged them into this one PR.
Issue #3569 is another problem caused by the mixed-use of optimization mode and manual render function, technically, the user can get any VNode in the manually written render function, e.g.
```js
setup(props, { slots }) {
const index = ref(100)
return () => {
// get any vnode
return slots.foo()[3].children[index.value]
}
}
```
Suppose the initial value of `index` is 100, and then it becomes `999`, then the old and new subTree may be:
```js
// old
{ type: 'div', dynamicChildren: [vnode1, vnode2] }
// new
{ type: 'div', dynamicChildren: …
```
=> fix(runtime-core): should not track dynamic children when the user calls a compiled slot inside template expression

packages/runtime-core/__tests__/rendererOptimizedMode.spec.ts, packages/runtime-core/src/vnode.ts
=> fix(runtime-core): treat slots manually written by the user as dynamic

packages/runtime-core/__tests__/directives.spec.ts, packages/runtime-core/src/directives.ts
=> fix(runtime-core): should disable tracking inside directive lifecycle hooks

packages/runtime-core/__tests__/rendererComponent.spec.ts, packages/runtime-core/src/vnode.ts
=> fix(runtime-core): the component VNode should be cloned when reusing it

packages/compiler-core/__tests__/utils.spec.ts, packages/compiler-core/src/utils.ts
=> fix(compiler-core): improve the isMemberExpression function

packages/runtime-core/__tests__/rendererAttrsFallthrough.spec.ts, packages/runtime-core/src/component.ts, packages/runtime-core/src/componentOptions.ts, packages/runtime-core/src/componentRenderUtils.ts, packages/server-renderer/src/render.ts
=> fix(runtime-core): fix resolving inheritAttrs from mixins

packages/runtime-dom/__tests__/patchProps.spec.ts, packages/runtime-dom/src/modules/props.ts
See https://github.com/vuejs/vue-next/issues/3475#issuecomment-805671304.
=> fix(runtime-dom): should remove attribute when binding `null` to `value`

packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap, packages/compiler-sfc/__tests__/compileScript.spec.ts, packages/compiler-sfc/src/compileScript.ts
=> fix(compiler-sfc): correctly remove parens used for wrapping

packages/reactivity/src/ref.ts
RefImpl Doesn't seem to need default value,  createRef already guaranteed to it have a value
=> chore(reactivity): RefImpl _shallow default value

packages/runtime-core/__tests__/apiInject.spec.ts, packages/runtime-core/src/apiInject.ts
This PR fixes the issue #3923.
I added a regression test. I'm not familiar with this code base especially how you normally type things.
Let me know if you need me to modify anything.
=> fix(runtime-core): bind default function of inject to instance (fix #3923)

packages/runtime-core/src/components/Suspense.ts, packages/vue/__tests__/Transition.spec.ts
=> fix(Suspense): fallback should work with transition

packages/runtime-core/__tests__/components/Suspense.spec.ts, packages/runtime-core/src/components/Suspense.ts
=> fix(suspense): emit initial fallback and pending

packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap, packages/compiler-sfc/__tests__/compileScript.spec.ts, packages/compiler-sfc/src/compileScript.ts, packages/runtime-core/__tests__/apiSetupHelpers.spec.ts, packages/runtime-core/src/apiSetupHelpers.ts, packages/runtime-core/src/index.ts, packages/sfc-playground/src/codemirror/CodeMirror.vue, test-dts/setupHelpers.test-d.ts
Based on https://github.com/vuejs/rfcs/pull/243 and the 3 other repeated PRs. I'm proposing to deprecate `defineEmit` in favour of `defineEmits` as defined in the RFC and to match the `emits` option as well as the plural of `defineProps`
Even though the we are defining the `emit` type of the context option in `setup(props, { emit })`, it seems more idiomatic to make it plural to match `defineProps`
=> feat(sfc): add defineEmits and deprecate defineEmit

packages/reactivity/src/computed.ts, packages/reactivity/src/effect.ts, packages/reactivity/src/reactive.ts, packages/reactivity/src/ref.ts
New PR created, see https://github.com/vuejs/vue-next/pull/2345.
=> feat(reactivity): ref-specific track/trigger and miscellaneous optimizations

packages/reactivity/__tests__/computed.spec.ts, packages/reactivity/__tests__/effect.spec.ts, packages/reactivity/__tests__/readonly.spec.ts, packages/reactivity/src/computed.ts, packages/reactivity/src/effect.ts, packages/reactivity/src/index.ts, packages/runtime-core/__tests__/scheduler.spec.ts, packages/runtime-core/src/apiWatch.ts, packages/runtime-core/src/compat/global.ts, packages/runtime-core/src/component.ts, packages/runtime-core/src/renderer.ts, packages/runtime-core/src/scheduler.ts
Based on #2345 , but with smaller API change
- Use class implementation for `ReactiveEffect`
- Switch internal creation of effects to use the class constructor
- Avoid options object allocation
- Avoid creating bound effect runner function (used in schedulers) when not necessary. Only component update effects will need to create a bound copy of the runner.
Consumes ~17% less memory compared to last commit (which already improved the memory usage a bit) when creating computed/watch/watchEffect (image showing benchmark of creating 10k each).
Introduces a very minor breaking change: the `scheduler` option passed to `effect` no longer receives the runner function. Instead, simply call the reference of the returned runner:
```js
const run = effect(() => {}, {
scheduler: () => {
run()
}
})
```
=> perf(reactivity): improve reactive effect memory usage

packages/runtime-core/src/componentProps.ts
IDE features like find references / renaming... not working with `RequiredKeys<O>`, `OptionalKeys<O>` object keys types, this PR add `[K in keyof O]` to patch this problem.
Problems:
- Not sure `unknown` type has consistency behavior with some special tsconfig.json settings.
=> feat(types): support renaming for props

packages/runtime-dom/types/jsx.d.ts
`StringKeyOf` seem has no practical effect, unused it to support find definition for jsx tags and events in IDE.
=> feat(types): support find definition for jsx tags, events

packages/runtime-core/src/index.ts, test-dts/setupHelpers.test-d.ts
Cant import useAttrs and useSlots from ”vue“ in my program，because there is no export of useAttrs and useSlots.
=> fix(runtime-core): add useAttrs and useSlots export

packages/runtime-core/__tests__/apiExpose.spec.ts, packages/runtime-core/src/componentPublicInstance.ts
The instances provided by `$parent` and `$root` when dealing with a `$parent` or `$root` that used the 'expose(...)' function do not not return the `ExposeProxy`, thus no Vue public `$` getters are accessible on these objects.
This PR returns that functionality.
=> fix(runtime): Addressed issue with $parent chain when using expose()

packages/runtime-core/src/compat/compatConfig.ts
Without this change components that do no define any props can see problems when logging a v-model related `@vue/compat` warning. This can be see in the `AsyncComponentWrapper` below.
=> fix(runtime): Fix logic check verifying props existence for v-model compat warning.

packages/reactivity/__tests__/effect.spec.ts, packages/reactivity/src/Dep.ts, packages/reactivity/src/computed.ts, packages/reactivity/src/effect.ts, packages/reactivity/src/ref.ts, packages/runtime-core/src/renderer.ts
Currently for every effect run, all existing dependencies are first cleaned up and then retracked. This involves Set additions and removals. In many cases, dependencies rarely change so we already discussed that there was room for optmization here (https://github.com/vuejs/vue-next/pull/2345#issuecomment-727200679).
This PR optimizes re-tracking of effect dependencies.
It uses markers which identify whether a dependency is new, stable or old. Because effect execution/tracking may be recursive, the markers are actually bitwise and support up to 30 levels deep (the amount of bits we can safely use for a SMI small integer). When the depth is more than 30 levels (notice that this is unlikely to occur), the 'old' full cleanup method is used instead. 
Notice that this optimization, unlike the …
=> feat(reactivity): bitwise dep markers to optimize re-tracking

packages/runtime-dom/__tests__/helpers/useCssVars.spec.ts, packages/runtime-dom/src/helpers/useCssVars.ts
=> fix(runtime-dom): useCssVars work with static vnode

packages/shared/__tests__/__snapshots__/codeframe.spec.ts.snap, packages/shared/__tests__/codeframe.spec.ts, packages/shared/src/codeframe.ts
The generateCodeFrame function had the chance to infinite loop on windows machines due to how newline sequence lengths were being treated.
Newline sequence lengths were assumed to be a single character long which is not true on windows machines.
closes #3987
=> fix(compiler): Addressed infinite loop in compiler

packages/reactivity/src/ref.ts, test-dts/component.test-d.ts
fix #3990
`ShallowUnwrapRef` was not handling the `Ref<T>|undefined` type
Minimal repro
```ts
setup() {
return {
a: undefined as Ref<number> | undefined
}
},
methods: {
test() {
// @ts-expect-error `a` should not be a ref
this.a?.value
}
}
})
```
=> types(defineComponent): fix unwrap when returning `Ref<T>|undefined` from `setup`

packages/runtime-dom/__tests__/patchProps.spec.ts, packages/runtime-dom/src/modules/props.ts
=> fix(runtime-dom): capture errors when setting value for IDL

packages/compiler-sfc/__tests__/__snapshots__/cssVars.spec.ts.snap, packages/compiler-sfc/__tests__/cssVars.spec.ts, packages/compiler-sfc/src/cssVars.ts
When the same css var was used multiple times in <style>, that var was injected several times in the <script>
For the added test case it was generating
```js
_useCssVars(_ctx => ({
"xxxxxxxx-color": (color),
"xxxxxxxx-color": (color)
}))
```
This PR removes duplicated vars in `parseCssVars` so we get
```js
_useCssVars(_ctx => ({
"xxxxxxxx-color": (color)
}))
```
=> fix(compiler-sfc): duplicated injected css var with repeated vars

packages/compiler-core/__tests__/transforms/vModel.spec.ts, packages/compiler-core/__tests__/transforms/vOn.spec.ts, packages/compiler-core/__tests__/transforms/vOnce.spec.ts, packages/compiler-core/src/transform.ts, packages/compiler-core/src/transforms/vModel.ts, packages/compiler-core/src/transforms/vOn.ts, packages/compiler-core/src/transforms/vOnce.ts
`
// <div v-once><div @click="handleClick" /></div>
`
when cacheHandlers is true,the handleClick will be compiled into this:
`
onClick: _cache[1] || (_cache[1] = (...args) => (_ctx.handleClick && _ctx.handleClick(...args)))
`
but when it inside v-once, this is enough because external div will be cached.
`
onClick: _ctx.handleClick
`
This PR will solve the problem,  reduce the size of the output code.
=> chore(compiler-core): reduce unnecessary cache inside v-once

packages/sfc-playground/src/Message.vue, packages/sfc-playground/src/codemirror/CodeMirror.vue
Importing `defineEmits` and `defineProps` is no longer needed since v3.1.3
=> chore(sfc-playground): remove compiler macro imports

packages/shared/src/domTagConfig.ts
remove deprecated tag : hgroup、rtc
detail see : [Obsolete and deprecated elements
](https://developer.mozilla.org/en-US/docs/Web/HTML/Element#obsolete_and_deprecated_elements)
=> chore(shared): html tags

packages/compiler-core/__tests__/parse.spec.ts, packages/compiler-core/src/options.ts, packages/compiler-core/src/parse.ts
Close: #3392
Replace: #3395
This PR does not change any default behavior, but allows the `comments` option to fully control comment nodes.
=> feat(compiler): Allow 'comments' option to effect comment inclusion in development

packages/shared/src/index.ts
since `x !== x`  is the only true when x is `NaN` , so that indicate the `oldValue` and the `value` are both `NaN`
so remain one is fine
=> chore(shared): remove extra NaN logic

packages/compiler-sfc/__tests__/parse.spec.ts, packages/compiler-sfc/src/parse.ts
The current implementation ignores `<script/>` and `<styles/>` but not empty blocks like `<script>  \n\t</script>`.
This results in unnecessary code generated for a component when these blocks are actually empty.
This commit filters such nodes in the SFC compiler, resulting in less code generated.
For example, this component:
```vue
<template>
<h1>{{ msg }}</h1>
</template>
<script setup>
</script>
<style scoped>
</style>
```
currently produces:
```js
/* Analyzed bindings: {} */
import { toDisplayString as _toDisplayString, openBlock as _openBlock, createBlock as _createBlock, withScopeId as _withScopeId } from "vue"
const _withId = /*#__PURE__*/_withScopeId("data-v-f13b4d11")
const __sfc__ = {
expose: [],
setup(__props) {
return /*#__PURE__*/_withId((_ctx, _cache) => {
return …
```
=> feat(compiler-sfc): ignore empty blocks

.prettierrc, package.json, packages/runtime-core/src/apiDefineComponent.ts, packages/runtime-core/src/componentEmits.ts, packages/runtime-core/src/componentOptions.ts, test-dts/defineComponent.test-d.tsx, yarn.lock
=> feat(types): add defined emits to props

packages/sfc-playground/src/output/moduleCompiler.ts
[fix issue: vite #4049](https://github.com/vitejs/vite/issues/4049)
[align behavior with vite #4053](https://github.com/vitejs/vite/pull/4053)
[Reproduction link](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgaGVsbG8gZnJvbSAnLi9oZWxsby5qcydcbmNvbnNvbGUubG9nKGhlbGxvKVxuY29uc3QgbXNnID0gJ0hlbGxvIFdvcmxkISdcbjwvc2NyaXB0PiIsImhlbGxvLmpzIjoiZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gaGVsbG8oKSB7XG4gIHJldHVybiAxMjM0O1xufVxuXG5jb25zb2xlLmxvZyh0eXBlb2YgaGVsbG8pO1xuXG5oZWxsby50ZXN0ID0gMTIzNDsifQ==)
=> fix(sfc-playground): Transform named default exports without altering scope

packages/runtime-core/src/scheduler.ts
These assertions are unnecessary
=> refactor(scheduler.ts): remove unnecessary assertions

packages/compiler-sfc/__tests__/__snapshots__/cssVars.spec.ts.snap, packages/compiler-sfc/__tests__/cssVars.spec.ts, packages/compiler-sfc/src/cssVars.ts
=> fix(cssVars): should ignore comments when parseCssVars

packages/compiler-sfc/__tests__/__snapshots__/cssVars.spec.ts.snap, packages/compiler-sfc/__tests__/cssVars.spec.ts, packages/compiler-sfc/src/cssVars.ts
=> fix(cssVars): improve ignore style variable bindings in comments

packages/vue-compat/LICENSE
The vue-compat package was added after #2857 ensured that every package
has a LICENSE file
=> fix: Add LICENSE file for vue-compat (#2650)

packages/reactivity/src/reactive.ts, packages/reactivity/src/ref.ts
Using `UnwrapRef` in `UnwrapNestedRefs` is actually redundant, direct use of `UnwrapRefSimple` can reduce the level.
=> types(reactivity): simplify the UnwrapNestedRefs

packages/reactivity/__tests__/effectScope.spec.ts, packages/reactivity/src/effectScope.ts
When you create a nested effectScope, and then stop it, it will still be referenced by the parent. Causing memory leaks.
One of the mean features (for me at least) of effectScopes is the ability to prevent memory leaks when using it outside of the normal component context. After testing 3.2-beta I realized that my scope/effects were still leaking due to the parent scope still holding a reference after stopping it.
This PR solves this issue without (significant) memory or performance impact on normal (not nested) scopes. It simply reuses the slot in the effects array to dereference efficiently in O(1).
=> feat(effectScope): dereference child from parent after stop to prevent memleaks

packages/server-renderer/package.json
Scope of changes:
Add ESM as a build target for `@vue/server-renderer`
Reasoning:
I'm trying to fix [Vue compatibility with Astro](https://github.com/snowpackjs/astro/issues/182), which is build on top of Snowpack, so build tool that doesn't like non-ESM sources, and that causes issues with code duplication and breaking solutions based on being singletons, like [`currentRenderingInstance`](https://github.com/vuejs/vue-next/blob/1867591e7c54406e92575753dd77fffba17606a2/packages/runtime-core/src/componentRenderContext.ts#L9), that leads to errors while trying to render nested components.
Exposing this package as ESM is probably the simplest way to solve that problem, and from what I see some changes in this area was already made, for example …
=> build(server-renderer): Add ESM as a build target

packages/shared/__tests__/toDisplayString.spec.ts, packages/shared/src/toDisplayString.ts
Vue 2 did this, but this functionality was quietly removed
from Vue 3 as a side effect of 3c60d40827f65cbf.
Closes #3944.
=> fix(shared): support custom .toString() in text interpolation again

packages/reactivity/src/computed.ts, test-dts/defineComponent.test-d.tsx
=> fix(types): fix `this` type broken in computed options

packages/runtime-dom/src/index.ts
When using browsers not support the **shadowRoot** interface, this would throw `invalid 'instanceof' operand type` error because the window.shadowRoot got undefined.
So i add a defensive code here.
=> fix(warn): skip ShadowRoot check on unsupported platforms

packages/runtime-core/src/components/KeepAlive.ts, packages/runtime-core/src/renderer.ts, packages/runtime-core/src/vnode.ts
[#4240](https://github.com/vuejs/vue-next/issues/4240)
3.2.0-beta.7
[Reproduction link](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8dWw+XG4gICAgPGxpIHYtZm9yPVwiKGl0ZW0sIGkpIGluIGxpc3RcIiA6a2V5PVwiaXRlbS5zeW1ib2xcIiB2LWh0bWw9XCJpdGVtLnRpdGxlXCI+PC9saT5cbiAgPC91bD5cblxuICA8dWw+XG4gICAgPGxpIHYtZm9yPVwiKGl0ZW0sIGkpIGluIGxpc3RcIiA6a2V5PVwiaVwiIHYtaHRtbD1cIml0ZW0udGl0bGVcIj48L2xpPlxuICA8L3VsPlxuXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuY29uc3QgbGlzdCA9IFtcbiAgeyBzeW1ib2w6IFN5bWJvbCgpLCB0aXRsZTogJ0EnIH0sXG4gIHsgc3ltYm9sOiBTeW1ib2woKSwgdGl0bGU6ICdCJyB9LFxuICB7IHN5bWJvbDogU3ltYm9sKCksIHRpdGxlOiAnQycgfSxcbl07XG5cbi8vIFdoZW4gd2UgYXJlIHVzaW5nIDprZXk9XCJpXCIgaW4gdGhlIHRlbXBsYXRlLCB0aGUgZm9sbG93aW5nIGFjdGlvbnMgd2lsbCByZXVzZSBET00gZWxlbWVudHMgaW5jb3JyZWN0bHk6XG5cbi8vIFRoa …
=> updated typing of key in VNodeProps (fix #4240)

packages/server-renderer/README.md, packages/server-renderer/src/renderToStream.ts
Fixing the typo is pretty self explanatory, but the Cloudflare Workers doc change needs a little more explanation:
Unfortunately, Cloudflare Workers does not expose the `ReadableStream` constructor, which means it's not as simple as `return new Response(renderToWebStream(app))` here.
There are ways to get this to work in Cloudflare Workers via ponyfill-ing `ReadableStream`, and then manually writing back to a `TransformStream` which is available in their environment, and ends up looking something like this:
```js
...
import {ReadableStream as polyReadableStream} from 'web-streams-polyfill/dist/ponyfill.es2018.mjs';
async function pipeReaderToWriter(reader, writer){
const encoder = new TextEncoder();
for(;;){
const {value, done} = await reader.read();
const encoded = encoder.encode(value); …
```
=> docs(server-renderer) fix typo in `renderToWebStream` error, and remove Cloudflare Worker reference

packages/compiler-dom/src/transforms/stringifyStatic.ts
Looks like this slipped into the 3.2 release @yyx990803
=> Remove left over debugger line

packages/runtime-dom/__tests__/patchAttrs.spec.ts, packages/runtime-dom/src/patchProp.ts
=> fix(runtime-dom): patch `textContent` on svg properly

packages/shared/__tests__/toDisplayString.spec.ts, packages/shared/src/toDisplayString.ts
fix: https://github.com/vuejs/vue-next/issues/4334 
fix for the case object without `toString`  for example: 
```js
let obj = Object.create(null)  // typeof  is Object, however it will not have toString in prototype chain
``` 
handle the case that `toString` is non invokable, and use the JSON formatter for that case
```js
let obj = {a:1, toString: 'bar')
```
improving on: https://github.com/vuejs/vue-next/pull/4335
=> fix(shared): toDisplayString toString override support

packages/runtime-core/__tests__/apiAsyncComponent.spec.ts, packages/runtime-core/src/renderer.ts
=> fix(runtime-core): vnode hooks should not be called on async wrapper

packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap, packages/compiler-sfc/__tests__/compileScript.spec.ts, packages/compiler-sfc/src/compileScript.ts
=> fix(compiler-sfc): defineProps generates unnecessary array of same types

packages/compiler-ssr/__tests__/ssrElement.spec.ts, packages/compiler-ssr/__tests__/ssrVModel.spec.ts, packages/compiler-ssr/src/runtimeHelpers.ts, packages/compiler-ssr/src/transforms/ssrTransformElement.ts, packages/runtime-dom/__tests__/patchAttrs.spec.ts, packages/runtime-dom/__tests__/patchProps.spec.ts, packages/runtime-dom/src/modules/attrs.ts, packages/runtime-dom/src/modules/props.ts, packages/server-renderer/__tests__/ssrRenderAttrs.spec.ts, packages/server-renderer/src/helpers/ssrRenderAttrs.ts, packages/server-renderer/src/index.ts, packages/shared/src/domAttrConfig.ts
TLDR; Boolean attributes do not handle falsy values consistently. The same value does not always lead to the same result, depending on other factors. This only impacts certain edge cases involving `0`, `NaN` and `''`. More common values, such as `false`, `null` and `undefined`, are not affected.
The origin of this PR is an issue we received in the docs repo: https://github.com/vuejs/docs/issues/1173. I believe this is a bug rather than a documentation problem.
For most boolean attributes (e.g. `checked`, `disabled`), the attribute is set via its corresponding property. An empty string is handled specially and is treated as `true`. Otherwise, usual JS truthy/falsy rules apply.
However, some boolean attributes need to be handled specially because their property names aren't in lower-case. …
=> fix(shared): consistently remove boolean attributes for falsy values

packages/reactivity/__tests__/effectScope.spec.ts, packages/reactivity/src/effectScope.ts
`onDispose` looks like a typo to me, as there's no other reference to this name in the codebase
=> chore: rename `onDispose` to `onScopeDispose` in warnings and tests

packages/compiler-ssr/src/transforms/ssrTransformSuspense.ts, packages/runtime-core/src/component.ts, packages/runtime-core/src/componentOptions.ts, packages/runtime-dom/src/directives/vOn.ts, packages/vue/__tests__/e2eUtils.ts
remove unnecessary type assertions
=> chore(types): remove unnecessary type assertions

packages/compiler-sfc/src/compileScript.ts
https://github.com/vuejs/vue-next/blob/57f10812cc7f1e9f6c92736c36aba577943996fd/packages/compiler-sfc/src/compileScript.ts#L202-L213
The judgment conditions on lines 202 and 204 are duplicated, remove duplicate  `cssVars.length`
=> refactor(compiler-sfc): remove duplicate judgment conditions

packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap, packages/compiler-sfc/__tests__/compileScript.spec.ts, packages/compiler-sfc/src/compileScript.ts
fix: https://github.com/vuejs/vue-next/issues/4371
=> fix(compiler-sfc):   fix 'export    default' with extra spaces  transformation

packages/runtime-core/src/componentProps.ts, test-dts/defineComponent.test-d.tsx
=> types(PropType): Allow `undefined` function to be used on `PropType`

packages/compiler-core/__tests__/utils.spec.ts, packages/compiler-core/src/utils.ts
see issue #4422  
If component name is not strict, the generated render function will not run. 
We can solve this edge case by adding an unique identifier on specific `validAssetId`.
Close #4422
=> fix(compiler-core): adding identifier on validAssetId if variable `name` has specific character

package.json
As some packages rely on the experimental "stream/web" package only available in node v16.5+,
this commit updates the `engines` property to reflect that.
https://nodejs.org/en/blog/release/v16.5.0/
=> chore: set node engine to v16

jest.config.js, package.json, packages/vue-compat/__tests__/instance.spec.ts, packages/vue/examples/__tests__/grid.spec.ts, yarn.lock
Updates jest and ts-jest to v27, as jest v27.1.0 includes a necessary fix to unblock further work on spying issues.
See https://github.com/facebook/jest/pull/11721
=> chore(deps): update jest to v27

packages/runtime-core/src/apiAsyncComponent.ts
At the definition of this function, we wanna the type of the return value of this function is `T`. So I change the type assertion from `any` to `T`.
=> refactor(runtime-core): improve the type of defineAsyncComponent

packages/compiler-core/src/parse.ts
CDATA only ends with `]]>`, we can skip `<` or `{{`. This can save us
several TEXT node generation.
=> refactor(compiler): refine CDATA endTokens

packages/compiler-sfc/__tests__/__snapshots__/compileScriptRefTransform.spec.ts.snap, packages/compiler-sfc/__tests__/compileScriptRefTransform.spec.ts, packages/ref-transform/src/refTransform.ts
=> fix(refSugar): should transform $ref when used in typed declaration

packages/runtime-core/src/components/Suspense.ts
We want to create a commet node  at [here](https://github.com/vuejs/vue-next/pull/4451/files#diff-069bd39ee093a8545c4e26aa7264c6ba4561a28f07f3d7d7080f4c0f71710281L723) but forget to import the `Comment` symbol. The Comment constructor from dom has been used, then we get the error:
=> fix: misuse Dom's Comment element constructor as a vnode type

packages/compiler-core/__tests__/transforms/transformElement.spec.ts, packages/compiler-core/src/transforms/transformElement.ts
https://github.com/vuejs/vue-next/issues/4431#issuecomment-911308513
fix: #4431
=> fix(compiler): generate function ref for script setup if inline is true

packages/ref-transform/__tests__/refTransform.spec.ts, packages/ref-transform/src/refTransform.ts
=> fix(ref-transform): not transform the prototype attributes.

packages/compiler-sfc/__tests__/compileScript.spec.ts, packages/compiler-sfc/src/compileScript.ts
=> fix(compile-sfc): generate setup prop type format error

packages/compiler-core/src/transforms/transformExpression.ts, packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap, packages/compiler-sfc/__tests__/compileScript.spec.ts, packages/compiler-sfc/src/compileScript.ts, packages/runtime-core/src/apiSetupHelpers.ts
=> fix(compiler-sfc): properly handle assignment expressions with local vars in inline mode

packages/runtime-core/src/componentProps.ts, test-dts/defineComponent.test-d.tsx
=> fix(type): fix prop type infer

rollup.config.js
https://github.com/vuejs/vue-next/commit/f2fb8a51a95ec28f34267c6e0ea85b30810409ea introduced change in rollup configuration  - `output.exports` for all packages was swapped from `auto` to `named` (to avoid warnings, I assume). Unfortunately this [broke](https://github.com/vuejs/vue-test-utils-next/runs/3437177804?check_suite_focus=true#step:7:12) `vue-compat` commonJS package where single default export is **expected** to be spreaded so `@vue/compat` will be a drop-in replacement for `vue`. 
Now, for example, when you require `@vue/compat` in node.js environment (for example when running vue-test-utils) you need to access `defineComponent` as `require('@vue/compat').default.defineComponent` instead of `require('@vue/compat').defineComponent`
Since `@vue/compat` is expected to serve as …
=> fix(build): build vue-compat in default exports mode

packages/compiler-core/__tests__/__snapshots__/parse.spec.ts.snap, packages/compiler-core/src/parse.ts
Example: 
`<div :[miss="exp"/>` compiles to `[mis]` instead of `[miss]`
[Vue template compiler link](https://vue-next-template-explorer.netlify.app/#%7B%22src%22%3A%22%3Cdiv%20%5B%20%3A%5Bmiss%3D%5C%22exp%5C%22%2F%3E%22%2C%22ssr%22%3Afalse%2C%22options%22%3A%7B%22mode%22%3A%22function%22%2C%22filename%22%3A%22Foo.vue%22%2C%22prefixIdentifiers%22%3Afalse%2C%22hoistStatic%22%3Afalse%2C%22cacheHandlers%22%3Afalse%2C%22scopeId%22%3Anull%2C%22inline%22%3Atrue%2C%22ssrCssVars%22%3A%22%7B%20color%20%7D%22%2C%22compatConfig%22%3A%7B%22MODE%22%3A3%7D%2C%22whitespace%22%3A%22condense%22%2C%22bindingMetadata%22%3A%7B%22TestComponent%22%3A%22setup%22%2C%22foo%22%3A%22setup%22%2C%22bar%22%3A%22props%22%7D%2C%22optimizeImports%22%3Afalse%7D%7D)
=> fix(compiler): pick last char when dynamic directive doesn't close

packages/runtime-core/__tests__/apiCreateApp.spec.ts, packages/runtime-core/src/componentPublicInstance.ts
fix: https://github.com/vuejs/vue-next/issues/4532#issuecomment-917781706
=> fix(runtime-core): When __isScriptSetup is true, properties on setupState should not be proxied on ctx.

packages/compiler-core/__tests__/transforms/transformElement.spec.ts, packages/compiler-core/src/transforms/transformElement.ts
=> fix(compiler): add the judgment about setup-maybe-ref when generating function ref.

packages/compiler-core/__tests__/transforms/vOn.spec.ts, packages/compiler-core/src/transforms/vOn.ts
=> fix(compiler-core): v-on inline async function expression handler  #4568 

packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap, packages/compiler-sfc/__tests__/compileScript.spec.ts, packages/compiler-sfc/src/compileScript.ts
=> fix(compile-sfc):  add symbol judge in prop type checks.

packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap, packages/compiler-sfc/__tests__/compileScript.spec.ts, packages/compiler-sfc/src/compileScript.ts
empty strings could trip up usage detection in templates during `script setup` compilation.
fix #4599
=> fix(compiler-sfc): Handle empty strings during template usage analysis of setup bindings. (fix #4599)

packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap, packages/compiler-sfc/__tests__/compileScript.spec.ts, packages/compiler-sfc/src/compileScript.ts
=> fix(compiler-sfc): support nested await statements

packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap, packages/compiler-sfc/__tests__/compileScript.spec.ts, packages/compiler-sfc/src/compileScript.ts
=> fix(sfc): recognizes exported vars in normal script

packages/compiler-core/__tests__/transforms/transformSlotOutlet.spec.ts, packages/compiler-core/src/transforms/transformSlotOutlet.ts
This patch fix the duplicated default props in`renderSlot` code generation and simplifies the logic by splicing a default argument array.
[Minimal reproduction](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8c2xvdD5mYWxsYmFjazwvc2xvdD5cbjwvdGVtcGxhdGU+XG48c3R5bGUgc2NvcGVkPnB7fTwvc3R5bGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0ifQ==)
`renderSlot` takes at most 5 arguments but the compiler generates 6. 
Note the last argument `true` should follow immediately after the fallback function. 
It looks like an accidental bug that default `slotProps` is pushed twice when children are defined and SFC has no slotted selector. 
Instead we can provide a default arg array, set arguments in their position if defined, and finally splice the array to remove unused args.
=> fix(compiler-core): dedupe renderSlot's default props

packages/runtime-core/src/apiWatch.ts
Ref: https://github.com/vuejs/vue-next/commit/2937530beff5c6bb57286c2556307859e37aa809#diff-59e3ee98b310f26c42283eaed3c0d4b53eee884d097d9fa89b7e1b546453b411
Actually, I'm not sure the thoughts behind the above refactoring, my guess is to delay initialization for better performance. If so, this PR is necessary.
=> fix(watch): remove redundant parameter default value

packages/compiler-core/src/transforms/transformElement.ts
[Minimal Repro](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmxldCBmID0gKCkgPT4gYWxlcnQoXCJjYWxsZWRcIilcbjwvc2NyaXB0PlxuPHRlbXBsYXRlPlxuICA8cCBvbmNsaWNrPVwiZlwiIDpvbmNsaWNrPVwiZlwiIHYtYmluZDpvbmNsaWNrPVwiZlwiPiBvbmNsaWNrPC9wPlxuICA8cCBvbkNsaWNrPVwiZlwiIDpvbkNsaWNrPVwiZlwiIHYtYmluZDpvbkNsaWNrPVwiZlwiPm9uQ2xpY2s8L3A+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59In0=)
Users can provide :onClick as event handler since vnode structure is flat. However, only /^on[^a-z]/ is accepted as event pros and props like `onclick` are bogus.
This fix makes dedupeProperties consistent with the runtime.
=> fix(compiler-core): only merge true handlers

packages/runtime-core/__tests__/hydration.spec.ts, packages/runtime-core/src/hydration.ts
=> fix(runtime-core): errorHandler should work when hydrated.

packages/compiler-ssr/src/transforms/ssrTransformTransitionGroup.ts
chore: fix docs typo in ssrTransformTransitionGroup.ts
=> chore: fix docs typo ssrTransformTransitionGroup.ts

packages/runtime-core/__tests__/apiExpose.spec.ts, packages/runtime-core/src/apiCreateApp.ts
When using `expose` or `defineExpose`, the 'public' instance (`exposeProxy`) is used for template refs, `$parent` and `$root`. The instance returned by `mount` is currently still the internal instance.
```js
const vm = createApp({
setup(_, { expose }) {
expose({ a: 1 })
return () => h('div')
}
}).mount('#app')
console.log(vm.a) // undefined as vm is the internal instance
```
This PR changes `mount` to return the `exposeProxy`.
I couldn't find any mention of `mount` in either the RFC or the associated discussion thread:
* RFC: https://github.com/vuejs/rfcs/blob/master/active-rfcs/0042-expose-api.md
* Discussion: https://github.com/vuejs/rfcs/discussions/345
I'm assuming it was simply overlooked, but if there is a good reason why `mount` should return the internal instance then it should …
=> fix(runtime-core): return the exposeProxy from mount

packages/compiler-core/__tests__/transforms/vIf.spec.ts, packages/compiler-core/src/errors.ts, packages/compiler-core/src/transforms/vIf.ts
When parsing template in case v-else-if is followed by v-else, there should be error msg.
=> fix(compiler-core): add check when v-else-if is behind v-else

packages/ref-transform/src/refTransform.ts
Although It is integrated in @vue/compiler-sfc.
But the package can be used standalone as a low-level library.
So I think it's better to warn by @vue/ref-transform.
=> chore: fix warning in ref-transform

packages/compiler-core/__tests__/transforms/vFor.spec.ts, packages/compiler-core/src/transforms/vFor.ts
` <template v-for="a in b" key="c"/>` should treat the `key` property as static string. But currently it is compiled to `_ctx.c` like expression.
[reproduction link](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8dGVtcGxhdGUgdi1mb3I9XCJhIGluIGJcIiBrZXk9XCJjXCI+XG4gICAgPHAvPlxuICA8L3RlbXBsYXRlPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59In0=)
=> fix(compiler-core): no prefixing on attribute key

packages/vue/package.json
After https://github.com/vuejs/vue-next/commit/570c955b4896db2e0deb46d3eb30bbc9eba7747b we now have a root-level `index.mjs`. But it's [not packaged](https://unpkg.com/browse/vue@3.2.18/) as it needs to be added to `files` array.
resolves https://github.com/vuejs/vue-next/issues/4677
=> chore(vue): package `index.mjs`

packages/server-renderer/__tests__/ssrCompilerOptions.spec.ts, packages/server-renderer/src/helpers/ssrCompile.ts
Currently, only the deprecated form of `isCustomElement` is respected when performing runtime template compilation with SSR. All other compiler options are ignored. e.g.:
```js
import { createApp } from "vue"
import { renderToString } from "@vue/server-renderer"
const app = createApp({
template: `<mjml></mjml>`
})
// This works, but it is deprecated and no other compilerOptions are respected
app.config.isCustomElement = tag => tag.startsWith('mj')
;(async () => {
const markup = await renderToString(app, {})
console.log(markup)
})()
```
This PR attempts to use `compilerOptions` consistently with other forms of template compilation.
Unresolved problems:
* ~~The cache does not take the options into consideration. It was already ignoring `isCustomElement` and I didn't want to expand the scope …
=> fix(server-renderer): respect compilerOptions during runtime template compilation

.github/contributing.md
docs: update link to nodejs.org to use https
=> docs: update link to nodejs.org to use https

packages/compiler-core/__tests__/utils.spec.ts, packages/compiler-core/src/parse.ts, packages/compiler-core/src/utils.ts, packages/compiler-dom/src/decodeHtml.ts, packages/global.d.ts, packages/sfc-playground/src/Header.vue, packages/shared/src/escapeHtml.ts
String.prototype.substr is deprecated.
`String.prototype.substr()` is defined in [Annex B](https://262.ecma-international.org/9.0/#sec-string.prototype.substr) of the ECMA-262 standard, whose [introduction](https://262.ecma-international.org/9.0/#sec-additional-ecmascript-features-for-web-browsers) states: "… Programmers should not use or assume the existence of these features and behaviours when writing new ECMAScript code. …"
=> chore: remove deprecated String.prototype.substr

.gitignore
Fixes #4837
(that ticket's been closed in the meantime, so I'll just copy-paste the description here)
Simple quality-of-life fix: Ignore intelliJ's workspace folder. intelliJ is my daily driver for working with code. Everytime I clone a repo and open up its contents in intelliJ, the IDE will automatically create the .idea folder for storing project-specific settings etc.
I'd rather not put .idea in my global git ignore since some projects prefer to deliberately add the workspace folders for sharing settings, live templates and stuff like that.
=> chore: Ignore .idea folder

packages/runtime-core/src/devtools.ts
fix: #4829 fix: #4738
Clear buffer after 3s once is not enough. When devtools is not installed, buffer will increase via `emit`.
````ts
function emit(event: string, ...args: any[]) {
if (devtools) {
devtools.emit(event, ...args)
} else {
buffer.push({ event, args })
}
}
````
=> fix(devtools): fix memory leak when devtools is not installed

packages/compiler-sfc/__tests__/__snapshots__/compileScriptPropsTransform.spec.ts.snap, packages/compiler-sfc/__tests__/compileScriptPropsTransform.spec.ts, packages/compiler-sfc/src/compileScript.ts
=> fix(compiler-sfc): add type for props's properties in prod mode

packages/compiler-sfc/__tests__/__snapshots__/compileScriptPropsTransform.spec.ts.snap, packages/compiler-sfc/__tests__/compileScriptPropsTransform.spec.ts, packages/compiler-sfc/src/compileScript.ts
Solve the problem of the following scenarios: 
* Link to minimal reproduction : [sfc.vuejs.org](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBDaGlsZCBmcm9tICcuL0NvbXAudnVlJ1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPENoaWxkIC8+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vc2ZjLnZ1ZWpzLm9yZy92dWUucnVudGltZS5lc20tYnJvd3Nlci5qc1wiXG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59IiwiQ29tcC52dWUiOiI8c2NyaXB0IHNldHVwIGxhbmc9J3RzJz5cbiAgaW1wb3J0IHsgb25Nb3VudGVkIH0gZnJvbSAndnVlJ1xuICB2YXIgcHJvcHMgPSB3aXRoRGVmYXVsdHMoZGVmaW5lUHJvcHM8e2Y/OiBGdW5jdGlvbn0+KCkse2Y6KCk9PlsxLDIsM119KVxuICBvbk1vdW50ZWQoKCk9PntcbiAgICBjb25zb2xlLmxvZyhcImY6XCIscHJvcHMuZilcbiAgfSlcbjwvc2NyaXB0PiJ9) …
=> fix(compiler-sfc): add type for props include Function in prod mode

packages/runtime-core/src/devtools.ts
The latest version of vue3 cause ssr failed, devtools judge in server side is not exact. Mock window object is common in some ssr program for compatibility, maybe only use `typeof window` as condition is not exact
=> fix: the latest vue3 version cause ssr failed, devtools judge in server side is not exact

packages/runtime-core/src/apiSetupHelpers.ts, test-dts/setupHelpers.test-d.ts
This fixes an issue where `InferDefaults` fails to handle union types with base types and array or object types.
`TS2322: Type 'number' is not assignable to type '((props: Readonly<{ foo: number | number[]; }>) => number | number[]) | undefined'.`
would throw for
```ts
withDefault(
defineProps<{ foo: number | number[] }>(),
{ foo: 123 },
)
```
This adds handling of base types and array or object types separately, so that both types can exist in prop type unions.
=> fix(runtime-core): add InferDefaults handling of array and object union types

packages/runtime-core/__tests__/rendererAttrsFallthrough.spec.ts, packages/runtime-core/src/vnode.ts
=> fix(runtime-core): improve dedupe listeners when attr fallthrough

packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap, packages/compiler-sfc/__tests__/__snapshots__/compileScriptRefTransform.spec.ts.snap, packages/compiler-sfc/__tests__/__snapshots__/cssVars.spec.ts.snap, packages/compiler-sfc/src/compileScript.ts
=> fix(compiler-sfc): improve expose codegen if user did not explicitly call `defineExpose`

.github/workflows/ci.yml
Jobs are currently failing with:
```
> @3.2.22 test /home/runner/work/vue-next/vue-next
> run-s test-unit test-e2e "--ci"
ERROR: Invalid Option: --ci
```
=> chore: fix ci build

packages/runtime-core/__tests__/components/KeepAlive.spec.ts, packages/runtime-core/__tests__/errorHandling.spec.ts, packages/runtime-core/src/components/KeepAlive.ts
=> fix(runtime-core): return hook() in wrappedHook to handle the async call in KeepAliveHook.

packages/runtime-core/src/apiSetupHelpers.ts
`null` was missing from the list of primitive types in `InferDefault`, so it caused a type error when used in `withDefaults()`
fix:  #4868
=> fix(runtime-core): script-setup+ts: ensure proper hanlding of `null` as default prop value in types. (fix #4868)

packages/reactivity/src/ref.ts, test-dts/ref.test-d.ts
The `ToRefs` type should not do any ref unwrapping. In #4734 this was also changed for `ToRef` but was forgotten in `ToRefs`.
[Sandbox link to reproduction](https://codesandbox.io/s/ref-unwrapping-in-torefs-xtnfg)
I also grouped together some of the tests for `toRef` and `toRefs` in `ref.test-d.ts`.
=> fix(types): `toRefs` should not do any ref unwrapping

packages/runtime-core/src/componentProps.ts, packages/runtime-core/src/helpers/typeUtils.ts, packages/shared/src/index.ts, test-dts/component.test-d.ts, test-dts/index.d.ts
fix #4983 
from [url](https://stackoverflow.com/questions/49927523/disallow-call-with-any/49928360#49928360)
=> fix(types): propType<any> type infer

packages/runtime-dom/__tests__/patchProps.spec.ts, packages/runtime-dom/src/modules/props.ts
This PR covers an edge case where the OPTION element has a `textContent` matching its assigned `value` attribute.
Previously, Vue would fail to properly assign the value in this case (and consequently, the `value` attribute was missing), because for OPTION elements, `el.value` falls back to `el.textContent` when no distinct value has been set (yet)
close #4956
=> Ensure value for OPTION elements is properly set in edge case (fix #4956)

packages/reactivity/src/ref.ts
Actually it caused a type error in my command line, which complained for missing properties: [Symbol.iterator], [Symbol.unscopables].
=> Return a more reasonable type for arrays.

packages/reactivity/__tests__/ref.spec.ts
Hi , I saw this code in the `ref.spec.ts`:
https://github.com/vuejs/vue-next/blob/5eb72630a53a8dd82c2b8a9705c21a8075161a3d/packages/reactivity/__tests__/ref.spec.ts#L32-L38
you can see that `a.value = 2`  has repeated twice and I guess the second part is for checking that the calls won't change after setting a.value to same number but `expect(dummy).toBe(2) ` has repeated again and that's useless because it has a test at line 34
=> test(reactivity) : fixed a small copy & paste mistake in ref.spec.ts

package.json
CI failed: https://github.com/vuejs/vue-next/runs/4207501061?check_suite_focus=true
Because option of `run-s` is invalid.
See: https://github.com/mysticatea/npm-run-all/blob/master/docs/run-s.md
=> chore: update `test` command

packages/compiler-sfc/src/compileScript.ts
chore(compiler-sfc): fix typo in compileScript
=> chore(compiler-sfc): fix typo in compileScript

packages/runtime-core/src/compat/componentFunctional.ts, packages/runtime-core/src/component.ts, packages/vue-compat/__tests__/componentFunctional.spec.ts
Legacy functional components could have own `compatConfig` which is lost when they are converted to function due to `COMPONENT_FUNCTIONAL` flag. This commit copies `compatConfig` to created function, so it continues to work in expected way
=> fix(compat): maintain compatConfig option in legacy functional comp

packages/vue/package.json
The fix in 124570973df4ddfdd38e43bf1e92b9710321e5d9 seems incomplete - it works in VSCode, but vue-tsc still throws: 
> vue-tsc --noEmit && vite build
> src/env.d.ts:2:23 - error TS2688: Cannot find type definition file for 'vue/ref-macros'.
> `2 /// <reference types="vue/ref-macros" />`
it seems that the `"exports"` entry for the ref-macros should not have the .d.ts extension:
```diff
"exports": {
// ....
"./dist/*": "./dist/*",
"./package.json": "./package.json",
-    "./ref-macros.d.ts": "./ref-macros.d.ts"
+    "./ref-macros": "./ref-macros.d.ts"
},
```
Doing that change in an actual plain vite project and running build works without throwing an error. 
I used: https://github.com/malobre/vue3-ref-transform-type-reference-bug
=> fix: ensure ref-macros export plays nice with vue-tsc

packages/vue-compat/README.md
The chainWebpack arrow function wasn’t being closed.
=> chore(compat): Fix example config syntax error

packages/runtime-core/src/apiSetupHelpers.ts
Currently, the public API for a component defined using `defineExpose` is not typed when this component is used elsewhere (as discussed in #4397).
My current workaround is to define the API as an interface and casting the object in the component:
`MyComponent.d.ts`
```ts
export interface IMyComponent {
doSomething(): void;
}
```
`MyComponent.vue`
```vue
<script setup lang="ts">
import type { IMyComponent } from './MyComponent';
const publicAPI: IMyComponent = {
doSomething() {
// ...
},
};
defineExpose(publicAPI);
</script>
```
But writing that is cumbersome, I'd prefer doing the following:
```ts
defineExpose<IMyComponent>({
doSomething() {
// ...
},
});
```
So that's what this PR allows :). Given that it's optional, it shouldn't affect people who isn't using this approach.
I tried …
=> dx(script-setup): add generic type to defineExpose

packages/sfc-playground/src/App.vue
By default it opens the browser's 'save web page' dialog, which is annoying, because this shortcut is about 'save code change' in most code editors. And also since it's auto-save by default, so I think it can just be ignore.
------------
maybe I should commit this to @vue/repl?
=> feat(sfc-playground): prevent ctrl+s default behavior

packages/sfc-playground/src/Header.vue
Right now when using a variable width size (I use it inside slides taking half the width), the title blocks clicks:
https://user-images.githubusercontent.com/664177/145827475-d6a8ceca-443a-4ffb-96e3-76dd67d39092.mp4
This change hides the title to avoid blocking the click:
https://user-images.githubusercontent.com/664177/145827650-71356ad6-6749-4fce-a707-12355f1c5d79.mp4
=> fix(sfc-playground): hide title to avoid overlap

packages/runtime-core/src/componentProps.ts, packages/runtime-core/src/helpers/typeUtils.ts
Relate issues: https://github.com/johnsoncodehk/volar/issues/799, https://github.com/microsoft/TypeScript/issues/31992
Remove `O extends object` from `ExtractPropTypes` to avoid tsc remove props JSDoc comments.
And it can also help for improve component props hover info in IDE.
~In addition, changed `{ [K in KeysType]: T[K] }` to `{ [K in keyof Pick<K, KeysType>]: T[K] }` to fixed find references, renaming not working for props again. (#3656)~
Revert this change from `LooseRequired` because it cause tests failed.
Before simplify `ExtractPropTypes`:
```ts
import { PropType } from 'vue';
declare const _default: import("vue").DefineComponent<{
/**
* The icon name as per the reference at https://pepicons.com
* @type {'airplane' | 'angle-down'}
* @example 'airplane'
*/
name: {
type: …
```
=> feat(types): simplify `ExtractPropTypes` to avoid props JSDocs being removed

packages/runtime-core/src/components/KeepAlive.ts
=> fix(KeepAlive): remove cached VNode properly

packages/runtime-core/__tests__/vnode.spec.ts, packages/runtime-core/src/vnode.ts, packages/runtime-dom/src/modules/events.ts
closes #5296
Note: The true fix is in `mergeProps`' handling of `on*` props whose values are undefined, but I also added a nonnull check in `patchStopImmediatePropagation` for good measure.
=> fix(runtime-core): ensure mergeProps skips undefined event handlers (fix #5296)

packages/runtime-core/src/compat/global.ts
Some Vue plugins that are actually compatible with the `vue-compat` won't work because of the version check ([an example from vue apollo](https://github.com/vuejs/apollo/blob/029d934cce8d28e1a5454956909f57cc3e2349a1/packages/vue-apollo/src/mixin.js)). Right now `vue-compat` returns 3x version for the legacy method of checking Vue version via `Vue.version`. This PR instends to simulate Vue 2 version in those instances and instead return a 2x-compatible version: `2.6.14-compat:3.x.x`.
=> compat: Simulate Vue 2.6.14 version in vue-compat

packages/runtime-core/src/componentProps.ts
This PR solves #5222 where a fallthrough event listener from a Vue 2 `v-bind.native` was removed on a component re-render.
I would need some guidance regarding how to add a test for this.
=> fix(compat): ensure fallthrough *Native events are not dropped during props update (fix #5222)

packages/compiler-core/__tests__/transforms/__snapshots__/vMemo.spec.ts.snap, packages/compiler-core/src/transforms/vFor.ts
=> fix(compiler-core): handle v-memo in template v-for

packages/runtime-core/src/compat/componentVModel.ts
If a Vue 2 component defines `model` option via `mixins`, `convertLegacyVModelProps` will not take care of it and break it.
=> fix(compat): convertLegacyVModelProps should merge model option in mixins

packages/reactivity/__tests__/readonly.spec.ts, packages/reactivity/src/baseHandlers.ts
When we have a readonly _object_ nested in another reactive object, attempting to write to a property of that readonly object fails, as expected.
```js
const state = reactive({
subState: readonly(reactive({ msg: 'Hello' }))
})
state.subState.msg = 'Bye' // => fails as `subState` is readonly
```
But if we have a readonly _ref_ nested in a reactive object, it successfully writes to it.
```js
const state = reactive({
msg: readonly(ref('Hello' ))
})
state.msg = 'Bye' // => succeeds even though `msg` is a readonly ref.
```
This PR fixes that edge case.
* Is the behavior introduced by this PR the desired one?
* Is this a "risky fix" as it may break code that works in current user projects?
fix: #5042
=> fix(reactivity): mutating a readonly ref nested in a reactive object should fail. (close #5042)

packages/compiler-sfc/__tests__/__snapshots__/cssVars.spec.ts.snap, packages/compiler-sfc/__tests__/cssVars.spec.ts, packages/compiler-sfc/src/cssVars.ts
=> fix(cssVars): cssVars work with complex expression

packages/reactivity/__tests__/readonly.spec.ts, packages/reactivity/src/baseHandlers.ts
in 171f5e9 we fixed a bug concerning reactive objects allowing to write to nested read-only refs.
That fix had the unintended side-effect of also disallowing to *replace* a nested (readonly) ref with a new ref.
This PR fixes that and restores the original behavior to allow refs to be replaced, but still prevents readonly refs to be written to.
fix: #5307
=> fix(reactivity): ensure readonly refs can be replaced with new refs in reactive objects  That was the behavior before 171f5e9 (fix #5307)

packages/runtime-core/src/hydration.ts
fix #5405
fix https://github.com/nuxt/framework/issues/1036
In Dev, hoisted nodes are not always "static" as developers might change it with HMR. We shouldn't skip the children's hydration.
Not sure if tests are required in this case
=> fix(runtime-core): always hydrate hosited children for HMR

packages/runtime-core/__tests__/componentPublicInstance.spec.ts, packages/runtime-core/src/componentPublicInstance.ts
Since Jest v26.6.1, the mock method changed (see this commit facebook/jest@30e8020)  to rely on `Object.defineProperty` in some cases.
This breaks spying on proxy's methods, because even if Jest is properly calling `Object.defineProperty`, the cached value in the `get` section of the proxy is never updated, and the spy is in fact never used.
This is easily reproducible as vue-next already uses a version of jest with these changes.
This is blocking projects (like vue-test-utils-next and vue-cli) to update to recent Jest versions.
This commit adds a `defineProperty` method to the proxy handler, that properly updates the defined value in the cache.
Again, the fix is maybe too naive, and I'm happy to update the PR with a better solution.
edit: the same happens with Vitest
=> fix(runtime-core): allow spying on proxy methods

packages/runtime-core/__tests__/componentPublicInstance.spec.ts, packages/runtime-core/src/componentPublicInstance.ts
a getter should not get evaluated when defining a property using `defineProperty`
```js
this.set!(target, key, descriptor.get(), null)
```
instead we invalidate the key `accessCache`
```js
target.$.accessCache[key] = 0;
```
fixes: #5415  #4216
=> fix(runtime-core): allow spying on proxy methods regression  #5415 #4216

.github/contributing.md
I noticed that optional operator(?.) is used in scripts/dev, but it only supports node 14+, so should node 14 be the minimum version limit for developers?
=> docs(contributing): change node version

packages/runtime-core/src/componentProps.ts
when event listener as dynamicProp  on updateProps, it is added to the  instance’s props and it can be implicit binded to other components again by "v-bind=$props".  it maybe trigger the callback function multiple times.
close https://github.com/vuejs/core/issues/5520
=> fix(runtime-core): fix event listener as dynamicProp is added erroneously  to props

packages/runtime-core/__tests__/helpers/resolveAssets.spec.ts, packages/runtime-core/src/apiCreateApp.ts, packages/runtime-dom/__tests__/createApp.spec.ts
=> fix(runtime-core): Avoid mutating original options object in createApp (fix #4398)

packages/runtime-core/__tests__/directives.spec.ts, packages/runtime-core/src/directives.ts
For closed instances (those crreated with `<script setup>` or a normal setup function in which `expose()` has been called), we currently expose a different proxy ("`exposeProxy`") for i.e. refs. 
This proxy provides access  to the public instance methods provided by Vue and the explicitly exposed custom properties.
With this PR we now also expose this same `exposeProxy` to custom directives in `binding.instance` so that custom directives can access exposed properties correctly.
Edit: I moved this to p4- important as I realized that this is currently working in dev with script-setup, but breaking in prod, which is - bad.
fix: #5018
=> fix(runtime-core): ensure that binding.instance in custom directive hooks properly exposes properties on closed instances (fix: #5018)

packages/runtime-dom/__tests__/patchProps.spec.ts, packages/runtime-dom/src/patchProp.ts
=> fix: patch translate as an attr

packages/shared/package.json
As far as I can tell, all the code in this package is side-effects-free.
Without the `sideEffects` flag, bundlers rely on code analysis and
the `/*#__PURE__*/` comments for tree-shaking.
As bundlers' implementations vary, the analysic may or may not be
exhaustive.
For example, a file that contains only the following line of code:
```js
import { capitalize } from '@vue/shared'
```
If bundled by esbuild (`esbuild --bundle test.js --tree-shaking=true`),
the output would be tens of lines.
(Technically, it's not esbuild's bug, because `Object.freeze` can be overwritten, `Array.isArray` could be overwritten to a getter, `+` can have side effects… Even though we know they *are* side-effects-free, it would require much more work from us to make bundlers happy)
After this PR, the output will be an …
=> chore(@vue/shared): add `"sideEffects": false`

packages/runtime-dom/__tests__/patchProps.spec.ts, packages/runtime-dom/src/modules/props.ts
some dom property is has getter, but no setter,like
```html
<select :type="null"></select>
```
patchDOMProp method will throw an error in  'use strict'
=> fix: some dom property setting error #5545

packages/runtime-core/__tests__/components/Suspense.spec.ts, packages/runtime-core/src/component.ts
We should warn users when they are  using asnyc setup in a component that is not inside a Supsense boundary, because that component will now be stuck and never render.
Prior Art by https://github.com/HcySunYang in #3657
close #3649
=> fix(suspense): warn when using asnyc setup when not inside a Supsense boundary. (fix: #3659)

packages/reactivity/src/baseHandlers.ts, packages/reactivity/src/deferredComputed.ts, packages/runtime-core/src/componentPublicInstance.ts, packages/runtime-core/src/scheduler.ts, packages/runtime-dom/src/index.ts, packages/runtime-dom/src/modules/events.ts, packages/runtime-dom/src/nodeOps.ts
More `/*#__PURE__*/` markers are added to improve treeshakeability. Intended for libaries that bundle vue.
I was writing a library that exports some pure function and some UI-related function to render something. To make it standalone, vue is bundled. To simplify build setup and .d.ts generation, the whole library is bundled into one ESM file.
I created a test app with vite and found even when UI-related functions aren't imported (they depend on vue), the resulting app bundle contains some vue code that wasn't removed. This PR contains all that I could find that lacked `/*#__PURE__*/` marking, and by adding these all unused code were correctly removed.
=> feat: improve treeshakeability

packages/runtime-core/src/helpers/renderSlot.ts, packages/runtime-dom/__tests__/customElement.spec.ts
=> fix(custom-elements): work with async component + slots

packages/runtime-dom/__tests__/patchStyle.spec.ts, packages/runtime-dom/src/modules/style.ts
style definition objects that had an initially falsy value for a custom property would add that custom property with the stringified falsy value:
```vue
<div :style="{ '--color': undefined }">
<div style="--color: undefined;"> 
```
Note that this only affected *initial* values. if the falsy value was added in an update, the property was properly removed.
After this PR, the custom property would not be added in the first place on mount:
```html
<div style>
```
close: #5322
=> fix(runtime-dom): properly handle custom style properties with falsy values (fix: #5322)

packages/vue-compat/__tests__/global.spec.ts
A `test.only`has been introduced in 16129714714e19c5c6bfbd05c439ff68bcac00b9
cc @LinusBorg
=> fix(vue-compat): remove test.only

packages/reactivity-transform/__tests__/__snapshots__/reactivityTransform.spec.ts.snap, packages/reactivity-transform/__tests__/reactivityTransform.spec.ts, packages/reactivity-transform/src/reactivityTransform.ts
=> fix(reactivity-transform): should not rewrite catch param

packages/server-renderer/__tests__/ssrRenderAttrs.spec.ts, packages/server-renderer/src/helpers/ssrRenderAttrs.ts
Fix missing reserved prop `ref_key` in SSR code output. (fix #5563)
=> Fix: missing reserved props `ref_key` & `ref_for` (fix #5563)

packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap, packages/compiler-sfc/__tests__/compileScript.spec.ts, packages/compiler-sfc/src/compileScript.ts
If not, an exception will be thrown once the type is used in the template.
=> fix(compiler-sfc): Check if the type modifier in the import statement

packages/runtime-core/__tests__/componentEmits.spec.ts, packages/runtime-core/src/componentEmits.ts
This change ensures that calling `emit` after the component has unmounted will no longer call any of the registered custom event listeners.
Is it possible/realistic that we have implementations out there that rely on the current behavior where this event would still be triggered?
If so, how do we approach this?
close: #5674
=> fix(runtime-core): ensure custom events are not emitted anymore after unmount. (fix #5674) 

packages/compiler-dom/src/transforms/stringifyStatic.ts
File may have moved since comment in evaluateConstant was written
(does not modify any code)
=> chore: reference to transformExpressions

packages/runtime-dom/src/directives/vModel.ts
In compat mode `el._assign is not a function` is thrown when you bind a model to a radio button because `onUpdate:modelValue` does not exist in the props. As far as I could see in compat mode it's called `onModelCompat:input` instead:
https://github.com/vuejs/vue-next/blob/4f17be7b1ce4872ded085a36b95c1897d8c1f299/packages/runtime-core/src/compat/componentVModel.ts#L38-L40
I created a reproducible repository here:
https://github.com/jaulz/vue-repro
=> fix(runtime-dom): "el._assign is not a function" in compat mode

packages/shared/__tests__/looseEqual.spec.ts, packages/shared/src/looseEqual.ts
https://github.com/vuejs/vue-next/blob/4fe4de0a49ffc2461b0394e74674af38ff5e2a20/packages/shared/src/looseEqual.ts#L12
I think the `looseEqual` function of above code should work like this:
`looseEqual(Symbol('a'), Symbol('a')) // false`
But `looseEqual(Symbol('a'), Symbol('a'))` returns `true` now.
=> fix(shared): missed Symbol judge in looseEqual

packages/runtime-dom/types/jsx.d.ts
Change a small typo in the type definition of `HTMLAttributes`.
```diff
-autocave?: string
+autosave?: string
```
For a reference, the `@types/react`, which the code is based on, has the [`autoSave`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6d9d1c7a924548017fa3c23959c7dac4492c2e85/types/react/index.d.ts#L1030) property in `HTMLAttributes`.
=> types(runtime-dom): fix typo in jsx type autosave

packages/runtime-core/src/componentSlots.ts
This PR ensures that an already normalized slot isn't normalized again, which could potentially lead to a "max stack" error from too many nested function calls (aside from simply being unnecessary work).
I didn't add a test case as this change doesn't have a public effect I could test against - if all tests still pass this should be fine.
But I can come up with one if necessary.
close: #5353
=> fix(runtime-core): Ensure raw Slots are only normalized once by withContext (Fix: #5353)
